### ISSUE TITLE
Not able to accept License SNOMED on mobile

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#1007]
### Expected behavior
I am able to accept the license on my mobile

### Actual behavior
The accept button is out-of-scope and you cannot move to it (also not in landscape mode)

![img_6733](https://user-images.githubusercontent.com/7252105/46692397-708e2000-cc07-11e8-9c67-11bb132e5ebe.jpg)
![img_6732](https://user-images.githubusercontent.com/7252105/46692400-72f07a00-cc07-11e8-8620-2ad938039952.PNG)

### Steps to reproduce behavior
Open the site on your phone.

(I am trying out the amazon test vm)

**Comment by anthonysena** [comment]
One option: left-align accept/reject buttons which makes them visible on lower resolutions such as mobile.
