### ISSUE TITLE
Recent Searches Links

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#101]
The "recent searches" links under the Vocab Search is a nice touch.  When you have hit the back button to get to the search screen they update the URL but do not execute the call.
1. Go to ATLAS
2. Search the Vocabulary
3. Search for "Lymphoma"
4. Press the browser back button.
5. "Lymphoma" will show up as a "Recent Search", click the link.
6. URL updates but no action is taken.  

I would consider this low priority issue.

**Comment by anthonysena** [comment]
I've experienced this myself - generally the information is still available under the "results" tab so you can check there but the UI is not handling this case.

**Comment by cerdman** [comment]
Will check on this one.

**Comment by anthonysena** [comment]
Recent search items will be removed in the V2.0 release.
