### ISSUE TITLE
Unable to delete cohort definition

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#1013]
### Expected behavior
Clicking delete of a cohort should result in cohort deleted.

### Actual behavior
No feedback from UI, console shows internal server error

### Steps to reproduce behavior
Create a cohort Definition
Add the cohort as a linked cohort to a Treatment Pathway
Remove linked cohort from Treatment pathway
Try to delete cohort definition.

**Comment by anthonysena** [comment]
@pavgra - This problem still remains in the latest code base from my testing.

**Comment by ssuvorov-fls** [comment]
@anthonysena - Could you add more details, may be some screenshots? I still can't reproduce described behaviour

**Comment by pavgra** [comment]
> However, this failure is not surfaced in ATLAS so perhaps we can provide some feedback to the user when this happens?

@anthonysena , makes sense
