### ISSUE TITLE
Generate button does not show activity when status of job is 'STARTING'

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#1014]
Not related to #968.

### Expected behavior
Clicking generate button should show a spinner that there is activity for this source.

### Actual behavior
Clicking generate does kick off a job and marks it as 'STARTING', but does not show a sniper in this state.

### Steps to reproduce behavior
Hard to reproduce, exactly, because it is not clear when a state of an execution is STARTING vs. STARTED. However, to reproduce, keep clicking on generate buttons until you get to the point where the job status is 'STARTING' and you will find the generate button doesn't have the spinner.

**Comment by anthonysena** [comment]
After discussion on WebAPI call, this may require a check for the current job that is either 'STARTING' or 'STARTED' and not solely 'STARTED'
