### ISSUE TITLE
estimation specification flag for adding descendants should be set to Yes

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/Atlas#1017]
The default for  [estimation -> analysis settings -> covariate settings -> "Should descendant concepts be added to the list of excluded concepts?"] is set to No. The default for this setting should be Yes in order to include descendants to exclude as specified in the comparison settings

**Comment by anthonysena** [comment]
Note to self: make this change while addressing #988

**Comment by anthonysena** [comment]
@jamieweaver spoke with @schuemie regarding this change and we're going to hold on this until the next planned release of Atlas/WebAPI 2.8. 

In summary: the interface for specifying covariates to include/exclude is not optimal - you can specify covariates to include/exclude as part of the comparison definition as well as in the analysis itself. However, the "switch" to include descendants is only at the analysis level. Overriding the default to 'Yes' for covariate exclusion would change the defaults specified by FeatureExtraction which we'd like to avoid. 

One idea for making the interface & user choices clearer in this regard: when specifying a comparison, the interface should show each analysis and the respective settings for include/exclude descendant concepts.

**Comment by anthonysena** [comment]
@olga-ganina - for this one, let's plan to ensure that the "Comparisons" detail view in the Estimation editor allows for the display of a concept set's contents in the UI.

**Comment by anthonysena** [comment]
Closing due to age.
