### ISSUE TITLE
UI generates wrong link to cohort definition

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1024]
### Steps to reproduce behavior

1. Go to Cohort Definitions, choose any Cohort.
2. Press button with the tip "Get a link to this Cohort Definition.
3. Check the link.

### Actual behavior
1. The link has double slash.

### Expected behavior
1. the link doesn't have double slash.

![image](https://user-images.githubusercontent.com/10010071/47100845-6e7b2100-d206-11e8-9710-e3a9808b3cae.png)

**Comment by alondhe** [comment]
Seeing this still in public Atlas, are there plans to update that version to include @pavgra's bugfix?
