### ISSUE TITLE
I want to connect multiple CDMs with one webapi DB

### ISSUE THREAD

**Issue by parkdongsu** [OHDSI/Atlas#1032]
CDM: db1.dbo
Vocabulary: db1.dbo
Results: webapi.dbo
CEM: db1.dbo

CDM: db2.dbo
Vocabulary: db2.dbo
Results: webapi.schema
CEM: db2.dbo

This is my setting.

webapi.dbo Copied all tables to webapi.schema

However, only 'generate' is executed for db1
Could you tell me which table should be copied for the new schema, and how to generate 'generate' for all DBs?

**Comment by chrisknoll** [comment]
First thing you must do is separate your WebAPI database from your CDM databases.  If you haev 2 CDMs, then you need 3 Databases:

WebAPIDB:
```webapi``` schema that will be managed by WebAPI, it will create tables automatically

CDM Database:
```cdm``` schema for storing your vocabulary and patient-level tables. This will be created as a result of your ETL process.
```results``` schema for storing analysis results.  You can get the DDL for this schema by going to a WebAPI URL: ```{your_webapi_server}/WebAPI/ddl/results```.
```CEM schema```: I will need to direct you to @anthonysena for instructions on how that is set up.

In your envirnment you'll hae 1 WebAPI DB and your WebAPI configuration in ```settings.xml``` will contain the jdbc URL and username/password to connect to your WebAPI database.

The other CDMs will be set up in separate databases, each database will contain at least these two schemas:  ```dbo``` for your CDM, ```results``` for the results.  

The way to connect to multiple CDMs from a single webAPI is to insert the JDBC connection strings in the WebAPI.source table, and then set the names of the schemas for each source in the ```source_daimon``` table.

**Comment by anthonysena** [comment]
@parkdongsu - The information you need to set up WebAPI and Atlas are found at:

https://github.com/OHDSI/WebAPI/wiki/WebAPI-Installation-Guide
https://github.com/OHDSI/Atlas/wiki/Atlas-Setup-Guide

I'll close out this issue since it is old but if you are still experiencing issues with the setup, please do re-open this item. Thanks!
