### ISSUE TITLE
naming of concepts in hierarchy page is confusing

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1048]
### Expected behavior
search on a term, for example, 4086243, click on name, click on hierarchy tab, view hierarchy, click on concept id higher (438688) or lower (4093002) in hierarchy, and page shows under Name just the new term (for example: 438688) with correct hierarchy

### Actual behavior
search on a term, for example, 4086243, click on name, click on hierarchy tab, view hierarchy, click on concept id higher (438688) or lower (4093002) in hierarchy, and page shows under Name the new term and the old term with correct hierarchy for new term

### Steps to reproduce behavior
search on a term, for example, 4086243, click on name, click on hierarchy tab, view hierarchy, click on concept id higher (438688) in hierarchy, and page shows under Name the new term and the old term with correct hierarchy for new term

**Comment by anthonysena** [comment]
Closed via #1162
