### ISSUE TITLE
Update of browser was needed for new ATLAS V2.6.0

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#1050]
Just putting this in the log, so save others some hours..

When installing the new ATLAS in our internal offline Linux server i got a lot of errors all related to finally function not supported. 

For example in router.js line 65:

`Uncaught TypeError: routes[key].checkPermission(...) then (...) catch (..) finally is not a function`

After quite some searching i found that that the finally function has only recently been approved and that older browsers do not support it yet.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally#Browser_compatibility

After updating Chrome on Linux all worked fine.

**Comment by anthonysena** [comment]
Thanks @PRijnbeek - I've updated the wiki to reflect this information. Based on the link above, it looks like users should use Chrome v63 or higher. 

http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas#atlas
