### ISSUE TITLE
Minimizing the ATLAS window 

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#106]
While on the cohort editing page, if the window is minimized the buttons move so that they are on top of each other and unable to be used effectively. I am using a screen with 1366x768 resolution and I minimized the window to the left side of the screen so I could use it side-by-side with another application. 

![image](https://cloud.githubusercontent.com/assets/12911960/15075880/c505512e-1374-11e6-87f5-4f9310817a70.png)

**Comment by anthonysena** [comment]
Only appears to be happening on the cohort definition editor screen so tagging it with the cohort feature. Also keeping with the system feature in the event that this issue is spotted elsewhere.

**Comment by fdefalco** [comment]
resolved in feature integration branch
