### ISSUE TITLE
Visit count feature displayed twice in table

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1062]
### Expected behavior
Feature should appear once.

### Actual behavior
![image](https://user-images.githubusercontent.com/6586384/47505478-372af680-d83c-11e8-9f3a-f084af2e0caa.png)

**Comment by pavgra** [comment]
@fdefalco , could you share the CC definition?

**Comment by pavgra** [comment]
@anthonysena / @chrisknoll / @fdefalco , would it be possible to double-check the issue presence using the latest master and if it still exists - share the CC or sequence of actions to reproduce?

**Comment by anthonysena** [comment]
I'm going to close this out since I've been unable to reproduce this on the latest code base. If we can reproduce this, I'll re-open and attach the characterization export. Thanks!
