### ISSUE TITLE
error while browsing vocabulary hierarchy

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1063]
### Actual behavior
![image](https://user-images.githubusercontent.com/6586384/47507770-d05c0c00-d840-11e8-8bc1-7795616c49df.png)

### Steps to reproduce behavior
browse to concept (https://epi.jnj.com/atlas/#/concept/45888235)
browse to related concept from related concepts tab
https://epi.jnj.com/atlas/#/concept/42742329
switch to hierarchy tab

**Comment by jhardin29** [comment]
Hi @fdefalco I think this is what I was trying to convey in post https://github.com/OHDSI/Atlas/issues/1048.

**Comment by aklochkova** [comment]
Note that Table Qualifiers in Source configuration matter to reproduce this bug. While it works correctly for `CDM: synpuf_50_test
Results: synpuf_50_test_results
Vocabulary: synpuf_50_test` after this PR https://github.com/OHDSI/Atlas/pull/1073 it fails for `CDM: synpuf_53_test
Vocabulary: synpuf_53_test
Results: synpuf_53_test_results`. So I redesigned code here https://github.com/OHDSI/Atlas/pull/1094. Now it includes all cases of Table Qualifiers.
