### ISSUE TITLE
after new pathway analys is created and saved, it is impossible to return to analysis list

### ISSUE THREAD

**Issue by vantonov1** [OHDSI/Atlas#1072]
click to "pathway analysis" redirected to a last saved item

**Comment by chrisknoll** [comment]
You have to close the analysis you have opened using the 'close' button.

![image](https://user-images.githubusercontent.com/6818777/47653422-ef1f1300-db5e-11e8-8bab-77f87f798225.png)

This is the behavior for estimation, prediction, incidence rate analysis, and should be the same for characterization (but there's an outstanding bug with that).   The only exception to this is cohort definitions and concept sets which are coupled in a very unfortunate way, which I hope will be addressed in a near-term release.
