### ISSUE TITLE
Treatment pathways sunburst plot keep color scheme consistent between analyses

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1077]
### Expected behavior
Within a given treatment pathway analysis colors on portions of ring in sunburst are consistent for identical drug names
### Actual behavior
Within a given treatment pathway analysis colors on portions of ring in sunburst vary between databases for identical drug names
### Steps to reproduce behavior
Within a given treatment pathway analysis view plot in one database examine drug names and colors; switch to report for alternative database and view drug names and colors

**Comment by pbr6cornell** [comment]
When making comparisons across Sources, I agree its important to have a common legend.  Currently, we perform analyses on a per-source basis, so this isn't readily possible.  However, I know in ATLAS 3.0, a critical capability we need to add is to enable cross-source comparisons, in which case this will become essential.  @chrisknoll can think about if theres a quickfix to get into ATLAS 2.8, or if it must wait until ATLAS 3.0 when it'll be required.

**Comment by chrisknoll** [comment]
The colors are now based off the design elements, and not based on the values found in the result.
