### ISSUE TITLE
Request - add capability to choose custom cohort as entry event

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1092]
### Request
It would be useful to have the ability to pull in a custom cohort into ATLAS as the cohort entry event, for example, the pregnancy episodes table or any other custom built cohort. A potential way to do this would be to add a drop down option of custom cohort and then pass either a .sql file or reference a scratch table. Maybe others have ideas too. 

This would help me on a current pregnancy project and would have helped others using the pregnancy table on their projects; tagging @jweave17

**Comment by jhardin29** [comment]
Tagging @jamieweaver

**Comment by gowthamrao** [comment]
A similar issue way posted here (involves combining cohorts)

https://github.com/OHDSI/Atlas/issues/398

**Comment by pbr6cornell** [comment]
functionality now in Cohort Generator ,and may be exposed if ATLAS UI designs Strategus workflows in future.
