### ISSUE TITLE
Characterization page takes a very long time to render

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1097]
### Expected behavior
The characterization page should render in 10 seconds or less (sorry not sure of the exact seconds expected)

### Actual behavior
The characterization page requires ~ 60 seconds to render

### Steps to reproduce behavior
click on the characterization left hand menu item
tagging @rmakadia

**Comment by AntonStepanof** [comment]
Looks like it has been already fixed. Cannot see this behavior now.
@pavgra Could you please confirm that?

**Comment by pavgra** [comment]
@anthonysena , I suggest closing this because in my opinion this was resolved by introducing threshold level which filters out covariates with very low presence

**Comment by pbr6cornell** [comment]
@pavgra per our discussion yesterday, I think this remains a top priority for ATLAS 2.8 and should be focal point of our priority testing.  In our environment, characterization rendering is still very slow, and I think it's largely connected to the other issue here: #1142.   Let's figure out how to create some examples that we can benchmark against, and @leeevans @gklebanov  and I can set some appropriate 'maximum allowable time' thresholds to compare with in the OHDSI CI environment.

**Comment by anthonysena** [comment]
I'm closing this issue in favor of #1142 to specifically address the suggestions left by Patrick here: https://github.com/OHDSI/Atlas/issues/1142#issuecomment-511164352. Some of the updates around characterization have helped to improve things but addressing the comments in #1142 will satisfy the needs we have for 2.8.
