### ISSUE TITLE
If cohorts are not generated, prompt users to generate it from IR as a part of the process

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1098]
Today IR works with the assumption that cohorts used for the analysis were previously generated from Cohort Definitions page. So, if the cohorts were not generated, IR would return zero results and it is not obvious whether those are due to the lacking cohorts info or due to IR issue or just there are zero cases for the cohorts. Therefore, there comes a suggestion: if cohorts were not generated, prompt users to generate it from IR as a part of the process.

**Comment by chrisknoll** [comment]
I'd suggest not even prompting:  it's never a valid case to try to generate an IR analysis withou un-generated cohorts.  So, in the simplest case, always generate the cohort. In a more advanced approach, if we could cache results of a prior generation and only generate what is necessary, that would be better (tho, more complicated to implement).
