### ISSUE TITLE
where is a R -code in Atlas?

### ISSUE THREAD

**Issue by SungJun9212** [OHDSI/Atlas#1103]
I know previously there was an R code in Atlas ,Estimation.

but i don't know where is a R-code.

I have to find r-code.

I am use Atlas 2.6 version.

Anyone help me.

**Comment by anthonysena** [comment]
Hi @SungJun9212 - the R-code functionality in Atlas 2.6.0 has been replaced by the ability to download the full study as an R package. This is done by going to the estimation study designer in ATLAS, open the study, click on 'Utilities'. 

From there, click 'Click here to review the full study specification' and review the full set of hypotheses that are tested as part of the study design as shown here:

![image](https://user-images.githubusercontent.com/12902366/48358920-ca03c780-e669-11e8-9a96-ea05c4fe3b9e.png)

Once you have reviewed the full specification, at the bottom of the page you can download the study package. Provide a name for your study package in the textbox and then click "Download" to obtain the code in a ZIP file.

The ZIP file contains a full R Study package that includes the design choices you made through ATLAS. Within the package, there is code that will use your design to run the study using the OHDSI methods libraries - in the case of estimation, this will utilize CohortMethod (as well as several other packages). Inside of the R package, please review the  `/extras/CodeToRun.R` This is an example R script that is provided to show how to run the package by replacing the placeholders with information that is specific to your environment (i.e. the connection to your CDM). Towards the bottom, the main 'execute' function provides flags for the steps to execute. 

Please reach back out if you have further questions - for now I'll close this issue but please re-open if you are facing any challenges. Thanks!

**Comment by SungJun9212** [comment]
thank you for your comment :)

**Comment by SungJun9212** [comment]
Thank you for a detailed description.
There are many folders for downloading packages and checking the code inside.
Could you please explain the guide or method to use?
Since the version has been changed, it is very difficult to confuse with the first use.

**Comment by chandryou** [comment]
@SungJun9212  activate Rproject inside the folder by R. 
Install the package in the R studio
And then open the CodeToRun.R file in the extra folder.
