### ISSUE TITLE
wrong loading animation used on drill down reports

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1107]
### Expected behavior
Use current loading animation

### Actual behavior
Uses old loading animation

### Steps to reproduce behavior
Drill down to a report in the data sources tab.

![image](https://user-images.githubusercontent.com/6586384/48366630-75b61300-e67c-11e8-891f-6c971bde3501.png)

**Comment by anthonysena** [comment]
Re-opening and adding a label since this work is not yet merged into master. I'll do this for other issues that are in the same state. Thanks!

**Comment by chrisknoll** [comment]
Closed by #1165.
