### ISSUE TITLE
loading indicator is not visible

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1109]
### Expected behavior
user always is aware when loading is taking place

### Actual behavior
on some screen resolutions or if an existing report is very tall (height) the loading indicator appears below the fold (off the screen) and is not visible

**Comment by fdefalco** [comment]
![image](https://user-images.githubusercontent.com/6586384/48366983-62577780-e67d-11e8-9926-053c32088098.png)

**Comment by chrisknoll** [comment]
Closed by #1165.
