### ISSUE TITLE
inconsistent graph behavior when no data available

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1110]
### Expected behavior
Charts should behave consistently when no data is available

### Actual behavior
Some charts show 'no data' message while others appear blank

### Steps to reproduce behavior
drill down to elements on the measurement report

![image](https://user-images.githubusercontent.com/6586384/48367240-16590280-e67e-11e8-9772-7c1bc7b86124.png)

**Comment by chrisknoll** [comment]
Closed by #1165.
