### ISSUE TITLE
source key instead of name shown on reports

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1112]
### Expected behavior
Show the data source name (user friendly name of the data source)

### Actual behavior
The source key (unique identifier for data source) is shown.

### Steps to reproduce behavior
shown on all data source reports

![image](https://user-images.githubusercontent.com/6586384/48420767-1d891a80-e729-11e8-8daa-a8ef230cf700.png)

**Comment by chrisknoll** [comment]
Closed by #1165.
