### ISSUE TITLE
Data Source report routes do not function

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1116]
### Expected behavior
reports load on the basis of routes

### Actual behavior
routes are ignored, specifically: 
https://github.com/OHDSI/Atlas/blob/master/js/pages/data-sources/routes.js#L12

### Steps to reproduce behavior
attempt to load a report using datasources/:sourceKey/:reportName ie datasources/CDM1/Dashboard

**Comment by chrisknoll** [comment]
Closed by #1165.
