### ISSUE TITLE
Warning of "No concept set specified" when Condition Source Concept Used

### ISSUE THREAD

**Issue by llhester** [OHDSI/Atlas#1119]
This is an add-on to the open bugs reported in #867 and #1085. 

### Expected behavior
When source codes are added to the condition source concept for an initial condition occurrence event,  there should be NO warning in the Messages tab. that there is "no concept set specified in.

### Actual behavior
When no concept set is entered for the initial condition occurrence event (label "Any Condition" remains) and the source codes are added to a condition source concept for that condition occurrence, the cohorts will generate for patients with the condition source concepts. However, the Message tab states that the Source Concept Set was not used and "No concept set specified as part of a criteria at initial event in condition occurrence criteria." Additionally, there is an Info message that " It's not specified what type of records to look for in condition occurrence at initial event." I would expect that the system could identify that there is a condition source concept used even when there is no concept set specified for the condition occurrence.

### Steps to reproduce behavior
1) Created a condition occurrence as an initial event  and included no concept set ("Any Condition" label remains).
2) Added a Condition Source Concept for the empty condition occurrence and specified a source code concept set.
3) Saved the cohort and generated the cohort in a database to make sure it worked.
4) Read the warnings in the Messages tab.

**Comment by AntonStepanof** [comment]
I cannot reproduce this problem on last build.
I added a Condition Source Concept for the empty condition occurrence and there is n warning:
![1119](https://user-images.githubusercontent.com/48437569/56193052-75a9ad00-6038-11e9-8c60-5f991b2d5687.png)

**Comment by llhester** [comment]
Hi Anton,

I don’t have a “Messages” tab in our newest Janssen version of Atlas, so I cannot check whether this was fixed! I believe you can close out that issue if you do not see the message appearing. Thank you for checking.

Best,
Laura

**Comment by AntonStepanof** [comment]
Actually I can reproduce it after reentering to cohort definition screen. I will check that

**Comment by chrisknoll** [comment]
Hey @llhester  and @AntonStepanof , I temporarily disabled that tab in our internal env to address another issue, it will be restored to our internal env when we do our next internal upate.
