### ISSUE TITLE
Created and Updated Dates/Times Not Accurate in Cohort Pathways Tab

### ISSUE THREAD

**Issue by llhester** [OHDSI/Atlas#1120]
### Expected behavior
The created and updated dates and times in the Cohort Pathways tab should indicate when the cohort pathway was created and updated.

### Actual behavior
The created and updated dates and times in the Cohort Pathways tab shows the current date and time for all analyses.

### Steps to reproduce behavior
1) Noted that the date/time of each cohort pathway analyses was the same as the current date and time.
2) Closed out of the Cohort Pathways tab.
3) Re-entered the Cohort Pathways tab a minute later and noted that the time was recorded as minute later.

**Comment by anthonysena** [comment]
@llhester - closing this out since it was fixed with the 2.7 release.
