### ISSUE TITLE
messages tab - identifies concept as unused when they are

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1124]
### Expected behavior
messages tab identifies concepts that are truly unused and offers user to remove them (side note: using language such as 'delete it' would be preferred to using 'fix it') 
### Actual behavior
messages tab identifies concepts that are used in the cohort
### Steps to reproduce behavior
see ATLAS cohort id: 7936 for examples

**Comment by anthonysena** [comment]
I'm closing this since I duplicated this with #1250 and that issue includes a sample cohort that illustrates the problem.
