### ISSUE TITLE
Cohort Pathways language on design page

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1130]
### Request
1. Can the length of time for evaluation of the event cohorts be exposed to the user on the treatment pathway design page so that they do not have to return to the target cohort to evaluate the observation time selected? 
2. Under Event Cohorts section, the language introduces a new term which I think should read "Each Event Cohort defines the step in a pathway that may occur for a person in the **Target (not Treatment)** Cohort.
3. Also if the analysis settings options can be more clearly articulated that would be helpful; suggestions below
1. Combination window - "Window of time when two event cohorts need to overlap to be considered a combination." 
2. Minimum cell count - "Minimum number of subjects in the target cohort for a given event in order to be counted in the pathway". Sorry I'm not sure myself what this really means...
3. Maximum path length - "Maximum number of steps in a given pathway to be included in the sunburst plot."

**Comment by chrisknoll** [comment]
@jhardin29 , @johnSamilin  addressed the messaging elements of this request, but I'd like clarification on the first one:

> Can the length of time for evaluation of the event cohorts be exposed to the user on the treatment pathway design page so that they do not have to return to the target cohort to evaluate the observation time selected?

The evaluation time window comes from several elements of the cohort: start date, cohort exit settings (either 'end of observation', end of a continuous drug exposure, or a fixed time offset), censoring events, and censor window.  

What are your thoughts about summarizing those settings into a message in the pathway UI?

**Comment by jhardin29** [comment]
That would be fine to summarize those settings into a message in the pathway UI and if you have specific language in mind please share and we can discuss. Thank you for following up on this.
