### ISSUE TITLE
Screen displays  “New Concept Set” for existing concept set

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1131]
![image](https://user-images.githubusercontent.com/19151846/48637685-74e2f100-e99c-11e8-9dcc-d3d865ef1a7b.png)

**Comment by fdefalco** [comment]
Suggest this has a similar functionality to cohort definition screen and displays the current Concept Set Identifier.

![image](https://user-images.githubusercontent.com/6586384/48781691-854fe000-ecaa-11e8-866f-5f649734466e.png)
