### ISSUE TITLE
Middle section of Vocabulary retains lines from previous click

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1132]
### Steps to reproduce behavior
a)	Clicked on a concept in a concept set
b)	Viewed hierarchy
c)	Clicked on a parent in the hierarchy
d)	Shows original and parent in middle section

**Comment by jswerdel** [comment]
![image](https://user-images.githubusercontent.com/19151846/48638945-115ac280-e9a0-11e8-8522-6835d1a5f574.png)

**Comment by jhardin29** [comment]
Thanks; this was also noted this in post #1048
