### ISSUE TITLE
In Characterizations- "No changes to persist" comes up when there are changes

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1135]
## Steps to reproduce behavior
1) go into characterizations
2) select a characterization
3) make changes
4) hover over save button
5) "No changes to persist" is shown

**Comment by jswerdel** [comment]
![image](https://user-images.githubusercontent.com/19151846/48639021-4c5cf600-e9a0-11e8-9374-7f4110d4066b.png)

**Comment by pavgra** [comment]
Closed by following commits:
https://github.com/OHDSI/Atlas/commit/02b3b18626a3a96210ea4d0749314313c0324473
https://github.com/OHDSI/Atlas/commit/e74b0112a575b6add351e82a57f504dde94e00d2
