### ISSUE TITLE
Cohort Characterization generation causes other cohort characterizations screens to hang

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1136]
## Steps to reproduce behavior
1) go into characterizations
2) generate a characterization
3) wait a minute - then go open another window and go into characterizations
4) opening screen hangs

**Comment by fdefalco** [comment]
Appears to be hanging waiting on the following request:

https://epi.jnj.com:8443/WebAPI/cohort-characterization?size=10000

**Comment by chrisknoll** [comment]
Reported in WebAPI: OHDSI/WebAPI#700

**Comment by anthonysena** [comment]
Currently unable to reproduce this on the latest code base and will close this out since we can continue to track this under OHDSI/WebAPI#700.
