### ISSUE TITLE
Concept Hierarchy doesn't show correct info

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1138]
### Steps to reproduce behavior
a)	Click on a concept in a concept set
b)	View hierarchy
c)	Go back to concept set
d)	Click on concept
NOTE: if you switch tab back to details before going to the concept set it will work correctly

![image](https://user-images.githubusercontent.com/19151846/48639109-98a83600-e9a0-11e8-885b-3780de4f186f.png)

**Comment by anthonysena** [comment]
Added debugging details:

`Message: metarchy is not defined`

![image](https://user-images.githubusercontent.com/12902366/49163241-a5ab1a80-f2fa-11e8-8f2f-d84ca78c7463.png)

**Comment by anthonysena** [comment]
Fixed via https://github.com/OHDSI/Atlas/commit/31e1e16eb11d820f6ee0ffc3e90bf6ea81b3f0ac
