### ISSUE TITLE
Cost, device exposure, location tables are unavailable in Data Sources reports pull down

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1141]
### Expected behavior
select a data source, for example Optum Extended SES, select report type and look for cost or device exposure but neither are there to select

![image](https://user-images.githubusercontent.com/11822115/48642621-6cde7d80-e9ab-11e8-8bef-2905e5a5aa39.png)

**Comment by fdefalco** [comment]
These reports have yet to be developed in ATLAS.  Moving to enhancements for future release.

**Comment by anthonysena** [comment]
Closing due to age. Please see [Ares](https://github.com/OHDSI/Ares) for more information on CDM data quality exploration.
