### ISSUE TITLE
Characterization standardized difference plot requests

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1144]
### Requests
1. Please include a legend of the color and domain on or near the all prevalence covariate standardized difference plot.
2. Provide a button or method to export the plots and tables of comparisons. 
3. Provide ability to grey out those covariates that are < 0.1 in Std Diff and only have the covariates > 0.1 appear by domain color.

**Comment by anthonysena** [comment]
Related to #1320 for performance and also includes the ability to export for tables & plots. I'm going to move this into 2.7 since the ability to export tables was identified as a critical feature for characterization.
