### ISSUE TITLE
Cohort Characterization - generation button enabled before saving

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1150]
### Expected behavior
Generate buttons should not be active until characterization is saved

### Actual behavior
Generation buttons should be disabled until the characterization design is save

### Steps to reproduce behavior
Create new characterization and navigate to the generate tab, clicking generate button is possible but performs no action.

**Comment by johnSamilin** [comment]
should be fixed by #1159 
@fdefalco could you check?

**Comment by fdefalco** [comment]
Yes, looks to be resolved. Thanks!
