### ISSUE TITLE
characterization shows 3 cohort definitions when only one was imported

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#1153]
###When going to the characterization, only the cohort definitions you created should appear

###I generated a cohort on 3 databases, so I have 3 cohort definitions but its only 1 cohort that was imported.

### Created a characterization on 3 databases, closed the cohort, and then reopened it and 3 cohort definitions appeared

![image](https://user-images.githubusercontent.com/11390491/48781899-f55e6600-ecaa-11e8-9c03-59b473a8a908.png)

**Comment by anthonysena** [comment]
@rmakadia - I'm unable to reproduce this issue on the latest code. I'm going to close this out but please let me know if you encounter this again. Thanks!
