### ISSUE TITLE
prediction package name issue

### ISSUE THREAD

**Issue by jreps** [OHDSI/Atlas#1170]
After reviewing the prediction study you type a name for the study package and download it.  If you use special characters in the name for the study R will throw an error as packages cannot have special character names.  At the moment there is no check for the package name. It would be good to check the name and either show a warning instructing the user to change the name or automatically remove special characters.

**Comment by chrisknoll** [comment]
Thanks, do you know what the set of valid characters are, or should we just only allow alpha-numeric + ``_` in the name?

**Comment by ericaVoss** [comment]
Just ran into this myself.

Underscore ( _ ) is not allowed.

**Comment by anthonysena** [comment]
The only valid characters are alpha-numeric and I'll in a check to enforce that. Thanks!

**Comment by pavgra** [comment]
Closed by https://github.com/OHDSI/Atlas/pull/1337
