### ISSUE TITLE
Add R Markdown export for cohort definitions

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1181]
### Expected behavior
Provide an R markdown format friendly export.

### Actual behavior
Current text export is hard to integrate into R Markdown.

**Comment by gowthamrao** [comment]
@fdefalco I second this functionality. It is pretty cool to knit content into html or pdf's using R-markdown. I have successfully experimented getting Atlas cohort characterization (heracles results) output from WebApi endpoints in R, and rendering it in R-markdown. It would be great to have a WebApi endpoint deliver cohort definition descriptions in R-markdown friendly format.

**Comment by anthonysena** [comment]
Related to OHDSI/WebAPI#617

**Comment by chrisknoll** [comment]
This is already implemented as a function of OHDSI/CirceR, but we'll address using that function and expose endpoints in WebAPI and render the Cohort print friendly as html from the markdown source.  There still may be issues copying the markdown from the HTML in atlas into a word document, but in that case you would use the direct API in R.
