### ISSUE TITLE
"/" in Vocabulary Search String Blocks Search

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#119]
Having a "/" in the search string in the text box of the main vocabulary screen prevents the search from initiating after hitting the enter key.  An example is:
Acetaminophen / Caffeine Oral Capsule

**Comment by jswerdel** [comment]
There also seems to be the same problem with the "+"

**Comment by cerdman** [comment]
Will check on this one.

**Comment by anthonysena** [comment]
Linking to #250 and closing.
