### ISSUE TITLE
No RC/DRC counts

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1190]
### Expected behavior
search for a concept for example: 312327 - examine RC/DRC counts to evaluate utility
### Actual behavior
search for a concept for example: 312327 - no RC/DRC counts displayed
### Steps to reproduce behavior
search for a concept for example: 312327 - examine RC/DRC counts

**Comment by anthonysena** [comment]
Hi @jhardin29 - the fix for this is covered in #1175 and I'll look to deploy this into our environment soon. I'm going to close this for now but please reach out if you have any concerns. Thanks!
