### ISSUE TITLE
No hierarchy displayed

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1191]
### Expected behavior
click on concept in existing concept set to review hierarchy
### Actual behavior
click on concept in existing concept set and no hierarchy is displayed

![image](https://user-images.githubusercontent.com/11822115/50011201-75fe4280-ff89-11e8-8471-16e8b418c297.png)

**Comment by anthonysena** [comment]
@jhardin29 - the fix for this issue is covered as part of #1179 which I'll plan to deploy in our environment soon. I'm going to close this out for now but please let me know if you have any concerns. Thanks!
