### ISSUE TITLE
Is it possible Using "OMOP Common Data Model  V6" in ATLAS(ver.2.6) and WebAPI(ver2.6) 

### ISSUE THREAD

**Issue by ParkChanghHyun** [OHDSI/Atlas#1192]
### Expected behavior
I heard that  "OMOP Common Data Model  V6" was a little changed something than previous version V5.

So!! I Really want to know that **In ATLAS 2.6, Is it possible to cover "OMOP Common Data Model  V6".**

**Comment by anthonysena** [comment]
Hi @ParkChanghHyun - in short, ATLAS & WebAPI 2.6 does not provide full support for the CDM v6 specification just yet. Supporting CDM v6 is a planned goal Atlas & WebAPI for 2019. 

That said, many of the features of ATLAS will still work with a CDM v6 compliant data source but you may find that there are new portions of the data model that are not yet exposed through ATLAS. 

Hope this helps to answer your question!
