### ISSUE TITLE
Cohort Comparison between cohorts that have covariates in only one cohort, leads to mis-matched rows on cohort compare view.

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#1194]
### Expected behavior
When comparing cohorts, the value of a covariate should appear properly for both cohorts.

### Actual behavior
if the covariate is one (such as an age group) that only exists in one cohort but not the other, the 'count' column value is assigned wrong. When looking at the single-cohort view, the values of the covariates appear correctly.

### Steps to reproduce behavior
Create 2 cohorts, with mutually exclusive cohort covariates (make one cohort with age = 34 another with the age = 35.  Run a cohort characterization with age-group covariates.

Here's an example of output from our internal report:
![image](https://user-images.githubusercontent.com/6818777/50106208-288a0b80-01fd-11e9-8265-1daadae54ccc.png)

Note that the age group 20-24 shows a count of 36, but a pct of 2.9% which can not be correct since the prior row of a count of 1 is 3.7% and the next row count of 2 is 7.41%.  The age group 20-24 appears to only exist in 1 cohort, which is leading to the mismatched display (that value probably belongs to the right-hand cohort.

Looking at the measurement report:
![image](https://user-images.githubusercontent.com/6818777/50106267-625b1200-01fd-11e9-9dc1-a6819a9d4734.png)

Sorting by count shows a mismatch:  the count of 150 is 12%, however, sorting the same table by the PCT column to see the rows that have 100%:

![image](https://user-images.githubusercontent.com/6818777/50106320-8ae30c00-01fd-11e9-8e22-66876064cb6b.png)

You can see that the rows that show 100% in the left-cohort exists in the right cohort, and the 27 count is 100% of the cohort, So the prior table showing 150 count is 12% probably is the right-cohort stats shown under the left-cohort's columns.

**Comment by chrisknoll** [comment]
Due to the complexity of the reporting and the additional logic around strata, I'm going to ask the original devs that worked on this functionality to implement a fix.

**Comment by johnSamilin** [comment]
@chrisknoll could you provide an exported characterization so I could import it locally and reproduce an issue?

**Comment by chrisknoll** [comment]
Attached:
[mismatchedCC.txt](https://github.com/OHDSI/Atlas/files/2812752/mismatchedCC.txt)

**Comment by johnSamilin** [comment]
@chrisknoll unfortunately this characterization didn't give me any report after generation. Could it be possible that this issue is fixed here: https://github.com/OHDSI/Atlas/pull/1277?

**Comment by chrisknoll** [comment]
Possibly.  I'll check #1277 against this issue and see if it is resolved.

**Comment by jhardin29** [comment]
Tagging @chrisknoll and @rmakadia - this issue seems to have arisen from the ashes please see characterization #270 in prod. The counts are incorrect within each cohort/age strata. 
As reference characterizations #274, #275, and #276 are the individual cohorts, which also display incorrect counts.
