### ISSUE TITLE
Color of concepts

### ISSUE THREAD

**Issue by hripcsa** [OHDSI/Atlas#120]
I keep getting confused by colors of the concepts. Red means non-standard, and that is good. Green to me means good or go, which would be best as a standard concept. Blue is now standard but would be a good color for classification. Is there a reason why blue is standard and green is classification?

**Comment by fdefalco** [comment]
We've updated colors - Blue is still standard, Red is non-standard, and Purple is classification.  Hopefully this eliminates the confusion around green.

**Comment by t-abdul-basser** [comment]
@hripcsa
