### ISSUE TITLE
Vocabulary hierarchy display

### ISSUE THREAD

**Issue by hripcsa** [OHDSI/Atlas#121]
The current vocabulary hierarchy display is confusing. It actually looks at first like the display had a bug and misplaced the title of the second table, which is also accidentally indented. 

The other issue is that I found myself going back and forth between the hierarchy tab and the details and record counts tabs in order to compare the concept to its parents or children.

Therefore, I think I would put the concept itself in a table (one row plus header). The title of the table could be "Concept".

Then either that table could be indented halfway between the parents table and children table, or you could skip the indents and use a block arrow between succeeding tables to graphically indicate parent-child relationships.

**Comment by fdefalco** [comment]
resolved in https://github.com/OHDSI/Atlas/commit/9821d5c64572f8f4ab5847d11ebe67a9feb5046a
