### ISSUE TITLE
webAPI is blocked by enterprise policy

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#1218]
### Expected behavior
atlas works for an FDA user

### Actual behavior
webAPI is blocked, but the other search via athena works !!!
 
see below for errors

### Solution
I have an FDA IT ticket that will investigate what server needs to be unblocked by the firewall rules for ATLAS to work

Work with developer to help the FDA IT folks as much as possible

![image](https://user-images.githubusercontent.com/7526119/51040582-e1860080-1585-11e9-999a-322f7590b2c7.png)

athena website works fine (it does not use the API??)
![image](https://user-images.githubusercontent.com/7526119/51040609-f367a380-1585-11e9-83b9-24047dc9c39c.png)

![image](https://user-images.githubusercontent.com/7526119/51040648-1003db80-1586-11e9-95ec-b2f824e29bf0.png)

![image](https://user-images.githubusercontent.com/7526119/51040674-1d20ca80-1586-11e9-8e43-2ead894e9b53.png)

**Comment by gklebanov** [comment]
if we do not use a DNS name for WebAPI deployed for OHDSI - we definitely should do

**Comment by fdefalco** [comment]
I've seen similar behavior from locations in Janssen at well at times.  Tagging @leeevans

**Comment by leeevans** [comment]
I'll take a look - thanks for the info on the probable cause @gklebanov

**Comment by leeevans** [comment]
@vojtechhuser I've now updated OHDSI cloud ATLAS to use the WebAPI DNS name api.ohdsi.org instead of the IP address

**Comment by vojtechhuser** [comment]
I am pleased to report that the DNS change (and my ticket to FDE ERIC system (IT system) did it and it works now.  @fdefalco @gklebanov @leeevans  Thank you!
