### ISSUE TITLE
Navigation structure

### ISSUE THREAD

**Issue by hripcsa** [OHDSI/Atlas#122]
I am getting confused by the menu on the left. I am used to left menus being for navigation, but this left menu is really just a shortcut bar. If we just want shortcuts, then they should be at the bottom of the screen. If the left menu is for navigation, then we need a consistent navigation model. For example, at the top of the screen, there can be "Concept" or "Concepts" and those are two different places. And "Concept" does not appear anywhere on the left, so it is not clear where you are.

One approach would be to show the hierarchy using arrows like "Vocabulary --> Concept" on the top of the main display to signify that you are under vocabulary. I think every screen should feel like you are under one of the left menu items.

"Data source" doesn't let you choose a data source for use elsewhere, so I would rename that item "Browse data" because that is what it really does.

I really get confused by the new left menu item appearing at the top. E.g., a particular cohort or concept set. It doesn't set the context, because it is not applied to other menu items. It is really just another shortcut to get there quickly. I know that Atlas used to put these things under the corresponding menu items, which I liked. There must have been some reason for the change. But either way, I do not like confusing the left navigation menu with a shortcut.

**Comment by fdefalco** [comment]
Thanks for the feedback - I will certainly try to incorporate it as the UI evolves.
