### ISSUE TITLE
constant polling of sources and generation on pathway page

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1225]
I'm witnessing constant polling on a pathway design page for both sources and generation status for a job that is completed.  The polling should stop if the generation is marked as completed.  Sources shouldn't be polled for every 30 seconds, their cached values should be used for the duration of a session.

![image](https://user-images.githubusercontent.com/6586384/51194149-78212d00-18b8-11e9-97b5-d5e34645aa1e.png)

**Comment by pavgra** [comment]
![image](https://user-images.githubusercontent.com/10010071/51615398-c1473180-1ef5-11e9-9239-a1f8fa849683.png)
