### ISSUE TITLE
All tables sorting for dates works incorrectly

### ISSUE THREAD

**Issue by johnSamilin** [OHDSI/Atlas#1226]
![image-2019-01-15-13-26-09-136](https://user-images.githubusercontent.com/5821894/51244686-b725b000-1996-11e9-9315-87196abb40de.png)

**Comment by pavgra** [comment]
![image](https://user-images.githubusercontent.com/10010071/51611455-44b05500-1eed-11e9-8315-d3b3e22f2286.png)
