### ISSUE TITLE
In 'Data sources' (ACHILLES) view, table views should allow user to choose which columns to show

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#123]
Use case:  curently table doesn't show CONCEPT_ID, but we want to be able to view it sometimes (like when we see a concept in the summary, and want to then go back into vocabulary browser to explore it further).    Currently table view does not have the same 'column chooser' that is used in other parts of ATLAS.  Can we make the table component consistent throughout?

**Comment by fdefalco** [comment]
column chooser and standard datatable DOM applied to data sources view.
https://github.com/OHDSI/Atlas/commit/60f9c5de62637435fb883d09a89851c13876f402
