### ISSUE TITLE
Component disposal promoted from Page class

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1249]
From a review with @chrisknoll, I'd like to propose promoting the `dispose()` method and `subscription` property from the `js/page/Page.js` class to the `js/components/Component.js` class, All components that extend `Component` should have a dispose() method that is declared with a base implementation that performs the cleanup. Since `Page` extends `Component`, it could then use the inherited `subscription` property as it does now.

Tagging @wivern @pavgra for their thoughts.

**Comment by chrisknoll** [comment]
I like this since it gives us a consistent 'subscription disposal' construct that any component can leverage, without having to come up with multiple implementations on how to track the component's subscription.

**Comment by pavgra** [comment]
@anthonysena , due to missed deadlines I'd propose to move the issue into 2.8 milestone
