### ISSUE TITLE
Tagging & Annotating entities

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#125]
The list of cohorts/concept sets is getting harder to navigate since we lack the ability to personalize the list based on the current user. It would be useful to have a global tagging system that would enable someone to tag any entity in the system (cohort, concept set, etc) to allow for better organization of items.

**Comment by fdefalco** [comment]
As I'm working on other things it occurred to me that the "selected tags" should be stored for the duration of a session. That way once you set your tags any asset browsing will be limited to those tags.  In addition we could default users to a set of tags that we determine to be appropriate, such as only 'approved' cohort definitions.
