### ISSUE TITLE
Cohort check incorrectly flags concept set as unused when it is part of the definition

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1250]
### Expected behavior

When defining a cohort, the "Messages" tab properly indicates concept sets that are not used as part of the cohort definition. 

### Actual behavior

Sometimes concept sets are improperly identified as "not used" when they are.

### Steps to reproduce behavior

Import this [cohort_check_example.txt](https://github.com/OHDSI/Atlas/files/2788740/cohort_check_example.txt) into Atlas using the code currently on master and you'll be able to reproduce the bug for "Suicide attempt"

**Comment by pavgra** [comment]
@anthonysena , could you get a look if this issue describes the same problem as https://github.com/OHDSI/Atlas/issues/1124 ?
