### ISSUE TITLE
Some piecharts in Heracles reports take too much space

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1255]
E.g. "Drugs by Type" in "Drug Exposure" report:

![image](https://user-images.githubusercontent.com/10010071/51646413-6d186d80-1f46-11e9-83ad-1819e7f155b1.png)

**Comment by pavgra** [comment]
Also "Procedures by Type" in "Procedure" drilldown

**Comment by mpozhidaeva** [comment]
Fixed 
- Condition -> conditionsByType
- Drug Exposure-> drugsByType
- Procedure -> proceduresByType
