### ISSUE TITLE
Heracles "Data completeness" report throws exception

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1258]
![image](https://user-images.githubusercontent.com/10010071/51647493-0fd2eb00-1f4b-11e9-9a8d-cc9b696897d9.png)

**Comment by vlbe** [comment]
@anthonysena, is it ok to have negative values for genderP/raceP/ethP?  Cause if we get negative values in response data, d3 throws error in console. Maybe we should transform negative values to 0?
![data](https://user-images.githubusercontent.com/47257857/52425106-5fe5ac00-2b0c-11e9-8778-26b8fa1d2ec9.PNG)

![d3_error](https://user-images.githubusercontent.com/47257857/52424954-17c68980-2b0c-11e9-9872-81451ef3d371.PNG)

**Comment by pavgra** [comment]
@vlbe , the negative values do not seem to be OK. @ssuvorov-fls will get a look at why this happened from middle-tier point of view

**Comment by anthonysena** [comment]
@vlbe - No, those values should be >=0 based on OHDSI/WebAPI#223. This is likely a bug somewhere in the middle tier processing.

**Comment by ssuvorov-fls** [comment]
"-999" is the default value when no data found for the age interval, it can be found in "runHeraclesAnalyses.sql".
Is zero value valid in such case? 
If I change the script it will only affects new reports, for the old ones the migration script is needed

**Comment by chrisknoll** [comment]
I would think that a count of 0 would be a valid value for the case where no records were found in that age group.

> If I change the script it will only affects new reports, for the old ones the migration script is needed

we don't have migrations scripts for the results schema (if you mean 'migration scripts' = flyway scripts), but we can either ask people to re-execute their analysis to see the correct result, or give them an update script to run manually to correct the data. Normally we just tell people to re-run.

**Comment by pavgra** [comment]
@chrisknoll, I suggest to display dashes instead of 999 and therefore don't draw such items on a chart if no records were found. The reason is that 0 is for No valid data whereas lack of records at all doesn't mean that data is invalid (same as `null` vs `0`). Also, such solution is going to be UI only and wouldn't require any migrations

**Comment by anthonysena** [comment]
@ssuvorov-fls - You are correct that the query uses "-999" as a default and so for the purposes of fixing this bug, I'd suggest we treat it as a 0 value for the purposes of the d3 rendering and in the table display, we can use "-" to show there was no data. Thanks!
