### ISSUE TITLE
concept sets error 

### ISSUE THREAD

**Issue by DaeIlYang** [OHDSI/Atlas#1273]
You go into Atlas concept sets.   

Attempting to find an optimal definition for this concept set....
The current concept set definition is fully optimized.
Please review the optimized definition and options for saving.

A different screen appears with the message atlas. If you know the cause, please answer.

**Comment by anthonysena** [comment]
Hi @DaeIlYang - could you please provide some further information to help us better understand your issue? It would be helpful to know: what version of Atlas/WebAPI you are using and the concept set definition JSON you are using that is causing the problem?

The concept set definition JSON is found in the export tab under the concept set definition. Thanks!
