### ISSUE TITLE
Data Sources / Procedure report - Frequency Distribution plot 

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1282]
### Expected behavior

On the Data Sources / Procedure Occurrence report, in the Frequency Distribution graph, hoverover a value should show the x-axis (count) and y-axis (% of total number of persons) values, with the appropriate units.

### Actual behavior

It is unclear to me what the tooltip is showing.  I think it might be the integer value matching up to the y-axis %.

![image](https://user-images.githubusercontent.com/731930/52077566-503ff380-255f-11e9-8c11-36cf14f5ff1c.png)

### Steps to reproduce behavior

Hoverover a value on the Data Sources / Procedure Occurrence report, in the Frequency Distribution graph

**Comment by pbr6cornell** [comment]
The y-axis is showing 4 decimal places, but then the values appear to be rounded to integers.  I think y-axis could be rounded to integer, but the plotted values could be more precise as needed (and shown on hoverover to 2 decimal places as required).

**Comment by pbr6cornell** [comment]
The graph appears to be rounding values to integer.  We need to display values to 2 decimal.

**Comment by pbr6cornell** [comment]
Note, this plot, now I see 2 decimals on plot, but the value is still integer based.  I think the problem is we're pulling back rounded values when we shouldn't be.

![image](https://user-images.githubusercontent.com/731930/58676002-baf21780-8324-11e9-979f-dc64066b4d62.png)

I'm ok to wait until v2.8, but lets not close this until we confirm it's actually fixed.

**Comment by anthonysena** [comment]
Closing since this appears to be fixed.
