### ISSUE TITLE
Cannot generate or save features to an existing characterization

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1284]
### Expected behavior
When updating an existing characterization with additional feature analyses, should be able to save changes and generate on data sources. 

### Actual behavior
When updating an existing characterization with additional feature analyses, cannot save changes or generate on data sources.
### Steps to reproduce behavior
Using epibeta.jnj.com characterization #27 add feature analyses - demographics age group, age etc; click save button. Please see attached error pages. 
![characterizationerror](https://user-images.githubusercontent.com/11822115/52080003-ce52c900-2564-11e9-8be0-234683760489.jpg)
![characterizationerror1](https://user-images.githubusercontent.com/11822115/52080005-ce52c900-2564-11e9-8da9-35523e281f29.jpg)

**Comment by aklochkova** [comment]
@jhardin29 Hello! Could you please attach this characterization here?
And please describe permissions which do you have for this characterization.
I cannot reproduce this behaviour: if I have 'generate' and 'put' permissions everything is saved ok and Generate button is enabled.

**Comment by pavgra** [comment]
@anthonysena , would it be possible to check the presence of the issue using the latest codebase?

**Comment by anthonysena** [comment]
I'm unable to reproduce this bug on the latest code base - I'm going to close this out but @jhardin29 please re-open this if the issue persists. Thanks!
