### ISSUE TITLE
Data Source / Death report - Death prevalence by month needs appropriate precision

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1286]
### Expected behavior

Data Sources / Death Report, Death prevlaence by month report, shows prevalence per 1000 persons .  the Y-axis and plotted values should be an appropriate precision to show values.

### Actual behavior

Currently on this plot, with y-axis rounded to integer, all values are 0 on y-axis and hoverover on any value also showed value of 0.  likely need decimal points?

![image](https://user-images.githubusercontent.com/731930/52083548-b6cc0e00-256d-11e9-89f9-a830769fd840.png)

### Steps to reproduce behavior

Look at Data Sources/Death report, Death Prevalence by Month plot.

**Comment by anthonysena** [comment]
For reference, here is a snippet of the "prevalenceByMonth" section returned from the WebAPI call: `WebAPI/cdmresults/<source_key>/death`

#### Response snippet

```
"prevalenceByMonth": [{
			"xCalendarMonth": 200104,
			"conceptId": 0,
			"conceptName": null,
			"yPrevalence1000Pp": 0.00397496797,
			"numPersons": 0
		}, {
			"xCalendarMonth": 201208,
			"conceptId": 0,
			"conceptName": null,
			"yPrevalence1000Pp": 0.010299582284,
			"numPersons": 0
		}, 
```
