### ISSUE TITLE
Data Sources / Death report:  toggling between sources produces error

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1287]
### Expected behavior

On Data Sources / Death report:  when on a report for a given database, switching to a different database should refresh the report without error.

### Actual behavior

![image](https://user-images.githubusercontent.com/731930/52083829-89339480-256e-11e9-8e13-7939b7779ff7.png)

### Steps to reproduce behavior

On Data Sources / Death report:  Selected first database.  Then switched to different database in list.

**Comment by YangDaeIl** [comment]
I am also waiting for an answer.

**Comment by pavgra** [comment]
@anthonysena , could you try to reproduce the issue with the latest codebase? We were not able to catch the issue

**Comment by anthonysena** [comment]
@pbr6cornell I'm unable to reproduce this on the latest code base in our beta environment so I'm going to close this out. Thanks!
