### ISSUE TITLE
displaying seconds in timestamp label make it too long and have no value

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#1288]
### Expected behavior
While full date.time stamp is saved in the database, but created / update label displayed (cohorts, concepts sets, etc..) should probably not contain seconds in it. Seconds are just taking extra space and make it look too crowded while does not have any value to the user by itself. Never mind I am not even sure seconds are consistently capture as they are 00 in most of the cases

![image](https://user-images.githubusercontent.com/26966141/52084013-0ced8100-256f-11e9-9cb7-8b51ac4f4cf9.png)

### Actual behavior

Proposal - do not display seconds in labels on screen
01/28/2019 11:20 AM

**Comment by vlbe** [comment]
@gklebanov , could you check again? I think this was fixed in https://github.com/OHDSI/Atlas/pull/1292

**Comment by pavgra** [comment]
Right, it was closed in #1292
