### ISSUE TITLE
Concept set names and cohort names are not unique

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#1307]
### Duplicates are in production

Cohort ID 8700 and 8405
Concept ID 101 and 102 & 7780 and 5892

###

**Comment by anthonysena** [comment]
At the moment, we do not enforce unique names on cohort definitions but I've opened a new issue (#1338) to make sure we're doing that for all items in the system. For now, I'll focus on making sure that concept set names are unique in the system since that was established functionality.
