### ISSUE TITLE
Limited number of cohort correlated criteria 

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/Atlas#1308]
### Expected behavior
User can enter any positive number of correlated criteria occurrences 
### Actual behavior
The maximal number of correlated criteria is set to 10
![limited_correlated_criteria](https://user-images.githubusercontent.com/25959256/52339687-77426d80-2a16-11e9-9f4f-2bd7bac2dd6a.png)

**Comment by twamarc** [comment]
Good! keep us informed when this is improved!

**Comment by pbr6cornell** [comment]
+1 for this request, as it came up in a design session today:)  glad to see it on ATLAS 2.8 roadmap.
