### ISSUE TITLE
cohort generation process failed !!!

### ISSUE THREAD

**Issue by DaeIlYang** [OHDSI/Atlas#1317]
A failure occurred in the cohort generation process.

I am using atlas 2.6 and WebAPI 2.6 and dbms is sql server.

I checked the log.
The log is as follows.

insert into slh.dbo.cohort_summary_stats (cohort_definition_id, base_count, final_count, mode_id)
select 4 as cohort_definition_id, PC.total as person_count,coalesce(FC.total, 0)as final_count,1 as mode_id
FROM
(select count_big(event_id) as total from #best_events) PCs,
(select sum(sr.person_count) as total
from slh.dbo.cohort_include_result sr
CROSS JOIN (select count*) as total_rules from slh.dbo.cohort where cohort_definition_id = 4) RuleTotal
where sr.mode_id = 1 and sr.cohort_definition_id = 4 and sr.include_rule_mask = POWER (cast(2 as bigint),RuleTotal.total_rules)-1
) FC

Wait for an answer.
Thank you.

**Comment by chrisknoll** [comment]
Can you confirm that the tables slh.dbo.cohort_summary_stats, dbo.cohort_include_result and slh.dbo.cohort exist?

**Comment by DaeIlYang** [comment]
The slh.dbo.cohort_summary_stats table and slh.dbo.cohort exist.
You mean slh.dbo.cohort_include_result table slh.dbo.cohort_include_result? The slh.dbo.cohort_include_result exists.
