### ISSUE TITLE
cohort generation process failed 

### ISSUE THREAD

**Issue by DaeIlYang** [OHDSI/Atlas#1318]
A failure occurred in the cohort generation process.

I am using atlas 2.6 and WebAPI 2.6 and dbms is sql server.

I checked the log.
The log is as follows.

insert into slh.dbo.cohort_summary_stats (cohort_definition_id, base_count, final_count, mode_id)
select 4 as cohort_definition_id, PC.total as person_count, coalesce(FC.total, 0) as final_count, 1 as mode_id
FROM
(select count_big(event_id) as total from #best_events) PC,
(select sum(sr.person_count) as total
  from slh.dbo.cohort_inclusion_result sr
  CROSS JOIN (select count(*) as total_rules from slh.dbo.cohort_inclusion where cohort_definition_id = 4) RuleTotal
  where sr.mode_id = 1 and sr.cohort_definition_id = 4 and sr.inclusion_rule_mask = POWER(cast(2 as bigint),RuleTotal.total_rules)-1
) FC

Wait for an answer.
Thank you.

**Comment by DaeIlYang** [comment]
@chrisknoll 
The slh.dbo.cohort_summary_stats table and slh.dbo.cohort exist.
You mean slh.dbo.cohort_include_result table slh.dbo.cohort_include_result? The slh.dbo.cohort_include_result exists.

**Comment by DaeIlYang** [comment]
This error occurs when sql is turned from sql server.
(Displayed in red)
Event_id, #best_event two parts are error.

**Comment by YangDaeIl** [comment]
Oh, thank you. My mistake!

**Comment by chrisknoll** [comment]
If there is no issue here, please close the issue. Otherwise, please provide additional details (such as, what the text of the error message is) and we will investigate.
