### ISSUE TITLE
Atlas initiatlization error

### ISSUE THREAD

**Issue by mgkahn** [OHDSI/Atlas#132]
See attached screen shot of Atlas demo
![atlas_initialization_error](https://cloud.githubusercontent.com/assets/3923918/15519616/8bca451e-21bf-11e6-9e03-1d35e0d3922c.jpg)

**Comment by mgkahn** [comment]
Working spontaneously now....

**Comment by chrisknoll** [comment]
Saw that earlier myself!  Something with caching, after refreshing browser it came up.  But you're not crazy, i saw that too!
