### ISSUE TITLE
Cohort definition editor - gender selection doesn't update dirty flag

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1321]
### Expected behavior

When creating a cohort definition with a gender condition, I expect that when I add/remove an item to the list that it allows me to save after detecting a change.

### Actual behavior

Adding/removing items from the gender list does not appear to update the dirty flag that should indicate that a save is required.

### Steps to reproduce behavior

Create a cohort, add an entry event for "any visit" and an attribute criteria of "gender". Save the cohort. Next, add a gender of "Female" and note that the save icon is not active to allow for a save.

**Comment by chrisknoll** [comment]
@pavgra , this is related to the changes made when the optimizations to the dirty checks were being performed: the change to the dirtyFlag.  I can confirm that adding/removing the gender to the criteria is leading to a different JSON form, so the dirty flag should ahve seen this, but we're not doing json-to-json comparisons anymore...and it looks like @anthonysena found a corner case.

For reference, this is the Primary Criteria without the gender:
```
  "PrimaryCriteria": {
    "CriteriaList": [
      {
        "DrugEra": {
          "CodesetId": 0,
          "First": true,
          "Gender": []
        }
      }
    ],
```

And with the gender concept specified:

```
  "PrimaryCriteria": {
    "CriteriaList": [
      {
        "DrugEra": {
          "CodesetId": 0,
          "First": true,
          "Gender": [
            {
              "CONCEPT_CODE": "F",
              "CONCEPT_ID": 8532,
              "CONCEPT_NAME": "FEMALE",
              "DOMAIN_ID": "Gender",
              "VOCABULARY_ID": "Gender"
            }
          ]
        }
      }
    ],
```

So, clearly very different, and should signal the dirty flag.

**Comment by chrisknoll** [comment]
One theory is that this is related to fields that are of type `Array` vs any other literal type or object.
