### ISSUE TITLE
Prefered web browser to use for Atlas?

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/Atlas#133]
I am using Atlas on Firefox and I see some weird issues here and there. Here is my list:

1) Cohort generation: Click on generate and I don't see the button change to the 'running animation'... sometimes. Then the dates get all garbled up. I need to basically re-load my Atlas browser window and refresh a couple of times. Sometimes the button does change... but stays like that even after the job completes. 

2) Reporting: I don't see any explanation of what the exclamation sign with a circle or triangle means (might be a missing feature). 
- When I generate the reports, I also need to re-load the Atlas browser window and refresh to see the reports appear. 
- When trying to zoom into the treemaps, it does not happen, just a white border gets highlighted around the full treemap and nothing happens. 

3) Notification messages: This I don't think is a bug, but rather a feature request. Every time I click on something that will take a while (cohort generation, report generation) I don't see any status messages leaving me wonder if anything is going on. This should be quite useful as I have to go over to the tomcat/apache log files to see if anything is actually going on.

Great job on this tool! Atlas is looking great and works pretty well. I hope some of the smaller issues are an issue with my browser.

**Comment by fdefalco** [comment]
We're all using Chrome here at least and its the recommended browser.

There is a known race condition that is causing that generate bug where the buttons do not stay linked to the job status that you are seeing (#112), we're aware of it and working on a resolution.  We are also aware of the lack of appropriate feedback on the report generation at this time, again, something we're working on resolving but is low priority as so far the reporting features are somewhat under-utilized.  Happy to see someone taking advantage of them though, so we'll try and get that issue cleared up.

**Comment by anthonysena** [comment]
#147 - let's make sure that the documentation includes a mention that Chrome is the preferred browser.

**Comment by anthonysena** [comment]
I've noted this on the ATLAS documentation: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas.

**Comment by jhardin29** [comment]
thanks Anthony!
