### ISSUE TITLE
Record counts in search not displayed

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1334]
### Expected behavior
Go to Search page, search for concept, for example 4319466, click on the concept link, click on the record counts tab, should see record counts
### Actual behavior
Go to Search page, search for concept, for example 4319466, click on the concept link, click on the record counts tab, do not see record counts
### Steps to reproduce behavior
Go to Search page, search for concept, for example 4319466, click on the concept link, click on the record counts tab

**Comment by jhardin29** [comment]
This issue is in prod not beta - i understand now that it will be fixed with the next release; apologies!

**Comment by anthonysena** [comment]
No problem @jhardin29 - I'm going to close this since it was addressed with #1064.
