### ISSUE TITLE
Closing concept set in a cohort and then starting a new one retains the previous concepts

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#134]
When working with a concept set that is saved as part of a cohort definition, upon closing the concept set and going to vocabulary search to create a new concept set in HIX, if you put a concept in your shopping cart the new concept set will automatically contain all of the concepts that were present in the set you just closed.

**Comment by anthonysena** [comment]
This appears to be closed with v1.2.0 #203
