### ISSUE TITLE
Which version is the stable version of Atlas?

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/Atlas#1342]
### Expected behavior
Clone master, add config-local.js, Atlas to load properly
### Actual behavior
Atlas splash screen gets stuck because of missing dependencies. 
![image](https://user-images.githubusercontent.com/10423944/52915051-3fdc8800-3284-11e9-8c22-65c5959bd0c8.png)

Caused by this line (in index.html):
```
<script src="node_modules/bowser/bundled.js"></script>
```
There are is not path ./node_modules in the code repo. 

The issue dependency issue is worse with version tagged: 2.6.0. The latest version is a branch of 2.5.2.... so which version is the actual newest/stable/working one?

### Steps to reproduce behavior
Clone master, add config-local.js check in Chrome browser

**Comment by pavgra** [comment]
@jmbanda , install NodeJS and execute `npm i` in the root of the Atlas folder

**Comment by jmbanda** [comment]
Thanks! Will this be documented at some point? The installation
instructions ommit this step.

**Comment by jmbanda** [comment]
New error after installing NodeJS and doing npm i
![image](https://user-images.githubusercontent.com/10423944/52919702-10487280-32ba-11e9-8113-bc44c05e7b34.png)

**Comment by NEONKID** [comment]
Do you want to try this command?
```npm run build```

**Comment by anthonysena** [comment]
Hi @jmbanda - just noticed this was still open. The latest stable version is [v2.7.1](https://github.com/OHDSI/Atlas/tree/v2.7.1) and the [v2.7.0](https://github.com/OHDSI/Atlas/releases/tag/v2.7.0) release describes the process for building ATLAS using npm as described in this thread. I'm going to close this out but please let us know if you are still facing issues.
