### ISSUE TITLE
Limit CC Prevalence results to minimum prevalence threshold

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#1357]
Related to #1142.  The following is a proposal for a stop-gap measure to address page hanging on viewing Cohort Characterization reports

### Expected behavior
By default, when fetching prevalence reports, we do not want to pull down those covariates that have very small prevalence in the overall cohort (either count < 10 or prevalence < .01 (1%).  This would reduce the co-variate payloads by ~80% in normal cases because in large cohorts, usually there's many 'one off's' that lead to > 20k records that would otherwise be < 4k records with the filter applied.

When exploring the hierarchy, however, we can allow all records to be returned because the nature of exploring a hierarchy would limit the records in a way that restricting by prevalence is not required.  Also, this lets you see the 'full picture' only when exploring a hierarchy. 

### Actual behavior
All data is returned leading to page hangs.

**Comment by pavgra** [comment]
I would go for percentage filter (`< .01 (1%)` ) instead of an absolute one because there might be cases when there are 100 people at all in cohort (so the absolute filter will cut out too much)
