### ISSUE TITLE
Data source reports contain hidden age decile line graphs and NaNs

### ISSUE THREAD

**Issue by mark-velez** [OHDSI/Atlas#137]
Age decile line graphs are hidden and showing the text "NaN" (see screenshot below). The impacted age deciles differ depending on the selected concept. We suspect it could be related to outliers in the data, but it is unclear.
![hidden-line-graph-nan](https://cloud.githubusercontent.com/assets/8049605/15825073/5083dcf2-2bd0-11e6-8385-4371cccc324f.PNG)

**Comment by chrisknoll** [comment]
The age decile graphs (I believe) have some pre-processing on the raw data file (from the JSON request) that creates the different trellis and series of data into a nested structure, and it does some work to fill in the blanks so each trellis has the same amount of data (such as one age decile has years 2004-2008 and another decile has 2007-2011, and so the final dataset to be graphed should cover years 2004-2001).  So something could be happening inside here that results in NaN.  

I am not sure if it's possible to share the JSON files (the condition occurrence json and the specifc conceptID json file that has the drilldown data), that would make it easier to debug this issue on my side, but I understand the concerns about sharing this data, so if you can't share, then I'd suggest setting breakpoints and reviewing how your source data is being transformed before being rendered in the plot.

**Comment by mark-velez** [comment]
Thanks @chrisknoll, I set breakpoints as you suggested (maybe we can share the data offline if we cannot solve it on our side). I see that an exception is encountered on [this line of code in jnj.chart](https://github.com/OHDSI/Atlas/blob/master/js/jnj.chart.js#L1868) when those deciles are being processed, `d.values` contain objects whose `Y_PREVALENCE_1000PP` is `0`. Sorry, I'm not well acquainted with this part of the code, but is it possible this might lead to division by zero, hence `NaN`? Are you inclined to say that we have some nonsensical Achilles json output or that the client is not processing valid json appriopriately?

**Comment by chrisknoll** [comment]
I think it's reasonable that you could show a prevalence for a given year of 0.  Example, in the 80-90 age range, you might have a case where the censor all 80+ people from the data, so nothing appears there.

What I can try to do on my side is take the synpuf dataset and manually change the prevalence values to be 0 for a series of the dataponts, and see where the erorr is comming from. It could be dcomming from the following places:

1) A divide by 0 (tho, not sure we're ever dividing the y values)
2) the d3 line() construct is working with the raw data oddly resulting in NaN.

That's all I got :)  Let me see if I can replicate the data situation of 0's for y prevlanece (tho i'm sure that must have happened in the past before!) and see what I can find.

**Comment by mark-velez** [comment]
Indeed, these values appear to have been pre-processed/normalized at the time the exception occurs because they do not directly correspond to the raw JSON output where all `Y_PREVALENCE_1000PP` values are non-zero. Thanks for any help @chrisknoll, I'll also try some experiments and follow-up.

**Comment by mark-velez** [comment]
I took a condition_occurrence json file which did **not** exhibit the visualization problem. I set the first value of the `Y_PREVALENCE_1000PP` array to `0`. This appears to reproduce the issue in a single point (as depicted in the 20-29 decile below). Please let me know what you think.
![one-zero-point](https://cloud.githubusercontent.com/assets/8049605/15941868/0eaf0efa-2e50-11e6-8f72-d45e76c8bd74.PNG)

**Comment by chrisknoll** [comment]
Good good!  One thing that's odd is where that NAN is appearing on the plot while the other points show a number.  But it's good you reproduced this, makes it much easier to dig in.

**Comment by chrisknoll** [comment]
@mark-velez ,
 I added a comment in the PR about a possible alternative fix to handle the case where the property is provided but set to NULL:
https://github.com/OHDSI/Atlas/pull/141

Let me know your thoughts.
