### ISSUE TITLE
Concept Import for Cohort Concept Set Fails

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1372]
### Expected behavior

I can import a list of concept IDs to create a cohort concept set.

### Actual behavior

Get the following failure:

![image](https://user-images.githubusercontent.com/12902366/53246530-0094a980-367f-11e9-9452-8b5e1e27fd94.png)

### Steps to reproduce behavior

Create a new cohort
Go to the concept set tab
Create a new concept set
In the Concept Set definition, click Import
Under the Concept Identifiers, use the text box and enter a concept id or multiple (separated by commas).

**Comment by pavgra** [comment]
Closed by https://github.com/OHDSI/Atlas/pull/1373
