### ISSUE TITLE
Cannot compare concept sets

### ISSUE THREAD

**Issue by johnSamilin** [OHDSI/Atlas#1379]
###Actual behavior
`VocabularyAPI.getDeafultSource()` returns `undefined`
### Steps to reproduce behavior
Compare concept sets on the concept set page

**Comment by johnSamilin** [comment]
![image](https://user-images.githubusercontent.com/5821894/53336534-a2cac080-390f-11e9-92e6-47f23448dec4.png)

**Comment by anthonysena** [comment]
@johnSamilin - I think the code you have may be older. The latest code on master for concept set compare utilizes the code in `js/services/Vocabulary.js` which does not have this issue. Would you mind checking? Thanks!
