### ISSUE TITLE
Add ability to match on visit id

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#138]
Currently, matching criteria in cohort building is time-based from the primary criteria. Visit generation in CDM ETLs is a bit of a mixed bag, but even still, it might be useful to allow for matching specifically on a visit_id rather than on just a day range relative to an index event. Then, you could find inpatient visits with a primary condition and limit that based on if other conditions occurred during that same visit rather than using a day range and assuming the visits are the same.

**Comment by fdefalco** [comment]
This isn't an ATLAS issue, please post in WebAPI or Circe-be if the problem persists.
