### ISSUE TITLE
Unauthorized error message is not displayed

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1420]
There is no error message regarding the lack of permissions on following Atlas pages for unauthorized user:
- Search
- Concept Sets
- Estimation
- Prediction
- Jobs

\+ in some pages AJAX requests are attempted to be done even though there are no perms

**Comment by johnSamilin** [comment]
Is authentication enabled?

**Comment by pavgra** [comment]
![image](https://user-images.githubusercontent.com/10010071/53883365-c912ef00-3fe6-11e9-88b1-a0a6e23930d0.png)

![image](https://user-images.githubusercontent.com/10010071/53883378-d62fde00-3fe6-11e9-9f2a-a5d663fc79d0.png)

![image](https://user-images.githubusercontent.com/10010071/53883409-e9db4480-3fe6-11e9-8a4b-6241d3623bd1.png)

**Comment by anthonysena** [comment]
Closed via #1435
