### ISSUE TITLE
Characterizations - Stratas  should it be renamed Subgroup analyses?

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1426]
### Expected behavior

In epidemiology, stratification is most commonly associated with partitioning a population into 2 or more mutually exclusive sub-populations.   Examples are 'stratify by gender' splits a population into Male or Female, stratify by age splits a population into various distinct age groups (e.g. age<18, age18-65, age>65).  It is also common that if one were to define a 'stratification factor', that one would expect to see whatever summary statistics produced within each strata (which would include the sub-population that satisfied the stratification criteria, and separately, the sub-population that did not satisfy the stratification criteria).   In ATLAS, the Incidence Rate tool offers the notion of 'stratification' and partitions the incidence estimates by these stratification criteria, individually and in aggregate.

In contrast, 'subgroup analysis' is the act of selecting a sub-population that means some inclusion criteria and examining statistics within the sub-population.   It is possible to define multiple subgroup analyses, and there is no expectation that each subgroup be mutually exclusive.  For example, I could do one subgroup analysis of 'Gender=Female' and a different subgroup analysis of 'Age > 65', recognizing that 'women age>65' are contained within both subgroups.

The new Characterization - 'Stratas' capabilities appears to be acting more like a capability to generate 'subgroup analyses' than 'stratification', in that each criteria are independently defined and do not necessarily produce mutually exclusive sub-populations.  

So, assuming I have that right, I would recommend renaming this section heading 'Subgroup analyses', and then rename the bullet: 'New subgroup', and the checkbox 'Calculate subgroup analyses only'.

But if I am not understanding the functionality and it is indeed doing proper stratification (subsetting population into mutually-exclusive sets), then I think we should determine how to describe that behavior appropriately and consider checks that can be perhaps to ensure subgroups are not overlapping.

**Comment by pavgra** [comment]
@pbr6cornell , you are absolutely right. Thanks for the proper naming suggestion!
