### ISSUE TITLE
Jobs notification not updating properly

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1430]
### Expected behavior

All jobs are listed in notifications with appropriate status, duration, end time

### Actual behavior

1) Not all jobs submitted are listed in notifications (example below, I'm running 3 sources but only 2 appear in notifications)

2) Jobs that successfully completed are not listed as completed (example below, IR Analysis 42 is completed on all 3 sources, but only 1 got marked as completed),

![image](https://user-images.githubusercontent.com/731930/53929446-c69eac80-405b-11e9-9d46-c7bae7ddaf5c.png)

### Steps to reproduce behavior

Kick off jobs and then open up notifications.

**Comment by anthonysena** [comment]
Closed via #1475 and OHDSI/WebAPI#942
