### ISSUE TITLE
Support launching Achilles jobs from Atlas

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Atlas#145]
Modify Atlas to support start, monitoring of major Achilles R features as batch jobs, i.e. to support start OHDSI/Achilles analysis + Heel (OHDSI/IRIS R package)via R Service Bus. 

Depends on RSB implementation.

**Comment by alondhe** [comment]
Assuming Shiro isn't available to lock down who can run Achilles via this method, could this be a bit flag in the repository db per daimon? Then anyone could kick off Achilles for a new daimon initially, but subsequent attempts would be prevented. You'd have to manually update the flag if you want to allow it to be re-run, a permission that only the DBAs would have.

**Comment by fdefalco** [comment]
We are making progress on the SHIRO integration so this might just be something we hold off on until we have that enabled.

**Comment by t-abdul-basser** [comment]
@alondhe @fdeflaco Agreed. It would be ideal if this feature were implemented with Shiro-provided access control.

**Comment by anthonysena** [comment]
Closing this and linking to OHDSI/WebAPI#505 since the idea of running Achilles via a shared set of components is mentioned there.
