### ISSUE TITLE
Achilles - description says cohort, should be datasource

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#1458]
### Expected behavior
![image](https://user-images.githubusercontent.com/13936600/54003701-14311d00-4121-11e9-97a9-0d31a68c799d.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/13936600/54003618-c9170a00-4120-11e9-927c-13f3e4ad1afd.png)

**Comment by anthonysena** [comment]
@aklochkova please note that this is on the Person report under Data Sources.
