### ISSUE TITLE
Characterization import missing features

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1459]
### Expected behavior

Imported a cohort characterization created in v2.6 ([cc-225.txt](https://github.com/OHDSI/Atlas/files/2944233/cc-225.txt)) into a different environment with Atlas running v2.7.0-rc. Expected that the 2 cohorts and 10 feature analyses defined in the exported JSON would properly transfer all design choices.

### Actual behavior

The 2 cohorts transferred well but only 1 feature was imported:

![image](https://user-images.githubusercontent.com/12902366/54004890-50667c80-4125-11e9-9aa3-2d22e99c120e.png)

### Steps to reproduce behavior

Import the attached export into a v2.7.0-rc instance and see if the problem appears.

**Comment by pavgra** [comment]
@anthonysena , I am able to reproduce that and the issue seems to be related to `Set` nature and current `FeAnalysisEntity.equals` implementation which compares objects by ID. If you want me to, I can grab the task - have some ideas

**Comment by anthonysena** [comment]
Yes please - I'll assign it to you. Thanks @pavgra
