### ISSUE TITLE
Conceptset/

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1469]
### Expected behavior

Saving a conceptset from 'explore evidence' should open a new conceptset and allow it to be edited/saved.

### Actual behavior

Clicking 'save as a new conceptset' seems to try to construct a conceptset but gets stuck and does not allow editing.  Grayed out screen persists, see below:

![image](https://user-images.githubusercontent.com/731930/54079872-2a6ee280-42b3-11e9-8b48-3e6f8268764f.png)

### Steps to reproduce behavior

Try to create a new conceptset from 'explore evidence' on an existing conceptste.

**Comment by anthonysena** [comment]
Closed via #1472
