### ISSUE TITLE
 Atlas user documentation

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Atlas#147]
Enhance Atlas documentation user guide. It is my understanding that @anthonysena is workign on user guide in the [Atlas wiki](https://github.com/OHDSI/Atlas/wiki) and that he and @juh7007 are collaborating on synthesizing material from @cumc-dbmi [cookbook effort](https://github.com/cumc-dbmi/Atlas-wiki).

**Comment by fdefalco** [comment]
The ATLAS wiki has been moved:

http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas

**Comment by rwpark99** [comment]
I would like to know the shopping card icon is what for? Does the color (orange..) has meaning?

**Comment by rwpark99** [comment]
I am not able to understand what for the the Import section is.
Illustration of the usage by a usecase must be greatly helpful to understand.
Thank a lot.

**Comment by rwpark99** [comment]
Aha! Sorry!
Now I understood it. The import section is for generation of the 'New Concept sets' in the left menu.

**Comment by anthonysena** [comment]
While software documentation is an on-going effort, I'm going to close this issue since the documentation has been migrated to the OHDSI wiki per @fdefalco 's link above. To that end, the CUMC cookbook can now be integrated into the overall ATLAS documentation.
