### ISSUE TITLE
Compare concept set: endless loader in the table header for RC/DRC

### ISSUE THREAD

**Issue by spbima** [OHDSI/Atlas#1474]
### Expected behavior
When compare concept set, after datasource change DB icon is displayed in the table header for RC/DRC

### Actual behavior
When compare concept set, after datasource change endless loader is displayed in the table header for RC/DRC

![test-2 7 0-20190307-cs-compare2](https://user-images.githubusercontent.com/804934/54119754-248a1600-4407-11e9-94f7-0f5d057a3213.jpg)

after change DS

![test-2 7 0-20190307-cs-compare3](https://user-images.githubusercontent.com/804934/54119761-26ec7000-4407-11e9-8d7f-61046779bfb7.jpg)

### Steps to reproduce behavior
Open section Concept sets
Choose one of Concept set
Go to Compare tab
Choose Concept set 2 for compare
Press button "Compare Concept set"
DB icon is displayed in the header
Change datasource 
Endless loader is displayed in the header

**Comment by anthonysena** [comment]
Closed via #1478
