### ISSUE TITLE
Tooltip from previous data source report doesn't disappear

### ISSUE THREAD

**Issue by spbima** [OHDSI/Atlas#1477]
### Expected behavior
New report is opened with only its data

### Actual behavior
New report is opened both with its and previous report's data
https://gyazo.com/aa43bcf6b2de7778ed0c5c22aa15d993
if you move cursor out from treemap area while new report is loading everything is ok: https://gyazo.com/70002352b5ea799a08bb1b1b6fa82340

### Steps to reproduce behavior
1) Data Sources tab -> choose any datasource 
2) Open Procedure report
3) Open list with reports and choose Drug Exposure and leave cursor where it is while new report is loading

**Comment by pavgra** [comment]
@spbima , cannot reproduce. Could you try once more using the latest build?
