### ISSUE TITLE
List of parameters in 'column visibility' appears weird

### ISSUE THREAD

**Issue by spbima** [OHDSI/Atlas#1479]
### Expected behavior
When the last column in a list is deselected the size of this list doesn't change

### Actual behavior
Size of list is minimized 
https://gyazo.com/961ef0c6802ebfbd3216349f2c17b01f
but you can scroll it which is not obvious 
https://gyazo.com/f5288c73dee2a797d6091650f4d4837e

Check this table in all reports: Visit / Condition Occurrence / Condition Era / Procedure / Drug Era / Drug Exposure / Measurement / Observation / Achilles Heel

### Steps to reproduce behavior
1) Data Sources tab -> open Visit report
2) open tab 'Table' in Prevalence table
3) press Column visibility and deselect all columns

**Comment by anthonysena** [comment]
Closed via #1483
