### ISSUE TITLE
Icon of handcart isn't displayed in 'Column visibility' list

### ISSUE THREAD

**Issue by spbima** [OHDSI/Atlas#1480]
### Expected behavior
All column icons and titles are displayed

### Actual behavior
Icon of handcart isn't displayed
![icon-handcart](https://user-images.githubusercontent.com/804934/54129401-31b2ff00-441f-11e9-9080-a2af9cf0cd1c.png)

### Steps to reproduce behavior

1. Open 'Search' section 
2. In Search tab search something
3. In result's table press 'Column visibility'

**Comment by anthonysena** [comment]
Closed via #1482
