### ISSUE TITLE
Broken table when choosing cohort in IR

### ISSUE THREAD

**Issue by aklochkova** [OHDSI/Atlas#1487]
### Expected behavior
table is displayed correctly

### Actual behavior
table is broken

### Steps to reproduce behavior
Create new Incidence Rate
Press 'Add target cohort' and observe table
![image](https://user-images.githubusercontent.com/38942654/54194457-5bc2fa80-44cd-11e9-94af-5f2fbbe1d6e0.png)

**Comment by anthonysena** [comment]
Closed via #1490
