### ISSUE TITLE
Estimation list is empty

### ISSUE THREAD

**Issue by johnSamilin** [OHDSI/Atlas#1488]
### Expected behavior
Estimations list is shown
### Actual behavior
Estimation list is empty
## Steps to reproduce behavior
Create estimation
Return to list

**Comment by wivern** [comment]
This is not an issue with Estimation itself but an issue with out of sync permission sequence value.
Anyway an error should be passed to front when entity could not be created, and this is similar to OHDSI/WebAPI#948

**Comment by anthonysena** [comment]
Closed via OHDSI/WebAPI#953
