### ISSUE TITLE
Trouble building population-level estimation package in R due to duplicate "Description" file

### ISSUE THREAD

**Issue by llhester** [OHDSI/Atlas#1506]
### Expected behavior
I named, downloaded, and extracted the zipped estimation package from the "Population-Level Estimation" tool into a new folder. I should be able to open the project in R and build and install the package.
### Actual behavior
The package would not build in R and gave this error: ERROR: installing package DESCRIPTION failed for package 'analysisPackageName.' 
### Steps to reproduce behavior
After deleting the unextracted, zipped file in my Downloads folder, I retried building and installing the package in R, and it was successfully built. It appears that you cannot have two versions of the same Description file on your system in order to build the package (especially if the downloaded file has the same name as the folder in which you extract the package materials). 

*This may be a question to add to the issue tracker for CohortMethod instead, so let me know if this should be mentioned elsewhere.
**This may not be a bug but rather something that should be mentioned in the Estimation instructions.

**Comment by anthonysena** [comment]
Hi Laura - this has been fixed in the 2.7.0 release candidate so I'm going to close this one out. Thanks for testing it!
