### ISSUE TITLE
Comparative Efficacy

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Atlas#151]
Using R Service Bus and CohortMethod R package, implement a comparative efficacy feature suitable for transplantation research scenarios. Solution should include survivability curve visualization(s).

**Comment by anthonysena** [comment]
Tying this back to #82

**Comment by t-abdul-basser** [comment]
Thanks. I meant to this. The implementation seems to be coming along nicely btw. Great work! :)
