### ISSUE TITLE
Excessive polling for source info on IR after generations are complete.

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#1510]
### Expected behavior
While poling for IR status, it should only poll for generation status on sources that are currently generating.,

From a knockout perspective, it should either add/update the sources in the generated list (if someone deletes a source, or someone else generates on a new source, the UI should just do the diff and update the rows (keyed on source_id)...not re-push a new list of sources.

### Actual behavior
Requests several sources at the same time looking for specific source info.
![image](https://user-images.githubusercontent.com/6818777/54360791-05c09500-463c-11e9-899d-b57b78eab8bf.png)

It only polls for generations that have completed executions, but if someone else in another session generates, shouldn't we see that generation here?

Eventually, one of the http requets return a failure (even for a completed generation):
![image](https://user-images.githubusercontent.com/6818777/54361636-cf841500-463d-11e9-9a72-2f5bf9210c4f.png)

Eventually, a top-level error occurrs during polling and you are sent here:
![image](https://user-images.githubusercontent.com/6818777/54361796-30135200-463e-11e9-88cd-a4c2d37f860d.png)

### Steps to reproduce behavior
1. Generate IR across 5-10 sources.
2. Go to the IR results screen and watch the notifications/generation info queries, eventually you will hit an HTTP 500 from one of the requests.

The extra hits on the server led to these errors (from the example from one of our sources):
```"localizedMessage":"The connection is closed.",```

But, this error also came from calling the /notifications endpoint:
```      "localizedMessage":"The connection is closed.", ```

So, possibly not related to the query that was reported in the IR source info query:
```
"select incidencer0_.id as id1_34_, incidencer0_.created_by_id as created_6_34_, incidencer0_.created_date as created_2_34_, incidencer0_.modified_by_id as modified7_34_, incidencer0_.modified_date as modified3_34_, incidencer0_.description as descript4_34_, incidencer0_.name as name5_34_ from dbo.ir_analysis incidencer0_ left outer join dbo.ir_execution executioni1_ on incidencer0_.id=executioni1_.analysis_id left outer join dbo.source source2_ on (source2_.SOURCE_ID=executioni1_.source_id and (source2_.deleted_date is null)) where incidencer0_.id=?"
```

I was expecting to see the 'design' column being returned from the `ir_execution` view, but that column is not used, so it's not selected (that's good). however, what's not good is eventually something is causing the connections to close, and then all the other queries get killed . (Possibly a connection pooling issue on the server?)

Very likely this could be an issue with our RDP instance of MSSQL hosted on amazon.  However, this screen shot is showing that just watching the pollForInfo calls get the info, sometimes a source will HTTP 500 out:

![image](https://user-images.githubusercontent.com/6818777/54361785-2b4e9e00-463e-11e9-9b8e-46d473ad60b9.png)

**Comment by pavgra** [comment]
> It only polls for generations that have completed executions, but if someone else in another session generates, shouldn't we see that generation here?

It only polls for results when a source has finished execution

> but if someone else in another session generates, shouldn't we see that generation here?

why wouldn't we?

> While poling for IR status, it should just poll for info once to get generations across all sources

If you mean results using term "generations" then no. Since results are pulled from CDMs, for one CDM it may take 1 sec to pull results whereas for another - 1 min. Therefore, we don't want to wait 1 min to return results for the first CDM.

**Comment by chrisknoll** [comment]
> It only polls for results when a source has finished execution

Not according to what I saw. It seemed to poll all 'generated' sources (including those currently generated) every interval (I think 10 seconds)

> but if someone else in another session generates, shouldn't we see that generation here?
> 
> why wouldn't we?
> 
Because i think it is only polling sources for the 'already-generated' sources.  For example,   we have a source for 'CPRD' but cprd is not included in the polling list:

![image](https://user-images.githubusercontent.com/6818777/54363483-67cfc900-4641-11e9-955a-89f33c9d34c8.png)

> If you mean results using term "generations" then no. Since results are pulled from CDMs, for one CDM it may take 1 sec to pull results whereas for another - 1 min. Therefore, we don't want to wait 1 min to return results for the first CDM.

I do not mean results, i mean 'Generations', which only queries the WebAPI database for generation status.  As you can see from my screenshot, only generated sources are polled.  So what happens when someone else generates on a new source that my client UI doens't know about?  I won't see that new source being generated because i am only polling for generated sources.

My suggestion is to have one HTTP endpoint that returns generation for all sources. This will only result in 1 query to the WebAPI (for some reason, our RDP instance is dieing with the multiple connections to the webAPI db...not sure if this is Hibernate, Connection pooling, or Spring JDBC templates, or prepared statements yet, but we're reaching out to AWS for support.)

Putting our internal AWS issues asside, the problem I'm reporting here is how generation info is being fetched from WebAPI (it should be one request, returning all sources with generations, and the UI should only update the UI elements that have updated data (which is pretty easy to do with KO).

**Comment by pavgra** [comment]
> My suggestion is to have one HTTP endpoint that returns generation for all sources. This will only result in 1 query to the WebAPI

![image](https://user-images.githubusercontent.com/10010071/54364006-766ab000-4642-11e9-8e6d-26723c2309e6.png)

![image](https://user-images.githubusercontent.com/10010071/54363990-7074cf00-4642-11e9-8b46-eef71eee895c.png)

**Comment by chrisknoll** [comment]
Ok, so can you explain the requsts to these endpoints:
Request URL: https://epi.jnj.com:8443/WebAPI/ir/216/info/IBM_MDCR

When all the sources show 'complete' and not generating?

**Comment by chrisknoll** [comment]
Pavel, I updated the 'expected behavior' part of the intial issue:

> While poling for IR status, it should only poll for generation status on sources that are currently generating.,

You are correct that we already have a single endpoint to get executions across all soruces. So that is not a problem.  The problem is polling for generation info on sources that already are complete.
