### ISSUE TITLE
Small spelling / description mistakes

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#152]
Neither of these are functionality bugs, just aesthetics. 

The description for adding a new "death filter" in primary criteria is incorrect, "find patients based on device exposure," see attached. 

The spelling of "occurrence" is also wrong, see attached.

![atlas death filter description wrong](https://cloud.githubusercontent.com/assets/8037742/16118484/3f7a13e0-33a5-11e6-97a4-c053c854b98e.png)
![atlas spelling wrong](https://cloud.githubusercontent.com/assets/8037742/16118483/3f738818-33a5-11e6-9e63-1d678290d71a.png)

**Comment by chrisknoll** [comment]
The Death Filter was addressed in a separate issue (and fixed), but the 'occurrance' needs to be fixed. I'll push up another commit to address this.
