### ISSUE TITLE
[ATLAS 2.7 TEST] Data Sources: Slow loading reports

### ISSUE THREAD

**Issue by AnthonyMolinaro** [OHDSI/Atlas#1521]
### Expected behavior
Data Sources loads reports in a reasonable time.

### Actual behavior

Loading various reports takes between 20  and 90 seconds.

### Steps to reproduce behavior

1. From Atlas Home click on the Data Sources tab.
2. Choose a db.
3. Choose a report.

Slow performance seems to be consistence across data sources and reports.

**Comment by alondhe** [comment]
Can these reports be cached?

**Comment by chrisknoll** [comment]
Yes, adding a caching library to the stack is definitely on the road-map for 2.8.

**Comment by anthonysena** [comment]
Associating to OHDSI/WebAPI#1018 for caching data source characterization information

**Comment by anthonysena** [comment]
Closed via https://github.com/OHDSI/WebAPI/pull/1070
