### ISSUE TITLE
[ATLAS 2.7 TEST] Importing Concepts to a Trashed Concept Set

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#1525]
While I prefer this behavior ( #667 ) of allowing imports to open concept set, I'm assuming we no longer support importing to a open concept set now.

### Expected behavior
You cannot add import to an existing concept set

### Actual behavior
You can sneak a concept into an existing concept set with this work around.

### Steps to reproduce behavior

1. Go to search
2. search for "lymphoma"
3. put a concept into the shopping cart 
4. navigate to the concept set
5. save it with a name
6. hit the trash
7. go to search --> import tab --> 194696 --> import button
8. Will will resurrect the last concept set when adding your new concepts

**Comment by chrisknoll** [comment]
I would also prefer to allow importing to an open concept set. If it's a mistake you can always close the concept set without saving.  But many times I will have a concept set open, i want to merge another, and I can't merge a concept set together.

**Comment by anthonysena** [comment]
Closed via #1651.
