### ISSUE TITLE
[ATLAS 2.7 TEST] Search Classifications are no longer highlighted purple

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#1527]
### Expected behavior
Classification concepts are highlighted in purple

### Actual behavior
Classifications concepts are highlighted in blue in the search

### Steps to reproduce behavior

1. Go to Search --> 21000471
2. See the code is listed in BLUE

![image](https://user-images.githubusercontent.com/6305439/54459326-c2018480-473c-11e9-8634-f1f9537ca14c.png)

But it is classification:
![image](https://user-images.githubusercontent.com/6305439/54459346-d0e83700-473c-11e9-9db9-f76cdff843f0.png)

This behavior looks fine on other screens.

**Comment by ericaVoss** [comment]
I don't remember if we also highlighted the "Included Source Codes" page or not, but there are all blue.

![image](https://user-images.githubusercontent.com/6305439/54460391-c5e2d600-473f-11e9-9b8b-5093dff4e232.png)

**Comment by chrisknoll** [comment]
I'm pretty sure we did, there was a common 'table column renderer' for concept names that would apply the link and also style it based on the `standard` column.

**Comment by ericaVoss** [comment]
@chrisknoll , Rupa was able to replicate the issue as well
