### ISSUE TITLE
Error Message after re-fresh of cohort definition screen

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1528]
### Expected behavior
Page re-fresh

### Actual behavior
![image](https://user-images.githubusercontent.com/19151846/54459463-23c1ee80-473d-11e9-9573-5571c0eab153.png)

### Steps to reproduce behavior
Hitting the re-fresh button

**Comment by chrisknoll** [comment]
We think this is an intermittent PDW issue in our env. @jswerdel , if you could keep an eye on this (I did a refresh of a cohort def, ddi not reproduce the error)...re-open if you see this again.
