### ISSUE TITLE
Information on Generation tab requires update if sitting for too long (or moved away from window)

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1530]
### Expected behavior
The information on generating the cohort should appear upon completion
### Actual behavior
The 
![image](https://user-images.githubusercontent.com/19151846/54459634-9c28af80-473d-11e9-94bf-9e5640d075ce.png)
button continues to spin with no generation information displaying.  Refreshing the window will show the completed generation information

### Steps to reproduce behavior
Run cohort generation that requires several minutes to perform

**Comment by AntonStepanof** [comment]
Currently It can be delay(about 10 seconds) with displaying status of generation. But eventually it displays correct status. 
@jswerdel Could you please provide exact steps? I tried to reproduce it for pretty long Generation(about 10 minutes)
