### ISSUE TITLE
In PLP study creation, deleting study package name in ATLAS does not allow removal of first character in string

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1533]
### Expected behavior
Using the delete key in the study package name field should delete all the characters in the field
### Actual behavior
The first character cannot be deleted:
### Steps to reproduce behavior
a.	Enter package name
 
![image](https://user-images.githubusercontent.com/19151846/54460093-f0805f00-473e-11e9-83b9-618a50110b5b.png)

b.	Use delete key from right end to delete characters
![image](https://user-images.githubusercontent.com/19151846/54460100-f5451300-473e-11e9-99e6-9144a1151bfc.png)

**Comment by anthonysena** [comment]
This is due to a bug in the alphaNumeric extender - it does not like the empty string so its preventing you from deleting that single character. 

#### Workaround

Type another character and then you can remove the first character. Sorry for this annoyance!
