### ISSUE TITLE
[ATLAS 2.7 TEST] Data Density Box Plot values not matching AchillesWeb

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#1536]
### Expected behavior
**In AchilesWeb**
![image](https://user-images.githubusercontent.com/8037742/54461891-2c112e00-472b-11e9-99bd-a583d1645ee3.png)

### Actual behavior
**In Data Sources**
![image](https://user-images.githubusercontent.com/8037742/54461853-113eb980-472b-11e9-9559-3ab396063b58.png)

### Steps to reproduce behavior
Go to Data Sources, pick a CDM, select Data Density report, then go to Concepts Per Person Box Plot

**Comment by ssuvorov-fls** [comment]
The same behavior is used in "Age at Death" plot for "Death" report type. Does it need to be fixed too?

**Comment by anthonysena** [comment]
I think this may be an issue with rounding inside of the visualization library for creating the box plot. Here is the data that is feeding into the chart:
```
"ageAtFirstOccurrence": [
{
"conceptId": 320128,
"category": "MALE",
"minValue": -1,
"p10Value": 39,
"p25Value": 49,
"medianValue": 60,
"p75Value": 70,
"p90Value": 79,
"maxValue": 89
},
{
"conceptId": 320128,
"category": "FEMALE",
"minValue": -1,
"p10Value": 40,
"p25Value": 51,
"medianValue": 62,
"p75Value": 73,
"p90Value": 81,
"maxValue": 89
}
],
```

And then the display in the chart itself:

![image](https://user-images.githubusercontent.com/12902366/55500962-72192d80-5617-11e9-8970-89200329f743.png)

**Comment by chrisknoll** [comment]
It looks like the values are being rounded to the nearest 10.  Is there some sort of number format applied?

**Comment by ssuvorov-fls** [comment]
Yes, values are rounded in the plot itself. I;ve already fixed it in this plot. But there's also another plot ("Age at Death" plot for "Death" report type) - should it also be fixed?

**Comment by chrisknoll** [comment]
Yes, they should be fixed everywhere, i'm not sure what value there is to round a number to a 'tens' value, but in these specific cases, it's important to see the difference between 36 and 44 (these would both be rounded to 40 using these formatting rules).
