### ISSUE TITLE
Data Sources text size

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#1540]
### Expected behavior
Text should be easily readable

### Actual behavior
Labels in trellis plots is too small. Here's a screenshot with the left nav for scale:
![image](https://user-images.githubusercontent.com/8037742/54464419-d5f4b880-4733-11e9-9e7a-4da372e42649.png)

### Steps to reproduce behavior
Go to Data Sources, pick condition occurrence report, drill down into a condition. Go to the Prevalence trellis plot.

**Comment by vlbe** [comment]
@alondhe Please, provide a screenshot what's wrong

**Comment by alondhe** [comment]
Sure, just added it above.

**Comment by vlbe** [comment]
I'm sorry, but it's not clear for me anyway. Let's be more precise.
What labels are are you talking about?
1) Male | Female | Unknown
2) Prevalence per 1000 people
3) digits on x/y-axis
4) tooltips' values - 0.06/0.02/0.06/0.03

Thanks

**Comment by alondhe** [comment]
@vlbe -- all except for the Prevalence Per 1000 People label. The font size and/or weight makes them tougher to read.

**Comment by pavgra** [comment]
Closed by https://github.com/OHDSI/Atlas/pull/1709
