### ISSUE TITLE
Few descriptions provided in cohort pathway

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#1543]
When creating a cohort pathway analysis, there are very few descriptions for how to fill out the analysis settings.

![image](https://user-images.githubusercontent.com/12911960/54468608-aca05080-4764-11e9-8b66-07bba4d1925e.png)

**Comment by pbr6cornell** [comment]
I agree with need additional documentation around these input parameters for ATLAS 2.8, and it would make sense to include better guiding text on the UI.

**Comment by anthonysena** [comment]
Descriptions for each setting are now included in 2.8:

![image](https://user-images.githubusercontent.com/12902366/102656651-30f5e380-4142-11eb-8c57-1b0e796a9ba6.png)
