### ISSUE TITLE
[ATLAS 2.7 TEST] Cohort pathways analysis takes over a minute to register generation

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#1544]
### Expected behavior
After clicking generate on MDCR v871 for a cohort pathway analysis it should immediately show as working.

### Actual behavior
It can take up to a minute or more for a cohort pathway analysis to show as working after clicking generate.

### Steps to reproduce behavior
Click generate next to a specific database in cohort pathways

**Comment by anthonysena** [comment]
Closed via #1549
