### ISSUE TITLE
Cohort Pathways path detail location

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#1545]
### Expected behavior
The path details window always shows up below the sunburst plot

### Actual behavior
Occasionally the path details window will show up to the right of the sunburst plot

### Steps to reproduce behavior
Click through the different pathway options

**Comment by anthonysena** [comment]
@clairblacketer - was there a specific pathways analysis that you ran in our environment that exhibited this behavior? I'm having trouble reproducing the issue at the moment.

**Comment by anthonysena** [comment]
@clairblacketer - I'm going to close this out as I'm not able to reproduce this. Thanks!
