### ISSUE TITLE
[ATLAS 2.7.1] Export Text does not copy full text in 1 click

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#1547]
### Expected Behavior
In Cohort Definition Print Friendly, To copy the print-friendly text of the cohort, the text should able to be copied in full without missing information, such as subsequent pages of concepts in the paged concept set datatble.

### Actual Behavior

If you select-all on the print friendly cohort definition,   the concept sets are only partially copied because the paging of the table is obscuring everything except the first 10 or 25 concepts.  To get all the concepts, the user would have to go to each table, and choose 'show all rows' which is cumbersome.  

In addition, copying all will include the buttons for navigation which isn't what you would put into a 'print friendly form'.

### Steps to Reproduce
1. Open cohort definition with multiple concept sets, where some of the concept sets have > 50 concepts in them.
2. Go to print friendly tab
3. Observe that you are unable to highlight the entire print-friendly text.  Anything shown on page 2 is not visible by default.

### Suggestion
Do not page concept sets in the print-friendly view, and use simple HTML table structures to display data so that it is easily copied-pasted into something like a word document.

**Comment by johnSamilin** [comment]
Hi @rmakadia 
could you record a video that will show the process of reproducing of this bug?

**Comment by rmakadia** [comment]
No need to video this, here is a screen shot below to describe the issue. The two screen shots show that its now not showing me everything in print friendly view, rather I need to click through and show all the concept set expression terms, and when the print friendly text is copied in the second picture we see that there are more items but can't see them (the point of print-friendly is to be able to see it all not a selected view) In order to select the full view you need to view all for all concept sets and hit copy to clipboard which is ALOT more work for larger cohorts

![image](https://user-images.githubusercontent.com/11390491/54762031-b34a2000-4bc9-11e9-99f1-07ba5388a2e4.png)

**Comment by chrisknoll** [comment]
Note: I updated the initial request with formatting and additional detail.

**Comment by johnSamilin** [comment]
Hi @chrisknoll @rmakadia 
thanks for the explanation, it helped a lot! I created a PR that will fix it
