### ISSUE TITLE
Data Sources Frequency distribution plot x-axis scale

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#1548]
### Expected behavior
Frequency distribution plots should scale based on the available data. If the max of the x value is very small in comparison to the max x value in the plot, the plot should re-scale.

### Actual behavior
![image](https://user-images.githubusercontent.com/8037742/54506380-66c8c100-48f9-11e9-8ada-a2b8d2024e1a.png)

Can this plot be re-scaled to fit the data more comfortably? In its current state, it is also hard to hover over the individual bars.

### Steps to reproduce behavior
Go to Data Sources, then the Procedure report, pick a procedure, then look at the Frequency Distribution chart.

**Comment by ssuvorov-fls** [comment]
![altlas-1548](https://user-images.githubusercontent.com/46920469/55080200-ca4baf00-50ae-11e9-8b52-e66961fb8cc9.PNG)
There're small values in such charts, which are rounded to zero values (in sql scripts) and only few records are shown. 
In my screenshot i removed rounding and there's popup with correct values. So it's not a scaling issue. 
Which way is better: remove records with small values, remove rounding or leave it as is?

**Comment by alondhe** [comment]
I'd say keep the values and remove rounding. But to help the user see these values better, could plotly-like functionality be added to allow for zooming and panning around all time series and bar charts?

**Comment by pavgra** [comment]
@alondhe , sounds reasonable. We'll treat that in a separate issue - https://github.com/OHDSI/Atlas/issues/1721
