### ISSUE TITLE
click on upper left ATLAS link goes to splash screen and stays there

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/Atlas#155]

**Comment by fdefalco** [comment]
Working as intended - how else can you see the AMAZING animated SVG? 

If you want to go back to the application you just click on the word ATLAS.  I admit that isn't obvious, but there's something about trapping a user and leaving them forced to stand in awe of the animated rings. :)

In all seriousness - there is a plan for this page - but its too low priority to even discuss.  For now we can make the link to guide the user back to the application more intuitive.

**Comment by fdefalco** [comment]
This link now redirects to the Home screen.
