### ISSUE TITLE
Cohort Pathways - Download pathways data

### ISSUE THREAD

**Issue by davekern** [OHDSI/Atlas#1552]
### Expected behavior
Ability to download the pathways data so that additional analysis can be performed by user

### Actual behavior
Unable to do this

**Comment by chrisknoll** [comment]
I am providing a tabular view of the pathway data, that lets you see the paths rolled up based on a user-selected 'Maximum Path Length':
![image](https://user-images.githubusercontent.com/6818777/55365982-bb04a100-54b4-11e9-9105-0b064d59111c.png)

By setting the path length lower, you can see a roll-up of fewer paths:
![image](https://user-images.githubusercontent.com/6818777/55366041-05861d80-54b5-11e9-9c19-3721fa30027f.png)

You can even set the max-paths to '1' to see the first-line path summary:
![image](https://user-images.githubusercontent.com/6818777/55366109-51d15d80-54b5-11e9-9e40-12b3fc829265.png)

Clicking 'export' above each report group will export the same columns displayed in the report.

If there are no objections to this approach, I can work on a PR.

**Comment by chrisknoll** [comment]
Closed in #2235
