### ISSUE TITLE
Cohort Pathways - Add key summary statistics on event cohort frequencies

### ISSUE THREAD

**Issue by davekern** [OHDSI/Atlas#1557]
### Expected behavior
Have  summary table of some key metrics, for example
- For each event cohort, the proportion of patients who enter that cohort at any time (regardless of order)
- For each event cohort, proportion of patients who enter that cohort at each line (regardless of what they had prior)

### Actual behavior
Details not available

**Comment by pbr6cornell** [comment]
I'd like to have more of the summary data available too.  It doesn't fit with thematic focus for ATLAS 2.8, but if @chrisknoll gets to it after other priorities, I'm all for including a better way to export the resulting data object.  For ATLAS 3.0, we should definitely add more elaborate reporting features that go beyond the sunburst for TxPathways.

**Comment by chrisknoll** [comment]
This should be addressed with the addition of 'tabular view'.  Table C and B cover the 2 usecases described: C is proportion of event cohort reagardless of line, and B is proportion of patients in each event cohort, by line (rank).
