### ISSUE TITLE
Profiles - incorrect index if patient not found in cohort

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1558]
### Expected behavior

Patient profile for a person in an cohort should index at time 0 based on cohort start date

### Actual behavior

Patient profile has index 0 at observation period start date.   Perhaps because person doesn't belong to cohort or cohort wasn't instantiated?   If either is the case, then that should be some notification.

### Steps to reproduce behavior

Open profile following URL:

https://epi.jnj.com/atlas/#/profiles/<source name>/<personid>/<cohortid>/

**Comment by pavgra** [comment]
@anthonysena , how the cohort start date is related to the Profiles page?

**Comment by anthonysena** [comment]
@pavgra, the profiles page contains 2 routes:

1. `atlas/#/profiles/<source>/<person_id>`
2. `atlas/#/profiles/<source>/<person_id>/<cohort_definition_id>`

When the patient profile is invoked without the `/<cohort_definition_id>`, the index of the person is assumed to be the beginning of their observation period versus when that value is supplied, the index is taken from the `cohort_definition_id` reference. The interface has one small difference in the display. Take this example where the cohort is defined:

![image](https://user-images.githubusercontent.com/12902366/55753413-454e8700-5a18-11e9-8ff3-586ba13c6197.png)

And for the same patient without the cohort definition reference:

![image](https://user-images.githubusercontent.com/12902366/55753460-5eefce80-5a18-11e9-975a-16ccedd595bf.png)

@pbr6cornell - I'd propose that if a profile is loaded without a cohort definition specified, we can put in some text, similar to the cohort display, that indicates that their index is the start of observation in the database. Something like:

![image](https://user-images.githubusercontent.com/12902366/55753595-b9892a80-5a18-11e9-826e-4ced2fb3ee9a.png)

Please let us know if this is the type of notification you had in mind or if it should be more prominent in the display.

**Comment by AntonStepanof** [comment]
@anthonysena I sent pull request with 'at start observation' option
