### ISSUE TITLE
Do not show date/time for tasks which have not started yet

### ISSUE THREAD

**Issue by spbima** [OHDSI/Atlas#1559]
### Expected behavior
Do not show date/time for tasks which have not started yet

### Actual behavior
Date/time has shown for tasks which have not started yet

![jobs2](https://user-images.githubusercontent.com/804934/54537458-8fa59080-49a3-11e9-901b-5a0916768c7d.jpg)

### Steps to reproduce behavior

1. Start several tasks to generate a cohorts
2. Go to Jobs

**Comment by anthonysena** [comment]
@spbima @vlbe - Could we consider adding the created date from the job table for this display? For jobs that have not started yet, the created date will be the time the job was dropped into the queue which is useful when monitoring the status of jobs. I'd recommend we look at that as part of #1560.

**Comment by spbima** [comment]
@anthonysena I agree with you and I created the issue for WebAPI
