### ISSUE TITLE
Slow Redraw/Sort speed with large data table

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#1571]
### Expected behavior
Sorting column of large datatable should be quick.

### Actual behavior
On a cohort definition list with ~7000 entries, takes about 2 seconds to sort by 'last updated date'.

### Steps to reproduce behavior
1. Open cohort definition list with large number of elements. (> 5,000)
2. Sort by Last Updated
3. Observe delay  in sort.

### Additional information

I created a quick 5 second Chrome profile that captures a sort event:
![image](https://user-images.githubusercontent.com/6818777/54652297-d02d0900-4a8c-11e9-9ad0-4ab759572c10.png)

It appears most of the energy is spent in the `datetime-formattted-desc` column. If you go to http://www.ohdsi.org/web/atlas/#/cohortdefinitions, that list has about 3000 entries in it, and the resize, sorting is instantaneous. Taking a profile doesn't show any obvious spikes, but it doesn't appear to do any heavy sorting.

Looking deeper in `datetime-formatted-desc`, a lot of time (relatively speaking) is spent inside moment.js
- configFromStringAndFormat
- unescapeFormat

### Implementation Suggestion

Instead of trying to parse out the dates and sort them (which could be an O(N^2) cost) we should have an integer representation of the date field (such as ms from epoc) that is more easily sorted, and we configure DataTables to use this special sort column for those date columns.

**Comment by johnSamilin** [comment]
Hi @chrisknoll 
this problem is related to the fact that data tables are sorting the whole array of data (7000 rows!) and renders only small piece of it. The only reasonable solution here is to do server-side pagination and sorting.

**Comment by chrisknoll** [comment]
I'll investigate other options.  Incurring a complete round trip to the server to re-query, scan to page, serialize objects in page down to client has been show to be inefficient.  From the profile I mentioned, the repeated calls to configFromStringANdFormat, unescapeFormat, etc, are easily avoided if there is a sort column that is more efficient to do row-comparisons with (and there is indeed specific options in datatables to support this function)
