### ISSUE TITLE
New Dataset screen is not returned to Dataset list

### ISSUE THREAD

**Issue by spbima** [OHDSI/Atlas#1591]
This issue happens on a clean instance. When there are no data sources at all and you are configuring the first one.
Exactly all is working for you after configuration is done.

### Expected behavior
New Dataset screen is returned to Dataset list

### Actual behavior
New Dataset screen is not returned to Dataset list after you click Save (had to hard refresh in browser)

### Steps to reproduce behavior
1. You need clean instance
2. Press new Datasource
3. Input data and press Save

**Comment by AntonStepanof** [comment]
It will be fixed at https://github.com/OHDSI/Atlas/issues/1593

**Comment by pavgra** [comment]
#1593 was closed so pls cherry-pick what you need and create a PR
