### ISSUE TITLE
New Cohort creation is blocked by JS Alert

### ISSUE THREAD

**Issue by spbima** [OHDSI/Atlas#1593]
This issue happens on a clean instance. When there are no data sources at all and you are configuring the first one.
Exactly all is working for you after configuration is done.

### Expected behavior
New Cohort can be created

### Actual behavior
New Cohort creation was blocked by JS Alert about a problem with Vocabularies (even I had permission) 

### Steps to reproduce behavior
1. You need clean instance w/o Cohort Definitions
2. Try to create new Cohort Definition
3. Creation block JS Alert

**Comment by wivern** [comment]
![cohort](https://user-images.githubusercontent.com/1109753/55086914-41d30b80-50ba-11e9-94b9-7bc8f51dce24.png)

**Comment by pavgra** [comment]
@spbima , the message seems to be self-evident and sufficient. If you agree, I would propose to close the issue
