### ISSUE TITLE
Unable to mange concept sets after importing to Criteria Feature

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#1595]
### Expected behavior
Once importing a concept set for use in a Criteria Feature design, i'm unable to amend the concept set (ie: add new concepts to it, remove concepts).  I am able to adjust the 'include descendants', 'exclude' options in the concept set (via the quick-edit component), but otherwise, if I need to make major changes to the concept sets, I'm unable to do so.

With complex criteria with multiple concept sets, it would be good to see the set of all concept sets that are in the feature criteria.  This should behave like cohort definitions where the set of concept sets used in the definition is given to the user as a list.

### Actual behavior
After imprting a concept set, the only way to manage it is via the inline-editor, which doen't allow you to search for concepts, or add/remove concepts to the concept set:
![image](https://user-images.githubusercontent.com/6818777/54941303-e7437f00-4f02-11e9-92ee-c8fbaed27013.png)

### Steps to reproduce behavior
1. Create new Feature
2. Add Criteria Feature
3. Add condition occurrence criteria
4. Import concept set to criteria.
5. Observe:  you can't add/edit the concept set to add new concepts.

**Comment by AntonStepanof** [comment]
@chrisknoll I believe this issue is related to https://github.com/OHDSI/Atlas/issues/1493 
and it can be fixed as part of new 'search redesign' issue for Atlas.
It it correct?

**Comment by chrisknoll** [comment]
Yes, that's correct.

**Comment by pbr6cornell** [comment]
I ran into this issue myself during the videos. Would be good to fix or else document the limitation, though seems odd to be inconsistent here vs elsewhere

**Comment by chrisknoll** [comment]
As a stopgap, we can use the same component found in the IR analysis strata section to allow management of concept sets attached to the features.

In addition, it's a bit difficult with working with > 5 criteria features as they all stack on top of each other. Another thing to pull from the IR implementation is how the list of features can appear on the left, and you click-to-edit the feature from the list and the editor will appear to the right:

![ManageConceptSets](https://user-images.githubusercontent.com/6818777/58362507-b4b3f500-7e65-11e9-908b-14c7c0084073.gif)

**Comment by pbr6cornell** [comment]
For ATLAS 2.8, should we add a 'Conceptset' tab, like exists under 'Condition Definitions' and 'Incidence'?  Just to ensure the minimum requirement of having the ability to fully edit any conceptsets is available?  @pavgra .    Or if that is too much effort, we can wait until ATLAS 3.0.
