### ISSUE TITLE
Wrong count included concepts

### ISSUE THREAD

**Issue by spbima** [OHDSI/Atlas#1598]
### Expected behavior
Count of included concepts on tab header and list is the same

### Actual behavior
Count of included concepts on tab header - 3, list is empty

![cs-26031029-1](https://user-images.githubusercontent.com/804934/55008997-ebe76080-4ff2-11e9-82c7-df21e94fbdf5.jpg)

### Steps to reproduce behavior

1. Create a new concept sets
2. Search _Aspirin_ on vacabs search page
3. Add concept 45680558, 36213168, 1112807
4. Save concept
5. Switch to _Included concepts_ tab

**Comment by pavgra** [comment]
Most possibly the same as https://github.com/OHDSI/Atlas/issues/1518

**Comment by chrisknoll** [comment]
Yes, i believe this is same issue.

Some hints on this:  it seems to 'break' after the concept set is saved. If you refrseh the browser, then the included concepts will reflrect (and refresh) the updates to the concept set expression. However, once you save your changes, the 'included concepts' becomes disconnected again, until you refresh the browser. It could be related to component initialization or a out-of-sync subscription, I didn't dig too deeply on it.

**Comment by pavgra** [comment]
The PR for the issue exists for more than a week now. The thing is that we didn't come in agreement with @anthonysena  regarding the solution:
https://github.com/OHDSI/Atlas/pull/1546

**Comment by anthonysena** [comment]
Closing as this has been addressed through #1546. @spbima let me know if you have any concerns.
