### ISSUE TITLE
Can't edit, delete and set Exclude/Descendants/Mapped for concept set

### ISSUE THREAD

**Issue by spbima** [OHDSI/Atlas#1599]
### Expected behavior
After creating, I can edit, delete or set/unset Exclude/Descendants/Mapped for the concept

### Actual behavior
After creating, I can not edit, delete or set/unset Exclude/Descendants/Mapped for the concept

![cs-26031029-2](https://user-images.githubusercontent.com/804934/55009849-459c5a80-4ff4-11e9-8929-d03902fd3dc7.jpg)

### Steps to reproduce behavior

1. Create a new concept sets
2. Search Aspirin on vacabs search page
3. Add same concepts into set
4. Save concept

**Comment by pavgra** [comment]
@spbima , I can not reproduce the issue either in `master` or in `master-2.7.1`. Could you provide a way?

**Comment by spbima** [comment]
Fixed in https://github.com/OHDSI/Atlas/issues/1612
