### ISSUE TITLE
cohort def primary criteria bug

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/Atlas#161]
If multiple primary criteria are added, changing the "with observation at least" numbers for one of the criteria changes it for all of them (after selecting a different number of days before or after and tabbing off the select box).

**Comment by Sigfried** [comment]
Probably there should be only one pair of numbers for primary criteria obs before/after index date, but then there shouldn't be multiple pairs of select boxes.

**Comment by chrisknoll** [comment]
Yes, what you see there is totally wrong.  There's only one 'observation window' defined for all primary criteria, but this component is being dropped one time per primary criteria.  I think it's just a matter of removing it from he loop and rendering that component once.   But it does explain why changing one box changes them all: they are all bound to the same data!
