### ISSUE TITLE
IR Results refresh with N/A or running status

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#1618]
### Expected behavior
Generation results should show the results of generation.

### Actual behavior

When looking at the IR results, the generation status will 'flash' as running during load, or when generation has completed, the results will show n/a, but refreshing the page will show the correct results.

### Steps to reproduce behavior
1. Have multiple sources set up
2. Run an IR analysis on several soures
3. Observe when the generation  is finished, n/a appears in counts until you refresh.  

Screenshot:
![IrResults](https://user-images.githubusercontent.com/6818777/55201333-ec216080-5198-11e9-9651-f682aed8cd61.png)

**Comment by vlbe** [comment]
@chrisknoll I cannot reproduce this bug. Could you check this again?

**Comment by anthonysena** [comment]
@chrisknoll - I'm going to close this out since I can't reproduce it on the 2.7.2 build.
