### ISSUE TITLE
Roboto font family causing text distortion

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#162]
With the roboto font family enabled on body tag, the text looks distorted:
![jaggy](https://cloud.githubusercontent.com/assets/6818777/16322358/901d79ce-3970-11e6-9f89-bf684c4a5ca0.png)

Compared to:
![smoothe](https://cloud.githubusercontent.com/assets/6818777/16322368/9f0181f6-3970-11e6-9569-79db35b37d47.png)

Simple change to remove the style from atlas.css, just wanted to report it here.

**Comment by fdefalco** [comment]
This isn't Roboto.  The only time I've seen anything like this isn't font related but occurs after windows goes into basic color mode during a WebEx.  Here is a screen capture with Roboto:

![image](https://cloud.githubusercontent.com/assets/6586384/16347331/1dd9fc84-3a1a-11e6-9fc6-9de12e21d126.png)

**Comment by chrisknoll** [comment]
Frank, I'm not going to get into a semantic argument about the meaning of 'cause' is, but having it work for you in one mode while it won't work for anyone in another does not invalidate the issue.  I'm going to apply this fix again, and once you have an alternative that works in a broader context, make the change.

**Comment by fdefalco** [comment]
Could you provide steps to reproduce this issue? I still haven't been able to reproduce.
