### ISSUE TITLE
Data sources are not displaying under Data sources tab

### ISSUE THREAD

**Issue by rahulbujji45** [OHDSI/Atlas#1631]
Hi, 

I am newbie to OHDSI, i have done Atlas setup with WebAPI integrated with oracle database, but when i got to the Datasource tab i can't see the list of data sources and i can't see any error in web browser console to Debug,

![](http://forums.ohdsi.org/uploads/default/original/2X/b/b1744d7b9daeaa6a3019ae3094aeb841ebe3732b.png)

Please help me in solving the issue.

Thanks,
Rahul.

**Comment by rahulbujji45** [comment]
> Have you implemented the Configure source and source_daimon tables section of the WebAPI Installation Guide?

Yes Don-Torok i have implemented the Configure sources and its working now there is a permission issue thanks for your response :) 

Thanks,
Rahul.

**Comment by anthonysena** [comment]
@rahulbujji45 I take it that this was a permissions issue on the database side from reading the issues here. I'm going to close it out but please re-open if you are still facing an issue with retrieving profiles. Thanks!
