### ISSUE TITLE
Many features do not work on Safari

### ISSUE THREAD

**Issue by msuchard** [OHDSI/Atlas#164]
Am not sure if the development team wants to support `Safari` on Mac OS X.  But, if you do, then many, many features do not work (under `ATLAS 1.1.0`).  E.g. (and this is a big oops)

* On main-page, hitting `Define a New Cohort`brings up a blank panel.

On the positive side, `Google Chrome` on Mac OS X seems to behave fine.

**Comment by chrisknoll** [comment]
Hey, @msuchard , we definitely didn't put a lot of effort into cross browser compatibility (beyond trying to use libraries that are reportedly cross-browser compatable (jquery, knockout, d3).  I'm wondering if you're not actually seeing an underlying error in Safari that isn't occurring in Chorme. Do you have a console that you could inspect in Safari that would report an error? 

I'd stick with chrome if that's not too much of a hardship (It's what we give our internal users instructions: don't use IE9, use Chrome), but we would definitely prefer people to have the best experience possible with the browser of their choice.  That might not be always possible, however.

**Comment by msuchard** [comment]
Safari js console reports:

```
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (cohort-definition-manager.js:106)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (explore-cohort.js:16)
```

which, looking at the code, makes little sense to me.  But, my knowledge of js is nonexistent.

**Comment by chrisknoll** [comment]
Ok, i see this in cohort-definition-manager:

~~~javascript
var sourceId = self.config.services[0].sources.filter(source=>source.sourceKey==cdsi.sourceKey)[0].sourceId;
~~~

@fdefalco , Is there an implementation you can use besides lambda expressions to perform this filter, or do you recommend that chrome is the only supported browser?

**Comment by chrisknoll** [comment]
Technically, this feature is called 'arrow functions' and is not supported in safari:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility

**Comment by chrisknoll** [comment]
@msuchard , is it possible you're running an out of date version of Safari?  I checked this compatablity table:
https://kangax.github.io/compat-table/es6/

Safari 9 is rather bad, but Safari 10 shows a lot more compatability.  Do you think you could update?

**Comment by msuchard** [comment]
I might disagree with the out of date part.  Safari 9.1 was released in March 2016.  So, yeah, I'm 3 months behinds the time.  Safari 10 is still in beta, to be released with new operating system sometime in the Fall. 

Safari is pretty bad, and I'm OK not supporting it if you don't want to.  I raised this issue so people know what's going to work on their systems.

**Comment by chrisknoll** [comment]
March 2016 is not what I'd consider out of date either (I didn't claim you were, I was just asking if you were, and sounds like the answer is 'no'), but I think we both agree that current Safari isn't supporting enough features to try to target as one of our supported browsers.

If you wanted to give the Safari beta a try and report if that looks better in Atlas, that would be appreciated, but I understand that it's beta and there might be some aversion to using it.

**Comment by Sigfried** [comment]
I think I'm probably the one who started using arrow functions. I'm not sure if I wrote the offending line, but if we want to stop using arrow functions in order to support Safari, I can go through and get rid of them. (It's really nice to be able to use them, though.)

**Comment by cgreich** [comment]
Hell no! Don't bring in the mouse-only Mac terror. :) Do both.

**Comment by chrisknoll** [comment]
Yeah, sigfried, the arrow functions are pretty widely supported at the compatibility list:
https://kangax.github.io/compat-table/es6/

Keep using them, I think it's good that we're using modern techniques, lets encourage that.
