### ISSUE TITLE
Inverse probability treatment weighting bug

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1657]
### Expected behavior

When user specifies inverse probability of treatment weighting (IPTW) for the outcome model, `createPs` should be set to true. 

### Actual behavior

`createPs` is not properly set which then causes an error when executing the study

**Comment by ssuvorov-fls** [comment]
@anthonysena could you give a screenshot with "createPs" flag?

**Comment by anthonysena** [comment]
@ssuvorov-fls - `createPs` is a flag that is set internally on the JSON specification for the study. The code that controls this is found [here](https://github.com/OHDSI/Atlas/blob/c2815b5311704860559630048f7e4982b9b871cb/js/pages/estimation/components/editors/cohort-method-analysis-editor.js#L155-L161). This code will require a change to take into account the user's selections in the outcome model editor to properly set the createPs flag.
