### ISSUE TITLE
search screen permission denied with security disabled

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1687]
### Expected behavior
You can access the vocabulary search.

### Actual behavior
With security disabled an error message appears preventing access to the vocabulary search.

![image](https://user-images.githubusercontent.com/6586384/56368201-eda4de00-61c4-11e9-8bd5-e4455ee485d9.png)

### Steps to reproduce behavior

Click search from the left hand menu.

**Comment by fdefalco** [comment]
This does not occur in the 2.7.0 label version.

**Comment by fdefalco** [comment]
I've traced this to the PermissionsService here:

https://github.com/OHDSI/Atlas/blob/22fc8d78d16e60a0c26fb2bd4bd4b308354b5e46/js/pages/vocabulary/PermissionService.js#L9

If all source daimon priorities are set to 0, then no default vocabulary provider is selected (a default should be selected even in this case) and when no default vocabulary provider is selected then sharedState.vocabularyUrl() is undefined, which leads the permission manager to return that search is not permitted due to security as opposed to a pseudo-configuration error.

**Comment by fdefalco** [comment]
It appears this started occurring with the introduction of the changes in 2.7.1 here where the default values were changed from 0 to 1.

https://github.com/OHDSI/Atlas/pull/1671/files#diff-3e5fedddd2b74418d3213e219c31c865

@pavgra - What was the reason for this change?

**Comment by pavgra** [comment]
@fdefalco , at least, I remember the following case:

Previously, WebAPI warmed caches for all sources. Later, to improve performance, @chrisknoll changed that behavior to caching of only those sources which have non-zero diamons. Therefore, imagine a case: you haven't prioritized a single source -> WebAPI hasn't cached any data -> but Source config panel still shows that the source is ready for supplying e.g. RC/DRCs which is not very true and leads to confusion.

**Comment by weeksjm** [comment]
Is there a work around?  Or do I have to pull a different branch and redploy?

**Comment by anthonysena** [comment]
The work-around we found is to ensure that there is at least one `source_diamon` entry for the Vocabulary daimon with a priority of 1 or higher. This should resolve the permission issue mentioned here. Let us know if that works for you @weeksjm

**Comment by weeksjm** [comment]
That did get the search to appear.  Thanks!

**Comment by ChavanShweta** [comment]
I also had same issue. I tried setting Vocabulary daimon with a priority of 1. This did not work for me.

**Comment by ChavanShweta** [comment]
The issue is here:

https://github.com/OHDSI/Atlas/blob/55fe8b036fdd72eb2253592a9203bdb806588ea0/js/services/SourceAPI.js#L119

authApi.hasSourceAccess is checking for the access. Its looking for the specific value `source:${sourceKey}:access`. 

https://github.com/OHDSI/Atlas/blob/18cc354865091b3587c2adcb4bf5d3c377430f97/js/services/AuthAPI.js#L450

In my case none of the roles or permissions already in the code does not have this.
I was able to fix this by adding one more condition in line number 450 of AuthAPI.js
```
return isPermitted(`source:${sourceKey}:access`) || /* For 2.5.* and below */ isPermitted(`cohortdefinition:*:generate:${sourceKey}:get`) || isPermitted(`vocabulary:${sourceKey}:search:*:get`) ;
```
I was able to search in the vocabulary.

**Comment by ssuvorov-fls** [comment]
@fdefalco 
Hello
Is this problem still exists?
I can't reproduce it on 2.8

**Comment by olga-ganina** [comment]
Hi @anthonysena , can you please assist with reproducing?

**Comment by anthonysena** [comment]
Closing this issue as this work-around is now documented as part of the WebAPI setup: https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration#daimon-priority.
