### ISSUE TITLE
Datasource configuration: kerberos keytab upload is broken

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Atlas#1693]
### Expected behavior
![image](https://user-images.githubusercontent.com/4144173/56471925-bbafa800-6460-11e9-893b-6dcc8242a6f8.png)
Upload button is visible

### Actual behavior
![image](https://user-images.githubusercontent.com/4144173/56471926-bc483e80-6460-11e9-994d-0e48661947d5.png)
No upload button available

### Steps to reproduce behavior
Configure datasource for Impala

**Comment by pavgra** [comment]
Fixed by https://github.com/OHDSI/Atlas/pull/1689 :
![image](https://user-images.githubusercontent.com/10010071/56832876-18350d80-683b-11e9-9ab1-d94936577812.png)
![image](https://user-images.githubusercontent.com/10010071/56832885-1ec38500-683b-11e9-8a51-cd7d477ff114.png)
