### ISSUE TITLE
Is shown wrong creation time in a list for CD, CC, IR

### ISSUE THREAD

**Issue by spbima** [OHDSI/Atlas#1695]
### Expected behavior
For Cohort Defenition, Cohort Characterizations, Incidence Rate Analysis  is shown right creation time in list

### Actual behavior
For Cohort Defenition, Cohort Characterizations, Incidence Rate Analysis is shown time 4 hours before the creation.
For Concept Sets, Pathways, Estimation, Prediction is shown right creation time

### Steps to reproduce behavior

1. Create Cohort Defenition / Cohort Characterizations / Incidence Rate Analysis
2. View creation time in the list Cohort Defenition / Cohort Characterizations / Incidence Rate Analysis

**Comment by anthonysena** [comment]
I cannot reproduce this in our environment - @spbima can you confirm if this issue is closed with the 2.7.2 release?

**Comment by pavgra** [comment]
The issue was closed with the 2.7.2
