### ISSUE TITLE
column meaning?

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#17]
Atlas is a great  tool
simple question:

What RC and DRC mean? (and how are they computed) and what sites contdibuted to the calculation

![image](https://cloud.githubusercontent.com/assets/7526119/10832111/bc1f6798-7e5f-11e5-9ef5-39ccd03d9257.png)

**Comment by ericaVoss** [comment]
RC = Row Count
DRC = Descendant Row Count

How many row does this concept have in a CDM or how many rows does this concept and its descendants have in a CDM.

Go to "Configure" menu item and it shows you the datasource, "OHDSI Cloud Source 1 [CS1]" - but I don't know what that is, @leeevans  or @fdefalco probably knows.

**Comment by leeevans** [comment]
"OHDSI Cloud Source 1 [CS1]" is the 1K synthetic patients demo data.
