### ISSUE TITLE
Patient profile not displaying data from PROCEDURE_OCCURRENCE table and other CDMv5 tables

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#170]
The patient profile shows data from the following tables:

CONDITION_OCCURRENCE (called 'condition', should probably write out fully)
CONDITION_ERA
DRUG_EXPOSURE  (called 'drug', should probably write out fully)
DRUG_ERA
MEASUREMENT
OBSERVATION
VISIT_OCCURRENCE (called 'visit')

It is missing data from the following tables (even though that data does exist in the person's record):

PROCEDURE_OCCURRENCE  (highest priority to fix)
DEVICE_EXPOSURE  (second highest priority to fix)
OBSERVATION_PERIOD  ( to see the spans of time that a person is supposed to have data)
DEATH
COHORT   (could list the cohorts the person is in and show the spans of time)
SPECIMEN  (no data for this person)
NOTE  (no data for this person)
PAYER_PLAN_PERIOD

![image](https://cloud.githubusercontent.com/assets/731930/16565202/ca9b8f7a-41d9-11e6-8d3d-db8bcab941e8.png)

**Comment by pbr6cornell** [comment]
Sigfried, a legitimate use case came up where we really needed to see PROCEDURE_OCCURRENCE and DEVICE_EXPOSURE in a patient profile, but it wasn't there.  Can you please add those in (and include the other data as well if not too much work)?

**Comment by anthonysena** [comment]
Device, procedure and specimen added as part of v1.2.0 #203

OHDSI/WebAPI@7fad59e91d990a5a0170614f50051d9212edcba5
