### ISSUE TITLE
Show author, last changed (date and version) and "changed by" in cohort design screen

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#1701]
### Expected behavior
The cohort design screen should show core cohort attributes, including the author, last changed (version) and changed by fields.  Ideally, would be good to think about implementing versions and version history (it is very easy to save JSON every time something changes). The version history - let's not make it a big effort and bells and whistles, simple things will be just fine.

### Actual behavior
No such fields are displayed except in the table view.  It is very unclear who created it, when and who changed it and when. I

@anthonysena, @pavgra

**Comment by pbr6cornell** [comment]
I agree that displaying cohort definition attributes, when available, is a good idea.

We should not pursue implementing version history in JSON for ATLAS 2.8, but may be something that we can consider during design sessions for ATLAS 3.0 (though we've many discussions about versioning, and it does not seem like that would be a problem unique to cohort definitions alone).

**Comment by anthonysena** [comment]
For this issue, I'd suggest we change the title on each entity design page to display the author & last updated details. For example, on the cohort screen this would look like:

`Cohort #<x> last updated: <YYYY-MM-DD HH:MM:SS> by <user>`
