### ISSUE TITLE
Error is thrown when a user saves updated PLP

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1708]
![error-during-plp-persistance](https://user-images.githubusercontent.com/10010071/56973997-fb028680-6b3b-11e9-8f31-d7e006ed4e8b.gif)

https://testatlas.arachnenetwork.com

**Comment by anthonysena** [comment]
Encountered the same problem - 404 when attempting to hit: `http://<server>/WebAPI/prediction/<id>/exists?name=<prediction study name>`

**Comment by anthonysena** [comment]
Nevermind - the 404 was my mistake (was on an older WebAPI branch)
