### ISSUE TITLE
Not possible to create AD sync job

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Atlas#1716]
### Expected behavior
It should be possible to create AD sync job

### Actual behavior
It's not possible to save entity as Execute dropdown is empty

### Steps to reproduce behavior
![image](https://user-images.githubusercontent.com/4144173/57682613-e98ca480-763a-11e9-8564-3580ddac2a48.png)

**Comment by pavgra** [comment]
Closed by https://github.com/OHDSI/Atlas/pull/1717 & https://github.com/OHDSI/Atlas/pull/1729
