### ISSUE TITLE
Need to have some functionality to delete a cohort

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#172]
I inadvertently hit 'copy' twice, creating two instances of a new cohort, when I only needed one.  There is currently no way to delete a cohort definition (and its associated cohort records) from the ATLAS UI.

**Comment by leenadR** [comment]
+1
Circe already has such a button to delete a cohort, perhaps the functionality could "easily" be copied?

**Comment by anthonysena** [comment]
Resolved as part of #199. Delete, but delete wisely.
