### ISSUE TITLE
Update included source codes after excluding standard concepts from existing concept set

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1722]
### Expected behavior
In previously created concept set when adding a standard concept for exclusion the included source codes should reflect what was excluded. 
### Actual behavior
In previously created concept set when adding a standard concept for exclusion the included source codes do not reflect what was excluded until a page refresh is done. 
### Steps to reproduce behavior
Open previously created concept set add a standard concept for exclusion click on the included source codes tab and observe that the source code remains until the page is refreshed; after refresh the expected included source code is removed.

**Comment by anthonysena** [comment]
@jhardin29 I believe this issue has been fixed with the v2.7.2 release and so I'm closing this out. If the issue persists, please do let us know. Thanks!
