### ISSUE TITLE
New version of ATLAS includes SQL for creating counts, breaks standalone use of SQL

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Atlas#174]
The new version of ATLAS includes SQL for creating summary counts in the cohort definition SQL. However, this is not always desirable, for example when using the SQL inside a study R package.

The simplest solution for me would be to clearly demark the offending piece of SQL, for example using comments, so I can easily remove it when fetching the SQL from WebAPI.

**Comment by chrisknoll** [comment]
Martijn,
  Sorry for this problem: the code that generates the statistics shouldn't appear at all in the SQL from the webapi.  I can make a fix for tihs on master if you can pull that? Or would you want this on a branch?

**Comment by schuemie** [comment]
Hi Chris,

I'm using our internal WebAPI, so I'll wait for you guys to update it ;-)

No rush, I have a workaround in place. I just wasn't sure whether it was a permanent thing.

**Comment by chrisknoll** [comment]
Hi, pushed to our internal environment on hix so you should be able to work directly with the output from WebAPI. Sorry for the problem.

**Comment by schuemie** [comment]
I can see the fix of #cohort_candidate, but the count code is still there?

**Comment by chrisknoll** [comment]
Grumble!  I checked opening up the cohort in atlas and looking at the SQL. Nothing is there that shouldn't be.  Can you drop the snipit of the cohort SQL you're exporting here and I can see if I can see what you see? Can you also give me the cohort def id you're using in our internal environment and i'll look into what could be happening there.
