### ISSUE TITLE
Concept hierarchy are not showing concepts that have CONCEPT_ANCESTOR records

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1752]
This is likely due to an override from the [metatrix](https://github.com/OHDSI/Atlas/blob/master/js/const.js#L148) we should potentially deprecate that functionality and have the hierarchy use the min_levels_of_seperation with +1/-1 to show nearest parent/children concepts.

**Comment by pbr6cornell** [comment]
It woud prioritize this fix for 2.7.2 as many concepts do not appear as expected, including drug ingredient and classes.

**Comment by anthonysena** [comment]
Thanks @pbr6cornell. Just to note for this issue - here is the current (Atlas 2.7.1) display for metformin:

![image](https://user-images.githubusercontent.com/12902366/58498954-19649d80-814d-11e9-907d-31b0c93bcc48.png)
(children are cut off at the bottom of the screenshot).

After removing the metatrix, the number of parents (+1 for `min_levels_of_separation`) and children (-1 for `min_levels_of_separation`) grew substantially which made the display hard to navigate. So, I made some adjustments to solicit feedback. Here are the changes with a quick GIF to show the differences: 

- There are pill tabs at the top that allow you to see the full hierarchy and then filter to the parent, current, and child concepts. Additionally, I added some bootstrap panels to each section to make them a bit easier to find when the lists get longer.
- Added facets to the parents/children to make it easier to filter the contents (please let me know if there are others that would be useful to add here).

![issue-1752-draft](https://user-images.githubusercontent.com/12902366/58499223-b1fb1d80-814d-11e9-85d5-56ceb108c754.gif)

Tagging @fdefalco for awareness and feedback on this item.

**Comment by pbr6cornell** [comment]
I support the new UI for the hierarchy tab.   I am a bit concerned with how many children we're seeing for a given ingredient in your metformin example, so wondering if we need to confirm with vocabulary team and @cgreich that our logic for finding parent-child from the CONCEPT_ANCESTOR is correct (e.g. using the MIN_LEVELS_OF_SEPARATION = 1).

**Comment by anthonysena** [comment]
After review with @chrisknoll, @pavgra and @gklebanov we'd also like to remove the indentation on the tables since that's no longer necessary and also remove the redundant "concept" label. 

@pbr6cornell  thanks for that feedback and I'll post up the queries we're using for that section to confirm with @cgreich and team

**Comment by anthonysena** [comment]
To add to this discussion: the hierarchy tab in ATLAS is constructed from the related concepts endpoint:

`/WebAPI/<vocbulary source key>/concept/<concept_id>/related`

which then executes the [getRelatedConcepts.sql](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/vocabulary/sql/getRelatedConcepts.sql) query. Since this query is aiming to get all related concepts for the selected `concept_id`, it queries the `concept_relationship` and `concept_ancestor` tables and UNIONs the results together. This query aliases a column called **`relationship_distance`** which is set to 1 for those entries sourced from the `concept_relationship` table while the column `min_levels_of_seperation` is used for those entries source from `concept_ancestor`.

From the ATLAS side, to construct the hierarchy, we consider those entries from `/WebAPI/<vocbulary source key>/concept/<concept_id>/related` that meet the criteria in the [defaultConceptHierarchyRelationships](https://github.com/OHDSI/Atlas/blob/master/js/pages/concept-sets/const.js#L11):

````
    const defaultConceptHierarchyRelationships = {
		childRelationships: [{
			name: 'Has descendant of',
			range: [0, 1]
		}],
		parentRelationships: [{
			name: 'Has ancestor of',
			range: [0, 1]
		}]
	};
````

The `range` attribute in the data structure above is used to filter the related concepts to those that have a **`relationship_distance`** in range (in this example, between 0 and 1, inclusive). I adjusted this data structure so the range value is now: `[1, 1]` to consider those parent/child relations that are exactly 1 from the current concept. Here is the revised screen grab after adjustment based on feedback here:

![issue-1752-draft-v2](https://user-images.githubusercontent.com/12902366/58506155-a8c57d00-815c-11e9-8ead-89caee1570dc.gif)

I'll file the pull request based on what I've done so far and if there is other feedback, we can determine where it is best to make those changes (i.e v2.7.3, v2.8.0, etc)

**Comment by cgreich** [comment]
- confirm with @cgreich and team

How can I help, Anthony? I am not sure I understand the problem you are trying to solve.

**Comment by anthonysena** [comment]
Hi @cgreich - thanks for reaching out. We wanted to confirm that the approach we've planned for this issue is correct. 

When getting the parent/child relationship for a given concept in ATLAS, we're leveraging the results of WebAPI's "getRelatedConcepts" endpoint which queries the `CONCEPT_RELATIONSHIP` and `CONCEPT_ANCESTOR` to get all related concepts. In ATLAS, we're using the results of this query to populate the "Related Concepts" tab and then re-using those results to construct the contents of the hierarchy tab. The way the Hierarchy is constructed (based on changes in this issue) is to find those results returned and filter down to those that have a "Has ancestor of" or "Has descendant of" relationship and a relationship_distance of 1. 

I've modified the query from WebAPI a bit and translated it below for your review (using the metformin example from this issue):




```
select distinct * from (
    select c.CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, c.VOCABULARY_ID, RELATIONSHIP_NAME, 1 RELATIONSHIP_DISTANCE
    from Vocabulary_20190123.dbo.concept_relationship cr
    join Vocabulary_20190123.dbo.concept c on cr.CONCEPT_ID_2 = c.CONCEPT_ID
    join Vocabulary_20190123.dbo.relationship r on cr.RELATIONSHIP_ID = r.RELATIONSHIP_ID
    where cr.CONCEPT_ID_1 = 1503297 and cr.INVALID_REASON IS NULL
    union
    select ANCESTOR_CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, c.VOCABULARY_ID, 'Has ancestor of' , MIN_LEVELS_OF_SEPARATION RELATIONSHIP_DISTANCE  
    from Vocabulary_20190123.dbo.concept_ancestor ca
    join Vocabulary_20190123.dbo.concept c on c.CONCEPT_ID = ca.ANCESTOR_CONCEPT_ID
    where DESCENDANT_CONCEPT_ID = 1503297
    and ANCESTOR_CONCEPT_ID <> 1503297
    union 
    select DESCENDANT_CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, c.VOCABULARY_ID, 'Has descendant of' , MIN_LEVELS_OF_SEPARATION RELATIONSHIP_DISTANCE  
    from Vocabulary_20190123.dbo.concept_ancestor ca
    join Vocabulary_20190123.dbo.concept c on c.CONCEPT_ID = ca.DESCENDANT_CONCEPT_ID
    where ANCESTOR_CONCEPT_ID = 1503297
    and DESCENDANT_CONCEPT_ID <> 1503297
    union
    select distinct c3.CONCEPT_ID, c3.CONCEPT_NAME,isnull(c3.standard_concept,'N') STANDARD_CONCEPT, ISNULL(c3.INVALID_REASON,'V') INVALID_REASON, c3.CONCEPT_CODE, c3.CONCEPT_CLASS_ID, c3.DOMAIN_ID, c3.VOCABULARY_ID, CONCAT('Has relation to descendant of : ', RELATIONSHIP_NAME) RELATIONSHIP_NAME, min_levels_of_separation RELATIONSHIP_DISTANCE
    from (
            select * from Vocabulary_20190123.dbo.concept where concept_id = 1503297
    ) c1
    join Vocabulary_20190123.dbo.concept_ancestor ca1 on c1.concept_id = ca1.ancestor_concept_id
    join Vocabulary_20190123.dbo.concept_relationship cr1 on ca1.descendant_concept_id = cr1.concept_id_2 and cr1.relationship_id = 'Maps to' and cr1.invalid_reason IS NULL
    join Vocabulary_20190123.dbo.relationship r on r.relationship_id = cr1.relationship_id
    join Vocabulary_20190123.dbo.concept c3 on cr1.concept_id_1 = c3.concept_id
) ALL_RELATED 
WHERE ALL_RELATED.RELATIONSHIP_NAME IN ('Has ancestor of', 'Has descendant of')
  AND ALL_RELATED.RELATIONSHIP_DISTANCE = 1
order by RELATIONSHIP_DISTANCE ASC

```

Note the modification I made above is the outer WHERE clause to show you how we're effectively filtering these results on the ATLAS front-end. Does this look correct to you?

**Comment by cgreich** [comment]
Quick question:

Why are you not just using CONCEPT_RELATIONSHIP for the related concepts, and CONCEPT_ANCESTOR (maybe with min_levels_of_separation=1 if you don't want to overwhelm it) for the hierarchy? Why mixing the two?

**Comment by anthonysena** [comment]
> Why are you not just using CONCEPT_RELATIONSHIP for the related concepts, and CONCEPT_ANCESTOR (maybe with min_levels_of_separation=1 if you don't want to overwhelm it) for the hierarchy? Why mixing the two?

I think the goal was to get the most comprehensive view of the related concepts which was done by using both tables. @fdefalco - do I have that right? Your point is taken though: perhaps these endpoints should hit each table atomically vs creating a single endpoint that uses both tables.

That said, any concerns with the approach I detailed above?

**Comment by cgreich** [comment]
Yes. It's not a good idea (and killed the ATC classification in ATLAS)>

1. a single level of separation could be constructed through a string of more than one CONCEPT_RELATIONSHIP record. That happens because only the standard concepts count. So, you can have a chain standard - relationship - non-standard - relationship - standard. In the CONCEPT_ANCESTOR, it would still make a single level of separation.

2. There are lateral relationships that don't increment the level of separation. That way, Clinical Drug and Branded Drug have levels of separation=0.

So, trust the CONCEPT_ANCESTOR logic. Don't try to double-guess it. If there is a mistake complain.

**Comment by anthonysena** [comment]
Thanks @cgreich for this information - I'm going to open a new issue where we can see about adding additional end-points to WebAPI to query the vocab tables you mentioned apart from the current "related concepts" endpoint.

**Comment by chrisknoll** [comment]
This is a good idea to not break backwards compatibility/current behavior.  We can always plan to retire the obsolete endpionts in 3.0 (or later if we want to do it more gracefully:  mark as deprecated for 3.0, remove it in 4.0, etc).
