### ISSUE TITLE
Importing concept set into cohort definition fails to render included concepts/codes

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1753]
### Expected behavior

Importing a concept set from the repository into a cohort definition allows for browsing of included concepts and source codes.

### Actual behavior

Once the concept set is imported, the concept set expression is properly set and the count of included concepts is displayed. However, the list of included concepts & source codes is empty.

### Steps to reproduce behavior

Create a new cohort definition, import a concept set from the repository. Navigate to the concept set expression to verify that the concept set has been imported. Next, observe that the included concepts and source codes lists are empty and the export shows an empty concept set.

**Comment by pbr6cornell** [comment]
@pavgra and @gklebanov , I would appreciate if you guys could help with all the open bugs associated with conceptset expressions 'losing their state' and not refreshing the 'included concepts' and 'included conceptsets', and also when going into search, not having the appropriate flags set for which concepts are or are not in an active conceptset (e.g. the orange/gray shopping cares).   We need to do thorough testing by clicking on and out of conceptsets, import, add/delete, to make sure state is maintained everywhere.   we also have to make sure its consistent across the various places where conceptsets live  (e.g. in conceptsets,  within a given cohort definition,  in incidence rates for stratify criteria, etc.).
