### ISSUE TITLE
Reporting Export button bug when no reports available

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#178]
When clicking "Export" in the Reporting tab, if no reports are available, you get sent over to this URL which shows you a bunch of JSON:

http://<Atlas URL>:8080/WebAPI/<db name>/cohortresults/function%20d()%7Bif(0%3Carguments.length)return%20d.Wa(c,arguments[0])&&(d.X(),c=arguments[0],d.W()),this;a.k.Ob(d);return%20c%7D/export.zip

Probably just need to disable the button if no reports are available to export or a modal informing the user.

**Comment by fdefalco** [comment]
this button has been removed.
