### ISSUE TITLE
inclusion tab - select concept but not visible until exit and return to cohort

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#180]
In developing a cohort and working on the inclusion tab, when a concept was selected it was not visible until saving and exiting the cohort and then returning to the cohort.

**Comment by anthonysena** [comment]
Jill, can you check on this bug in the latest release? I believe that it is resolved. @chrisknoll

**Comment by anthonysena** [comment]
Addressed as part of v1.2.0 #203
