### ISSUE TITLE
Incidence Rates: embedded concept set import fails

### ISSUE THREAD

**Issue by wivern** [OHDSI/Atlas#1801]
### Expected behavior
Imported concepts shown in the IR embedded conceptset

### Actual behavior
![ir-conceptset](https://user-images.githubusercontent.com/1109753/58628881-8a3dbe00-82e3-11e9-8477-ff2ce210caaf.png)

### Steps to reproduce behavior
![09f92c82-c70c-429b-8177-f11b463e11f9](https://user-images.githubusercontent.com/1109753/58628885-90cc3580-82e3-11e9-9432-ab03e40d5933.png)

**Comment by chrisknoll** [comment]
Should be fixed in #2132
