### ISSUE TITLE
Atlas: Data sources view fails if datasource:name contains spaces

### ISSUE THREAD

**Issue by leenadR** [OHDSI/Atlas#181]
As the title says - AchillesWeb displays data from sources correctly, even if the name contains spaces. However, the integrated version of Atlas fails to render the document. Searching for the cause, I found: Atlas tries to load the data from a URL generated from the name, not escaping the space:
- Atlas: http://someip/Atlas/#/datasources/OHDSI Test/dashboard
- Achillesweb: http://someip/AchillesWeb/#/OHDSI%20Test/dashboard

Workaround: Do not use spaces (e.g. "OHDSI_Test"), then it works.

**Comment by anthonysena** [comment]
@t-abdul-basser I believe this is addressed with the upcoming V2.0 release? If so, can you tie this to the V2.0 milestone and close it when everything is released? Thanks!

**Comment by t-abdul-basser** [comment]
@mark-velez do you want to take this?

**Comment by fdefalco** [comment]
As the route is no longer tracked in the URL this should no longer be an issue.

**Comment by t-abdul-basser** [comment]
Ah. Good catch. I forgot about the new routing approach. Thanks @fdefalco!
