### ISSUE TITLE
Clicking on links in Notification screen should bring user to results that were generated

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1819]
### Expected behavior

From Notifications screen, clicking on a link would open the analysis on the results section of whatever was generated.

### Actual behavior

Inconsistent referencing from the Notifications screen:

![image](https://user-images.githubusercontent.com/731930/58706121-210b8880-837f-11e9-90a3-58382a9805ec.png)

Here, the incidence rate link sends to the incidene rate design page.  Characterization goes to the characterization results page (loads the results).   Heracles cohort link goes to cohort reporting, but then user must select source and report.   Cohort goes to cohort/generation page, but not selected on 'view reports' for the cohort generated.   Pathways analysis opens the results for the generated source.

### Steps to reproduce behavior

Click through links of generated features in ATLAS and see how they go to different places.

**Comment by pbr6cornell** [comment]
@Kenn4095 should be able to add some test cases to make sure that this works during the ATLAS 2.8 testing process.

**Comment by ssuvorov-fls** [comment]
Fixed. 
Ir link now opens report
Heracles cohort link goes to cohort reporting and selects source
Cohort link now opens report

**Comment by anton-abushkevich** [comment]
Please, add links to PLP and PLE generation results. For now, clicking PLP and PLE jobs leads to home page.

**Comment by ssuvorov-fls** [comment]
@anton-abushkevich fixed
