### ISSUE TITLE
Add description field for all ATLAS analyses

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#1823]
### Expected behavior
User should be able to specify description for each analysis in ATLAS

### Actual behavior
today, it exist on some analyses only - Cohort, PLE and PLP. The proposal is to add description for each ATLAS analysis as well as have it done in the same consistent UI design

**Comment by vojtechhuser** [comment]
+1

**Comment by anthonysena** [comment]
Closing in favor of #2724 which aims to address this enhancement.
