### ISSUE TITLE
Consistent execution / results screen across ATLAS

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#1825]
### Expected behavior
ATLAS should implement a consistent Execution/Results panel across all analyses. Today, the panel is different for just about every analysis type, with IR completely deviating from the rest of design choices.

**Comment by chrisknoll** [comment]
> with IR completely deviating from the rest of design choices.

IR was the latest iteration in the evolution of the UX.  IR should be considered the target approach for the following reasons:

1. Only sources generated show results.  In our local env, we have > 20 sources.  Finding the source with results is easier when you don't have to navigate through 19 other sources to find the 1 result.
2. IR allows you to delete executions, so if you did accidentally generate on 2 or 3 sources, you can clean that up.
3. IR allows you to select the sources you want to generate in a simpler and safer manner:  By clicking on generate, you get a display of sources which are available.  You can click on checkboxes accidently without triggering a generate (today, if you click on a generate button, you have to cancel it if you want to stop it, which leads to unnecessary load on the server

For these reasons (and more) we should be looking at IR as the model for the UX, not the exception.  

One reason for the lack of adoption was that, while this approach offered several improvements, it was still something that wasn't thoroughly reviewed by the community, and until we had full consensus, it was better to hold off on applying it everywhere.

**Comment by pavgra** [comment]
Basically, in the IR refactoring which @chrisknoll mentioned, we repeated all patterns which were previously implemented in Arachne. So I don't think that @gklebanov will have concerns with the approach
