### ISSUE TITLE
ATLAS / Characterization:  'create new conceptset' unknown function?

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1834]
### Expected behavior

I don't know what this button is supposed to do.

### Actual behavior

From Characterization / Executions, there is a button 'create new conceptset'. 

![image](https://user-images.githubusercontent.com/731930/58896269-a36bb380-86c3-11e9-8239-a7ffb73e080e.png)

It is unclear what this button is supposed to do.  When I click it on my v2.7.2RC2 instance, it froze my screen for several minutes, before opening up a new conceptset with many errors.

![image](https://user-images.githubusercontent.com/731930/58896393-e7f74f00-86c3-11e9-80a9-b1e3997b70ba.png)

### Steps to reproduce behavior

So, issue 1:  why is this button here?  for what purpose do we have it, and what do we expect this button to do?

Issue 2, which I can then test, will be to confirm whether it does what we want it to do (if we want to do something).

**Comment by pavgra** [comment]
@pbr6cornell , here is the request for the feature - https://github.com/OHDSI/Atlas/issues/1417

**Comment by anthonysena** [comment]
@pavgra - the functionality requested in #1417 is a different from the behavior @pbr6cornell has shown here. I'd propose we hide that button and circle back on #1417 to detail out the required functionality.
