### ISSUE TITLE
PLE should label NC field as required

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1846]
### Expected behavior
If Atlas allows to download/execute PLE, this should mean that the design is valid. Otherwise, Atlas should show issues with the design

### Actual behavior
Atlas allows to execute/download PLE with empty NC which leads to SQL exception during execution

**Comment by anthonysena** [comment]
This appears to be fixed now in reviewing a development build of 2.8. Assigning to @KSadomtsev to confirm it can be closed after testing.

**Comment by KSadomtsev** [comment]
verified
