### ISSUE TITLE
Cohort Generation Failed/Pending

### ISSUE THREAD

**Issue by ambuj369** [OHDSI/Atlas#1849]
Expected behavior - Cohort generation should complete.

Actual behavior - Cohort Generate either stuck on Pending state or Failed

Steps to reproduce behavior-
1. Click new cohort
2. Assign parameters
3. Click generate under generation tab
4. Status will stuck in PENDING
5. Click Cancel > takes lot of time to cancel then changes status to FAILED
6. Click Generate button again
7. Status > COMPLETE

Logs are attached for cohort which FAILED , then COMPLETED
Atlas version 2.7.1
WebAPI version 2.7.1
DB : Postgresql

![Screenshot from 2019-06-06 18-33-30](https://user-images.githubusercontent.com/47858365/59035394-d14f2480-888a-11e9-98a4-2f342a17f21d.png)

One more thing to observer that when cohort generation is in pending state and we go to create  Characterization Execution, it also stays idle with the status "STARTED" and Duration keeps incrementing.

Thank you
Ambuj

**Comment by chrisknoll** [comment]
That exception message from your log was very useful. This is the code that is reporting a null:

```
    CohortGenerationInfo info = findBySourceId(df.getGenerationInfoList(), sourceId);
    info.setIsValid(false);
```

The findBySourceId is:

```
  private CohortGenerationInfo findBySourceId(Collection<CohortGenerationInfo> infoList, Integer sourceId)
  {
    for (CohortGenerationInfo info : infoList) {
      if (info.getId().getSourceId().equals(sourceId))
        return info;
    }
    return null;
  }	
```

There is a code-path here that can return null from `findBySourceId`, which makes blindly calling `info.setIsValid(false)` unsafe.  findBySourceId should probably throw an exception if the source is not found (if we expect it to be not-null) or a new cohortGenerationInfo should be created in the event the generation info is not found.  Or some other option that I may not be aware of since this code has been modified a bit since I've worked on it.  Tagging @wivern , @pavgra.

**Comment by ambuj369** [comment]
@chrisknoll 
Thank You, I really appreciate your quick response on this.

@pavgra @wivern 
Please suggest how it can be fixed.

Ambuj

**Comment by ambuj369** [comment]
I have added logs I captured from postgresql for COMPLETE and FAILED operations from Atlas.
May be this will help to find out the root cause of the issue.

[pgsql-COMPLETE.txt](https://github.com/OHDSI/Atlas/files/3266110/pgsql-COMPLETE.txt)
[pgsql_FAIL.txt](https://github.com/OHDSI/Atlas/files/3266112/pgsql_FAIL.txt)

Thank You
Ambuj

**Comment by pavgra** [comment]
@ambuj369 , could you share your cohort design?

**Comment by chrisknoll** [comment]
@ambuj369 : to share your cohort design, go into the Atlas UI, go to the cohort definition -> export (tab) -> Json (tab), and copy the JSON content into a text file. Then attach it to this issue here. We'll be able to import the cohort definition and investigate if there's an issue.

**Comment by ambuj369** [comment]
Hello @pavgra 

The cohort design is attached.
[Cohort_Definition.txt](https://github.com/OHDSI/Atlas/files/3270932/Cohort_Definition.txt)

The pgsql logs from previous post are attached for the same cohort attached with this thread,

**Comment by chrisknoll** [comment]
I didn't step through code for this, but in theory, what is happening is the first time it runs, the call to ` CohortGenerationInfo info = findBySourceId(df.getGenerationInfoList(), sourceId);` returned a null info which causes the job to fail, which then led to a `CohortGenerationInfo` entity to be created.  Then, th enext time it is run (for the same source), the ` CohortGenerationInfo info = findBySourceId(df.getGenerationInfoList(), sourceId);` returns a non-null info, which allows the task to complete.  

Is this possible, @pavgra?

**Comment by ambuj369** [comment]
@chrisknoll @pavgra 
The situation occurs only for new cohorts. In addition, if a new cohort is in generation step, and again a new cohort is generated by some other user from some other computer in network, it also get stuck in PENDING state.
One PENDING state is stopping other cohorts to generate the report.

Also, I would like to know that how many concurrent users can create cohort or create IR analysis?

Thank You

**Comment by ambuj369** [comment]
@chrisknoll @pavgra 
I found some garbage entries in webapi tables due to which the cohort generation was failing. I dropped the schema, redeployed Webapi and cohort generation or any associated feature started working.

Suggestion: Add checks into user input fields to avoid any special characters or so to stop sql injection attacks on the application.

Thank You
Ambuj
