### ISSUE TITLE
Feature analysis - adding criteria requires multiple clicks

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1863]
### Expected behavior

When defining a prevalence feature, I can add a criteria to a group in a single click

### Actual behavior

When attempting to create demographic criteria, I have to click multiple times before the criteria is added to the display

### Steps to reproduce behavior

Create a new feature analysis - mark it as "demographics" under the description heading. In the design area, select "Criteria", select Analysis Type == "Prevalence". In the automatically added criteria, click "Add Criteria To Group" and select "Add Demographic". Then click "Add Attribute" and attempt to select "Add Age Criteria" and wait. It will not add. Repeat this and it will eventually add (usually after 2 to 3 clicks)

**Comment by vlbe** [comment]
That's wrong PR referenced for this issue. Actually i cannot reproduced it. I followed your steps on my local env and on stage but when i select "age of criteria" it's instantly shows.

**Comment by anthonysena** [comment]
Thanks @vlbe for reviewing this. While I was able to reproduce this consistently on Friday, after a reboot this morning, I'm having a bit of trouble reproducing this problem. Let me move this out for consideration for 2.8.

While trying to reproduce this problem this morning, I think the problem here may relate to selecting the same attribute more than one time. In this example, the drop down allows me to select "Add Age Criteria" multiple times (the screen only shows it once). If I do that, it seems that selecting some of the other options or even attempting to remove an attribute requires multiple clicks.

**Comment by chrisknoll** [comment]
@anthonysena , are you seeing this behavior on the cohort definition editor side?  Those are sharing the same components, so I would expect you see the same behavior in both places, but I don't recall seeing this (and I do a fair amount of cohort editing).

**Comment by anthonysena** [comment]
@chrisknoll - just confirmed that this also applies when editing a cohort. Here is how I'm (kind of) able to reproduce this:

Create a demographic criteria as mentioned earlier in this issue and then: 
1. From the "Add Attribute" drop down, click on "Add Age Criteria". The criteria will appear below the drop down. Repeat this same step a few times which will not change the display since that attribute is already displayed.
2. Repeat the same "Add Attribute" operation for "Add Gender Criteria". Again, repeat this unnecessarily a few times. The criteria is added properly.
3. Remove the Age criteria. Sometimes this can take a few clicks to register.
4. Remove the Gender criteria. Again, this can take a few clicks to register

If you keep cycling through the step above, you may be able to reproduce this. If not, it is likely just a browser/environment issue on my side but since I was noticing this, I thought it best to note it in case others find the same behavior.

**Comment by chrisknoll** [comment]
Ok, it's a good hint, thank you. I know the event handlers that respond to the click event on the little `X` that is used to remove the criteria, so I can set the breakpoint there and see if it is handling the event.
