### ISSUE TITLE
Number of occurrences for a given measurement can't be more than 10times!

### ISSUE THREAD

**Issue by twamarc** [OHDSI/Atlas#1866]
### Expected behavior
Set number of occurences for a given measurement at xtimes (eg. 100)
### Actual behavior
The only MAX number possible is fixed at 10
### Steps to reproduce behavior
Hi There, 
Not sure this is the right place to ask my question, but didn’t find other way of contact.
I am designing a query where I want to capture all patients with at least 100 occurrences of a lab tests of interest or measurements, on 10 years period.
Any help how I can do this?
The cohort I built was using the inclusion criteria … but number of occurrences is limited at 10! Probably is a wrong way…

Kind regards,

**Comment by chrisknoll** [comment]
We'd have to adjust the editor to allow any numeric value to be entered in that field instead of a preset.

**Comment by anthonysena** [comment]
@twamarc - I'm closing this item since I've now discovered that the same note was made in #1308 so we'll track our work there. Thanks!
