### ISSUE TITLE
Characterization generation fails with custom features

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1869]
The following designs failed to generate against a CDM on PDW:

[cc - Custom custom_fe.txt](https://github.com/OHDSI/Atlas/files/3266497/cc.-.Custom.custom_fe.txt)
[cc - Custom criteria_set.txt](https://github.com/OHDSI/Atlas/files/3266498/cc.-.Custom.criteria_set.txt)

I'm getting an uncategorized SQL Exception for each design. I can share the exceptions privately but just curious to see if it can be reproduced.

**Comment by anthonysena** [comment]
@wivern - we just saw that a number of DB connections were suspended when these characterizations failed to generate. I wanted to see if you saw the same behavior as you worked on OHDSI/WebAPI#1189? Just curious since it may be a good opportunity to also address that problem while we're making changes there. If not, it likely requires another issue.

**Comment by wivern** [comment]
@anthonysena No, I wasn't meet abnormal connections behavior. The root cause of the issue was in the quote in the name of feature.

**Comment by anthonysena** [comment]
OK thanks for confirming @wivern!
