### ISSUE TITLE
Generation display enhancement

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1882]
For consideration - when looking at the generation display such as this one:

![image](https://user-images.githubusercontent.com/12902366/59124565-0c566400-892e-11e9-9555-65f98a8f38fe.png)

When there are no executions for a given source (i.e the display shows "All executions (0)"), could we disable this button? Doing so may make it easier to visually distinguish those sources that have at least 1 generation.

This may be moot if/when we adopt the display strategy from Incidence Rates. Just thought I'd note it while top of mind.

**Comment by vlbe** [comment]
@anthonysena
1) I found out that we have duplication of code for "execution group" component in 4 places(characterization-executions, cca-executions, pathway-executions and prediction-executions). So as a first step we need to extract this to separate component.
2) As a second step i think we can adopt the display strategy from Incidence Rates -
 - There will be a button which opens the modal dialog where you can select sources for generation
- In the list of executions there will be only sources with at least one execution.

**Comment by anthonysena** [comment]
Thanks @vlbe for looking into this and making these notes. Let's hold on any actions here until we have an opportunity to triage and prioritize the items that will go into the 2.8 release.

**Comment by pavgra** [comment]
Overall proposal is to follow the design pattern utilized in Incidence Rates

**Comment by pbr6cornell** [comment]
We need to establish a consistent Generation View experience to be applied across all features.  This is a main goal of ATLAS 3.0.

**Comment by chrisknoll** [comment]
I beleive v2.12 or v2.13 introduced a standardized view for generation...as far as it can be standardized:   some cases (CC, TxP) you can have a history of generations.  Other cases (IR, cohrot defs) yu just have the latest generation.  However, we standardized the layout of the generate buttons, and filtering options.
