### ISSUE TITLE
Ordering of Daimon Alpha

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#190]
@chrisknoll  or @anthonysena 

Could we add an alphabetical sort to the daimon's in the UI?
- Configure Screen
- Generate page
- Reporting Screen
- Patient Profile DB Selector ("Select a data source")

**Comment by ericaVoss** [comment]
I think this is completed in some way as well?

**Comment by anthonysena** [comment]
Looks like we got this one - I'll close it out. Thanks!
