### ISSUE TITLE
Prediction covariate settings include string

### ISSUE THREAD

**Issue by jreps** [OHDSI/Atlas#1901]
The string guiding the user mentions propensity score which is not the case for the prediction interface: 

### Expected behavior
"What concepts do you want to include in baseline covariates in the patient-level prediction model? (Leave blank if you want to include everything)"

### Actual behavior
"What concepts do you want to include in baseline covariates in the propensity score model? (Leave blank if you want to include everything)"

**Comment by anton-abushkevich** [comment]
@anthonysena @jreps 
There are 2 mentions of "propensity score" in PLP. Should we change them both to "patient-level prediction"?
![изображение](https://user-images.githubusercontent.com/765539/91843047-bde16380-ec5d-11ea-8327-c028d5e4cdda.png)

**Comment by anthonysena** [comment]
@anton-abushkevich yes, both should state either "propensity score model" or "patient-level prediction model" depending on the context (estimation/prediction).
