### ISSUE TITLE
Auto Relogin

### ISSUE THREAD

**Issue by anemniugin** [OHDSI/Atlas#1907]
### Expected behavior
Do not change user 
### Actual behavior
Sometimes user changed to previous user who  login to this computer before.
### Steps to reproduce behavior
Can't get stable test case to reproduce this bug.

*I've sent video record with bug with this situation to developer.

**Comment by AntonStepanof** [comment]
cannot reproduce it locally. It can be useful to reproduce it with additional logs: https://github.com/OHDSI/WebAPI/tree/issue-1907-added-logs-for-debug

**Comment by olga-ganina** [comment]
Cannot reproduce.
