### ISSUE TITLE
ATLAS version label should display what the current version (build) is, including RC candidates

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#1910]
### Expected behavior
ATLAS version label should display what the CURRENT version (build) and not what is going to be. And the label should be configurable, ideally should display a build date in dev. If not a part of the label, it should be at least displayed somewhere

Examples:
Production (released) - 2.7.2
QA (release candidate) - 2.7.2 RC1 or 2.7.2 RC2 or 2.7.2 RC3
Development - 2.7.2 DEV or 2.7.2 DEV6.15.19

### Actual behavior
It only displays the one label across dev, QA and prod. It is hard to understand what is included
As an example, this is RC3

![image](https://user-images.githubusercontent.com/26966141/59549369-6658ba00-8f2a-11e9-95ab-b9545b9a9c8f.png)

**Comment by anthonysena** [comment]
@wivern - I apologize as I'm having some second thoughts about the approach taken in #2124 as it relates to ATLAS. I think that the work you did in OHDSI/WebAPI#1453 make good sense - it would be useful to know what minimum version of ATLAS WebAPI can support (via the pom.xml `buildinfo.atlas` settings). However, I'm not sure using the version information coming from WebAPI should be something dispalyed in ATLAS - I think that it could be used as a check as described in #688. 

ATLAS has its own versioning and that should be visible to the user to make it clear what has been installed. Perhaps this version could be controlled via the package.json: https://github.com/OHDSI/Atlas/blob/master/package.json#L3? Then on the homepage we display the version as configured in package.json and that can be used to verify that the WebAPI is compatible? Appreciate your feedback on this idea or if there is another approach we should consider.

**Comment by wivern** [comment]
@anthonysena I feel that a great idea to store Atlas version separately in the `package.json`. My point was to store version in a single place but I agree it's highly essential to be able to check versioning compatibility between UI and services.
Probably we can display two separate version labels: one for the WebAPI and another one for the Atlas.

**Comment by anthonysena** [comment]
@wivern - appreciate the feedback here. Would you be able to put in another PR that aims to use the version as specified in the package.json as described above? Then we can see how we might best handle #688 as a separate set of changes assuming that we've nailed this down. Thanks!
