### ISSUE TITLE
Cohort does not export SQL for MSSQL

### ISSUE THREAD

**Issue by wivern** [OHDSI/Atlas#1918]
For MSSQL cohort presents empty text box:

![dcb0d49d-387a-4db7-8076-ab7890eefe07](https://user-images.githubusercontent.com/1109753/59603942-61a32a00-9113-11e9-903b-fa3308766e8c.png)

**Comment by anthonysena** [comment]
@wivern I'm unable to reproduce this error. Can you share the cohort definition for this issue if possible?

**Comment by wivern** [comment]
@anthonysena Yes, here's cohort definition:

`{
  "ConceptSets": [
    {
      "id": 0,
      "name": "Ibuprofen & aspirin",
      "expression": {
        "items": [
          {
            "concept": {
              "CONCEPT_ID": 1112807,
              "CONCEPT_NAME": "Aspirin",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "1191",
              "DOMAIN_ID": "Drug",
              "VOCABULARY_ID": "RxNorm",
              "CONCEPT_CLASS_ID": "Ingredient"
            },
            "includeDescendants": true
          },
          {
            "concept": {
              "CONCEPT_ID": 1177480,
              "CONCEPT_NAME": "Ibuprofen",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "CONCEPT_CODE": "5640",
              "DOMAIN_ID": "Drug",
              "VOCABULARY_ID": "RxNorm",
              "CONCEPT_CLASS_ID": "Ingredient"
            },
            "includeDescendants": true
          }
        ]
      }
    }
  ],
  "PrimaryCriteria": {
    "CriteriaList": [
      {
        "DrugExposure": {
          "CodesetId": 0
        }
      }
    ],
    "ObservationWindow": {
      "PriorDays": 0,
      "PostDays": 0
    },
    "PrimaryCriteriaLimit": {
      "Type": "First"
    }
  },
  "QualifiedLimit": {
    "Type": "First"
  },
  "ExpressionLimit": {
    "Type": "First"
  },
  "InclusionRules": [
    {
      "name": "age",
      "expression": {
        "Type": "ALL",
        "CriteriaList": [],
        "DemographicCriteriaList": [
          {
            "Age": {
              "Value": 30,
              "Op": "gt"
            }
          }
        ],
        "Groups": []
      }
    }
  ],
  "CensoringCriteria": [],
  "CollapseSettings": {
    "CollapseType": "ERA",
    "EraPad": 0
  },
  "CensorWindow": {},
  "cdmVersionRange": ">=5.0.0"
}`

**Comment by anthonysena** [comment]
Thanks for sharing! I'm still unable to reproduce this on my side for what it is worth. Are the other dialects empty or just SQL Server?

**Comment by wivern** [comment]
Just SQL Server, others are ok. I'll double check this on our environment, may be this is the configuration issue but not code.

**Comment by wivern** [comment]
Now this is not reproducible
