### ISSUE TITLE
Characterization preset feature causes failure to display results

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1923]
Related to https://github.com/OHDSI/WebAPI/issues/1199. Using the design mentioned in that issue (but removing the "Age 1-18" feature), the generation of the characterization will work properly. However, when attempting to pull back the results, the following error is thrown:

![image](https://user-images.githubusercontent.com/12902366/59685484-41727a00-91aa-11e9-9fa2-8c34f9b3742d.png)

While tracing through the code, I found that this fails due to the fact that I have included a "custom" feature analysis that uses the "preset" design with the feature extraction preset name of "MeasurementRangeGroupShortTerm". 

Question: Why do we allow a user to define a preset feature through the ATLAS UI when these preset features are defined by FeatureExtraction and are automatically added to the WebAPI DB through this Flyway migration script: https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/db/migration/postgresql/V2.6.0.20180731092421__cohort-characterization.sql#L161

**Comment by pavgra** [comment]
> Why do we allow a user to define a preset feature through the ATLAS UI when these preset features are defined by FeatureExtraction

The original thought was that someone would be able to extend FE and therefore add the new preset analyses

**Comment by anthonysena** [comment]
Thanks @pavgra for that explanation. I'd propose then that for the 2.7.2 release, we remove the custom "preset" feature from the interface. In my experience with this particular issue, I found it confusing that a) I could add a preset feature since that is defined by FeatureExtraction and b) that adding a custom preset was duplicating an existing, system defined feature. Most importantly though, it caused some bugs when displaying results.

Let me know what you think of this proposal.

**Comment by pavgra** [comment]
Ok, let’s do so
