### ISSUE TITLE
CC covariate name improperly rendered

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1926]
![image](https://user-images.githubusercontent.com/10010071/59787028-8e337f00-9296-11e9-8830-2dd5fe2d4c12.png)

**Comment by chrisknoll** [comment]
@pavgra, I believe I understand your comment you made in the other Issue/PR related to escaping user input:  The reason why the text is cut there is the `>` symbol in the name may be leading to some HTML interaction that's causing it to be displayed incorrectly.  In this case, it's not about injecting some HTML tags in the name, it's just legit `>` or `<` or `&` that may be used that should be handled.

**Comment by pavgra** [comment]
@chrisknoll , the problem here is much more simple and is caused by https://github.com/OHDSI/Atlas/blob/master/js/pages/characterizations/utils.js#L26. The function was introduced to simplify covariate names like `condition_era during day -30 through 0 days relative to index: Chronic pyelonephritis with medullary necrosis` and `gender = FEMALE` since analysis name is already presented above covariates table
