### ISSUE TITLE
not enough permissions to generate

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1927]
### Expected behavior
mousing over the generate button on a cohort that has not been saved displays a message that you can not generate a cohort until it has been saved

### Actual behavior
mousing over the generate button on a cohort that has not been saved displays a message that you have insufficient permissions to generate the cohort

### Steps to reproduce behavior
Go to a new cohort definition and mouse over the generate button on the generate tab.
http://www.ohdsi.org/web/atlas/#/cohortdefinition/0/

**Comment by anthonysena** [comment]
@fdefalco - this has been addressed for the upcoming 2.7.2 release with fixes for #1860. I'm going to close this out since this appears to be a duplicate - let me know if you have any concerns with this. Thanks!
