### ISSUE TITLE
Cohort definition message tab

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1933]
### Expected behavior

The messages tab in the cohort definition editor checks the cohort definition for the presence of any unused concept sets and other potential logic errors.

### Actual behavior

The message tab appears to have some trouble with identifying the correct concept sets to delete, if the index has a nested critieria it does not recognize the concept set, etc

### Steps to reproduce behavior

For 2.7.2, let's hide this tab and for 2.8, let's find the root cause and fix it.

https://github.com/OHDSI/circe-be/commit/6926165654bbac739f097b6204771db5bba3faaa

**Comment by chrisknoll** [comment]
Here is the test case that demonstrates this issue.  It's related to sub-groups of criteria groups, where you can have a deeply nested criteria group group 1 -> group 2-> group 3 (*) and group 3 isn't checked for used concept sets, so if you have a concept set used in group 3, it doesn't get picked up.

The routine to find unused concept sets needs to recurse into each sub group all the way to the leaf nodes.

[UnusedConceptsetError.txt](https://github.com/OHDSI/Atlas/files/3315253/UnusedConceptsetError.txt)
