### ISSUE TITLE
Record counts for concept sets in incidence rates

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1935]
### Expected behavior

When reviewing the contents of included concepts for a concept set in the Incidence Rate calculator, the record counts are displayed.

### Actual behavior

The included concepts tab shows 'timeout' for all concepts

![image](https://user-images.githubusercontent.com/12902366/59934513-b7304d00-9419-11e9-94f9-08eafd05e88e.png)

### Steps to reproduce behavior

Create an incidence rate and add a new stratify criteria such as "no prior AMI" and add a concept set to the criteria.

### Important note

This behavior appears to be by design based on tracing through the code:

https://github.com/OHDSI/Atlas/blob/master/js/components/conceptsetbuilder/components/IncludedConcepts.js#L170

**Comment by chrisknoll** [comment]
I can remove these columns from the result. I think that's the quickest solution. The current UI for vocab searching was supposed to be a 'functional stub' to a full blown vocabulary search experience which never became component-ized for reuse here.
