### ISSUE TITLE
Bug? Atlas deselects exclude radio button, when mapped (all) radio button is selected

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#1937]
### Expected behavior
Should not deselect exclude, when (all) mapped is selected

### Actual behavior
Automatically deselects exclude

### Steps to reproduce behavior

create a concept set with both descendants and exclude, like

![image](https://user-images.githubusercontent.com/13936600/59942042-bd7bf480-942c-11e9-9483-eb1ba5e05bb1.png)

select mapped (**ALL**)
![image](https://user-images.githubusercontent.com/13936600/59942105-ce2c6a80-942c-11e9-9e6e-8c10f271212b.png)

notice - it deslected descendants

Same as 
https://github.com/OHDSI/Atlas/issues/280

Observed in Atlas v2.7

**Comment by chrisknoll** [comment]
The 'select all' for exclude/descendants/mapped' have been removed from the UI.
