### ISSUE TITLE
Special characters in the search bar boots you back to the home screen

### ISSUE THREAD

**Issue by Kenn4095** [OHDSI/Atlas#1950]
### Expected behavior
![image](https://user-images.githubusercontent.com/52466339/60537921-8ed90600-9cd7-11e9-85a9-2ae66f1e715f.png)
When a search concludes no results, the screen shows a page that reads "No results found for *input*"
### Actual behavior
![image](https://user-images.githubusercontent.com/52466339/60538531-cdbb8b80-9cd8-11e9-8baa-6ceff37b6ad1.png)
![image](https://user-images.githubusercontent.com/52466339/60538560-da3fe400-9cd8-11e9-8fed-778edd7337d3.png)
When using certain special characters, clicking search sends you immediately to the home screen instead of trying to complete the search
### Steps to reproduce behavior
Specifically, the characters that produce this behavior are !, *, ', and ~. To get this outcome, have any one of these characters in the search bar with any valid or invalid search and you will be returned to the home screen almost immediately upon searching.

**Comment by anthonysena** [comment]
Fixed via #1720
