### ISSUE TITLE
Concept set not loading

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#198]
I am attempting to edit HIX concept set 2401: http://hix.jnj.com/atlas/#/conceptset/2401/details and it never loads, it just continues to spin. I was using this same concept set in three cohorts and it will not load there either. Other concept sets can be edited, so far I have just found this one that cannot. I worked with this concept set yesterday morning so this is a fairly new issue.

**Comment by chrisknoll** [comment]
Console is showing an error. I'm looking at the concept set, and for some reason it has 7 elements in it, but the 7th one is NULL.  I will try to save a new version of the concept set expression to remove that trailing null, but it would be good to know how that's happening.

**Comment by chrisknoll** [comment]
Clair,
  In the 2014 concept set, there is a concept ID that seems to not exist: 43084218.  I'm not sure how it got there in the first place, unless this concept disappeared as a result of a recent data refresh.

Second issue, however, is that the concept set that has invalid concepts in it seems to be returned oddly in our REST api. 

@fdefalco : i think you put together the concept set repository services, for some reason these routes should return the same concepts but they do not:
http://hix.jnj.com:8080/WebAPI/conceptset/2401/items
http://hix.jnj.com:8080/WebAPI/conceptset/2401/expression

The /expression shows a null concept set item for the invalid concept.  While a solution could be to check for nulls everywhere, I don't think we should be returning nulls in the concept set expression.  Maybe the ones that are not resolved properly can be given a default name/class or some other indication it's not a valid item without polluting the concept set expression with nulls.

**Comment by chrisknoll** [comment]
Clair,
Further information, I did find that concept in ohdsi.org:
http://www.ohdsi.org/web/atlas/#/concept/43084218

So we probably lost it in a vocab refresh; I don't know how up to date the ohdsi.org CDM vocabulary is.  

@cgreich : I believe we have the latest vocabulary, and this concept is in Multilex (and a standard concept, no less) but maybe a recent update retired it? Could you confirm concept ID 43084218 got retired?

**Comment by chrisknoll** [comment]
Added code to prevent corruption of concept sets as well as being able to load already corrupted cohort defs.

**Comment by chrisknoll** [comment]
Sorry, this was fixed in the context of opening a cohort definition, but there is still some problem with the concept set REST apis that are resulting in nulls.
