### ISSUE TITLE
Sources list in Data sources tab does not respect user's permissions

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#2004]
### Expected behavior
Only sources with granted access are listed in the dropdown at Data Sources page.

### Actual behavior
A user observes a list of all sources in the system and can click any. Only then he/she will see a message telling about lack of access.

### Todo

Add permissions check similarly to how it is done in Profiles

**Comment by vlbe** [comment]
@pavgra 
We have 2 permissions related to data source page
1) cdmresults:%s:*:get" - Get Achilles reports on Source with SourceKey = %s
2)  cdmresults:%s:*:*:get" - Get Achilles reports details on Source with SourceKey = %s

There are 2 possible solutions:
1) To check permissions strictly for these 2 and filter data source options
2) To check only first permission and show data source in the select box. Add check for second permission when user click on treemap report to open drilldown report. If user doesn't have second permission - show the alert with "You have no permissions to see this report"?

**Comment by pavgra** [comment]
Imo, the second version is better

**Comment by anthonysena** [comment]
I agree with @pavgra that 2) above is a better way to go for this one.
