### ISSUE TITLE
Issues with npm run build on Atlas 2.7.2

### ISSUE THREAD

**Issue by ambuj369** [OHDSI/Atlas#2009]
### Expected behavior: 
Atlas build should be completed without errors,

### Actual behavior: 
Getting errors, attaching log file.

### Steps to reproduce behavior: 
Go to downloaded directory of Atlas and execute npm run build,
[npm-debug.log](https://github.com/OHDSI/Atlas/files/3481670/npm-debug.log)

**Comment by anthonysena** [comment]
@ambuj369 - can you share a bit more about the environment you are using that is giving this error? Specifically the operating system and also the version of NodeJS/npm you have installed?

@pavgra - could you or someone on your team take a look at this once we get more details?

**Comment by ambuj369** [comment]
@anthonysena 
My bad, I upgraded node.js and npm to version 12 and 6 respectively which resolved the issue.
