### ISSUE TITLE
Unable to view saved cohorts, getting error

### ISSUE THREAD

**Issue by ambuj369** [OHDSI/Atlas#2012]
### Expected behavior:  
Cohort details should load

### Actual behavior: 
Stuck on loading page, getting JSON error on console

### Steps to reproduce behavior:
Create new cohort
Save Cohort
Generate Report
Go back to list of cohorts
Click on saved cohort

Attaching screenshot for error.
![CohortLoadError](https://user-images.githubusercontent.com/47858365/62868581-9e665880-bd33-11e9-90dd-e96ee6b0424d.JPG)

Adding more for headers, preview , response and chortdef.expression function results from chorme.

![Headers](https://user-images.githubusercontent.com/47858365/62879778-86013880-bd49-11e9-82a2-0a89b01d99c4.JPG)
![Preview](https://user-images.githubusercontent.com/47858365/62879779-86013880-bd49-11e9-91ec-32d38741aaa5.JPG)
![Response](https://user-images.githubusercontent.com/47858365/62879780-8699cf00-bd49-11e9-9b54-1f7b5f8a2ebf.JPG)
[Cohortdef.expression.txt](https://github.com/OHDSI/Atlas/files/3493390/Cohortdef.expression.txt)
Atlas version : 2.7.3-RC1
WebAPI: 2.8.0
Upon debugging, I found that there is a change added to js/security/CohortDefinition.js file under getCohortDefinitionId function. I tried to replace the changes as present for version 2.7.2 and tried to launch Atlas, but failed to load. So I had to revert it and staying with the current issue.
This will be an issue for other users too who are on 2.7.3-RC1 version.
Kindly update on this as it is impacting production.
Atlas home screen shows Atlas version as 2.7.2, however the code it has belongs to 2.7.3-RC1. Similarly, WebAPI version on Atlas home screen shows as 2.7.2, but https://myurl.com:8443/WebAPI/info says 2.8.0.

@anthonysena @pavgra @chrisknoll 

If I want to deploy version 2.7.2 of Atlas, which WebAPI version should I consider to build WebAPI.war file.

**Comment by anthonysena** [comment]
@ambuj369 - could you try this with the 2.7.3 build? In general it is best to keep your ATLAS & WebAPI versions in sync.

**Comment by ambuj369** [comment]
@anthonysena 
sure, will try that and let you know.

**Comment by ambuj369** [comment]
@anthonysena 
I tried to deploy Atlas 2.7.3 with WebAPI 2.8.0 and unable to perform any operation. 

Attached is  the screenshot for the error. The same I have been receiving for cohort creation.
![Atlas2 7 3](https://user-images.githubusercontent.com/47858365/64408826-5245d400-d0a5-11e9-8020-3da9f9136413.jpg)

**Comment by anthonysena** [comment]
@ambuj369 - I'd suggest you make sure both Atlas & WebAPI are running the 2.7.3 builds:

https://github.com/OHDSI/WebAPI/releases/tag/v2.7.3

If the problem persists using this build, we can dig into it further.

**Comment by ambuj369** [comment]
@anthonysena I tried deploying Atlas2.7.3 with WebAPI 2.7.3. Things seems to be working fine except downloading the files from Prediction/Estimation modules.
I am attaching the screenshot for error I received in chrome console on Download button Click in Utilities page within prediction.
![Prediction_1](https://user-images.githubusercontent.com/47858365/64513327-e01ffa00-d305-11e9-83e3-fb24e56246ce.jpg)

**Comment by anthonysena** [comment]
@ambuj369 - ok, i'm glad to hear you are past the other error. It appears in this case the export is failing due to some problem in the underlying prediction design. That will also cause it to fail when you attempt to download the study package. The problem should appear in the WebAPI's log file - could you attach that for reference to this issue if possible?

**Comment by ambuj369** [comment]
@anthonysena 
I cannot find any relevant log associated with download study package section. But, I am attaching the tomcat logs for GET/POST requests I received while performing that operation.
![log](https://user-images.githubusercontent.com/47858365/64679360-370a0880-d499-11e9-8791-ae68f08f430b.jpg)

**Comment by anthonysena** [comment]
@ambuj369 - it looks like some of the requests there are returning a 500 error but I do not see any of the details which would appear in the tomcat logs (i.e. `tomcat8-stdout.YYYY-MM-DD.log`). I'm going to close out this issue since it is a bit old but if you are still facing issues please re-open this issue and provide any relevant details and we can continue to investigate.
