### ISSUE TITLE
Imported cohorts are read-only

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#2022]
### Expected behavior

When importing an analysis (i.e. estimation specification) in ATLAS with security enabled, I can view & edit the cohort definitions that are dependencies of the analysis.

### Actual behavior

The imported cohort definition is read-only after input - instead of viewing the cohort definition editor, the 'print friendly' is displayed after import on the 'definition' tab.

### Steps to reproduce behavior

With security enabled in ATLAS, import an estimation specification that contains a cohort definition not present in the system. Then, navigate to the newly imported cohort definition and view the definition tab.

**Comment by wivern** [comment]
@anthonysena I could not reproduce this issue with the current master codebase. Probably this issue was already gone. Could you review and close one, if not reproducible?

**Comment by anthonysena** [comment]
Closing since I can no longer reproduce this on current 2.8 master branch.
