### ISSUE TITLE
Minor bug - the ATLAS Search feature cannot search for parameters that include apostrophes

### ISSUE THREAD

**Issue by conovermitch** [OHDSI/Atlas#2041]
### Expected behavior
I am trying to use the Atlas "Search" feature to select the standard concept for Berger's IgA or IgG nephropathy (condition domain).  To do so, I entered Berger's into the search bar.

### Actual behavior
Instead of producing search results, entering a search term that includes an apostrophe redirects the user to the Atlas Home page. I suspect this is because the apostrophe in the search term is inadvertently closing a character string in the underlying code that is being used to search the database.

### Steps to reproduce behavior
I was able to reproduce this error within my own Atlas system (at Janssen R&D) as well as using the system at atlas-demo.ohdsi.org.  Searching the term including the apostraphe ("Berger's IgA or IgG nephropathy") will reproduce the behavior. To correctly see that there is a standard concept called "Berger's IgA or IgG nephropathy" search Berger and narrow to standard concepts in the condition domain.

Happy to follow-up if anything about my post is ambiguous.  Thanks!

**Comment by anthonysena** [comment]
@conovermitch - thanks for reporting this. This issue has been reported in #1950 which includes this problem. I'm going to close this out so we can track the fixes under that other issue.
