### ISSUE TITLE
Make Ancestor & Related Concept Retrieval On-Demand rather than Automatic

### ISSUE THREAD

**Issue by jduke99** [OHDSI/Atlas#2042]
Every time a user clicks a concept in Vocabulary Search, Atlas does the drill down to get related concepts and hierarchy.  This really pounds the database (particularly when constrained due to DB limitations).

Making these calls occur only when the respective tabs are actually clicked would save a huge amount of traffic and gnarly queries.

Request:  Modify or provide option to only launch these on tab click.

**Comment by jduke99** [comment]
Thank you so much @anthonysena and @fdefalco for getting  this assigned. The semester is starting next week and I am tackling Atlas once again with the class so this change should help with some of the crashing we saw last semester.

**Comment by fdefalco** [comment]
@jduke99 We have quite a few changes to the vocabulary queries and optimizations where in our environments we see query times averaging 2s for the related concepts.  Are you still seeing these performance issues in your environment?

**Comment by anthonysena** [comment]
@chrisknoll per our discussion today, it appears you may have fixed this with your work on concept sets. Assigning this to you to see if you've already fixed it.

**Comment by chrisknoll** [comment]
This may be unrelated to what is being asked here:  the concept set work involves loading included and source concepts, but the vocabulary search (that renders related concepts and hierarchy) is separate from concept sets, so it is possible that the concept set work is independent of this issue.

**Comment by anthonysena** [comment]
Agreed - the concept set behavior is different from the search behavior with respect to this issue.
