### ISSUE TITLE
Integrating Achilles with Atlas

### ISSUE THREAD

**Issue by jcabrerazuniga** [OHDSI/Atlas#2047]
Atlas's deployment instructions says:

Achilles
_To use the Data Sources feature within ATLAS you must first setup and execute ACHILLES in your environment. Once you have successfully generated summary statistics, you are ready to configure ATLAS to use this information._

I am able to run Achilles using a cmd like:

docker run \
  --rm \
  --net=host \
  -v "$(pwd)"/output:/opt/app/output \
  -e ACHILLES_SOURCE=DEFAULT \
  -e ACHILLES_DB_URI=postgresql://**dbuser**:**upassword**@**mydbhost**:5432/ohdsi \
  -e ACHILLES_CDM_SCHEMA=cdm5 \
  -e ACHILLES_VOCAB_SCHEMA=cdm5vocab \
  -e ACHILLES_RES_SCHEMA=webapires \
  -e ACHILLES_CDM_VERSION=5 \
  <image name>

Since I use PostgreSQL I believe I need to pass to Atlas at least the next info at the webapi.source table:

source_connection: jdbc:postgresql://**mydbhost**:5432/ohdsi?user=**dbuser**&password=**upassword**
source_dialect: postgresql
source_key: is this always webapi-CDMV5?
username:   is this **dbuser**?
password:  is this **upassword**?

Should my Achilles schemes (CDM, VOCAB, RES) follow some naming pattern? I went through Atlas Documentation and this is not clear for me.
Thx

**Comment by konstjar** [comment]
Hi

You are on the right way.
source_key - is the alphabetic/number key for your datasource. It could be anything just without spaces.
username - db username
password - db password

The scheme naming is up to you. You can setup own rules for scheme naming in your organization.

**Comment by jcabrerazuniga** [comment]
Then the question will be how to allow Atlas to identify my schema and how it understands from where it can get the Achilles results? How do I need to proceed to allow Atlas to understand my Achilles Schema? Is there any doc about this?  Thanks

**Comment by anthonysena** [comment]
Hi @jcabrerazuniga - the 'results' schema that you set up to run Achilles is the same that is used by Atlas/WebAPI to read in your Achilles results. When you set up your CDM for use with WebAPI & Atlas, you'll just use the same results schema (`webapires` in your case here). 

I agree that this could be more clearly stated in the wiki here: https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration#schema-setup. Let us know if this is of help.

**Comment by anthonysena** [comment]
Updated the wiki to make this clearer.
