### ISSUE TITLE
CCAE Data Sources

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#205]
Clicking on any of the CCAE data sources on the Data Sources tab does not bring you to the correct screen (takes you to vocabulary)

**Comment by chrisknoll** [comment]
Seeing this on our internal dataset as well for Optum Extended SES, note the spaces in the path. Seems like if there's spaces in the name, you get a failure when it tries to parse the route.  I think we need to introduce the notion of a 'key' to the datasources that are used in the routes that is separate from the name (which we can display on the report.

**Comment by t-abdul-basser** [comment]
Yes, I have a fix for this that should be an soon-to-be-submitted-PR. See OHDSI/Atlas/issues/181.

**Comment by chrisknoll** [comment]
Ok, closing as a DUPE.
