### ISSUE TITLE
Generate button on pathway analysis execution page doesn't show generating

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#2069]
### Expected behavior
Clicking Generate in a pathway analysis should show a spinner immediately
### Actual behavior
If there is a job backlog, the genrate button shows a 'not-running' state even tho there is a 'starting' job in the list of executions:

![image](https://user-images.githubusercontent.com/6818777/68886485-4d288500-06e5-11ea-9016-aa5e1d28c05f.png)

### Steps to reproduce behavior
1) Have a full backlog of spring batch jobs in the thread pool
2) Click generate on a pathway analysis so that the status goes into 'starting' (but not started) state
3) Observe, the gernate button is still a generate button, no indication of exeuction (can not cancel) and if you click it again, it will register another task to the backlog.

**Comment by anthonysena** [comment]
Also related to #2021
