### ISSUE TITLE
Error : application initialization failed

### ISSUE THREAD

**Issue by tarunshah** [OHDSI/Atlas#2070]
### Expected behavior
Getting Configuration Page
### Actual behavior
Getting Error 

![OHDSI_ATLAS](https://user-images.githubusercontent.com/18749045/68936801-440ce600-07c1-11ea-9029-63f60532d5ae.JPG)

**Comment by chrisknoll** [comment]
The CORS error means that you haven't configured the WebAPI property `security.origin`.

In your settings.xml file, just set an override of `security.origin` to `http://localhost:63342`, and that should pass the CORS check.

Additionally, you can override `security.cors.enabled` to `false` and that will bypass that check completely according to:
https://github.com/OHDSI/WebAPI/blob/05208923cf2ad6ad1647f006b9aec862db8aad98/src/main/java/org/ohdsi/webapi/shiro/filters/CorsFilter.java#L30

**Comment by tarunshah** [comment]
Still getting the issue
![OHDSI_ATLAS_2](https://user-images.githubusercontent.com/18749045/68952168-6b75aa00-07e5-11ea-80af-20dad6397635.JPG)

**Comment by anthonysena** [comment]
@tarunshah - could you set the `security.origin` to `*` and redeploy the WebAPI.war to see if that fixes this issue? Also, when navigating to Atlas, could you try using `http://localhost:63342/Atlas-2.7.4` and remove the remainder of the URL from your screenshot?

**Comment by anthonysena** [comment]
@tarunshah I'm closing this out due to inactivity but if the problem persists please re-open and we'll continue this investigation.

**Comment by yampeku** [comment]
I'm using atlas 2.9, with webapi `security.origin` to `*` and  `security.cors.enabled` to `false ` and somehow I'm still getting CORS errors when starting ATLAS

![imagen](https://user-images.githubusercontent.com/5321857/119635086-a06baf80-be13-11eb-8931-2564ad048a4e.png)
