### ISSUE TITLE
Concept set export button should be disabled if no one concept was chosen

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2095]
### Expected behavior
Concept set export button is disabled if no one concept was chosen
### Actual behavior
Concept set export button is enabled and we can see an endless loader after a click

![image](https://user-images.githubusercontent.com/56290675/72360220-b423e380-3700-11ea-856d-90617b0cf077.png)

**Comment by anton-abushkevich** [comment]
Problem fixed differently then proposed. Export button is not disabled, but shows an alert if no concept sets selected.
