### ISSUE TITLE
Cohort Name Goes Away in Cohort Reporting Tab

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#21]
When working with a specific cohort in cohort reporting, if you navigate to vocabulary search and then back to cohort reporting you are still examining the same cohort you were before but the name at the top reverts back to 'Click Here to Choose a Cohort'.

**Comment by anthonysena** [comment]
Clair, I'm going to put this issue into our V0.9.0 release and close it out. We've centralized the cohort reporting under the cohort screen so this will no longer be an issue.
