### ISSUE TITLE
update Atlas home page release notes to include the WebAPI 1.3.0 release info

### ISSUE THREAD

**Issue by leeevans** [OHDSI/Atlas#210]
Currently the Atlas home page release notes are manually curated and need to be updated when there is a new release of Atlas and WebAPI.  The latest WebAPI 1.3.0 release info needs to be displayed on the home page.

Here are some alternative solutions:

1) Just update the home page static text for this release to add the missing 1.3.0 WebAPI release info.
2) Remove the static text from the home page and display the Atlas and WebAPI release notes from GitHub via the GitHub API, so the home page release info will automatically be kept up to date when there are new releases.
3) Remove the static text & rename the "prior Atlas releases" and  "prior WebAPI releases" links to say "Atlas releases" and "WebAPI  releases", so users can just click the links to see the latest release notes. 

Note the "prior Atlas releases" and "prior WebAPI releases" links need to be renamed because they include the current release notes.

**Comment by fdefalco** [comment]
We currently curate this page with each release and it has been updated to 2.2
