### ISSUE TITLE
In case of the empty concept set сohort is not being deleted if we add and run generation

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2102]
### Expected behavior
Cohort has been deleted
### Actual behavior
Cohort is not being deleted
### Steps to reproduce behavior
1)Add to any cohort an empty concept set
![image](https://user-images.githubusercontent.com/56290675/72740525-e3ca6400-3bb6-11ea-9b52-f48b873964f7.png)
2)Click to save button
3) Run the generation on any data source
4)Trying to delete the cohort

**Comment by anthonysena** [comment]
Note: let's check if this is reproducible on master branch code for 2.8

**Comment by KSadomtsev** [comment]
I've double-checked this bug. it is not reproduced on 2.8

**Comment by anthonysena** [comment]
@KSadomtsev - do you want to move this to 2.7.7 then? Tagging @olga-ganina for awareness.
