### ISSUE TITLE
Provide ability to export pathway sunburst plots and data 

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#2117]
### Requested behavior
it would be super helpful if we could export the sunburst plots (jpg, bmp?) with all of the drugs included via an export button.
Presently the mechanism to include the plots is to cut and paste manually

**Comment by anthonysena** [comment]
@jhardin29 - I'm hijacking this issue a bit - completely agree that having the ability to export the pathway image is useful. Additionally, we do not currently provide a mechanism to export the underlying data set that is used to construct the pathway sunburst which is equally as valuable for reporting.
