### ISSUE TITLE
VOCAB_ID in front of Vocabularies on ATLAS Advance Search Tab

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#212]
On the Advance search page - could we put the VOCABULARY_ID before the VOCABULARY_NAME?  It hard to find the Vocabulary you want with their full name.  

Examples:

``` text
MedDRA - Medical Dictionary for Regulatory Activities (MSSO)
Gender - OMOP Gender
ATC - WHO Anatomic Therapeutic Chemical Classification
```

If you are looking for ATC you need to know it is prefaced with WHO.

**Comment by cgreich** [comment]
And why wouldn't you use the vocabulary_id - which is the abbreviation?

**Comment by ericaVoss** [comment]
I'm fine with that too.  :)  The long names in the Advance Search make it hard to find what you are looking for.

**Comment by cgreich** [comment]
But you already got that. What else do you need?

**Comment by ericaVoss** [comment]
I'm talking about ATLAS and the Advance Search tab.  If you just want to look at one vocabulary you have to find it in this list:

![image](https://cloud.githubusercontent.com/assets/6305439/17917348/9c339bdc-6989-11e6-84d0-63b02bace4c5.png)

**Comment by cgreich** [comment]
Isn't that an Atlas issue? They can concatenate the vocabulary_id with the vocabulary_name. Or not?

**Comment by ericaVoss** [comment]
@cgreich - yes it is an Atlas issue this is why I posted it in the Atlas GitHub.  :)  Maybe the title isn't descriptive enough.  I'll change it.

**Comment by ericaVoss** [comment]
This would still be a nice to have.  The Advance search for Vocabularies is hard to use without it.
