### ISSUE TITLE
Adding "Dose Era

### ISSUE THREAD

**Issue by chris2nd** [OHDSI/Atlas#2130]
### Expected behavior
By adding 'Dose Era' during designing Characterization, configuration component should be shown properly. 

### Actual behavior
page redirect to intro page

### Steps to reproduce behavior

<img width="1680" alt="Screen Shot 2020-02-14 at 6 21 08 PM" src="https://user-images.githubusercontent.com/8778015/74518233-c8a10900-4f56-11ea-9f00-82d9987901cc.png">
click "Dose Era" inside Characterization.

**Comment by anthonysena** [comment]
This should be fixed in v2.7.7 via #2145. @olga-ganina can your team confirm?

**Comment by olga-ganina** [comment]
Hi @anthonysena , yes it was covered by that PR, can we close ticket?

**Comment by anthonysena** [comment]
Perfect - thanks!
