### ISSUE TITLE
unclear how to save a new incidence rate analysis

### ISSUE THREAD

**Issue by micahstubbs** [OHDSI/Atlas#2133]
### Expected behavior

As a new user, the necessary actions to save an incidence rate analysis are clear to me.

This could be accomplished in a few incremental ways, taking the current UI as a starting point.

- Always show the green save button, including before a new incidence rate analysis name is entered.  If the name input is unchanged when the user clicks the green save button, then prompt the user to name their analysis in a dialog box or by highlighting the name input field.
- Show help text below the name input field, either immediately or after other fields are modified

### Actual behavior

No save button is shown until the default `New Incidence Rate Analysis` name placeholder text is modified.

![Screen Shot 2020-02-17 at 8 42 51 PM](https://user-images.githubusercontent.com/2119400/74704712-4454bd00-51c6-11ea-83c9-6f47b3e0ce7f.png)

### Steps to reproduce behavior

- click `Incidence rates` on the left sidebar
- select a target cohort
- select an outcome cohort
- try to save the Incidence Rate Analysis

**Comment by anthonysena** [comment]
Agreed @micahstubbs - the experience in the incidence rate section is inconsistent with the other save experiences in ATLAS at the moment. We need to unify this so that they work like the others. @olga-ganina can you team help on this one?
