### ISSUE TITLE
Typo on Export Page:  defintion --> definition

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#2135]
Go to Export tab on this example cohort:
http://atlas-demo.ohdsi.org/#/cohortdefinition/1773498

In "Date Offset Exist Criteria" the word definition is misspelled.
![image](https://user-images.githubusercontent.com/6305439/75070858-2044f480-54c2-11ea-8bca-6d8fa903ac52.png)

**Comment by chrisknoll** [comment]
Will be addressed when we implement server-side expression rendering.
