### ISSUE TITLE
Windows Authentication Fail

### ISSUE THREAD

**Issue by aandryc** [OHDSI/Atlas#2139]
### Expected behavior
With security enabled an individual should be able to click 'Sign In', select 'Windows' and be authenticated.

### Actual behavior
If a user has reset their windows password and has not closed their browser (Chrome) prior to attempting to authenticate, the user will receive a 'Login Failed' message.  When user closes browser (Chrome), reopens ATLAS, selects 'Sign-In' and then 'Windows', authentication processes and login works.  User should have a more clear error message (i.e. session time out, etc.)

### Steps to reproduce behavior

1. Open Chrome browser
2. Change windows password
3. Navigate to a security enabled version of ATLAS
4. Click Sign-in (login should fail)
5. Close Chrome browser entirely.
6. Reopen Chrome browser
7. Navigate to security enabled version of ATLAS
8. Click Sign-In and Windows (login succeeds)

**Comment by ssuvorov-fls** [comment]
@aandryc 
Hello
What version of windows do you use?
I tried to reproduce this error on windows 10 and login worked correctly

**Comment by olga-ganina** [comment]
Hi @anthonysena , could you please advice how to proceed with this issue

**Comment by anthonysena** [comment]
@aandryc - we're going to move this to 3.0 for now since we're having trouble reproducing this specific problem. For 3.0, we need to consider a path where a login fails and the user can see the details of why it failed.

**Comment by chrisknoll** [comment]
Let's close for now and if this continues to be an issue, we can reopen.
