### ISSUE TITLE
Estimation - exclude covariates SQL

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#214]
When selecting a concept set in either of the "What concepts do you want to exclude from baseline covariates", the resulting SQL is only the list of concepts that comprise the concept set; the "select" portion of the SQL is missing.

**Comment by anthonysena** [comment]
@alondhe can you point me to the specific estimation item that is exhibiting this problem? I took a look at a few internally and didn't see any issues with the SQL being rendered.

**Comment by anthonysena** [comment]
Ajit, I believe that this issue is the same problem as detailed in issue #263. I'm going to close this out since it is a duplicate and work to get that fixed soon. Thanks!
