### ISSUE TITLE
Use of visit hierarchy in event attributes

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#2140]
### Expected behavior
Allow the import of a concept set to define visits in an event attribute. 

### Actual behavior
If I choose a condition as my initial event, if I want to then filter down to conditions during an inpatient visit I have to choose from a list. Instead I should be able to upload a concept set.

![image](https://user-images.githubusercontent.com/12911960/75810235-38d1cc00-5d58-11ea-9dbd-c8e1e7560eca.png)

This will become more of an issue now that there is a large visit domain organized in a hierarchical structure. I don't want to have to remember all the concepts that roll up to an inpatient visit, etc.

**Comment by anthonysena** [comment]
@clairblacketer - this is a good point and is also covered by #2161. I'm going to close this issue and note the needs around the visit concept as part of that issue so we can track this work together. Let me know if you have any concerns. Thanks!
