### ISSUE TITLE
Cohort -> Cohort Entry Events -> Restrict initial events -> Add Dose Era redirects to home page

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Atlas#2142]
### Expected behavior
Dose Era settings are available to configure

### Actual behavior
Page is redirected on homepage

### Steps to reproduce behavior
1. Create new cohort
2. Set Cohort Entry Events
3. Press Restrict initial events
4. Select Add Dose Era

**Comment by YorgosA** [comment]
Issue also exists in: Cohort -> Cohort Entry Events ->  New Inclusion Criteria

**Comment by konstjar** [comment]
Closing as duplicate for https://github.com/OHDSI/Atlas/issues/2143
