### ISSUE TITLE
Concept Set Export Display Suggestion

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#2154]
Minor suggestion, reorder the export display to be:
1) Concept Identifer List
2) Included Concept Identifer List
3) Concept Set Expression JSON

This way all copy buttons would be visible without scrolling.  I use the "Concept identifier list" a lot, but I always have to scroll through the JSON.

Also, identifier is spelled wrong in both uses.

![bitmoji](https://render.bitstrips.com/v2/cpanel/01ab4994-1ffb-4752-a42c-8bc4f1f67b19-57e33e42-97a5-4431-9f6b-41da527dbc87-v1.png?transparent=1&palette=1&width=246)

**Comment by anthonysena** [comment]
Thanks @ericaVoss - we had this on our to-do list for 2.8 but like your suggestion here so closing out the other issue. Thanks!
