### ISSUE TITLE
Observation Period Results Might Not Be Correct

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Atlas#216]
On the 1K sample, I looked for patients with an observation period >= 730 days and there were 0 patients returned. When I ran this query on the database:

SELECT 
   COUNT( distinct person.person_id) AS num_persons
FROM 
   observation_period
JOIN
   person ON observation_period.person_id=person.person_id
WHERE
   observation_period_end_date - observation_period_start_date >= 730

I got 867 patients. Maybe I defined the cohort incorrectly. You can take a look at it here: http://www.ohdsi.org/web/atlas/#/cohortdefinition/3260

**Comment by anthonysena** [comment]
Hi, I just generated this cohort and now see the 867 people. I'm not sure if perhaps this was an environment issue or not but I'm going to close this for now. If you see this again, please do re-open this issue. Thanks!
