### ISSUE TITLE
Hierarchy should be working for Classification concepts

### ISSUE THREAD

**Issue by Alexdavv** [OHDSI/Atlas#2162]
### Expected behavior
The same as for Standard concept  - show hierarchy.

### Actual behavior
![image](https://user-images.githubusercontent.com/32357692/77843247-f3ac8880-71a3-11ea-8e32-c55d27d16040.png)
![image](https://user-images.githubusercontent.com/32357692/77843250-fad39680-71a3-11ea-9266-6ce04671b42c.png)

### Steps to reproduce behavior

Search - Import - use any concept_id of Classification concept - Inmort concept identifiers - Click on concept name - click on Hierarchy

**Comment by anthonysena** [comment]
@fdefalco any reason why we hide the hierarchy for classification concepts? I'm thinking that it could be due to size considerations (a classification concept may have many descendants) but just wanted to get your input here.

**Comment by fdefalco** [comment]
Not sure, looks like it was introduced here:

https://github.com/OHDSI/Atlas/pull/857/files
