### ISSUE TITLE
Characterization export enhancement

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#2163]
### Expected behavior
Be able to click a button and get complete report exported into a single bundle with multiple files named after respective features

### Actual behavior
Have to click export for each feature separately. Then it spits out a file that is named data.csv. then someone needs to go through all these files, rename them and bundle together. Too time consuming

**Comment by anthonysena** [comment]
Hey @gklebanov - this has been addressed in 2.8 via #1513 so I'm going to close this out.
