### ISSUE TITLE
Restrict cohort name length for PLP package creation

### ISSUE THREAD

**Issue by jreps** [OHDSI/Atlas#2164]
### Expected behavior
There is a limit for the length of the sql file names when they are inserted into the R package library.  If the names from the package are too long they don't get inserted and this causes the package to fail.

### Actual behavior
No limit to cohort name 

### Steps to reproduce behavior
create a cohort with a long name and create the PLP package

**Comment by anthonysena** [comment]
@jreps - I believe the character limit is 160, correct?

I'm wondering if this is something we should enforce via ATLAS as a "warning" to suggest that a person should shorten the name or if we should attempt to handle in Hydra? If the restriction lies on the R side of it, perhaps it is better handled when hydrating the package? I'm unsure.

**Comment by wivern** [comment]
@anthonysena I guess restriction is related to file system max length of filenames limit (255 characters for NTFS and EXT4).
But currently there's rule that limits maximum length of cohort name to 100 characters.
Maybe we can handle this during hydrating as you suggested, to prevent fail of legacy cohorts.

**Comment by anthonysena** [comment]
Closing this as we've address this functional requirement via #2182.
