### ISSUE TITLE
Design listings with security enabled

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#2167]
### Expected behavior

When navigating a list of design elements (e.g. cohort definitions), I would like to know which designs are created by me or shared with me. 

### Actual behavior

The list of designs is shown and there is a filter to find designs based on the author:

![image](https://user-images.githubusercontent.com/12902366/77965607-5d658900-72af-11ea-9012-42613953a27a.png)

However, a design could be shared with me via the lock icon: 
![image](https://user-images.githubusercontent.com/12902366/77965638-6eae9580-72af-11ea-821d-dccf090df82b.png) and it is unclear how to find those designs.

Additionally, the concept set listing differs from the other design lists in that it has no filters.

### Proposed idea for a solution

In the display for the design elements, provide a tabbed/pilled view that shows 

- My designs: those I've authored or have been shared with me. This is only displayed when security is enabled.
- All designs in the system (as is done today)

**Comment by anton-abushkevich** [comment]
Permission check failed with NPE on legacy data. Reopening. Need to add null pointer check in PermissionService.java:210.
