### ISSUE TITLE
Notifications area with security enabled

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#2168]
### Expected behavior

I can see notifications for my own jobs and throughout the system.

### Actual behavior

When security is disabled, the default behavior of the notifications area shows all completed jobs in the system which is useful for seeing what is running across the system. When security is enabled, this display defaults to showing the user's jobs only.

### Ideas to enhance this

Having a tabbed display that shows "my notifications" and "system notifications" so that we can view both when security is enabled. Additionally the "bell" icon should only activate when a person's jobs have finished versus any job in the system.

**Comment by ssuvorov-fls** [comment]
@anthonysena 
Hello. Is it right to show jobs of other users?

**Comment by anthonysena** [comment]
@ssuvorov-fls - that's correct. The idea here is the notifications area would have a place to show "my jobs" and "all jobs". All jobs would show all jobs in the system (as is done today with security disabled). The thinking here is that by having a way to check the status of all jobs with security enabled, it would fix the issues we observed whereby if a cohort is generated by 1 user, the other user's UI does not update. Please let me know if this is unclear. Thanks!

**Comment by anton-abushkevich** [comment]
@anthonysena Please clarify:
"My jobs" tab - shows only current user jobs. The "bell" icon activates only on these jobs` status changes.
"All jobs" tab - shows all jobs, **including current user jobs**.
Is this correct?

**Comment by anthonysena** [comment]
@anton-abushkevich - that's correct. Thanks!

**Comment by ssuvorov-fls** [comment]
@anton-abushkevich fixed
