### ISSUE TITLE
Copying the existing cohort definition to other Atlas site

### ISSUE THREAD

**Issue by rwpark99** [OHDSI/Atlas#217]
We've just set up an Atlas site on our AUSOM DB.
I would to know how I can copy some of the existing cohort definitions in the OHDSI's Atlas site into our own Atlas site.
After importing some of the existing useful one and modifying it into my own research will greatly facilitate the productivity of research.

**Comment by jhardin29** [comment]
To copy an existing cohort from OHDSI's ATLAS page, click the Cohort button on the left menu , and select the cohort you would like to copy. Within the cohort of interest select the Export tab, click the JSON button, click in the box, click the Ctrl + A keys simultaneously, and then Ctrl + C keys simultaneously. You've now copied the directions on how to create the cohort. To create your local copy of the cohort, navigate to your local ATLAS site, click the Cohort button on the left menu, click create the New Cohort blue button in the upper right hand corner of the page. Click the Export tab, click the JSON button, click in the box, remove all of the text in the box by selecting and hitting the Delete key, and then click the Ctrl + V keys simultaneously. You've now just created your new cohort and should see the cohort definitions, concept sets, etc within the new cohort. Don't forget to name your new cohort and click the blue Save button just outside the cohort name box. Good luck!

**Comment by rwpark99** [comment]
Wow!! this is great!
I found it requires clicking the Reload button after click Ctrl + V keys..
Thank you very much!

**Comment by anthonysena** [comment]
Thanks @jhardin29 for answering this question. Noting it for the #147 user guide in case we don't already have this information in there.
