### ISSUE TITLE
installation error (MethodEvaluation, CohortMethod)

### ISSUE THREAD

**Issue by novaraon** [OHDSI/Atlas#2178]
I set up the R environment on windows and tried to install packages but i got error on "MethodEvaluation" and "CohortMethod". They both show same error message.

* installing *source* package 'MethodEvaluation' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'Cyclops' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'MethodEvaluation'
* removing 'C:/R/R-3.6.2/library/MethodEvaluation'
Error: Failed to install 'MethodEvaluation' from GitHub:
  (converted from warning) installation of package ‘C:/Users/cdm/AppData/Local/Temp/Rtmp8oOPqq/file1f819b2337a/MethodEvaluation_1.1.0.tar.gz’ had non-zero exit status

How I can install the packages?

**Comment by anthonysena** [comment]
Hi - this may be related to this issue: https://forums.ohdsi.org/t/package-cyclops-was-removed-from-the-cran-repository/10440. It may be worth trying to install Cyclops via `devtools::install_github("OHDSI\Cyclops")` and then attempting to install the other packages above. I can also move this issue over to the relevant Methods Libraries repository for further help if needed.

**Comment by chrisknoll** [comment]
Closing this as not related to WebAPI, but @anthonysena provides good guidance to get more information, and you can report issues specifically with CohortMethod at https://github.com/OHDSI/CohortMethod.
