### ISSUE TITLE
Restrict use of characters not part of windows/linux file names

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#2182]
### Expected behavior
Dont accept atlas names (cohort, concept set) that has '/' in it.

### Actual behavior
Allows names

### Steps to reproduce behavior
create a cohort definition and give it a name with '/'

### why is this important
we are increasing the use of tools like ROhdsiWebApi to pull definition names to local. If a name has '/' in it, it will throw an error because Windows cannot create file names with '/' in it.

This is a known issue and right now we are just being careful. it would be nice to not allow characters that are not accepted by windows.

**Comment by anthonysena** [comment]
Linking this to OHDSI/WebAPI#1510 since these both touch on ways that we want to format/restrict the name of assets in the system. Additionally, I believe there is a length limit for file names when exported that should be considered here.

**Comment by gowthamrao** [comment]
In addition - recommend creating a max length to the file name.
- we commonly create files that use the names of the cohort. e.g. fileName.json or fileName.sql . 
- These names should not only be valid windows/linux file names, but should also be not more than a certain reasonable file length, as defined by number of characters. 
- I dont know what the max number of characters should be - but it should allow for adding '.json' and '.sql' to the end + maybe five characters for adding any prefix/suffix to the webApi file name.
