### ISSUE TITLE
Ability to add/exclude patient using their ids in a cohort definition

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/Atlas#2184]
Hello Everyone,

Currently we know that ATLAS allow us to identify a cohort of patients based on a set of inclusion and exclusion criteria. This finally results in a cohort table with a subject_ids and their cohort start and end dates.

But my question/usecase is a bit different. For ex, I already have a list of patient ids with me and now I would like to create a cohort with JUST these patient ids. Meaning I only have patient ids and I don't have/wish to use features/variables from other domains to create this cohort. **For background on why I was looking for this approach, refer the background section below**

Ex: let's say I have a patient id txt file list which only contains 3 subjects 21,22,23.

Now in ATLAS, I would like to create a cohort which will include these 3 subjects which are 21,22 and 23 (and exclude all other subjects).

I was trying with observation_period criteria (thinking that's the most close I can get to what I want) but unfortunately there is no way to exclude patients based on their ids. I understand that we do have options to exclude based on other columns/variables but not based on person_id/subject_ids.

Like discussed above, using feature/column names may not be reliable for me to add/exclude patients for my usecase. So I am looking for a way to know whether we can add/exclude patients in ATLAS based on just patient ids only 

Can I kindly check with you on whether this is possible in ATLAS?

**BACKGROUND**

OHDSI has R packages like APHRODITE and PheValuator for electronic phenotype model creation and validation. APHRODITE outputs a set of subjects as cases and controls based on a keyword/Anchor terms list. So by using APHRODITE, I got a list of subject_ids as cases and controls. Now to validate this phenotype model (probabilistic phenotype) produced by APHRODITE, I would like to use PheValuator. But PheValuator requires validation cohort (APHRODITE output) to be present in ATLAS. Hence I would like to create a cohort in ATLAS with subject_ids returned by APHRODITE which can help me validate using PheValuator. If not possible in ATLAS, only option is create entries in the `results.cohort` table based on my requirement and use it in PheValuator as they all look at db anyway?

**Comment by anthonysena** [comment]
Hi @SSMK-wq - at this time, you cannot construct a cohort in ATLAS using only the person_id's. 

If I'm reading this right, it sounds like the challenge you face may be with the fact that PheValuator assumes that your cohort exists in the WebAPI's cohort table. Do I have that right? If so, I'd suggest that we move this over to the PheValuator code repository to see about making the cohort table configuration in the SQL flexible like the other packages.

**Comment by anthonysena** [comment]
Closing this since it is not possible to exclude based on a subject_id nor would we want to provide this type of capability in ATLAS. Such an exclusion should happen in code that is directly working with the cohort table instead.
