### ISSUE TITLE
RE: In Atlas, the Text View for cohort definitions (Export tab) does not include source codes below "an observation of any observation"

### ISSUE THREAD

**Issue by conovermitch** [OHDSI/Atlas#2186]
### Expected behavior
In the atlas-covid19.ohdsi.org instance, I have created an example cohort (ID=572) to demonstrate this problem: http://atlas-covid19.ohdsi.org/#/cohortdefinition/572

_As specified in the definition tab:_ 
an observation of "Any Observation"
   Observation Source Concept is: "Random source codes"

However,  the Text View will fail to include the bullet that states "Observation Source Concept is:" 

### Actual behavior
_As it appears in the Text View (export Tab):_ 
an observation of Any Observation
with continuous observation of at least 0 days prior and 0 days after event index date, and limit 

### Steps to reproduce behavior
This behavior will happen any time an observation is specified using source codes.  When specifying source concepts for a condition occurrence, the correct bullet will appear in Text View

**Comment by chrisknoll** [comment]
Fixed in OHDSI/WebAPI#1655.
