### ISSUE TITLE
"New Concept Set" button doesn't work in Concept sets comparison tab modal window

### ISSUE THREAD

**Issue by anton-abushkevich** [OHDSI/Atlas#2187]
### Expected behavior
transition to new concept set page
### Actual behavior
doesn't work / exception in console log
### Steps to reproduce behavior
Go to "Concept Sets" -> choose any -> go to Compare tab -> click on "open" button -> click on "New Concept Set"

console log
```
CohortConceptSetBrowser.js:107 Uncaught TypeError: self.onActionComplete is not a function
    at CohortConceptSetBrowser.self.addConceptSet (CohortConceptSetBrowser.js:107)
    at HTMLDivElement.<anonymous> (knockout-latest.js:90)
    at HTMLDivElement.dispatch (jquery.js:5226)
    at HTMLDivElement.elemData.handle (jquery.js:4878)
```

**Comment by anthonysena** [comment]
Let's hide the "New Concept Set" button in this display when selecting a concept set instead:

![image](https://user-images.githubusercontent.com/12902366/79874745-b90aca00-83b6-11ea-97f2-36f237c34cc6.png)
