### ISSUE TITLE
Characterization: Remove the ability to change a design if you lack permissions

### ISSUE THREAD

**Issue by olga-ganina** [OHDSI/Atlas#2192]
Parent task #2174 

### Expected behavior
If a given entity is locked since I do not have rights, I should not be able to make changes that would require a save action.

### Actual behavior
Characterization: the cohort definitions, feature analyses lists contain "Remove" links. The buttons to Add/Import things into the design should be disabled.

**Comment by wivern** [comment]
`linked-entity-list` and `linked-cohort-list` used not only on the characterization edit page.
But there are neither passed `isEditPermitted` value for e.g. pathways nor provided a default value.
