### ISSUE TITLE
Estimation/Prediction: Remove the ability to change a design if you lack permissions

### ISSUE THREAD

**Issue by olga-ganina** [OHDSI/Atlas#2195]
Parent task #2174 

### Expected behavior
If a given entity is locked since I do not have rights, I should not be able to make changes that would require a save action.

### Actual behavior
Estimation/Prediction: The specification should prevent removal/copy. Drilling into details should produce a read-only form.

**Comment by aklochkova** [comment]
@anthonysena why 'copy' action should be forbidden?

**Comment by aklochkova** [comment]
@anthonysena could you please review my previous comment about the `copy` button?

**Comment by anthonysena** [comment]
Hi - sorry for the delay. Here is what I mean:

![image](https://user-images.githubusercontent.com/12902366/88052642-89d83600-cb28-11ea-991a-fc58325c4ea6.png)

The red "X" used to remove a comparison and the "Copy" button on each row should be disabled. Additionally, buttons like the "Add Comparison" should be disabled.

You will find a similar display in Prediction that should be handled the same way. Thanks!
