### ISSUE TITLE
Cartoon bug:  no brackets shown if no prior/post observation time is specified in initial events

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#220]
It should show a bracket that spans the whole time window, I would think?

here's the cohort definition:

![image](https://cloud.githubusercontent.com/assets/731930/18413653/ecd35bea-777b-11e6-94e2-da533eac4a68.png)

and here's the resulting cartoon:

![image](https://cloud.githubusercontent.com/assets/731930/18413656/fe22ca98-777b-11e6-8ee9-bbebc36c01d2.png)

**Comment by Sigfried** [comment]
There's no obs period, but there are also no specified durations or specific numbers of days before/after index date. So there's no information to base an x axis domain on. I'm not sure what to do in this case. We should talk about it.

**Comment by pbr6cornell** [comment]
I would making the figure have some minimum time before and after the index date always shown (180d on both sides?)   That way, you'll always get some logical view, even if no specific times were specified, but it can be expanded in cases when someone does put in something >180d.

**Comment by fdefalco** [comment]
The cartoon is currently showing brackets from -1 to 1 as a default range when no other range is specified.
