### ISSUE TITLE
Add "messages" to cohort pathways

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#2203]
### Expected behavior
User is warned if implements "stupid" design of cohort pathway

E.g., target cohort has only 1 day span (no room for events to occur)
(I made that error and took me a long time to figure out why I see no results)

### Actual behavior

Current cohort Patways has no "messages' tab

(like cohort definition has)
![image](https://user-images.githubusercontent.com/7526119/80832868-723d8100-8bbb-11ea-91bb-95a9f644c6b2.png)

### Steps to reproduce behavior

create stupid cohort exit criteria for pathway target cohort and see no results.

**Comment by chrisknoll** [comment]
Messages tab was added in 2.8.  Although, interrogating cohort definitions used in the analysis may be beyond scope of the messages tab: we warn that no event cohorts are specified, but we don't go as far as digging into cohort definitions looking for logical errors.
