### ISSUE TITLE
Add description field to ConceptSet

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#2204]
### Expected behavior
I can describe concept set

### Actual behavior
no place to say who created it (if on covid server), put references, write notes (like for cohorts)

### Steps to reproduce behavior
n/a

**Comment by gklebanov** [comment]
Yes, agreed. I would broaden this request because I think we need to be very consistent across all artifacts
- author
- created data
- modified date
- modified by
- title
- description

also, these attributes should be displayed on a main screen as well.

**Comment by anthonysena** [comment]
Closing as it is a duplicate of #1823
