### ISSUE TITLE
Inconsistent artifact link behaviour

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#2205]
### Expected behavior
resources behave in well consistent way

### Actual behavior
Cohorts used in pathway and characterizations are dynamic links  (import-as-linked)
But concept sets are imported as copy (import-as-copy)

### Steps to reproduce behavior
n/a

**Comment by anthonysena** [comment]
This is an old issue and I presume this is referring to the fact that cohort definitions retain a copy of a concept set vs using a reference to a concept set.

**Comment by vojtechhuser** [comment]
sena, your summary is correct

**Comment by chrisknoll** [comment]
This is a design choice:   we use cohort definitions in different contexts (ir, characterizations) and so we want a change in the cohort definitions to be reflected across those.  Concept sets, on the other hand, is something that we want to 'freeze' when imported into a cohort definition.
