### ISSUE TITLE
Highlight the function you are in on the lefthand menu?

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#221]
It could be useful if whenever you enter some function in ATLAS by clicking on the lefthand side menu that that menuitem was highlighted in some way (either the row in that table got a different background color, or maybe the icon got a different color), so that way you'd know where you are in the tool.  Sometimes when jumping between parts, like vocab/cohorts/conceptsets, the screens look sufficiently similar so it can be a bit confusing.

**Comment by fdefalco** [comment]
I'm open to thinking about this.  There is a function specific header at the top of each page that you are on that provides this context but highlighting the menu could provide another hint of where you are.  The header does get lost of the UI for the page is overly complex and requires that you scroll down.  I've considered fixing that title bar at the top so it is persistent even when you scroll, that is another option to improve awareness of where you are working.
