### ISSUE TITLE
Heracles progress field is always empty

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2211]
### Expected behavior
To see some % of progress 

### Actual behavior
Progress is always empty
![image](https://user-images.githubusercontent.com/56290675/82330036-f4ff7200-99ea-11ea-86d6-fabf9fdeb6a5.png)

### Steps to reproduce behavior
1)Generate cohort
2)Run full analysis

**Comment by anton-abushkevich** [comment]
Progress field removed, added start date and duration fields
