### ISSUE TITLE
Problem when changing concept set in custom features

### ISSUE THREAD

**Issue by AniekMarkus** [OHDSI/Atlas#2212]
### Expected behavior
When changing to a different concept set after the first initialization of a custom feature, I expect that the new concept set is used when I run my characterisation study with this feature. 

### Actual behavior
It seems like the the old concept is used, even after removing the feature from the characterization and importing again. For me, only creating an entire new feature seemed to work.

### Steps to reproduce behavior
Create a custom feature with concept set A, save it, change to concept set B, in characterisation study I get results for concept set A.

**Comment by AniekMarkus** [comment]
@anthonysena

**Comment by anthonysena** [comment]
Thanks @AniekMarkus for reporting this issue. This seems similar to #1595 so linking these issues and hoping that resolving #1595 also resolves this issue. I'll leave them linked so we can make sure of it when testing.

**Comment by chrisknoll** [comment]
I'd like to request if @AniekMarkus can pull the master branch of Atlas and WebAPI in a test env to verify this fix...I think we can assume this issue is fixed due to the rewrite of handling embedded concept sets.

**Comment by anthonysena** [comment]
Let me circle back with @AniekMarkus as we're having some offline discussions around treatment pathways (unrelated to this) and we can see how to best get this tested. Thanks!

**Comment by anthonysena** [comment]
Closing since it was fixed via #2132.
