### ISSUE TITLE
Configuration page selections not honored

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#2213]
### Expected behavior

Changing the priority for a source (using the radio buttons) to use it's vocabulary, record counts or evidence daimons is persisted for the user's session with security disabled.

### Actual behavior

User's selections are not captured for the session and revert back to their original settings.

### Steps to reproduce behavior

Assuming you have multiple vocabulary sources configured and security disabled:
- Navigate to the configuration page, select a vocabulary provider that is not the default
- Navigate to the search page, then back to the configuration
- Expected: the selection persists. Actual behavior: the defaults are still used.

**Comment by YaroslavTir** [comment]
was fixed by https://github.com/OHDSI/Atlas/pull/2098
