### ISSUE TITLE
New concepts for COVID-19

### ISSUE THREAD

**Issue by ZhengchunD** [OHDSI/Atlas#2217]
We just setup v6 Vocabulary in oracle database. Now we need to bring COVID-19 data to our OMOP oracle database. So we have to set up new COVID-19 concepts. Need to get the data and loaded to database. 

Vojtech Huser <noreply@ohdsi.org> suggest this Link:
http://atlas-covid19.ohdsi.org/#/conceptset/190/included-conceptsets

But it does not look like the 53 new concepts is for V6 model. Can You gurus please provide the COVID-19 concepts for omop V6?? 

Thanks and appreciate helps!!!!

**Comment by konstjar** [comment]
@ZhengchunD 
I think you mixed ATLAS and ATHENA repos. Vocabulary related issues should be addressed in ATHENA or Vocabulary-v5.0 repos
