### ISSUE TITLE
Active Directory/LDAP Job settings are not saved properly

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Atlas#2227]
### Expected behavior
"Preserve existing role" checkbox should be saved correctly

### Actual behavior
The value is sent "true" always independent on checkbox settings

### Steps to reproduce behavior
![image](https://user-images.githubusercontent.com/4144173/83626470-c01c1f00-a595-11ea-9b7e-a4f316211261.png)

**Comment by KSadomtsev** [comment]
![image](https://user-images.githubusercontent.com/56290675/88369093-ee4cfc80-cd97-11ea-9759-17fbd77f22fc.png)
Tested in 2.7.8
