### ISSUE TITLE
Cohort:  re-generating cohort did not bring back 'view inclusion criteria' button

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#223]
![image](https://cloud.githubusercontent.com/assets/731930/18413737/eb66cedc-777f-11e6-8917-1a4c534ff5e9.png)

**Comment by pbr6cornell** [comment]
I think this has to do with adding a 'demographic' criteria.....when I remove the rule of 'age>18', then the 'view' button reappeared.

**Comment by chrisknoll** [comment]
Right, it was a typo in the column. I've pushed a fix.
