### ISSUE TITLE
Ability to pick specialty

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#2233]
### Expected behavior
Specialty is offered in a special search for a concept

### Actual behavior
specialty is not offered
see bottom of screenshot where provider specialty constraint is added to a visit. But choice of subsets does not include specialty

![image](https://user-images.githubusercontent.com/7526119/84224592-f5030700-aaaa-11ea-99b8-e54e77e1f6cf.png)

**Comment by chrisknoll** [comment]
Scroll down further, it's called 'provider specialty'.  I see it in my env:
![image](https://user-images.githubusercontent.com/6818777/93546278-7e3e9b00-f930-11ea-8f1d-cb5f30b5ef52.png)

However, is it possible you have a vocabulary that doesn't include those domains?  We read the set of domains from the vocabulary.
