### ISSUE TITLE
Mac OS browser issue

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/Atlas#224]
Nigam and I have independently verified that when you click on 'Data Sources' using Chrome and Safari on a Mac it briefly flashes the sources page and gets re-directed to the vocabulary page. I have also confirmed that this does not happen on Windows and Chrome. I can provide some sort of video of this happening if needed.

**Comment by anthonysena** [comment]
@jmbanda Atlas 2.0 will have a new experience for the 'data sources' feature. When released, let's see if that addresses this bug.

**Comment by anthonysena** [comment]
Hi @jmbanda - could you confirm if this issue is still happening with Atlas 2.0? http://www.ohdsi.org/web/atlas/#/datasources. Thanks!

**Comment by anthonysena** [comment]
Closing and linking to #423
