### ISSUE TITLE
Copy conceptset button from Cohort definition does not copy new or replace existing when a conceptset of the same name is present.  instead it does nothing and doesnt notify user

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#2242]
### Expected behavior

If a user attempts to copy conceptset into repository by clicking the bottom in bottom right: 

![image](https://user-images.githubusercontent.com/731930/86519285-42069e80-be07-11ea-8f2e-269ec937fa9b.png)

If the conceptset name already appears in the conceptset repository, then I think user should be prompted that name already exists and asked to rename or cancel.

### Actual behavior

Clicking button provide no indication that nothing is happening.  But conceptset is neither created nor replaced.

### Steps to reproduce behavior

Create conceptset in conceptset repository,  create cohort, create conceptset in cohort with same name, click 'copy to conceptset repository', then go to conceptset repository and review that conceptset.  it hasnt been updated.

**Comment by ekaterinakrivets** [comment]
I have investigated a little, and found, that for now, when clicking on "Copy conceptset" button modal window appears (see attached screenshot) and it notifies, if conceptset is already exists.
![image](https://user-images.githubusercontent.com/69469730/91212002-9fb7b880-e6dd-11ea-9244-350ea087c1bb.png)

**Comment by chrisknoll** [comment]
This functionality will be touched in the PR for the new concept set editor:  #2297 which will amend the actual PR for the new concept set editor #2132.  When the main PR gets amended (which should be in the next days I hope) we can check this issue against that PR.

**Comment by KSadomtsev** [comment]
now it works
![image](https://user-images.githubusercontent.com/56290675/99949820-b2996200-2d8c-11eb-82dc-0c96ce21f73f.png)
