### ISSUE TITLE
Is concept_hierarchy table mandatory

### ISSUE THREAD

**Issue by shrikantkunte** [OHDSI/Atlas#2253]
- I am trying to setup Atlas for my OMOP CDM database.
- The script for results schema setup is running for almost a week.
- URL  I used to get the script - 
```
http://<server:port>/WebAPI/ddl/results?dialect=<your_cdm_database_dialect>&schema=<your_results_schema>&vocabSchema=<your_vocab_schema>&tempSchema=<your_temp_schema>&initConceptHierarchy=true
```
- After some analysis I found that creation of concept_hierarchy is the reason for script taking too much time to complete the run.
- What will be the effect on functionality of Atals if I remove concept_hierarchy part by setting initConceptHierarchy  = false?

**Comment by chrisknoll** [comment]
It is used to render the domain-level reports under Data Sources (which renders the results from Achilles).

If you don't plan on browsing those results in Atlas, then you can safely omit that table from being created.
