### ISSUE TITLE
Possible UI/UX enhancements

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Atlas#227]
- **datasources name change**: The _data sources_ name is potentially misleading to some users.  While _configuration_ is where some session-scope settings pertaining to data source/daimons (e.g. vocabulary, evidence) may are set, some users expect a page associated with a  view element entitled "Data Sources" where you can select a data source but the setting only applies to the current tab.
- **datasources navigation** The pull down for navigating data sources can be a difficult UI element for users to discover as it navigation element that is located somewhat out of the way in the upper right hand corner.
- **concept set creation & management** The workflow for global concept sets is confusing to some users. The concept set name in the title bar does provide some needed context, but it remains difficult to intuit the application navigation model. The workflow for cohort-level concept sets is also confusing to some users.  Once a user click _add_ next to an expression for one of the filters, the app takes them to a popup that allows them to create a cohort-level concept set...that leads you to what feels like an UI dead end to some users.  It is not intuitive that they need to populate this concept set in concept workflow and then resume the creation of the expression.

**Comment by chrisknoll** [comment]
I agree, the concept set creation and management is becoming a more serious problem now that we have multiple sources of concept sets:  Cohort definitions, incidence rate projects, estimations, and of course stand-alone concept sets.  I believe most of this dependency stems from the global nature of the app-level fields that store the 'selected concepts' and this prevents us from having multiple concept-sets open for editing at a time.  On the note of Add, we should only be showing concept sets that are in the repository here, we shouldn't give them the choice of choosing the concept set form the cohort becaues that's already in the dropdown to the left of the Add button (if I am speaking about the same Add button you are).

**Comment by t-abdul-basser** [comment]
Good points. After the symposium we plan to take a deeper look at these and related UI/UX issues.
