### ISSUE TITLE
Concept Sets: Clicking checkbox in header clears out all checks in columns without all boxes checked

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/Atlas#2272]
### Expected behavior
When I check the checkbox in the header for Descendants, Mapped, or Exclude, it should not affect which boxes are checked in the other columns.

### Actual behavior
If a column has only some of its checkboxes checked and I then check or uncheck the header checkbox in another column, all of the boxes in that other column will be unchecked.  Note that columns with all of their checkboxes checked are _not_ affected by this issue.

### Steps to reproduce behavior
See attached video

[Screen Recording 2020-08-06 at 9.19.11 AM.zip](https://github.com/OHDSI/Atlas/files/5035032/Screen.Recording.2020-08-06.at.9.19.11.AM.zip)

**Comment by chrisknoll** [comment]
Hi, thank you for your help on this, but with the changes to the concept set editor, I think this is out of date. But, I have made the changes to fix this relative to the new concept set editor, and so we can close this out.
