### ISSUE TITLE
Atlas does't work on localhost

### ISSUE THREAD

**Issue by sunyan-SG** [OHDSI/Atlas#2283]
### Expected behavior
**I expect Atlas to be properly run on http://localhost:9090/atlas (my localhost is 9090 as 8080 has been used by other application)**

### Actual behavior
**I have passed the WebAPI test on: http://localhost:9090/WebAPI/source/sources
Here is the output:**

[{"sourceId":1,"sourceName":"My Cdm","sourceDialect":"postgresql","sourceKey":"MY_CDM","daimons":[{"sourceDaimonId":1,"daimonType":"CDM","tableQualifier":"cdm","priority":0},{"sourceDaimonId":2,"daimonType":"Vocabulary","tableQualifier":"vocab","priority":1},{"sourceDaimonId":3,"daimonType":"Results","tableQualifier":"results","priority":1},{"sourceDaimonId":4,"daimonType":"Temp","tableQualifier":"temp","priority":0}]}]

**But when I try to logon http://localhost:9090/atlas , I got the following error:**

HTTP Status 404 – Not Found
Type Status Report
Message The requested resource [/atlas] is not available
Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
Apache Tomcat/9.0.37

**Can pls advise how to fix the issue? Thank you.** 

### Steps to reproduce behavior
**My js/config-local.js is as follows:**

define([], function () {
	var configLocal = {};

	configLocal.api = {
		name: 'Local NHG',
		url: 'http://localhost:9090/WebAPI/'
	};

	return configLocal;
});

**Comment by anthonysena** [comment]
Hi - could you attempt to run ATLAS on a different port for local host? Since WebAPI is using port 9090, it may be easier to run ATLAS on 9091 (as an example).
