### ISSUE TITLE
Role "admin" cannot edit any Feature Analysis

### ISSUE THREAD

**Issue by anton-abushkevich** [OHDSI/Atlas#2288]
### Expected behavior
"Admin" role can edit any Feature Analysis.

### Actual behavior
User with "admin" role can only edit Feature Analyses created by himself.

### Steps to reproduce behavior
Login as admin and open any Feature Analysis created by another user. 

### Commentary
There is no `*:put` permission for Feature Analyses (`feature-analysis:*:put`) while any other entity has it: `conceptset:*:put`, `ir:*:put` etc.

**Comment by anthonysena** [comment]
Adding back to 2.8 since this is a bug that needs to be addressed.

**Comment by olga-ganina** [comment]
Hi @anthonysena , just to confirm that the Expected behavior is correct here and we want user with role Admin to be able to edit any Feature Analysis created by another user.

**Comment by anthonysena** [comment]
Closing since security is set to only allow a creator of a design to edit his/her own work.
