### ISSUE TITLE
Message count refreshing after importing

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2315]
ATLAS Version 2.8.0 DEV
WebAPI Version 2.8.0 DEV
### Expected behavior
Message count is refreshed after importing
### Actual behavior
Message count is the same, we still see irrelevant messages
![image](https://user-images.githubusercontent.com/56290675/92892576-8b83f300-f421-11ea-8255-69628db782cb.png)

### Steps to reproduce behavior
1)Try to import any analysis(which is possible)

**Comment by chrisknoll** [comment]
Is it the case that messages only refresh on save, or does it do it for every change to the expression?

**Comment by ssuvorov-fls** [comment]
Message tab refreshes every time when design is changed
