### ISSUE TITLE
Concept filter in patient profiles doesn't work

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#232]
With the ATLAS refresh the filter in the patient profile view no longer works

**Comment by Sigfried** [comment]
I'm not seeing the problem. What filter?

Domain filter and brushing are working for me in both:

http://hix.jnj.com/atlas/#/profiles?N4Igxg9gFhBOAuARApgMwCoEMBGIBcIyAHgA4A2cyIANCAM4QCusYyA0sgJ74joBKAVQBqAUQByAYQkBBEQH0hAFkUBGGuGaxkAO3gTocJGgCW24/GMRtASQAm+AEwBOBwA5aJZLAY37eBwEqAAwAbCFOQQ4AvkA

and 

http://rndusrdhit01:8888/atlas/#/profiles?N4IgDCBcIA4gNCAjFEBTBIBMqBOmBmVAZ0wBZUB7TAVlQDtMA2VASUwHZUATTAY0oALSrgAuAETQAzACoBDAEao0ADxgAbERkTFKAV1x80AaTQBPVAHkACjICqAWQC018QHV+B3GnqiAwkIiEtIAlvQhoiGU9Ky8kEhIYEyIMGi4ujFxBARgBGRMOUxYBAC+QA==

**Comment by Sigfried** [comment]
Sorry, misunderstood. I'll look at that.
