### ISSUE TITLE
Cartoon not rendering, navigation bug

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#233]
For a cohort definition I'm using, clicking on the Cartoon tab results in a blank timeline. The console error I'm seeing is:

**Uncaught TypeError: Cannot read property 'name' of undefined**

Also, when you click off of the export tab, you cannot go back to the export tab

**Comment by Sigfried** [comment]
I see that bug on production, but not on the beta environment, for instance:

[http://rndusrdhit01:8888/atlas/#/cohortdefinition/1106?N4IgDCBcIA4gNCAjFEBTBIBMqBOmBmVAZ0wBZUB7TAVlQDtMA2VASUwHZUATTAY0oALSrgAuAETQAzACoBDAEao0ADxgjRIAL5A=](http://rndusrdhit01:8888/atlas/#/cohortdefinition/1106?N4IgDCBcIA4gNCAjFEBTBIBMqBOmBmVAZ0wBZUB7TAVlQDtMA2VASUwHZUATTAY0oALSrgAuAETQAzACoBDAEao0ADxgjRIAL5A=)

So it should be fixed when more recent code is pushed to production.

**Comment by anthonysena** [comment]
Looks resolved when testing under v2.0.
