### ISSUE TITLE
Can incidence prevalence be incorporated into ATLAS?

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#2335]
### Use Case
Often we are asked to provide in descriptive analyses incidence and prevalence estimates for a given condition for a given time period. It would be very helpful if we could generate these incidence and prevalence and associated 95% CIs for a given time period - yearly over many years or over a set of years for a set of databases. Presently I am using a package @jswerdel wrote that allows annual estimates and is a nice start: bb link here: https://sourcecode.jnj.com/projects/ITX-ASJ/repos/prevalence/browse

### Request 
Can this functionality be included in ATLAS? I can share relevant output if helpful.

**Comment by pbr6cornell** [comment]
consider inclusion of CohortIncidence and IncidencePrevalence packages into Strategus workflow, before incorporating into ATLAS.
