### ISSUE TITLE
Evidence tab missing from Concept Set Editor

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#2339]
### Expected behavior

Concept set editor has an "Evidence" tab when 1 data source is configured with a CEM daimon:

![image](https://user-images.githubusercontent.com/12902366/94451706-b9389e00-017c-11eb-987c-90c76c3dd475.png)

### Actual behavior

Concept set editor is missing the "Evidence" tab:

![image](https://user-images.githubusercontent.com/12902366/94451665-ab831880-017c-11eb-9a5c-d2a6643a9797.png)

### Steps to reproduce behavior

This is using the latest master branch. We could consider putting the "Explorer Evidence" tab at the end of the list of tabs.

**Comment by ssuvorov-fls** [comment]
@anthonysena 
Could you check it again using current master branch?
I can't reproduce it.

**Comment by anthonysena** [comment]
@ssuvorov-fls  you are correct - this is  fixed in the current master branch. Thanks!
