### ISSUE TITLE
Patient Profiles no longer linkable

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#234]
Previously, I could link to specific patient profiles (provided the cohort had been generated) using a URL like this: 
/atlas/#/profiles/database_id/cohort_definition_id/person_id

However, now these links no longer work, probably as the URL conventions have changed. Can this functionality be brought back? We use it to share specific patient profiles with our clinicians, who can then provide cohort definition feedback on a static list of patients.

**Comment by Sigfried** [comment]
You can still send those links, but they are no longer readable in the same way. Navigate to a person profile and copy the link. Let me know if it doesn't work.

**Comment by alondhe** [comment]
Copying the URL after landing on a patient profile does work. I was able to open the same patient in 1 chrome session and in an incognito session. 

However, is there a way to grab 100 patients' profile URLs now, in bulk? The URLs generated are chock full of GUIDs.

**Comment by Sigfried** [comment]
Sorry, I didn't understand, and didn't realize people were using those links that way, so that unintentional feature went away when I fixed another bug with profile-manager not having a copyable link when coming to it without a cohort.

**Comment by alondhe** [comment]
For anyone interested in sharing profile URLs, I've created a little web page utility to help convert the older style profile URLs to the new, GUID-based URLs. I've attached a version of it that uses OHDSI web's Atlas implementation, but that can be altered via the "atlasUrl" object. 

[atlas_url_encoder_ohdsi.zip](https://github.com/OHDSI/Atlas/files/509819/atlas_url_encoder_ohdsi.zip)

**Comment by fdefalco** [comment]
In my opinion we should switch back to the readable URL formats such as:

/atlas/#/profiles/source_key/person_id/cohort_definition_id (person in the context of a cohort)
/atlas/#/profiles/source_key/person_id (person without cohort context)

Or something like that.  I would support using the additional query string properties for storing things like filter state, zoom state, etc, but the readable URL for a profile could be easier to manage.

**Comment by alondhe** [comment]
@Sigfried it looks like the input patient profile URL string that would then get encoded by LZ encoder was something like this:
http://hix.jnj.com/atlas/#/profiles/<data source id>/<cohort definition id>/<person id>

In the past, I was able to successfully encode URLs like this using the LZ library and navigate to the exact profile/data source/cohort id combination. But now it's not working. Did the expected input URL string convention change?

**Comment by jswerdel** [comment]
It would be a useful addition to be able to right click on the subject id link and allow it to be shown in a new tab or at least allow the correct URL for that patient to be copied.  Currently you only get something like this "http://hix.jnj.com/atlas/#/profiles" when you right click and copy the link.  This would allow you to open several patient profiles very quickly in other tabs which is useful for comparisons.
