### ISSUE TITLE
Changing design of Characterization Feature

### ISSUE THREAD

**Issue by denyskaduk** [OHDSI/Atlas#2343]
### Expected behavior
After changing a design of characterization feature, from Criteria to Custom, saving of the feature is working

### Actual behavior
After changing a design of characterization feature, from Criteria to Custom, saving of the feature is NOT working, getting an error message
![image](https://user-images.githubusercontent.com/42732735/94802288-0b352a00-03f0-11eb-9949-d0ce4ea12711.png)

### Steps to reproduce behavior
Create a New Feature -> Pick 'Criteria' as design -> Save Feature -> Change design to 'Custom' -> Try to Save and get an Error

**Comment by KSadomtsev** [comment]
it is related to WebApi, need to check after fixing: https://github.com/OHDSI/WebAPI/issues/1642

**Comment by KSadomtsev** [comment]
OHDSI/WebAPI#1642 fixed
