### ISSUE TITLE
The same concept with the same concept set options should not be duplicated

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2346]
Atlas 2.8

### Expected behavior
It should not be possible to add the same concept's record a few times

### Actual behavior
![image](https://user-images.githubusercontent.com/56290675/95068894-98d58a00-070e-11eb-91bc-2d3602244e08.png)

After saving we get a concept set with only one concept(with parameters from last added)
![image](https://user-images.githubusercontent.com/56290675/95086523-43f33d00-0729-11eb-8bc0-4aa94bb18905.png)

### Steps to reproduce behavior
1)Search-> "aspirin"
2)Open the first concept
3)Click two or more times on the "Add to concept set"
4)Open Concept Sets page

**Comment by chrisknoll** [comment]
Ok, closing this now since the main issue is fixed (that was dropping duplicate concepts) but we can open a new issue if we want to deal with the case when a user makes duplicate selections int he concept set.   This won't hurt anything, but maybe it's less confusing to prevent dupes.
