### ISSUE TITLE
Import/Export specifications

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#235]
For every function, we need to have the ability to import/export specifications from one ATLAS instance to another.  Right now, we’re good on the cohort definition front, and we can do it for conceptsets (though we should move the ‘import’ capability into conceptset), but we don’t have it for incidence rate or estimation projects.

**Comment by jhardin29** [comment]
I exported this cohort : http://hix.jnj.com/atlas/#/cohortdefinition/801?N4Igxg9gFhBOAuARApgMwCoEMBGIBcIyAHgA5zwgC+QA and loaded it to create a new cohort and ATLAS is hanging and not allowing me to save.

**Comment by chrisknoll** [comment]
Hi, Jill,  I just tried to save a simple cohort and also had an error on our internal servers. I'm investigating it now.

**Comment by jhardin29** [comment]
Hi Chris, That cohort is also having issues generating in MDCR as it has been trying to do so for a few minutes. It is a simple test cohort from Rupa. Thank you.

**Comment by chrisknoll** [comment]
Yes, there seems to be some issue with the WebAPI on our hix server. I've tested locally against our beta environment, and there's no error saving.  So i need to now look directly at the production environment to check the logs.

**Comment by chrisknoll** [comment]
Jill, another note:  one thing I did notice is that when the cohort def saved locally, the tabs all became unselected,and I could see the cohort definition again once i selected a tab.

@Sigfried : This is related to the query strings maintaining state of the tab. When we save a new entity (cohort defs, concept sets, etc) we redirect the URL to the new ID of the item.  But this wasn't updated when you added the state to the URL. Can you please review the other areas of the application where saves are happenign and window.location.href is being called, and ensure that you are setting the query string state appropriately.  Thank you.

**Comment by chrisknoll** [comment]
Jill, 
  The updates to the production database were failing due to a DB permission issue. This has been resolved, but you will still see an issue saving a new cohort (raised in issue #237). The work around is, after you save a new cohort and it looks like the app is hung or the screen is blank, just click on one of the tabs at the top, (Definition) and the UI will come back up showing you the cohort definition.

**Comment by chrisknoll** [comment]
Reopening: this issue is about Import/Export functionality, and I close this in error.

**Comment by jhardin29** [comment]
thanks Chris!
