### ISSUE TITLE
Include an internal proxy to make configuring the WebAPI connection easier

### ISSUE THREAD

**Issue by chgl** [OHDSI/Atlas#2356]
### Expected behavior

It could be easier to configure the WebAPI and allow connections to a WebAPI endpoint that is not directly accessible by a user's  browser.

This could be achieved by adding proxy functionality to the application that would simply forward any request to the relative `/WebAPI`  path to the WebAPI server, which in turn would not need to be explicitely exposed. This proxy could be a simple NodeJS Express app using the [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) library. This would also simplify adding observability tooling to ATLAS (ie. [readiness and liveness probes](https://www.cloudnativejs.io/), [metrics](https://github.com/jochen-schweizer/express-prom-bundle), and [tracing](https://github.com/open-telemetry/opentelemetry-js)) to make it easier to run it in a cloud-native environment.

Configuration would then be simplified to:

1. Provide the URL of the WebAPI as a `OHDSI_WEBAPI_URL` environment variable to ATLAS. This URL can refer to an internal service that is not exposed otherwise, ie. a different service inside a Docker compose network, or a ClusterIP service inside Kubernetes as opposed to a NodePort or Ingress.
1. Start ATLAS
1. The ATLAS app defaults to sending all WebAPI requests to the relative `/WebAPI` URL
1. The proxy service forwards all requests to `/WebAPI` to `OHDSI_WEBAPI_URL` and returns the responses

If there's interest in this, I could give it a whirl in a PR.

### Actual behavior

ATLAS is provided as a static application, which makes configuring it difficult. In particular, setting the WebAPI endpoint currently requires overwriting and maintaining a custom config-local.js [[1]](https://github.com/OHDSI/Atlas/wiki/Atlas-Setup-Guide#atlas-configuration) or awkward string replacement operations to configure it via environment variables [[2]](https://github.com/OHDSI/Atlas/blob/a8930ce5a82b1c645497c321b020e034ff61ad67/docker/30-atlas-env-subst.sh#L19). Further, this WebAPI endpoint needs to be accessible from the user' browser, making it necessary to setup additional custom reverse-proxy configuration.

### Steps to reproduce behavior

Setup ATLAS following the official guide.

**Comment by anthonysena** [comment]
@chgl if you have suggestions on how to make the configuration of ATLAS/WebAPI easier, we'd be happy to consider your suggestions and proposed changes. If you have specific recommendations, could you post them here and/or file a PR for consideration? Thanks!

**Comment by chgl** [comment]
Thank you for the reminder! I think this issue is mostly already addressed by https://github.com/OHDSI/Atlas/pull/2080 and https://github.com/OHDSI/Atlas/pull/2575 now, which allows configuring the WebAPI URL as an environment variable and read the Atlas config from a custom path.

Things like readiness/liveness probes, metrics, and tracing would still be nice, but could be re-visited if there is interest by others as well.
