### ISSUE TITLE
Misspelled column in exported concept set CSV files

### ISSUE THREAD

**Issue by lebedov** [OHDSI/Atlas#2367]
### Expected behavior

The column containing the concept code in a concept set exported as a CSV file should be named "Concept Code"

### Actual behavior

The column containing the concept code is named "Cocnept Code"

### Steps to reproduce behavior

Create a concept set and export it to a CSV file.

The bug seems to be due to [this line](https://github.com/OHDSI/Atlas/blob/3dce09d83aaf31805f6ca945e42c48df68f80365/js/components/conceptset/ConceptSetStore.js#L189) in the code.

**Comment by chrisknoll** [comment]
Fixed in #2374
