### ISSUE TITLE
Estimation and Prediction loses Analysis settings during import

### ISSUE THREAD

**Issue by wivern** [OHDSI/Atlas#2370]
### Expected behavior
Completed analysis design should be exactly the same as in the source instance

### Actual behavior
Prediction and Estimation analyses has empty Analysis settings section after import

### Steps to reproduce behavior
1. Export analysis from Atlas 2.7
2. Import it into Atlas 2.8

**Comment by anton-abushkevich** [comment]
> Export analysis from Atlas 2.7
It seems export from 2.8 doesn't work too.
