### ISSUE TITLE
No RC or DRC on Hierarchy tab

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#2372]
### Expected behavior
RC and DRC values should show up when you go to the Hierarchy tab of a concept.

### Actual behavior
The RC and DRC columns show 'loading'

### Steps to reproduce behavior
Search for a concept
Click on the concept (going to concept details)
Switch to Hierarchy tab (observe loading values)

**Comment by KSadomtsev** [comment]
![image](https://user-images.githubusercontent.com/56290675/99646009-05a7a800-2a61-11eb-8406-64c67b04f1f9.png)
Verified
