### ISSUE TITLE
[Characterization FA] not allow users to select domain-specific field values for demographic criteria

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2389]
Atlas 2.8

Steps:
1)Create CC analysis
2)Create FA with distribution type
3)Add demographic criteria
4)Choose any domain-specific field to distribute by
5)Save
6)Add FA to analysis design
5)Run analysis

Expected:
not allow users to select domain-specific field values for demographic criteria

Actual:
Characterization FA containing demographic criteria with distribution domain-specific field always failed

**Comment by KSadomtsev** [comment]
@wivern ok, the issue has been moved to Atlas

**Comment by chrisknoll** [comment]
Btw: I don't think it makes sense to have demographic criteria a selection for the distribution:  demographic criteria is just a way to apply rules on the index event itself, and not for selection of observation records that are used in distribution criteria queries.  Therefore, maybe we can remove demographic criteria from the choice?  Or, we need to think about demographic criteria being used to select values for distribtion (like age, index year, etc) but this is not aligned with the current purpose of 'demographic criteria in groups', so if we want to get the usecase of 'distribution by age', we need a new type of 'demographic criteria for distribution'.

**Comment by KSadomtsev** [comment]
verified
