### ISSUE TITLE
"synthea1kresults.concept_hierarchy" does not exist;

### ISSUE THREAD

**Issue by umesh-clinakos** [OHDSI/Atlas#2396]
Trying to check the condition era in data source section of Atlas but getting the concept_hierarchy table does not exist error. Nor sure why it is happening. I have run the achillies analytics on all the data source already.

If anyone help to resolve then it will really great.

**Comment by anthonysena** [comment]
The `concept_hierarchy` table is established as part of setting up the results schema for your CDM: https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration#results-schema-setup.
