### ISSUE TITLE
duplication of inclusion report

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#2397]
### Expected behavior
Inclusion report on generated cohort is duplicating for a specific datasource, see attached. 
[ATLASIncReportError.docx](https://github.com/OHDSI/Atlas/files/5667154/ATLASIncReportError.docx)

**Comment by chrisknoll** [comment]
This was related to a double insert into the cache tables, once I manually cleared the cache, the execution occurred without duplication.  I'd like to keep this open until we can investigate further, but I think this may be related to an execution that was in-progress when a server underwent a restart.

**Comment by jhardin29** [comment]
This has happened again on these two cohorts
[IncReportDups.docx](https://github.com/OHDSI/Atlas/files/5788772/IncReportDups.docx)

**Comment by chrisknoll** [comment]
Fixed in CIRCE-be 1.9.1.
