### ISSUE TITLE
copy of custom feature loses concept set references

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#2399]
### Expected behavior
when copying a custom feature for a characterization the logic of the concept sets would remain in tact in the new copy and the custom feature being copied would remain as is
### Actual behavior
when copying a custom feature for a characterization the logic of the concept sets is removed, and reverts to the general domain being used and the logic of the custom feature being copied is removed/empty

### Steps to reproduce behavior
copy custom feature, see new copy and see copied feature

**Comment by chrisknoll** [comment]
Fixed in OHDSI/WebAPI#1714.
