### ISSUE TITLE
[Geospatial] Map or geospatial tab should not be shown for "non-geo" data sources

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2412]
### Expected behavior
Map or geospatial tab should not be shown for "non-geo" data sources

### Actual behavior
![image](https://user-images.githubusercontent.com/56290675/102348327-cc584e80-3fb2-11eb-98c3-2bdee862dcc3.png)

### Steps to reproduce behavior
1)Run a valid cohort on non-geo data source
2)Open report

**Comment by KSadomtsev** [comment]
@anton-abushkevich , please, apply the same for profiles

**Comment by anton-abushkevich** [comment]
@KSadomtsev Done. OHDSI/atlas-component-geospatial#5 updated.

**Comment by KSadomtsev** [comment]
Now we have an issue with "geo" source, it shows like "non-geo"

**Comment by KSadomtsev** [comment]
Verified
