### ISSUE TITLE
Harmonize execution results availability visualization for users who don't have proper permissions

### ISSUE THREAD

**Issue by alex-odysseus** [OHDSI/Atlas#2419]
ATLAS 2.8.0

### Expected behavior
For all types of analyses the look and feel should be the same, preferably in a way that a user sees the number of available execution results, a button is disabled and there is a popup message shown "Not enough permissions to view results" instead of an enabled button "All executions (0)" so that the user is misled if there no available results or they don't have necessary permissions assigned

### Actual behavior
For Charecterizations and Cohort Pathways

Not having enough permissions
![image](https://user-images.githubusercontent.com/75131044/102630265-a070d080-414c-11eb-91dd-1ec031af143a.png)

Having enough permissions
![image](https://user-images.githubusercontent.com/75131044/102631747-67396000-414e-11eb-9137-9bedd23f6be1.png)

For Estimation and Prediction

Not having enough permissions
![image](https://user-images.githubusercontent.com/75131044/102630989-884d8100-414d-11eb-941f-61dc305d53f3.png)

Having enough permissions
![image](https://user-images.githubusercontent.com/75131044/102631856-8df79680-414e-11eb-87bf-05c7ecbd8c21.png)

### Steps to reproduce behavior
Add/remove permissions for particular data sources where the results are available and then switch between different analyses types

**Comment by anthonysena** [comment]
Linking to #1882 and closing since we need to define and implement a common mechanism for controlling/displaying executions in ATLAS.
