### ISSUE TITLE
Configure access modal fails on cohort definition load

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#2441]
### Expected behavior

When loading a cohort definition on https://atlas.ohdsi.org, the cohort definition loads and a read-only version appears.

### Actual behavior

An error is thrown which stops the page from properly rendering:

![image](https://user-images.githubusercontent.com/12902366/105095592-de2a8700-5a73-11eb-984a-ec163e8f9e6f.png)

### Steps to reproduce behavior

Navigate to https://atlas.ohdsi.org/#/cohortdefinition/317 with the developer tools enabled to view the error.

**Comment by chrisknoll** [comment]
I don't have a solution, but a little trace and clue:  when the router is routed to `cohort-definition-manager`, the component 'ConfigureAccessModal' is created, but the component param `isModalShown` is undefined.

**Comment by anthonysena** [comment]
I was tracing through the code a bit - here is the block where the ConfigureAccessModal is declared in the `cohort-definition-manager`:

https://github.com/OHDSI/Atlas/blob/317d1975e43fb2f017e224cea173e67a6194cf71/js/pages/cohort-definitions/cohort-definition-manager.html#L604-L611

Then this code should establish the `isAccessModalShown` observable:

https://github.com/OHDSI/Atlas/blob/317d1975e43fb2f017e224cea173e67a6194cf71/js/pages/cohort-definitions/cohort-definition-manager.js#L812

But when I compare this to the characterization module, it is using a `Global` permission service:

https://github.com/OHDSI/Atlas/blob/317d1975e43fb2f017e224cea173e67a6194cf71/js/pages/characterizations/components/characterizations/characterization-view-edit.js#L146

Not sure if this is the root cause but noting it as a difference.
