### ISSUE TITLE
Loader gets stuck when we adding Included Concepts in Concept Sets

### ISSUE THREAD

**Issue by DKashenko** [OHDSI/Atlas#2446]
Atlas 2.8

### Actual behavior

Loader gets stuck. Eventually, concept was added but if we don't switch the tab loader is still getting stuck. No errors were found in the console.
<img width="675" alt="loader Included Concepts" src="https://user-images.githubusercontent.com/77493858/105336972-ec4ee380-5bea-11eb-9350-fb555c6fb9c9.png">

### Steps to reproduce behavior

1. Create a new Concept Set
2. Add some concept (example "aspirin") -> Save
3. Add descendants to make Included Concepts available
4. Included concepts -> Choose some concept
5. Add concepts to Consept Set

**Comment by KSadomtsev** [comment]
fixed by https://github.com/OHDSI/Atlas/pull/2460
