### ISSUE TITLE
Graphical View - tooltip appearing offscreen

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#245]
In the graphical view, the tooltip for the timelines can appear offscreen. Good example of this is Cohort #3079 in the J&J environment. 

![image](https://cloud.githubusercontent.com/assets/8037742/18800240/f312bcfc-81a9-11e6-9137-b5ef6b3b9141.png)

**Comment by Sigfried** [comment]
It's just using d3.tip. Same thing with patient profile. Have people fixed this when using d3.tip on other charts?

**Comment by chrisknoll** [comment]
There's an open issue on d3-top's repo: 
https://github.com/Caged/d3-tip/issues/8
A pull request that addresses it is here:
https://github.com/Caged/d3-tip/pull/153

However that PR has conflicts. Also, d3-top (like d3) has been moving to a modularized design, so take some care when considering if the version of d3 (v3 vs. v4) is being used when applying a fix.
