### ISSUE TITLE
Cohort Pathways analysis "Uncaught TypeError: Cannot read property 'title' of null" when execution is not selected

### ISSUE THREAD

**Issue by DKashenko** [OHDSI/Atlas#2450]
Atlas 2.8

### Actual behavior

Error was found in the console
<img width="437" alt="pathway TypeError" src="https://user-images.githubusercontent.com/77493858/105486339-5fc22500-5cbf-11eb-8677-786e35cfccaf.png">

### Steps to reproduce behavior

1. Open any generated pathway 
2. Go to Execution tab -> Choose already generated execution
3. Click 'View reports'
4. Filter panel -> Take checkmark away from chosen cohort
5. Close opened window

**Comment by chrisknoll** [comment]
This was a null-check that was fixed in #2834.
