### ISSUE TITLE
Loader gets stuck after the first attempt to create a concept set

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2455]
Atlas 2.8.1
### Expected behavior
The concept set page is opened

### Actual behavior
Loader gets stuck after the first attempt to create a concept set
![image](https://user-images.githubusercontent.com/56290675/105678646-70141300-5efe-11eb-86bd-83faba184d2e.png)

### Steps to reproduce behavior
1)Log in by the user which has permissions to create a concept set
2)Concept sets -> new concept set

**Comment by chrisknoll** [comment]
One that that looks interesting in your screenshot is that the requested URL had an 'undefined' in the path to the vocabulary, making me think that either the source list for vocabularies wasn't loaded or this login doesn't have access to any sources.

I think the error you received from parsing the json was a HTTP error result in the request.
