### ISSUE TITLE
http://atlas-demo.ohdsi.org/ is unresponsive

### ISSUE THREAD

**Issue by artgoldberg** [OHDSI/Atlas#2467]
### Expected behavior
Accessing the http://atlas-demo.ohdsi.org/#/concept/320128 returns the concept set information about Essential hypertension

### Actual behavior
Accessing the http://atlas-demo.ohdsi.org/#/concept/320128 returns nothing in about 15 minutes

### Steps to reproduce behavior
Access http://atlas-demo.ohdsi.org/#/concept/320128

Thanks
Arthur

**Comment by leeevans** [comment]
It was most likely due to the nightly database backup that was running. I'm closing this issue because that URL is returning within a couple of seconds now.

**Comment by artgoldberg** [comment]
Good to know. Thanks!

**Comment by leeevans** [comment]
@artgoldberg Thanks for posting the screenshots - they are helpful.

What happens when you open this url in chrome? Does it timeout?
**http://api.ohdsi.org:8080/WebAPI/info**

We recently switched to using port 8080 instead of port 80 for the WebAPI calls, so I'm wondering if port 8080 is open to the internet on your network?

**Comment by artgoldberg** [comment]
You’re welcome.


I get this response immediately:


{"version":"2.8.0","buildInfo":{"artifactVersion":"WebAPI 2.8.0","build":"NA","timestamp":"Thu Dec 24 18:43:06 UTC 2020","branch":"refs/tags/v2.8.0","commitId":"029e12c","atlasRepositoryInfo":{"milestoneId":22,"releaseTag":"*"},"webapiRepositoryInfo":{"milestoneId":25,"releaseTag":"*"}},"configuration":{"security":{"samlActivated":false,"enabled":false,"samlEnabled":false},"vocabulary":{"solrEnabled":false},"person":{"viewDatesPermitted":false},"plugins":{"atlasgisEnabled":false},"heracles":{"smallCellCount":"5"}}}





On Feb 3, 2021, at 11:47 AM, Lee Evans <notifications@github.com> wrote:






USE CAUTION: External Message.






@artgoldberg
 Thanks for posting the screenshots - they are helpful.
What happens when you open this url in chrome? Does it timeout?
http://api.ohdsi.org:8080/WebAPI/info
We recently switched to using port 8080 instead of port 80 for the WebAPI calls, so I'm wondering if port 8080 is open to the internet on your network?
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.














Arthur Goldberg, PhD
Associate Professor of Genetics and Genomic Sciences
Institute for Data Science and Genomic Technology
Mount Sinai School of Medicine
646 526 5020
Scientific Computing

Arthur.Goldberg@mssm.edu

My Zoom:  https://mssm.zoom.us/my/arthur.goldberg?pwd=LzByMGJOZC9wM3A2aHV6OU94eUtSQT09
