### ISSUE TITLE
Unfortunately http://atlas-demo.ohdsi.org/#/concept/320128 continues to be unresponsive

### ISSUE THREAD

**Issue by artgoldberg** [OHDSI/Atlas#2468]
Hello

Following up on #2467.

### Actual behavior
Unfortunately http://atlas-demo.ohdsi.org/#/concept/320128 continues to be unresponsive. I'm learning about ATLAS and want to show it to some colleagues. Perhaps another ATLAS instance would be better to use.

**Comment by leeevans** [comment]
Hi @artgoldberg I'm not able to reproduce the error when I open:
http://atlas-demo.ohdsi.org/#/concept/320128

Is this an intermittent error or is that page never loading when you try to open it?

Could you try the following to provide some screenshots for further investigation?

Use Chrome browser - this is the only officially supported browser for Atlas
open new incognito window
open developer tools, click on the network tab and check 'disable cache'
open the above URL - ensuring it is using '**http**' not 'https'. 
click on the console tab take a screen shot (to show error messages) 
click on the network tab and take a screenshot to show network timeouts

Thanks

**Comment by artgoldberg** [comment]
Hi @leeevans 

Thanks for your reply. 

    Is this an intermittent error or is that page never loading when you try to open it?

Lately it has been reproducible, but some weeks ago I could load it.

    Could you try the following to provide some screenshots for further investigation?

    Use Chrome browser - this is the only officially supported browser for Atlas
All my usage has been with Chrome.

    open new incognito window
    open developer tools, click on the network tab and check 'disable cache'
    open the above URL - ensuring it is using 'http' not 'https'.
    click on the console tab take a screenshot (to show error messages)
![image](https://user-images.githubusercontent.com/33882/106776379-02f53180-6612-11eb-8356-93a97d9982c8.png)

    click on the network tab and take a screenshot to show network timeouts
![image](https://user-images.githubusercontent.com/33882/106776464-16a09800-6612-11eb-95ef-49ada68435b9.png)

As you see, this didn't reproduce the error, so I'll do the same steps using a non-incognito tab that does reproduce it.

    click on the console tab take a screenshot (to show error messages)
![image](https://user-images.githubusercontent.com/33882/106777164-bd853400-6612-11eb-9f91-c487a5eed3c3.png)

    click on the network tab and take a screenshot to show network timeouts
![image](https://user-images.githubusercontent.com/33882/106777628-266cac00-6613-11eb-912b-a8bcf99fd46c.png)

**Comment by artgoldberg** [comment]
http://atlas-demo.ohdsi.org/#/concept/320128 is responding now
