### ISSUE TITLE
expose concept set sql through concept set UI

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#247]

**Comment by pbr6cornell** [comment]
a nice-to-have feature we should consider for ATLAS 3.0....whenever we have a JSON spec that gets translated to SQL, it'd be nice to allow for user to see the SQL.

**Comment by anthonysena** [comment]
Closing this due to age. Most often, we're exporting the concept set SQL via the cohort definition(s) that use them. If there is a need for this, we can revisit and re-open this issue.
