### ISSUE TITLE
White screen on concept set page for users with AtlasUsers Role only

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2484]
### Expected behavior
![image](https://user-images.githubusercontent.com/56290675/109171398-cccf4b80-7792-11eb-921f-f475f6f6ec05.png)

or some information for the user about data source permissions

### Actual behavior
Just white screen, it happens because:
/WebAPI/conceptset/68/expression/{some_source}

`{"payload":{"cause":null,"stackTrace":[],"message":"An exception occurred: javax.ws.rs.ForbiddenException","localizedMessage":"An exception occurred: javax.ws.rs.ForbiddenException","suppressed":[]},"headers":{"id":"e5e81611-53f9-d97d-902f-6b463f2d0332","timestamp":1614265038294}}`

### Steps to reproduce behavior
1)Log in by user with Atlas users role only
2)Concept Sets
3)Open any concept set

**Comment by ssuvorov-fls** [comment]
also merged into master-2.8
