### ISSUE TITLE
estimation r code needs updating

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#249]
The following variables are no longer part of the call to getDbCohortMethodData

```
                                      #firstExposureOnly = FALSE,
                                      #removeDuplicateSubjects = TRUE,
                                      # washoutPeriod = 0,
```

**Comment by schuemie** [comment]
Just checking: are you saying `getDbCohortMethodData` no longer accepts these variables? Because [it does](https://github.com/OHDSI/CohortMethod/blob/master/R/DataLoadingSaving.R#L134)

**Comment by fdefalco** [comment]
You're right, there was an old version of the package on the server I was testing on, I'll leave this open because the code that ATLAS generates still needs other updates but the variables are accepted.

**Comment by anthonysena** [comment]
I'm going to close this issue as I have another issue #305 that will address this one.
