### ISSUE TITLE
Architecture Diagram or Design Diagram for Atlas

### ISSUE THREAD

**Issue by sorcerer-rc** [OHDSI/Atlas#2490]
I am looking for an Architecture Diagram or Design Diagram for Atlas.
This is needed for an internal deployment of Atlas/WebAPI.
Can someone please point me in the right direction.
thanks.
@anthonysena @chrisknoll @alondhe

**Comment by anthonysena** [comment]
Hi @sorcerer-rc - there is a logical diagram on the WebAPI Wiki [here](https://github.com/OHDSI/WebAPI/wiki#overview). I just noticed that the image was broken and have fixed it so it should display now. Just let us know if this fits the need.
