### ISSUE TITLE
User gets no error messages when adding Stratify Criteria in IR Analysis

### ISSUE THREAD

**Issue by DKashenko** [OHDSI/Atlas#2495]
Atlas 2.9

### Expected behavior
User receives an error message that the required parameter value is empty

### Actual behavior
No error messages when required parameter value is empty . It is not clear for user where he made the mistake if he does
<img width="395" alt="age_40" src="https://user-images.githubusercontent.com/77493858/111605528-6e244d00-87e7-11eb-921e-ceb7b495fe8a.png">
<img width="487" alt="NoMessage" src="https://user-images.githubusercontent.com/77493858/111605539-6fee1080-87e7-11eb-8670-179aa020f02c.png">

### Steps to reproduce behavior

1. Open any IR analysis
2. Add new Stratify Criteria -> Add criteria to group
3. Add demographic -> Add age criteria

**Comment by anton-abushkevich** [comment]
Same for cohort charactezation "Subgroup analyses". Need to add validation for org.ohdsi.circe.cohortdefinition.CriteriaGroup in Incident Rates and Characterizations.
