### ISSUE TITLE
Select all concepts in datatable not available

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#2499]
### Expected behavior
In Atlas 2.7, we could select all concepts in the search results using the shopping cart at the top of the datatable:

![image](https://user-images.githubusercontent.com/8037742/112852472-97f43400-9071-11eb-8ffb-00c36855b242.png)

### Actual behavior
In 2.8+ there is no option:

![image](https://user-images.githubusercontent.com/8037742/112852532-a3dff600-9071-11eb-9832-f19163ce1a47.png)

### Steps to reproduce behavior
Use Atlas 2.8+ and search for something. Datatable does not have a select all checkbox.

**Comment by anton-abushkevich** [comment]
Done in #2543
