### ISSUE TITLE
Vocabulary Search doesn't honor special characters

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#250]
Case: search for ICD10: E78.5 does not return results due to the '.' character.

**Comment by anthonysena** [comment]
Replicated on ohdsi.org: http://www.ohdsi.org/web/atlas/#/search/E78

**Comment by ericaVoss** [comment]
Just tried to search for "MG/DL" and it chokes on the "/" I think.

1. Go to ATLAS
2. Search for MG/DL
3. Search just doesn't seem to activate.  Generates the URL ".../atlas/#/search/MG/DL"
