### ISSUE TITLE
Broken URL(undefined) after clicking PLP/PLE analysis in notification

### ISSUE THREAD

**Issue by DKashenko** [OHDSI/Atlas#2508]
Atlas 2.8+
### Expected behavior
The PLP/PLE results are shown
url's:
#/estimation/cca/108/executions/26557
prediction/91/executions/26557

### Actual behavior
Broken url's:
prediction/**undefined**/executions/26557
estimation/cca/**undefined**/executions/26557

### Steps to reproduce behavior

1. Login by a user
2. Run plp/ple analysis
3. Open notification
2. Click to plp/ple job link

**Comment by KSadomtsev** [comment]
Heracles:
/cohortdefinition/undefined/samples/undefined
