### ISSUE TITLE
DRUG_SOURCE_VALUEs

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#251]
We currently cannot search for DRUG_SOURCE_VALUEs within the ATLAS tool.  This is valuable when you have new drugs entering the market that you need to review but the codes don't exist at all in the Vocabulary yet.

**Comment by pbr6cornell** [comment]
Are you looking to search the SOURCE_VALUE field in the SOURCE_TO_CONCEPT_MAP table as part of the vocabulary exploration process?   (in which case, I don't see any harm in it though I can't comment on the work to implement it).

Or are you looking to use the SOURCE_VALUE fields in a COHORT definition?  (in which case, I do see challenges with that, not the least of which is that this represents an unstructured freetext search, not a concept mapping exercise).

**Comment by ericaVoss** [comment]
I meant DRUG_EXPOSURE.DRUG_SOURCE_VALUE but obviously this is a huge pain and against all of our standardization.  I just use DRUG_SOURCE_CONCEPT_ID now.

Let's close this issue.
