### ISSUE TITLE
npm run build error in Atlas

### ISSUE THREAD

**Issue by SungJun9212** [OHDSI/Atlas#2513]
### Expected behavior
npm run build success in Atlas

### Actual behavior
![캡처](https://user-images.githubusercontent.com/31676950/115204118-1acd5380-a133-11eb-9b8f-811677677e0c.PNG)

**Comment by anton-abushkevich** [comment]
Please upgrade your node.js version to 8+.

"Unexpected token ..."
Three dots operator (or spread operator) was introduced in ES6 and not supported in old versions of V8 javascript engine and therefore in old versions of node.js.
