### ISSUE TITLE
(Feature) Add more detail to browser title

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#252]
Hi,

Currently, the browser title, on any page, is just 'ATLAS'. I was thinking it might be useful to have something like 'ATLAS: Search for Clopidogrel' or 'ATLAS: Cohort 1234' or 'ATLAS: Concept Set 1234'. Additionally, including an asterisk to the title if there are unsaved changes could also be useful in identifying your active cohorts or concept sets.

Hopelessly lost in Chrome tabs,
Ajit

**Comment by fdefalco** [comment]
see #211 :)
