### ISSUE TITLE
Page display delay due to repeated (concept search then add Related Concepts) process

### ISSUE THREAD

**Issue by tomBSUC** [OHDSI/Atlas#2533]
### Expected behavior

I would expect no growth in page display delay in ATLAS after repeatedly adding Related Concepts to a concept set.

### Actual behavior

I have noticed a page display delay that grows slowly to a longer and longer delay the more I repeat a specific short process.  

### Steps to reproduce behavior

The process is:
1)	Use the Search box to search my Concept Set for a concept ID.
2)	After finding the ID, click the Concept Name.
3)	Click the Related Concepts tab.
4)	Click the shopping cart icon to add one or more of the concepts that appear on the Related Concepts tab.
5)	Click the <- (back arrow) link near the top of the screen (which includes the name of my concept set) to go back to my Concept Set’s list of concepts.

The delay starts to grow to the length of 1-3 seconds or so after about 20 repetitions of this otherwise quick process.  

The delay goes away if I Refresh the ATLAS browser window.  It likely also goes away if I close and re-open my browser, but I have not confirmed this.  

The delay does NOT go away if I click the Save button for my concept set, nor if I simply wait a few seconds or minutes before repeating the process.

I have noticed this growing delay on multiple occasions across the span of a few months, most recently today/yesterday. I am using Google Chrome as my browser (version 90.0.4430.93 official build 64-bit).  

Hope you can resolve this delay in a future build, and/or make it easier to compile a list of all Related Concepts for all concepts that are currently in a concept set.

Thank you,
Tom

**Comment by anthonysena** [comment]
@tomBSUC - thank you for providing a very clear description of how to reproduce this issue. I've reviewed this issue on the latest code base (v2.11) and it appears that these issues are now resolved. Thanks!
