### ISSUE TITLE
Unable to share concept sets with other users.

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#2541]
### Expected behavior
You should be able to share concept sets when security is enabled.

### Actual behavior
The 'lock' button is not present in the repository conceptset.

### Steps to reproduce behavior
1. Open a repository concept set with security enabled atlas.
2. Observe: no lock button available to assign permissions to other users, so only the creator can modify.

**Comment by anton-abushkevich** [comment]
duplicate of #2521
