### ISSUE TITLE
Atlas CORS error

### ISSUE THREAD

**Issue by yampeku** [OHDSI/Atlas#2545]
I'm using atlas 2.9, with webapi `security.origin` to `*` and  `security.cors.enabled` to `false ` and somehow I'm still getting CORS errors when starting ATLAS

![imagen](https://user-images.githubusercontent.com/5321857/119635086-a06baf80-be13-11eb-8931-2564ad048a4e.png)

_Originally posted by @yampeku in https://github.com/OHDSI/Atlas/issues/2070#issuecomment-848609334_

**Comment by yampeku** [comment]
tomcat has a CorsFilter defined like this
`<filter>
<filter-name>CorsFilter</filter-name>
<filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
<init-param>
<param-name>cors.allowed.origins</param-name>
<param-value>*</param-value>
</init-param>
</filter>
<filter-mapping>
<filter-name>CorsFilter</filter-name>
<url-pattern>/*</url-pattern>
</filter-mapping>`

Also added `Access-Control-Allow-Origin` to `*` IIS Http headers

**Comment by dormistonsmith** [comment]
I'm having the exact same issue, likewise having compiled WebAPI.war with `security.origin` set to * and `security.cors.enabled` set to false. To be honest I'm not sure why CORS is even an issue, given everything is running on localhost?

**Comment by yampeku** [comment]
For it to work it needs to be security.cors.enabled to true and security.origin to *
I had to delete it from tomcat because I got an error of defining the policy twice

I'll leave this issue open as I think the false + * should indeed work

**Comment by dormistonsmith** [comment]
Recompiled WebAPI today using the newer v2.9.0 release and the CORS errors have cleared up. Was using version 2.8.2 previously. Worth a try if anyone else is having similar problems!

**Comment by anthonysena** [comment]
Sorry for the trouble @yampeku and @dormistonsmith but glad that a newer release of the platform solved this.
