### ISSUE TITLE
Github release lacks package.json

### ISSUE THREAD

**Issue by jnothman** [OHDSI/Atlas#2546]
### Expected behavior

`npm run build` should succeed.

### Actual behavior

`No such file or directory ... /atlas/package.json`

### Steps to reproduce behavior

Following https://github.com/OHDSI/Atlas/wiki/Atlas-Setup-Guide#atlas-installation I download the latest release, unzip, enter the `atlas` directory and run `npm run build`

I.e.
```sh
cd /tmp
wget https://github.com/OHDSI/Atlas/releases/download/v2.9.0/atlas.zip
unzip atlas.zip
cd atlas
npm run build
```

**Comment by anthonysena** [comment]
The ATLAS documentation should recommend cloning the repository which contains the `package.json` since the tagged `atlas.zip` lacks this file. Sorry for any problems this caused @jnothman
