### ISSUE TITLE
Add mean and median age to person report ? 

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#255]
It would be helpful to add a table with the mean, median, and standard deviation to the person report on the reporting tab. 

Thank you.

**Comment by t-abdul-basser** [comment]
Please elaborate.

**Comment by jhardin29** [comment]
for a given cohort, on the reporting tab, for the person report, when it is generated it currently shows the distribution of birth years of the subjects in the cohort. In addition to this it would be nice to have a table containing the mean subject age, median subject age, and standard deviation.

**Comment by anthonysena** [comment]
Closing this out since it is now possible to obtain this information using the cohort characterization features (#930).
