### ISSUE TITLE
Cohort Definition List

### ISSUE THREAD

**Issue by shreyanssethi** [OHDSI/Atlas#2567]
### Expected behavior

In the Atlas repo, the following path is used to get a list of the cohort definitions:
webAPIRoot + 'cohortdefinition/'

### Actual behavior

The endpoint above does not seem to be working with a curl request or with ajax (Even when CORS is turned off). It either returns an empty result (even if there are clearly cohort definitions in the Atlas UI) or gives an error message. Is there any better way to access the WebAPI or Atlas as an endpoint and get a list of the cohort definitions?

### Steps to reproduce behavior

Try curl in the command line with the URL as specified (webAPIRoot + 'cohortdefinition/')

**Comment by anthonysena** [comment]
I'd suggest looking at the https://github.com/OHDSI/ROhdsiWebApi project for programmatic access to WebAPI.
