### ISSUE TITLE
format to connect a postgres source

### ISSUE THREAD

**Issue by jcabrerazuniga** [OHDSI/Atlas#2571]
I can not find the information about the format used to specify the connection information for a postgres database. Assuming that the psql database is located at ip X, port P, DBname = mydb, DBschema=myschema, how can I combine this info to fill up the new source page:

![atlasSource](https://user-images.githubusercontent.com/27739794/122984409-371b8580-d35a-11eb-9185-e808e369b2df.png)

Thanks

**Comment by don-torok** [comment]
Have you installed WebAPI?
The first prerequisite for ATLAS is to Install the OHDSI WebAPI. Installation and configuration information is available on the WebAPI wiki. The ATLAS setup assumes WebAPI is available and configured with one or more patient data sets converted to the OMOP Common Data Model.
https://github.com/OHDSI/Atlas/wiki/Atlas-Setup-Guide

**Comment by jcabrerazuniga** [comment]
Yes, I have WebAPI successfully running. But, I want to know how to connect to another OMAP DB. So Far, I tried:

Connection string:  jdbc:postgresql://hsc-ctsc-atlas.health.unm.edu:7432/truven/

Username:  atlasuser

Source Dialect: PostgresQL

From the server from where Atlas is running I have been able to connect to the database using

psql -h localhost -U atlasuser -p 7432

But it does not work if I use your interface. I also need to specify a schema as it is within the schema ccae20169 that exist in our truven database where all the data we want to analyze exists.

Thanks in advance

**Comment by don-torok** [comment]
This is beyond my ability to help.  I suggest you post your original question in the Implementer Forum.  More people are likely to monitor the Forum (and hopefully provide an answer) then they are to monitor git issues.

**Comment by ssuvorov-fls** [comment]
Hello
Try to remove trailing slash from connection string.
Schema is specified in "Source daimons" section.

**Comment by jcabrerazuniga** [comment]
@ssuvorov-fls 
Can you please tell me where is the source daemons located? Thanks

**Comment by anthonysena** [comment]
> Hello Try to remove trailing slash from connection string. Schema is specified in "Source daimons" section.

The additional trailing slash in your connection string is the issue here.
