### ISSUE TITLE
Uncaught TypeError: ko.i18n is not a function

### ISSUE THREAD

**Issue by blootsvoets** [OHDSI/Atlas#2577]
### Expected behavior

Atlas loads (albeit with a warning) on most browsers.

### Actual behavior

On Brave and Firefox browsers on Windows, Atlas gets stuck at the loading screen. The Javascript console gives error message `Uncaught TypeError: ko.i18n is not a function` using the contents of "only Chrome v63 or later is supported ... etc.". It seems that the engine gets stuck after this message and does not proceed with loading.

### Steps to reproduce behavior

Install Atlas 2.9.1 via docker image `ohdsi/atlas:2.9.1` with WebAPI 2.9.1, for example using the https://github.com/thehyve/ohdsi-docker repository.

@keesvanbochove do you have anything to add?

**Comment by blootsvoets** [comment]
Most likely this is related to merged PR #2493.

**Comment by anthonysena** [comment]
Closing due to the fact that we only support Google Chrome and this issue is a bit old. If this still persists with the most recent version ATLAS, please re-open and we can investigate.
