### ISSUE TITLE
Patient profile navigation from cohort explorer messed up.

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/Atlas#259]
At least in the version of the code I'm working from, the tab navigation is screwy: 1) pick a cohort, 2) click Explore tab; 3) click data source button; 4) screen refreshes to Definition tab; 5) click Explore tab again; 6) Explore tab displays correctly. Not sure when this got messed up. Maybe when removing tab navigation from cohort page (but I thought I left it in working condition at that point.)

**Comment by fdefalco** [comment]
I can confirm this is an issue on the current master branch.

**Comment by anthonysena** [comment]
Closing as it is a duplicate of #330
