### ISSUE TITLE
Add Visit Criteria - shows place of service attribute

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#2594]
### Expected behavior
When pulling in a visit criteria, no attributes should be populated by default.

### Actual behavior

This odd "with distance from a Place of Service to Patient" attribute appears by default:

![image](https://user-images.githubusercontent.com/8037742/130380911-22434393-5374-4e5d-9be9-88b7124a2d19.png)

### Steps to reproduce behavior
Add a visit criteria to a new cohort in Atlas v2.9x. Found in our version and in the Atlas demo site: http://atlas-demo.ohdsi.org/#/cohortdefinition/1777598/definition

**Comment by alondhe** [comment]
@chrisknoll  -- does this relate to the bug #2599 ?

**Comment by chrisknoll** [comment]
Yes, sorry, I did not see this issue, i'll close the other.

**Comment by chrisknoll** [comment]
So, I looked at the object model of Circe, and I don't see anything that looks like a place of service distance.   Someone from @OdysseusMark or @alex-odysseus or @OHDSI/odysseus-product-team could shed light on this element, but if it was never implemented, it should probably be removed from the UI.

**Comment by alondhe** [comment]
Yeah, we didn't see it either until 2.9.x. It wasn't happening prior. Must be Atlas UI.
