### ISSUE TITLE
Condition status as attribute missing header

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#2601]
### Expected behavior
Condition status should have a header in the attribute dropdown of condition occurrence
### Actual behavior
![image](https://user-images.githubusercontent.com/8037742/130496697-b47c027a-13bb-4778-84da-3a9ba62fda2d.png)

### Steps to reproduce behavior
Use the attribute dropdown of condition occurrence

**Comment by alondhe** [comment]
Looks like something here is incorrect: https://github.com/OHDSI/Atlas/blob/master/js/components/cohortbuilder/const.js#L720

@anton-abushkevich

**Comment by chrisknoll** [comment]
Are you sure you're working off master?  I have latest from master and have this:
![image](https://user-images.githubusercontent.com/6818777/130671647-413ff2d8-cd82-4b37-8ee4-bb875baee333.png)

**Comment by alondhe** [comment]
Hmm, not master, but I do see it in both ours and the demo site.

**Comment by chrisknoll** [comment]
Ah, Ok, so I checked the releases, and there is a 2.9.1 version, but atlas-demo is running off of 2.9.0. According to the [release notes](https://github.com/OHDSI/WebAPI/releases/tag/v2.9.1) they do call out a fix to the ConditionStatus heading. So, probably just need to get 2.9.1 docker-ized and deployed to the demo site (not sure exactly how that's done)

**Comment by chrisknoll** [comment]
I see this fixed in https://github.com/OHDSI/WebAPI/pull/1896, so I'll close this, but please re-open if you think this issue is still unresolved.  Thanks!
