### ISSUE TITLE
Drug Exposure Report No Data 

### ISSUE THREAD

**Issue by gywlsdms123** [OHDSI/Atlas#2602]
![image](https://user-images.githubusercontent.com/51704606/130550729-b4504f24-f362-4492-8c8c-1798f9f489bd.png)

![image](https://user-images.githubusercontent.com/51704606/130550806-83a0f045-271a-4d33-8505-70010f5bdbc6.png)

![image](https://user-images.githubusercontent.com/51704606/130550932-7df26ac5-1e8b-4abc-af0f-e1f6e130e150.png)

![image](https://user-images.githubusercontent.com/51704606/130551601-5dc14be0-2169-4dcb-a9f0-5e8fb6d0ac7a.png)

Even though there is data composing the treemap, it does not appear in Atlas Data Source.
For data sources other than drug, a treemap is normally formed.
What's the reason?

I am using postgresql, tomcat 9.0, Atlas v2.9.1, WebAPI v 2.9.0 in windows. 

Any help would be appreciated.

**Comment by konstjar** [comment]
I'm not sure this issue is related to ATLAS, as it's more about your data and ACHILLES reports. You can get SQL query here and try to run it on your data:
https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/report/drug/treemap.sql

**Comment by gywlsdms123** [comment]
Which table should this query insert into?

**Comment by konstjar** [comment]
This query makes select

**Comment by gywlsdms123** [comment]
I found this problem. 
My drug concept id is configured with ATC, and treemap is configured with RxNorm, so there was no matching data. 

The drug concept will be replaced by RxNorm.

Thanks for help!
