### ISSUE TITLE
Patient profile highlighting has HTML in name

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#2605]
### Expected behavior
Line items in profile highlighting window do not have any extra HTML text included.

### Actual behavior
The line items here have the HTML tag in text:

![image](https://user-images.githubusercontent.com/8037742/130719356-9970f830-80c0-4dab-94de-2d2e9f9e61f5.png)

### Steps to reproduce behavior
Generate patient sample then look at its profile. Use the highlighting option. 

It appears that perhaps the cohort entry events / inclusion rules have this issue. Here, for instance, we looked at remicade with prior RA, and both have this extra HTML.

**Comment by alondhe** [comment]
Replicated this in atlas-demo site for a melanoma cohort:

![image](https://user-images.githubusercontent.com/8037742/130719923-3fc1fba3-a2c7-45e2-aa0a-1ea58f0caf65.png)

**Comment by anthonysena** [comment]
This appears to be resolved in v2.11.
