### ISSUE TITLE
# Fatal error in , line 0 # Fatal process out of memory: Zone

### ISSUE THREAD

**Issue by rezabaharmand** [OHDSI/Atlas#2608]
![Screenshot 2021-09-03 161204](https://user-images.githubusercontent.com/77742999/132020170-7889968d-3b5e-4ec1-b050-c74935c92eb3.png)

**Comment by rezabaharmand** [comment]
Hi Dears,

I hope at least someone has an idea!
Thanks

**Comment by chrisknoll** [comment]
Try to run `npm cache verify`.

I did a search on that error number and that led me here: https://stackoverflow.com/questions/58756101/npm-err-errno-3221225477-error-in-node-when-making-a-query-using-oracledb.

You should try your own searches and see if it is something related to your own environment.
