### ISSUE TITLE
Selecting Censoring event for Payer Plan period fails

### ISSUE THREAD

**Issue by mik-ohdsi** [OHDSI/Atlas#2616]
### Expected behavior
For Cohort Exit add a Censoring Event, choose Payer Plan Period, a new line appears to specify the period.

### Actual behavior
Adding a censoring event with Payer Plan Period seems to do nothing. Later, after scrolling up to the cohort entry section an entry was found with a message saying that Payer Plan Period only works with v.5.3 up. The entry ended up in the wrong place.
![ATLAS_payerplanperiod](https://user-images.githubusercontent.com/60365423/133100819-303ae65e-d3ed-4732-94f2-441112522f2b.png)

### Steps to reproduce behavior
http://ohdsisym21.us-east-1.elasticbeanstalk.com/#/cohortdefinitions, ATLAS & WebAPI Version 2.9.1

Create cohort, create some entry criteria, add a censoring event for Payer Plan Period to the cohort exit section, scroll up to the entry section and find a misplaced Payer Plan period line.

On a different note: when selecting visit, a specimen entry is created instead. This is presumably fixed by #2579 in version 2.10 that added specimen (and hopefully reintroduced visit properly).  
![ATLAS_censoring_visit](https://user-images.githubusercontent.com/60365423/133101567-2c233495-0e00-4574-bab3-30d96498daee.png)

**Comment by vvcb** [comment]
Thanks @mik-ohdsi . I have just looked at this file in 2.10 release and the error persists. 

https://github.com/OHDSI/Atlas/blob/master/js/components/cohortbuilder/components/CohortExpressionEditor.js

Lines 391 - 397 seem to be the culprit.

**Comment by mik-ohdsi** [comment]
Thanks, @vvcb (Vishnu). I had just double checked myself and you are right, the bug that is responsible for adding a specimen when selecting a visit is still present in the current [ATLAS code](https://github.com/OHDSI/Atlas/blob/master/js/components/cohortbuilder/components/CohortExpressionEditor.js) (starting line 391).
![ATLAS_censoring_visit_code](https://user-images.githubusercontent.com/60365423/133105324-3f2d36d1-6a78-4bfe-8b17-fc3122083492.png)
