### ISSUE TITLE
Cohort sql export not refreshed

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/Atlas#262]
Changes made to a cohort are not shown in the Export > SQL tab. This caused us a lot of confusion when we exported our new cohorts to R.
After a lot of trial and error, we found that the export is not reloaded when this SQL tab was already selected before changes were made.

To replicate the problem: 1) open a cohort 2) go to Export > SQL 3) edit the cohort and save 4) go back to the Export tab. The SQL has not changed. 
The exports are only reloaded when switching from SQL to e.g. the JSON tab and back again. A hard refresh of the webpage works as well, of course.

We suggest that the SQL exports are always reloaded when the cohort is saved.

**Comment by chrisknoll** [comment]
Apologies for the confusion. I think your suggestion is reasonable. I'll make this fix.

**Comment by fdefalco** [comment]
resolved in https://github.com/OHDSI/Atlas/commit/8b743e3cf248abd1465fd3488179047374942d61
