### ISSUE TITLE
Ability to define cohorts based on VisitDetail information

### ISSUE THREAD

**Issue by AEW0330** [OHDSI/Atlas#2638]
### Expected behavior
Information represented as care_site_id/place_of_service_concept_id concepts from the VISIT_DETAIL table is available (e.g. using Add Criteria - filter Visit for place of service) when defining cohorts.

BACKGROUND: Research using the OMOP-converted form of the important MIMIC IV dataset used by the PhysioNet and OHDSI communities cannot use ATLAS for phenotyping because cohorts need to be defined in part by the place of service within an inpatient stay. E.g. cohort entry needs to be defined by admission to ICU, NICU, NeuroICU, Med ICU etc. The ETL from MIMIC IV to OMOP 5.3 appropriately captures this information on transfers across hospital units in the care_site_id/place_of_service_concept_id concepts from the VISIT_DETAIL table. 

### Actual behavior
[ATLAS makes no use of information in VISIT_DETAIL](https://forums.ohdsi.org/t/modified-use-of-visit-detail-consequences-atlas-hades/14686/3). 

### Steps to reproduce behavior
Stand up an ATLAS instance pointed at the OMOP version of MIMIC IV and attempt to use Add Criteria - filter Visit for place of service in specifying a cohort's Initial Event.

**Comment by anthonysena** [comment]
Noting that VISIT_DETAIL is part of the OMOP v5.3: https://ohdsi.github.io/CommonDataModel/cdm53.html#VISIT_DETAIL.

**Comment by chrisknoll** [comment]
Visit detail is a supported criteria object that can be used as entry events or inclusion rules.
