### ISSUE TITLE
Patient level prediction covariate settings include/exclude concepts popup broken.

### ISSUE THREAD

**Issue by ellisille** [OHDSI/Atlas#2645]
### Expected behavior
0. Atlas 2.10 or 2.11.
1. In patient-level predictions, adding or editing covariate settings.
2. Select "What concepts do you want to include in baseline covariates in the patient-level prediction model? (Leave blank if you want to include everything)" or "What concepts do you want to exclude in baseline covariates in the patient-level prediction model? (Leave blank if you want to include everything)".
3. In the popup that opens, click on a concept set.
4. The concept set is included/excluded in the covariate settings.

### Actual behavior
3. In the popup that opens, nothing is clickable.
4. Unable to use the included/excluded functionality.

### Steps to reproduce behavior
Using Atlas 2.10 or 2.11, add included/excluded concept sets to a covariate setting.

**Comment by anthonysena** [comment]
Noting that this is a bug that is still present in v2.11:

![image](https://user-images.githubusercontent.com/12902366/166562498-6f1457d8-1d9e-4890-acb3-bd6ed23913e7.png)
