### ISSUE TITLE
Cohort generation 100x slower in Atlas than in SQL

### ISSUE THREAD

**Issue by altosaar** [OHDSI/Atlas#2648]
### Expected behavior
Cohort generation does not take several hours and matches the performance of a SQL query against the same database.

### Actual behavior
Cohort generation takes several hours.

### Steps to reproduce behavior
1. Create a cohort for delivery hospitalizations using the JSON exported from Atlas (attached as `cohort.json`). 
2. Generate the cohort; it takes several hours:
![image](https://user-images.githubusercontent.com/5317244/146552598-ae478a0d-dc5e-4bd6-8393-56046495d40c.png)
3. Use the `cohort.sql` OHDSI SQL template - plug in the details in https://data.ohdsi.org/SqlDeveloper/ and paste it into Microsoft SQL Server Management Studio or another IDE. The SQL template is incomplete so needs these lines added to it: 
```
CREATE TABLE target_database_schema.target_cohort_table (
	cohort_definition_id INT,
	cohort_start_date DATE,
	cohort_end_date DATE,
	subject_id BIGINT
);
```
4. Run the SQL query. It takes 49 seconds as opposed to 1h 38 min, which is over 100x faster. (And there are the same number of rows/persons in the cohort.)

This causes several days' worth of delays regularly: every slight change in a cohort definition (including or excluding a concept set, etc) means many hours of waiting to rerun characterizations and tweak the cohort definition. 

Any idea how to debug the source of this slowdown? 

cc @t-abdul-basser @noemieelhadad @cukarthik 

[sql-and-json.zip](https://github.com/OHDSI/Atlas/files/7735469/sql-and-json.zip)

**Comment by altosaar** [comment]
Just in case it helps someone else, it looks like this issue is database-dependent. Running the query against an older version of the database on Atlas is fast, but running it on a newer database takes very long. 

Curious if anyone else has run into this! My hunch is that it might be related to the way inpatient visits are coded (that was a key step when the cohort generation started taking 5+ hours), but I am not sure how to investigate and don't have access to the logs.

**Comment by anthonysena** [comment]
@altosaar - these types of issues are tricky to diagnose but generally speaking differences in performance between databases on the same database platform comes down to storage and indices. I'm going to close this out now since it is a few months old so hoping that you guys got this all figured out. Thanks!
