### ISSUE TITLE
Display rule drill down SQL once a heel rule detects an DQA issue

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#266]
See this file 

https://github.com/OHDSI/Achilles/blob/master/inst/csv/rule_drill_down.csv

Colum code contains the code that should be offered to the Heel report consumer.

Heel output in Atlas needs many improvement
AtlasWeb github repo contains additional feature request that I hope to re-post here.

**Comment by anthonysena** [comment]
Closing this out due to age. Please see [DataQualityDashboard](https://github.com/OHDSI/DataQualityDashboard) for more information on data quality assessment.
