### ISSUE TITLE
How to debug cohort generation for Truven Marketscan Medicare data?

### ISSUE THREAD

**Issue by jaanli** [OHDSI/Atlas#2666]
### Expected behavior
- more than 1 person in a large cohort

### Actual behavior
- 1 person in a cohort

### Steps to reproduce behavior
Use Atlas to generate this cohort:
[delivery-hospitalizations.txt](https://github.com/OHDSI/Atlas/files/8156865/delivery-hospitalizations.txt)
On the Truven Marketscan Medicare data source:
![image](https://user-images.githubusercontent.com/5317244/156059472-f9a3f0f9-d5e4-4dd0-9b85-bfa259b0a786.png)

Note that there are 100k+ people in the other data sources, but only a single person in Medicare.

How would you debug this?

Any help would be appreciated. @toekneesunshine and I looked at the exported SQL but it is messy, and all the concept sets are compressed into a single line, so something like a stack trace or binary search to comment out parts of the query will be difficult. Has anyone debugged errors like this that are data source dependent?

Alternatively, is there a point person at Truven to ask about potential preprocessing in the data that is different than the Multi-state Medicaid data, leading to only a single person in this cohort?

Thanks!
Jaan

cc @cukarthik @t-abdul-basser @noemieelhadad

**Comment by altosaar** [comment]
That is very confusing because there is another cohort generated on the same data with 26k pregnancy-related outcomes (severe maternal morbidity).

Cohort for severe maternal morbidity with delivery hospitalization: 
[severe-maternal-morbidity-json.txt](https://github.com/OHDSI/Atlas/files/8162184/severe-maternal-morbidity-json.txt)

There are 26k people who match this criteria on the Truven Medicare data:

![image](https://user-images.githubusercontent.com/5317244/156185552-2d24fd3a-1a44-44f3-80a7-95e7745284e7.png)

**Comment by anthonysena** [comment]
@altosaar - my advice here is check the source codes and how they map. If you are obtaining patients on one data set and are confident in the definition, then you'll need to review the individual domains (i.e. condition_occurrence) and the concepts to see where people may be falling out. This could be done by SQL directly on your CDM or by creating a simple base cohort and use inclusion rules to see the impact.

**Comment by pbr6cornell** [comment]
@jaanli  I'm going to close this out, as it doesn't appear to be an issue with ATLAS.

Your cohort definition is attempting to use a series of non-standard concepts and is looking in the standard concept fields, so I would not expect that to return back many if any persons.   Also, your cohort is about finding pregnancy-related inpatient visits, and you are looking at the Medicare data, which is age>65, so wouldn't expect to find qualifying patients in that population.  Feel free to reach out to me directly if you think there is still issue.
