### ISSUE TITLE
Bring back Dataset profiling in Atlas public instance

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#267]
This was disabled before symposium.
(e.g., view dashboard, heel report).

I mean this instance http://www.ohdsi.org/web/atlas/#/home

Are there plans to bring it back?  (I hope it will come back)

**Comment by fdefalco** [comment]
Yes - the bug that had caused us to disable it has been fixed and merged into the master branch however we have not yet published that build to the ohdsi.org.

**Comment by vojtechhuser** [comment]
bump (can this be added back?)

not there as of today


![image](https://cloud.githubusercontent.com/assets/7526119/21153828/2a096d44-c13a-11e6-8079-4e992be7ee86.png)
