### ISSUE TITLE
Display measure numeric values distribution parameters in AchillesWeb

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#268]
Achilles analysis 1815 allows data quality review (and data characterization) of measurement data.

e.g., Min and Max value for weight.

This allows data quality assesment.

Second, analysis 1807 allows browing which units are used for which measurement.

This would be useful (totally new Achilles characterizations) that would benefit EHR dataset sites.

Users could see what units are being used for which measurement.

For example Sentinel CDM requires certain measurement to use a single target unit.

**Comment by vojtechhuser** [comment]
This would also need JSON export first (if we always have to do JSON)

**Comment by anthonysena** [comment]
Closing due to age. Please see [DataQualityDashboard](https://github.com/OHDSI/DataQualityDashboard) for more information on CDM data quality.
