### ISSUE TITLE
Access restriction error is shown while initial search loading

### ISSUE THREAD

**Issue by ToGL** [OHDSI/Atlas#2686]
Atlas 2.11
WebApi 2.11

### Expected behavior
User should not see Access restriction error message while Search page initially loading

### Actual behavior
For a 20-25 seconds user see:

![Accces_denied](https://user-images.githubusercontent.com/4649532/160101413-de5da893-9788-469d-ba98-ca55e5bb57d7.PNG)

### Steps to reproduce behavior
1. Run browser in incognito mode
2. Login into Atlas 
3.  Click Search menu item

**Comment by anthonysena** [comment]
My guess is that this error is related to permissions (or lack thereof) for your account. You may require the `AtlasUsers` role assigned to your account to make this work? Can you verify?

**Comment by ToGL** [comment]
this account has AtlasUser role.

**Comment by konstjar** [comment]
Your account should have Source User role too to have access to data

**Comment by ToGL** [comment]
it has as well Source User roles (for required sources)

**Comment by anthonysena** [comment]
> it has as well Source User roles (for required sources)

That's also correct - you'll need to make sure the user has access to the data source that is providing the vocabulary daimon. Can you also verify that the priority on the vocabulary daimon is set to 1? Can you also confirm if you can access any other parts of the system or is this only the search component?

**Comment by alex-odysseus** [comment]
Closing as no longer reproduced and related to permissions configuration for a particular account
