### ISSUE TITLE
Prevalence per 1000 plot scaling

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#2694]
### Expected behavior
The prevalence per 1000 plot auto-scales to fit the data, so that the y-axis and tooltip use appropriate value scales.

### Actual behavior

A low prevalence concept shows zeroes in the y-axis and in the tooltips:
![image](https://user-images.githubusercontent.com/8037742/161863818-3f341592-ea3a-4f87-90a0-1f9bc1c114af.png)

### Steps to reproduce behavior
Find a low prevalence concept, examine its drilldown report for prevalence per 1000.

**Comment by chrisknoll** [comment]
I don't think this is an issue, I checked condition and procedure report and the y-axis has 3 digits of precision.
![image](https://user-images.githubusercontent.com/6818777/236529401-d4d20d7d-fa98-43ad-9902-ea83fdf3c39a.png)
