### ISSUE TITLE
Characterization Custom Feature - Counting Across Domains

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#2695]
I wanted to count EKGs, which is a concept set that straddles multiple domains.  I wanted to count the days that someone had an EKG and set up a custom feature like this:

![image](https://user-images.githubusercontent.com/6305439/162745413-499d9412-b8fb-45e6-8a41-12c28c90f49a.png)

Then I realized that it was going to count each domain separate.

I'm asking for a feature request where you could count across domains.  There is no urgency to this request form my side.

**Comment by chrisknoll** [comment]
This isn't going to be possible under the circe-framework for counting records (circe is always at the per-domain level when querying records, and there's no way (or plan) to query across domains.

I'd use a custom sql feature to handle this functionality.
