### ISSUE TITLE
Concept Set Description

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#271]
Would it be possible to have a Concept Set description field?  I would use this to document caveats or gotcha's to a Concept Set.

**Comment by pbr6cornell** [comment]
I think this represents a more general issue about capturing meta-data and annotations for all artifacts.  Putting a description into conceptset could be a short-term approach, but likely would require a different long-term solution.

**Comment by llhester** [comment]
I also would like to add a text box to the concept sets that would let you describe the citation for the concept set, the source codes used to create the concept set, or other notes that might inform other users why it was created.  This doesn't address Patrick's note above about a long-term solution, but might be a good short-term solution.

**Comment by pbr6cornell** [comment]
This gets to ATLAS 3.0 redesign and how we want to handle meta-data, so let's not lose the thought.

**Comment by anthonysena** [comment]
Closing in favor of #2724 which will address this enhancement.
