### ISSUE TITLE
Export Summary Statistics of a Data Source via JSON

### ISSUE THREAD

**Issue by paulnagy** [OHDSI/Atlas#2711]
The OHDSI Health Systems WG is surveying health system to assess the state of their OMOP deployment.  Would like an export button added to the Data Sources tab of Atlas looking at a specific Achilles summarization report for JSON export.  A site can use to submit the state of their OMOP.  Number of patients, overall observation date range, Number of concepts in each clinical domain as well as number of unique concepts in each clinical domain.  The Summarization report specification has not yet been finalized. Other stats such as CDM version & vocabulary version.  

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/7782463/171445685-c93e2517-ea79-4516-828c-1a45cc2288a3.png">

**Comment by chrisknoll** [comment]
All charts now support an export SVG/PNG option by hover overing the chart.
