### ISSUE TITLE
Central Cohort Definition Repository / Cohort Definition Import

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#272]
Would it be possible to connect your local ATLAS to a remote central Cohort Definition Repository next to your local install?

For example, a cohort is defined in the public OHDSI ATLAS and I can simply re-use this locally by selecting from the central repository? Can this be done my making such a central Webapi schema available over the internet?

Currently the Cohort Definition Repository is a drop-down box which suggest it is possible to have multiple, is this indeed the case?

If not, is there an interactive way to import a cohort definition in ATLAS (for example created after export from a central location). 

Thanks.

**Comment by fdefalco** [comment]
You can connect a local ATLAS installation to any accessible WebAPI installation.  For example I can run ATLAS locally and point to the public WebAPI to browse that repository.

That drop down box is not fully functional.  There was an early version of ATLAS where the intent was to provide the ability to toggle which repository you were connected to and switch between them interactively during a session.  That functionality isn't supported today as features evolved where we didn't follow through on the idea.

You can however go to the export tab of a cohort in one environment and grab the JSON for the definition, then go into the same place in another environment and paste the JSON in and hit the reload button to move a cohort definition between environments.

**Comment by PRijnbeek** [comment]
Yes, I am aware I can connect my local ATLAS to any accessible WebAPI but that is not exactly what I want. I like to have both my local and the central. It would allow us to build a central repository with conceptsets and cohort definitions I could browse and apply on my local CDM.

Good to know this is not possible.

The export and paste option is indeed a workaround. It is not very obvious from the interface this is possible though. Would an import button be something to put on the wish list for a next update?

Thanks

**Comment by anthonysena** [comment]
For consideration for Atlas 3.0 - could we enable Atlas to be multi-WebAPI aware for this use case.
