### ISSUE TITLE
Improve user tagging usability

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#2722]
### Expected behavior
A user can tag their assets (concept sets, cohorts, characterizations, IRs, pathways, etc) in batch.

### Current behavior
Our initial tagging release does not have this capability. Instead, a user needs to go to each study asset they own / have write access to and tag individually. This is cumbersome, as often a study requires many assets.

### Steps to development
We have begun development of this new enhancement for 2.12:

![image](https://user-images.githubusercontent.com/8037742/181246098-ff278f92-4ad1-408a-867d-0c9937a029d2.png)
![image](https://user-images.githubusercontent.com/8037742/181246131-e81303be-7c76-44c0-823f-92bd8e03216c.png)

**Comment by anthonysena** [comment]
Some initial thoughts here:

- When this is implemented, the "Tagging" item on the left-hand menu item should be hidden by default and optionally enabled for those that want to use the feature.

- ![image](https://user-images.githubusercontent.com/12902366/181272553-80a54e0d-69cb-4853-a2a4-f680cd499a8d.png)
- The screenshot above is a bit confusing to me as I believe the (x) in the screenshot above refers to the tag ID and I'd actually interpret this as the # of entities with the tag. Perhaps it could be formatted as "Tag Name (ID = X)" to make it clear?
