### ISSUE TITLE
Phoebe 2.0 Integration

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#2728]
### Overview

This issue tracks the features and requirements for PHOEBE 2.0 integration into Atlas.

###  Functions

1. Add a "Recommendation' tab to Concept set editors which will provide a list of suggested concepts from PHOEBE 2.0 based on the current concept set's 'included concepts'.

2. Add a sort of 'I feel Lucky' search which will take a search string in the vocabulary search, but when the user clicks the Phoebe search, the concept selected by PHOEBE will be automatically placed into a new concept set expression (with descendants selected).   The user is then redirected to the concept set editor with the 'recommended' tab selected.

### Mockups

To Be Added....

**Comment by alondhe** [comment]
@chrisknoll -- hope you don't mind, shifting to 2.12 as discussed. @anthonysena -- we'd like to hold on 2.12 to bundle this in as the lift isn't too much, but the value is huge.
