### ISSUE TITLE
Invalid Object Source_to_concept_map

### ISSUE THREAD

**Issue by nzurawski** [OHDSI/Atlas#2738]
### Actual behavior
Hello, I'm a data engineer with the Maine Health Institute for Research. We have recently installed got Atlas setup here and our analyst is running into an issue with the Concept Sets tab. In the stdout log file for Apache the error appears to be related to a non existent table in our CDM called Source_to_concept_map. Can anyone tell me what this table is supposed to be? Is it user generated? Apologies if this is a dumb question. I'm not intimately familiar with Common Data Model.
### Steps to reproduce behavior
Click on Concept Sets, choose 'Hyper Tension' and choose 'Included Source Codes
[source_to_concept_map_error.txt](https://github.com/OHDSI/Atlas/files/9376184/source_to_concept_map_error.txt)
'

**Comment by don-torok** [comment]
Check the OMOP CDM table definitions [here](https://github.com/OHDSI/CommonDataModel/tree/main/inst/ddl/5.4).  The source_to_concept_map table will be empty, which is fine, but looks like it needs to exist.

**Comment by nzurawski** [comment]
Thanks Don! I guess it's just an unnecessary table that is still referenced in the executed SQL script. Interesting. I created the table from a script in that link and that seems to have solved the issue.
