### ISSUE TITLE
Qualifying Inclusion Rules with Long Names Causes is_valid = 0 and no cohort generated

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#276]
Recently I created a cohort with two qualifying inclusion rule titles:

`Exclude DMARDs (abatacept, adalimumab, anakinra, apremilast, Auranofin, Aurothioglucose, Aurothiomalate, Azathioprine, certolizumab pegol, Cyclophosphamide,  Cyclosporine, Etanercept, golimumab, Hydroxychloroquine, infliximab, leflunomide, Methotrexate, Minocycline, mycophenolate mofetil, Penicillamine,  rituximab, Sulfasalazine, tocilizumab, tofacitinib)`

`2+ Exposures of Topical Plaque Psoriasis Treatment (Alclometasone, amcinonide, Anthralin, Betamethasone, calcipotriene, Calcitriol, Clobetasol, clocortolone, Coal Tar, Desonide, Desoximetasone, Dexamethasone, Diflorasone, Flumethasone, fluocinolone, Fluocinonide, Flurandrenolide, fluticasone, Halcinonide, halobetasol, Hydrocortisone, Methylprednisolone, Mometasone, Pimecrolimus, prednicarbate, prednisolone, Tacrolimus, tazarotene, Triamcinolone)`

In the cohort_generation_info table I see is_valid=0.

See on Janssen side:
select * 
from cohort_generation_info cgi
join [source] s on s.source_id = cgi.source_id
where id = 3368

The reason for the titles is we do not believe the individuals that we are performing studies for will review the concept sets themselves but want to ensure that the ingredients were exposed directly to them.

**Comment by chrisknoll** [comment]
@ericaVoss : the 1.4.0 release will put limits on the inclusion rule title input box to not exceed a maxlength on the IR title (on the UI side), but we didn't implement a validation check for long rule name.  Let me know if just putting a maxlen on the inclusion rule title is enough of you'd like this addressed more comprehensively.

**Comment by ericaVoss** [comment]
Has this already been addressed?  We may be able to close this ticket.

**Comment by anthonysena** [comment]
The max length on the inclusion rule title is enforced on the UI now so closing this out.
