### ISSUE TITLE
Cannot export PLP/PLE after second save

### ISSUE THREAD

**Issue by anton-abushkevich** [OHDSI/Atlas#2760]
### Expected behavior
Export works.

### Actual behavior
After firts save (creation of new asset or copy existing) of PLP/PLE export works. After any update and save export doesn't work with 500 error code.

### Steps to reproduce behavior
1. Create valid PLP/PLE and save (or crate a copy of existing one), check if export works.
2. Do any update and save.
3. Go to export tab, click export - infinite loader and 500 code from server.

**Comment by alex-odysseus** [comment]
Caused by https://github.com/OHDSI/Atlas/issues/2714
