### ISSUE TITLE
Add Concept Set preview

### ISSUE THREAD

**Issue by anton-abushkevich** [OHDSI/Atlas#2791]
Users aren’t confident with the impacts of adding/subtracting a concept to their concept set in terms of included source codes. This is only possible by opening each concept in a new tab and exploring related concepts.

Solution: add a preview button next to the Add to Concept Set button that then brings up a modal window with a preview of: expression, included concepts, included source codes, and export for the set with the newly checked concepts.

**Comment by anton-abushkevich** [comment]
The last commit 6d2376da197865986974d856532e55c16700d433 was Work In Progress, there are still issues:

1. Individual option flags in the preview window do not apply. Still need to move some logic into the concept-add-box component.
2. Need to add new parameter ("concepts") to all other uses of the concept-add-box component. Now it is only in search.js and included.js.

**Comment by chrisknoll** [comment]
Apologies,  wasn't aware it was work-in-progress, as it seemed to function properly. But thank you for catching this.

In future PRs, let's mark any PR that is in-progress as 'draft'.

**Comment by anton-abushkevich** [comment]
Sorry, I will mark PR as draft next time. Now, the PR is ready - please review.
