### ISSUE TITLE
Remove references to unsecured (http) resources

### ISSUE THREAD

**Issue by mark-velez** [OHDSI/Atlas#28]
When Atlas is deployed on a secured server (https), requests for external http resources (i.e. [css](https://github.com/OHDSI/Atlas/blob/master/index.html#L11) and [js](https://github.com/OHDSI/Atlas/blob/master/js/main.js#L26)) fail. We should always use https, right?

**Comment by chrisknoll** [comment]
I need to see the specific example, but they have 'protocol relative urls' that we can use such as:

//somehost.com/css/mycss.css

Which will use whatever protocol was used when accessing the page.

**Comment by mav7014** [comment]
@chrisknoll What is the advantage of using protocol-relative URLs over always using https?

**Comment by chrisknoll** [comment]
On sites where they have an HTTP server set up without an SSL certificate, https won't be available.  I'm not exactly sure which external http resources you mean, but for those served up by CDNs, https is probably always guaranteed, so can probably be set to https always.

**Comment by chrisknoll** [comment]
Reading further on this, this link talks about  that using protocol relative URLs as a helper to avoid those 'mixed content' messages, but has since been updated to stress using SSL for everything. So, for those external refs (css and other CDN hosted assets) we should update our refs to use HTTPS.

**Comment by mav7014** [comment]
@chrisknoll thanks for the link- will keep this in mind going forward. Should I submit a separate issue for Achilles?

**Comment by chrisknoll** [comment]
Yes, that would help us track where we need to make the change. Thanks!

**Comment by jduke99** [comment]
I am seconding this thread.  It generally is as easy as just switching to https for the references listed below.  Would be greatly appreciated as we cannot run Atlas in our environment.

![image](https://cloud.githubusercontent.com/assets/5069947/12068415/83f6b7e2-afdb-11e5-8f78-b125867b1323.png)

**Comment by jduke99** [comment]
Sorry, to save your eyeballs:

Mixed Content: The page at 'https://10.16.1.23/Atlas/#jobs' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto:400,700'. This request has been blocked; the content must be served over HTTPS.

(index):1 Mixed Content: The page at 'https://10.16.1.23/Atlas/#jobs' was loaded over HTTPS, but requested an insecure script 'http://animate.adobe.com/runtime/5.0.1/edge.5.0.1.min.js'. This request has been blocked; the content must be served over HTTPS.

require.js:34 Mixed Content: The page at 'https://10.16.1.23/Atlas/#jobs' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-1.11.2.min.js?bust=1451596961614'. This request has been blocked; the content must be served over HTTPS.

**Comment by anthonysena** [comment]
All references are now using SSL. This is undergoing testing now and will be part of a formal release at the end of this month.
