### ISSUE TITLE
Add CSV file code list comparison against concept set

### ISSUE THREAD

**Issue by anton-abushkevich** [OHDSI/Atlas#2800]
Adjust the concept set comparison tool to allow for comparison of source concepts with the CSV file.

CSV file would need to have a structure: concept_code, vocabulary_id, concept_name

**Comment by anthonysena** [comment]
From discussion: this feature would be useful for helping to identify those codes that are missing in the vocabulary. It fills the gap whereby we cannot construct a concept set since there may be 1 or more concepts that are not yet in the vocabulary. .
