### ISSUE TITLE
What version of node?

### ISSUE THREAD

**Issue by jcabrerazuniga** [OHDSI/Atlas#2802]
Node versions evolve and sometimes somethings became obsolete. For instance, it is important to indicate the version of node needed to be used to compile Atlas in the documentation and this can not be found.
Can you please tell me the recommended version of node used to compile Atlas?

Thanks

**Comment by anthonysena** [comment]
Always assume to use the latest version of Node and if this does not work, please open an issue with that specific version. Thanks!
