### ISSUE TITLE
Add Achilles drilldown reports to Concept / Concept Set pages

### ISSUE THREAD

**Issue by anton-abushkevich** [OHDSI/Atlas#2805]
The concept and concept set pages lack any practical time series statistics. These statistics can only be viewed in Data Sources; and in the case of concept sets, this information can’t be accurately pulled for the concept set.

1. Add Data Sources time series and charts to concept pages, so that users can drill down into these insights while examining concepts.
2. For concept sets, add an “Explore Time Series” tab that allows a user the ability to generate time series information for the concept set as a whole, against the CDMs available.
3. The execution may span multiple CDM clinical tables (e.g. condition occurrence, drug exposure, etc, based on the domains of the concepts).
4. The charts would be same as drilldowns in Data Sources – Prevalence by gender and year; prevalence by month; and age at first occurrence box plots, by gender.

**Comment by chrisknoll** [comment]
This is the 'explore time series' graph for a concept set that has multiple concepts in it:
![image](https://user-images.githubusercontent.com/6818777/209171660-6ff41cfc-5b2e-4c67-a283-44519850dcf6.png)

Can you explain how this graph is constructed?  There are multiple concepts with different time-series statistics, but only one  line in the graph, is there some sort of averaging happening with the statistics?
