### ISSUE TITLE
Characterization - Custom Feature - "Copy Analysis SQL Template to Clipboard"

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#2812]
### Expected behavior
That regardless if I own a feature, I can copy the SQL to clipboard.

### Actual behavior
I can only copy the SQL if I own the feature

Someone else's feature:
![image](https://user-images.githubusercontent.com/6305439/208495332-2c7d9c59-2597-43f8-ab85-27bd9ad9f758.png)

My own feature:
![image](https://user-images.githubusercontent.com/6305439/208495762-909b7c53-8b76-4022-b8ac-22af90ae1afd.png)

### Steps to reproduce behavior

1. Navigate to "Characterizations"
2. Search "feature Analyses" for a custom feature that you do not own, made through SQL not the GUI
3. The "Copy Analysis SQL Template to Clipboard" button is greyed out.

**Comment by katy-sadowski** [comment]
+1!  Also, for other people's features, scroll is disabled in the SQL text box so we can't see the full SQL code.
