### ISSUE TITLE
npm run build builds dev version

### ISSUE THREAD

**Issue by nzurawski** [OHDSI/Atlas#2816]
### Expected behavior
npm run  build to build v2.12 stable release
### Actual behavior
npm run build builds V2.13DEV
### Steps to reproduce behavior
I first used git clone to download the latest release and then ran npm run build and got the dev version. I then downloaded the zip file directly from release page and opened CDM from that directory, npm run build still resulted in the dev version.

**Comment by anthonysena** [comment]
If you need to build a specific version of the project, please clone the project and checkout by tag: `git checkout tags/<tag number>` and then you can build that released version.
