### ISSUE TITLE
Concept drilldown report calls concept record count for all configured sources

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#2819]
### Expected behavior

When navigating to a concept and clicking the 'drilldown' report, it loads the drill down report for the selected (default) source without requesting record counts. 

### Actual behavior

When navigating to a concept and clicking the 'drilldown' report, it loads the drill down report for the selected (default) source AND requests all record counts for all configured sources with a results daimon. 

### Steps to reproduce behavior

Using the latest build of Atlas (v2.13), you will see this behavior:

![image](https://user-images.githubusercontent.com/12902366/215211415-a825393f-f502-44da-a6f7-9e5888160966.png)

**Comment by anthonysena** [comment]
Also related: OHDSI/WebAPI#2187 - this behavior is throwing a number of errors and it seems to be related to the problem described in that issue.

**Comment by chrisknoll** [comment]
Not exactly related:   I think the errors we see in your screenshot are that the record count table is not built on those datasources.   The main problem here is that getRecordCount is being called on each source when we look at a drilldown report.
