### ISSUE TITLE
export of pathways via png or svg not working

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#2823]
Sorry they did eventually download but it took over 5 minutes. Apologies for this post. 

### Expected behavior
click the png or svg button on a pathway and the graphic exports and downloads

### Actual behavior
click the png or svg button on a pathway and the page freezes and eventually displays page unresponsive box, see attached; if wait is clicked it results in the same behavior
[pathwaysexport.docx](https://github.com/OHDSI/Atlas/files/10546396/pathwaysexport.docx)
### Steps to reproduce behavior
go to a generated pathways and click the png or svg button to export

**Comment by chrisknoll** [comment]
Based on the visualization, the export could take a long time. We have taken steps to try to optimize the 'css-lookup' overhead, but there are limits to how far we can go. For now, it does work, tho it some cases will take a long time.

For a future task, we can revisit these sorts of issues in a performance optimization push.
