### ISSUE TITLE
SQL Export template error on new Cohort

### ISSUE THREAD

**Issue by anton-abushkevich** [OHDSI/Atlas#2825]
### Expected behavior
No errors.

### Actual behavior
![изображение](https://user-images.githubusercontent.com/765539/216038392-a0453a26-9f90-4877-a6bc-b2b220e7fe04.png)

### Steps to reproduce behavior
Create new cohort, observe console log.

**Comment by chrisknoll** [comment]
There is another issue related to this function, that we may be able to extend this issue to cover:

When you select other sources from the dropdown, the input boxes don't populate with the values of cdmschema, etc.   I haven't looked closely a tthe code but what is surprising to me is that the text boxes for each of the paramaters is dynamically built based on what tokens are found in the SQL....but how does the values in the SOURCE map over to the tokens found in the SQL? Seems like this couldn't be done...unless you somehow hard coded that the token 'cdmdatabaseschema' maps over to the cdm schema in the source.

Steps to reproduce:
1. Go to sql export
2. Turn on checkbox that will make the replacements from th etextbox
3. select a source to populate the input boxes based on the values from the Source.

**Comment by anton-abushkevich** [comment]
You're right, there is a map: https://github.com/OHDSI/Atlas/blob/master/js/components/utilities/sql/sqlExportPanelConfig.js. It maps parameter names to daimon types (https://github.com/OHDSI/Atlas/blob/master/js/pages/configuration/sources/source-manager.js#L39).

**Comment by chrisknoll** [comment]
Excellent, I will check this as soon as I am able.  Thank you.
