### ISSUE TITLE
Generate UI Default Behavior

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#2828]
### Expected behavior
Before the update, people were used to seeing all datasources so they could scroll through a list to find source to generate on

### Actual behavior
Now it is in a paged table, so people have to click next-next-next or type in each specific source (in filter) to navigate to Non-GENERATED sources.

### Steps to reproduce behavior

Go into an environment with many sources (we have 73) and navigate to the 72nd one in the list.

### Potential solutions

For backwards compatibility, it seems it should be showing all records in the table by default.
For flexibility, maybe we need an Atlas config param (in config-local.js) that lets each site set their own 'default page size' of the generation list so that those that like 10 per page can set it to 10, others that like all can set 100.

**Comment by anthonysena** [comment]
This can be controlled through configuration and closing this out.
