### ISSUE TITLE
Error when view empty result tab on Pathways

### ISSUE THREAD

**Issue by ttemnikova** [OHDSI/Atlas#2837]
### Expected behavior
When the target cohort of a pathway analysis has 0 patients, the pathway generation results should contain empty tables
### Actual behavior
The tables are not shown properly because of the error in the browser console:
```bundle.js?build=219:1 Uncaught TypeError: Unable to process binding "if: function(){return reportData }"
Message: Cannot read properties of undefined (reading 'targetCohortCount')
    at bundle.js?build=219:1:6455727
    at Array.map (<anonymous>)
    at PathwayTableview.value (bundle.js?build=219:1:6455579)
    at bundle.js?build=219:1:6455268
    at Function.Uc (bundle.js?build=219:1:30384)
    at Function.Vc (bundle.js?build=219:1:30155)
    at Function.U (bundle.js?build=219:1:29975)
    at Function.ua (bundle.js?build=219:1:30986)
    at Function.Y (bundle.js?build=219:1:22610)
    at Function.yc (bundle.js?build=219:1:29655) 
```
### Steps to reproduce behavior
1. Create a cohort with 0 patients in result
2. Create a pathway analysis with this cohort as target cohort (my example: [pathway_with_0_patients_target_cohort.txt](https://github.com/OHDSI/Atlas/files/10885673/pathway_with_0_patients_target_cohort.txt))
3. Generate the analysis
4. When it finishes, open the results and switch to Tabular view

Connected with #2832

**Comment by chrisknoll** [comment]
This is marked as fixed in master. What version are you running?

**Comment by alex-odysseus** [comment]
Probably it was merged to 'master' later, we are on 'https://github.com/OHDSI/Atlas/tree/rc-2.13.0'

**Comment by ttemnikova** [comment]
Works with the fix
