### ISSUE TITLE
Implement LDAP using TLS

### ISSUE THREAD

**Issue by bskrade** [OHDSI/Atlas#2848]
We have installed Atlas on our server at the Medical College of Wisconsin using Broadsea. We would like to implement single sign on. However, MCW-IS requires the use of TLS certificates in our LDAP service. Is it possible to add an option for LDAP using TLS?

Some example java code can be found here:
https://docs.oracle.com/javase/jndi/tutorial/ldap/ext/starttls.html

**Comment by konstjar** [comment]
You can use SAML to realise the SSO. TLS certificates should be generated by your organisation. It's not related to application.

**Comment by anthonysena** [comment]
Closing this out due to age and based on the response by Konstantin. Please re-open if you feel there are enhancements required to support the TLS authentication.
