### ISSUE TITLE
Uncaught TypeError: ko.i18n is not a function

### ISSUE THREAD

**Issue by m0nhawk** [OHDSI/Atlas#2851]
### Expected behavior
* Atlas loads properly

### Actual behavior
* Atlas stuck at loading screen with the following error in the console. The place in question is usually different, e.g. [`js/components/cohortbuilder/options.js`](https://github.com/OHDSI/Atlas/blob/master/js/components/cohortbuilder/options.js), [`js/pages/cohort-definitions/const.js`](https://github.com/OHDSI/Atlas/blob/master/js/pages/cohort-definitions/const.js) or some other.

```
Uncaught TypeError: ko.i18n is not a function
    at Object.<anonymous> (const.js:6:19)
    at Object.execCb (require.js:29:390)
    at Z.check (require.js:18:423)
    at Z.enable (require.js:23:330)
    at Z.init (require.js:17:68)
    at E (require.js:14:185)
    at Object.completeLoad (require.js:28:219)
    at HTMLScriptElement.onScriptLoad (require.js:30:10)
```

### Steps to reproduce behavior
1. Load using Chrome (Version 112.0.5615.49) and Atlas (2.12.0), somehow it doesn't happen every time, and mostly happen to new users and old returning users.

---

I would appreciate any ideas on why it's happening and how to debug (and provide more information), but that was a frustrating issue to caught.

**Comment by chrisknoll** [comment]
This is a race condition:  the dynamic loader is fetching the dependencies, but something is assuming the i18n plugin has been loaded, without declaring it a dependency.  

We have some bootstrap dependencies that can be loaded, and the i18n one should be part of it. I will take this on and report back when a patch is available.

**Comment by chrisknoll** [comment]
Could you try [this PR](https://github.com/OHDSI/Atlas/pull/2852) on your local env and see if that resolves it for you?
