### ISSUE TITLE
Achilles heel report enhancements

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#286]
It would be helpful if sample sizes could be included on the Achilles heel report for each notification, error, warning. 

![image](https://cloud.githubusercontent.com/assets/11822115/20439366/233e251e-ad89-11e6-92b2-bafe8385cb3f.png)

Credit to @fdefalco for identifying this issue.

**Comment by vojtechhuser** [comment]
Look at the table ACHILLES_RESULTS_DERIVED.  The output from Heel is not "richer" than just one text column in a single table. (see also Achilles DQ issues)

**Comment by vojtechhuser** [comment]
Add more columns to the current report.

Current:
![image](https://user-images.githubusercontent.com/7526119/33959691-50207ff8-e016-11e7-819a-4ea64b161418.png)


add column rule_id and the count value column. Also hyperlink or hover over can be displayed from rule description file here https://github.com/OHDSI/Achilles/blob/master/inst/csv/achilles_rule.csv

**Comment by t-abdul-basser** [comment]
Excellent suggestion @vojtechhuser. We need this also.

**Comment by pbr6cornell** [comment]
I'm moving this to ATLAS 3.0, though I suspect it will be superseded by the DQDashboard work that @alondhe and Clair are leading.

**Comment by anthonysena** [comment]
Closing due to age. Please see [DataQualityDashboard](https://github.com/OHDSI/DataQualityDashboard) for more information on CDM data quality assessment.
