### ISSUE TITLE
Question: For cohorts that occur when running pathway

### ISSUE THREAD

**Issue by dongyun909** [OHDSI/Atlas#2866]
Question
When running PATHWAY, is it possible to know where the cohorts that are generated are stored in the CDM table?
Also, if cohorts are already generated in ATLAS, will PATHWAY run without generating any additional cohorts (i.e. will PATHWAY refer to the generated cohorts when it runs)?

Actual behavior
there was a problem that cohort generation took too long when using national population data.

**Comment by chrisknoll** [comment]
When running the pathway analysis, we will use cached results (stored in results.cohort_cache) to copy over to temp tables used in Pathway analysis.   If cohorts are already generated in ATLAS, they will be cached, and therefore re-used in pathway execution.
