### ISSUE TITLE
ATLAS Timeout

### ISSUE THREAD

**Issue by lsq324324** [OHDSI/Atlas#2883]
### Steps to reproduce behavior
Number of records, number of offspring records timeout can not display the data why
![image](https://github.com/OHDSI/Atlas/assets/140598387/ef9f1e56-86d0-490e-9949-4677158a24c3)

**Comment by bskrade** [comment]
I am having the same problem on Atlas v2.13.0 displaying concept counts in Search and Concept Sets. I did see in the forums you recommended running the code to populate the achilles_results_concept_count table. I ran the code and there is data in the table. I cleared the server cache and my browser cache. I am still seeing the problem.

**Comment by alondhe** [comment]
Check your webapi logs - does it error on this?

**Comment by anthonysena** [comment]
Closing this out due to age - if you are still experiencing issues, please re-open this issue and as mentioned, please share the webapi logs. Most likely your concept record count cache is not properly built and stored in the WebAPI DB for some reason.
