### ISSUE TITLE
Altas does not start. Error ko.i18n is not a function

### ISSUE THREAD

**Issue by apopassias** [OHDSI/Atlas#2885]
![image](https://github.com/OHDSI/Atlas/assets/146077107/0ac92b87-87fa-4265-b57d-8c45cf8730c1)

Any ideas?

**Comment by prgueza** [comment]
This happens to us randomly, and my best guess is that the order in which require is loading the different modules is arbitrary and in some (many) occasions the module that injects the i18n function into knockout is not yet loaded when these function runs.

The file where this i18n function is injected into knockout is the `js/extensions/bindings/i18nBinding.js` ([here](https://github.com/OHDSI/Atlas/blob/596cde6c992367670029c2cc16a14a2c0f3d5c58/js/extensions/bindings/i18nBinding.js#L3C3-L3C51)). This module is loaded via the `js/extensions/bindings/main.js` module that theoretically is aliased as the `databindings` package in the `settings.js` file [here](https://github.com/OHDSI/Atlas/blob/596cde6c992367670029c2cc16a14a2c0f3d5c58/js/settings.js#L12C1-L13C35). There is however a comment in the `js/extensions/bindings/main.js` file that says "// is this being loaded? doesn't seem like it", so I don't really know what to think.

I'm no expert in knockout nor the require module loader, but I hope this sheds some light on the issue and helps someone who knows what they are doing solve it.
