### ISSUE TITLE
Cohort definition editor loads full list of concept sets multiple times

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#2887]
### Expected behavior

When the cohort definition editor opens, the only requests made to WebAPI are the ones necessary to set up the editor

### Actual behavior

When loading a cohort definition, there is a call to the `WebAPI/conceptset/` endpoint which loads the full list of concept sets in the WebAPI database for each concept set present in the cohort definition. 

### Steps to reproduce behavior

Load a cohort definition with > 0 concept sets. Observe the network trace via Google Chrome developer tools:

![image](https://github.com/OHDSI/Atlas/assets/12902366/18415bb7-a5d6-46ba-a696-0bbd54cdb29b)

The screenshot above shows 5 calls to `WebAPI/conceptset/` which is the number of concept sets in my cohort definition entry event section. If you open an inclusion rule with > 0 concept sets, `WebAPI/conceptset/` is once again called for each concept set present in the inclusion rule.

**Comment by chrisknoll** [comment]
I think this is used to update the concept names or standard/non-standard status of concepts? I'd have to see where the UI makes the call and how the result is used (such as: does it take the result of conceptset/ and update the embedded concept set expression.
