### ISSUE TITLE
Atlas Demo not working

### ISSUE THREAD

**Issue by sasutils** [OHDSI/Atlas#289]
The Atlas Demo site at http://www.ohdsi.org/web/atlas/ does not appear to be working.
Is this an issue that is impacting everyone? Or is it specific to my connection attempts? For example perhaps my company is blocking ports that it uses?

**Comment by Sigfried** [comment]
It's working for me.

**Comment by leeevans** [comment]
It is currently available.  A simple way to test if it's blocked by your company network is to try to browse to it using your phone.
