### ISSUE TITLE
Generate button doesn't indicate that an Incidence Rate Analysis is running

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/Atlas#2904]
### Expected behavior
When I click the blue Generate button to run an Incidence Rate analysis, it changes color and has a spinning wheel to indicate that the analysis is running.  It stays this way until the analysis has completed.

### Actual behavior
Nothing happens to the Generate button when I click it (and it is possible to click it again).  The duration field does populate with "00:00:00:00", and eventually the Started datetime will appear.  When the analysis completes the duration updates and the results appear.   

### Steps to reproduce behavior
Open an Incidence Rate analysis, navigate to Generation tab, click Generate button for a data source.

**Comment by katy-sadowski** [comment]
I think this also means it's not possible to cancel a running IR analysis from the UI.

This is ATLAS v2.14.1, btw.

**Comment by anthonysena** [comment]
Thanks @katy-sadowski - I've confirmed that this is indeed a bug.

**Comment by ericaVoss** [comment]
I am seeing this as well (although I guess if @anthonysena already said it, it didn't need to be said ^_^)
