### ISSUE TITLE
Atlas never loads and struck in the same state (attached screenshot) forever

### ISSUE THREAD

**Issue by hkamineni** [OHDSI/Atlas#2932]
Hello All, 
Please help to resolve the following issue. Thanks for your help.
Hari
### Expected behavior
I expect Atlas to load. But it struck forever to load.
### Actual behavior
![Atlas_screenshot](https://github.com/OHDSI/Atlas/assets/165437054/40928c31-7aa5-41ed-ae9d-e70423f7faa5)

The following is the result of http://localhost:8080/WebAPI/source/sources
[{"sourceId":1,"sourceName":"My Cdm","sourceDialect":"sql server","sourceKey":"MY_CDM","daimons":[{"sourceDaimonId":1,"daimonType":"CDM","tableQualifier":"cdm","priority":0},{"sourceDaimonId":2,"daimonType":"Vocabulary","tableQualifier":"cdm","priority":1},{"sourceDaimonId":3,"daimonType":"Results","tableQualifier":"results","priority":1},{"sourceDaimonId":4,"daimonType":"Temp","tableQualifier":"temp","priority":0}]}]

I have sql server for CDM/Vocabulary and postgres for WebAPI.

I used the following sql statements to populate source and souce_daimon tables.

INSERT INTO webapi.source (source_id, source_name, source_key, source_connection, source_dialect,username,password) 
VALUES(1, 'My Cdm', 'MY_CDM', 'jdbc:sqlserver://localhost:1433;encrypt=false;integratedSecurity=false,trustServerCertificate=true','sql server','ohdsi_app_user','app1');

INSERT INTO webapi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) 
SELECT 1, source_id, 0, 'cdm', 0
FROM webapi.source
WHERE source_key = 'MY_CDM'
;

INSERT INTO webapi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) 
SELECT 2, source_id, 1, 'cdm', 1
FROM webapi.source
WHERE source_key = 'MY_CDM'
;

INSERT INTO webapi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) 
SELECT 3, source_id, 2, 'results', 1
FROM webapi.source
WHERE source_key = 'MY_CDM'
;
INSERT INTO webapi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) 
SELECT 4, source_id, 5, 'temp', 0
FROM webapi.source
WHERE source_key = 'MY_CDM'
;

**Comment by chrisknoll** [comment]
It looks like it didn't find one of the external libraries (d3.js) when it started up the app.

Did you follow the [Atlas Setup Instructions](https://github.com/OHDSI/Atlas/wiki/Atlas-Setup-Guide#atlas-installation)?

To download the dependencies, you run:
```
npm run build
```

This requires you have node.js installed, which is indicated in the Prerequisites section.

**Comment by hkamineni** [comment]
Chris:
Thanks for your quick response. Yes, I did follow the installation
instructions  for Atlas. I did install nodejs and ran npm build command.
After npm run build and
few iterations of npm audit fix i got the following. Is there anything else
I should be doing to fix these errors? Thank you.
Hari
c:\Git\OHDSI\Atlas>npm audit fix

up to date, audited 412 packages in 2s

26 packages are looking for funding
  run `npm fund` for details

# npm audit report

moment-timezone  0.1.0 - 0.5.34
Severity: moderate
Command Injection in moment-timezone -
https://github.com/advisories/GHSA-56x4-j7p9-fcf9
Cleartext Transmission of Sensitive Information in moment-timezone -
https://github.com/advisories/GHSA-v78c-4p63-2j6c
fix available via `npm audit fix`
node_modules/moment-timezone
  eonasdan-bootstrap-datetimepicker  >=4.17.42
  Depends on vulnerable versions of moment-timezone
  node_modules/eonasdan-bootstrap-datetimepicker

2 vulnerabilities (1 low, 1 moderate)

To address all issues, run:
  npm audit fix

**Comment by chrisknoll** [comment]
After you confirmed npm run build ran,  can you check if there's a folder in your atlas root: node_modules/d3/build which should contain d3.js.  After all that is there, you should be able to reload atlas and check for errors again. If it says it can't find the d3.js file, there's some local problem with your environment that's preventing it from downloading.

**Comment by hkamineni** [comment]
I have C:\Git\OHDSI\Atlas\node_modules\d3 folder., but there is no build directory under it. I have dist, node_modules, src directories and LICENCE, package.json and README files. Thats all i have under d3 folder.

**Comment by hkamineni** [comment]
ATLAS v2.14.1 is the version I have installed.

**Comment by chrisknoll** [comment]
The problem is the modules aren't being instaled in an expected way.

This is what is on my filesystem under node_modules/d3:
![image](https://github.com/OHDSI/Atlas/assets/6818777/96aeb7d5-07d4-4e31-8e48-bf2a5f7b0294)

When you do an npm build, it should also produce a package-lock.json indicating the specific version of d3 installed like this:

```
        "d3": "4.13.0",
        "d3-scale-chromatic": "1.5.0",
        "d3-tip": "0.9.1",
```

Can you check that as well?

**Comment by hkamineni** [comment]
[image: node_modules_d3- folder.PNG]

**Comment by hkamineni** [comment]
Chris:
I don't see what you see. build directory is missing..

**Comment by hkamineni** [comment]
Chris:
Can you suggest ATLAS and nodejs version combinations that worked for you?
I will try that to make sure there are no other issues in my environment.
Thanks for your help.

**Comment by hkamineni** [comment]
Chris:
It looks like we simply need to download and unzip the atlas.zip
<https://github.com/OHDSI/Atlas/releases/download/v2.14.1/atlas.zip>
into C:\tomcat\webapps.
npm can't be run on this because package.json does not exist. I have been
trying to use Source code
<https://github.com/OHDSI/Atlas/archive/refs/tags/v2.14.1.tar.gz>
(tar.gz) <https://github.com/OHDSI/Atlas/archive/refs/tags/v2.14.1.tar.gz>
to run npm run build and it's been failing. With simply unzipping atlas.zip
in webapps folder, the atlas screen came up fine.  I am trying to install
Atlas first time and
has been following the installation instructions. Let me know if my
observation here is right. Thanks for your help.
Hari
