### ISSUE TITLE
user-defined temp schema in SQL server dialect

### ISSUE THREAD

**Issue by jgholap** [OHDSI/Atlas#2973]
### Expected behavior

We are trying to set up a custom user-defined temporary schema for storing temporary tables created by atlas.  our OMOP CDM is hosted on Azure Synapse and it supports temporary tables however we prefer to use a custom temporary schema to store these tables instead. Luckily this is supported feature as per existing documentation.  https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration

### Actual behavior
Atlas still uses temporary tables (created by default SQL engine that are named after #) and does not utilize a custom user defined temporary schema for storing temp tables.

**Comment by konstjar** [comment]
As it's said in the documentation `Additionally, WebAPI also utilizes a schema for temporary storage of information when performing certain analyses. To support this work, a temp schema is established that enables the WebAPI to create/drop temporary tables.`

Even though the schema is `temp` WebAPI does not keep created tabled there. It's per design. It's not related to a specific database dialect. It applies to all dialects.

**Comment by chrisknoll** [comment]
That's correct. this is a function of SqlRender.  You may ask on the SqlRender repo if it's possible to force permeant tables during translation, but I doubt this will be accepted as it would be a significant re-write for how the translation rules work.
