### ISSUE TITLE
Not handling empty inclusion rules 

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#299]
A cohort definition with an empty inclusion rule will cause the generation process to fail since the SQL generated is invalid. We should either check this when saving and prompt the user to fix it or do this type of validation before generation.

**Comment by chrisknoll** [comment]
I've pushed a fix into OHDSI/WebAPI#155 so that it will execute properly, but it might be worth putting some sort of UI warning in Atlas that this is happening.  Maybe this issue can be about UI notification and the OHDSI/WebAPI#155 about handling the backend.
