### ISSUE TITLE
Cohort Definition Inclusion Rule UI Enhancements

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#302]
Hi,

A few feature requests that would be nice to have in ATLAS would be: 

1. in the text view window the description fields from the inclusion rules could be captured 
2. if before a cohort is generated can there be a check to confirm that the inclusion rule titles are 255 chars or less and if they are not then highlight them so they can be shortened?  
3. can a feature be added to include more than 64 inclusion rules? 

tagging @ericaVoss @fdefalco @anthonysena @chrisknoll

**Comment by chrisknoll** [comment]
Hi, I can work on these.  Except for item 3:  in order to do the inclusion rule intersection report, we use a bitmap which is limited to a 64-bit integer.  The work around is to collapse different inclusion rules in to a single AND .. AND... AND rule to keep the number of rules below 64.
