### ISSUE TITLE
cancel generation of a cohort

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#304]
Is it possible to have a way to cancel generation of a cohort after it has started vs. waiting for the process to complete?  
@ericaVoss @fdefalco @chrisknoll

**Comment by alondhe** [comment]
Just one thing to consider: we'd need to be mindful of how clean each database platform handles killing running queries. It gets really messy in Microsoft PDW, causing cluster instability. It seems to be fairly clean in Amazon Redshift and SQL server. Does anyone know the impact of killing queries in other platforms?

We also should consider who should be able to terminate cohort generations. I'm thinking it should be limited to certain role types once shiro is in place.

**Comment by pbr6cornell** [comment]
I see the value here, so +1 on the idea, but as @alondhe points out, I don't have a good sense of the impact on each infrastructure, so would have to defer to our implementation team about the feasibility of this.

**Comment by anthonysena** [comment]
Closed by https://github.com/OHDSI/WebAPI/issues/430

**Comment by pavgra** [comment]
I want to re-open it until the https://github.com/OHDSI/WebAPI/pull/606 is not merged

**Comment by anthonysena** [comment]
Closing now that OHDSI/WebAPI#606 is closed.
