### ISSUE TITLE
Selection pre-defined Concept-sets from within Cohorts builder

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#315]
When building a Cohort-definition in Atlas, we need to define 'New Concept Set'. Would like to reuse previously defined 'Concept Set'.

Potential solution: currently there are two buttons under tab Concept Sets in Cohort builder - 'New Concept Set' and 'Export All Concept Sets to CSV'. Add new button, 'Pre-defined Concept Set' - that allows us to copy (or reference) previously defined concept-sets.

Thanks

**Comment by chrisknoll** [comment]
This is already handled.  When you start a cohort definition, within a criteria is a dropdown of loaded concept sets, and an 'add' button that will let you load a concept set from the repository.

After you have added a new concept set (either by loading from the repository or creating a new one local to the cohort definition) it will be in the dropdown list of concept sets which allows you to refer to the same concept set in multiple places.

Closing this as a discussion ticket. Feel free to add any questions you have.

**Comment by gowthamrao** [comment]
[Atlas enhancement request.pdf](https://github.com/OHDSI/Atlas/files/737573/Atlas.enhancement.request.pdf)

Thank you @chrisknoll  

I could not find that feature in v1.4. I dont think there is an 'add' button - please see attached, the experience i have.

**Comment by pbr6cornell** [comment]
On your second screenshot, the Add button is in green, to the right of the
dropdown that says 'Any procedure'.

**Comment by gowthamrao** [comment]
Thank you @pbr6cornell @chrisknoll  - thank you. Well - the 'Add' button only reference the concept-sets defined in the cohort-builder. It does not allow reusing the concept-sets. 

Will email you - maybe we do a five min screen share + phone call?

**Comment by chrisknoll** [comment]
Clicking the add button will bring up a dialog window, with the option to choose a local cohort definition concept set, or you can change the dropdown to select from the concept set repository.

One element of confusion is that the add button gives you the option of referencing the cohort definitions that are in the dropdown in the criteria editor, and also a way to see the cohort definition's concept sets the dialog (it shows you the same list in both the dialog and the dropdown). I'm thinking the dialog that opens should be only for choosing concept sets that were saved in the repository: ie: you only click add when you don't see what you need in the dropdown list.

@gowthamrao , if you think that this cleanup will eliminate some of the confusion, I can open an issue to address it.

**Comment by gowthamrao** [comment]
Yes -- changing the current default behavior will clean it up and avoid confusion. Please make it such that the current add button and corresponding window is only needed to physically copy from 'concept set repository'. Also changing the name on the button from just 'add' to 'retrieve from concept set repository'  will further clarify. 

On the same lines

Second enhancement request: There may be a name clash. If a concept set such as hysterectomy is defined using concept sets tab of cohort definition - and subsequently another concept set, also called hysterectomy is physically copied from concept-set-repository; the second may over write the first? So an alert is needed.

Third: if someone defines hysterectomy as a new concept-set in cohort definitions concept-set tab; some form of dynamic search results appear in concept-set tab that shows the concept-set repository may make it easier and allow for easier reuse of concept-sets from concept-set-repository.

Fourth: this process allows for governance and reproducibility. In v2.0+ when we have role-based-permissioning; a governance may be created to concept-set-repository for curated concept-sets. If a user selects a governed curated concept-sets from the repository, those should appear blue color font in cohort definition, compared to red color font for those concept-sets not in repository. This is similar to the standard and non-standard concepts. 

This adds to our strategy of creating a phenotype library.

**Comment by chrisknoll** [comment]
Hi, @gowthamrao , these are all great suggestions, but should go into separate issue requests.  If you would: please open separate issues and copy the text above for each of your issue into separate requests.  In addition, it's helpful to describe the use case for each of the requests, the problem it's solving, and user-interface suggestions for implementation.
