### ISSUE TITLE
Concept-sets name - improving user-experience and adoption of concept-set-repository

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#317]
If a concept set such as hysterectomy is defined using concept sets tab of cohort definition - and subsequently another concept set, also called hysterectomy is physically copied from concept-set-repository; the second may over write the first? 

Add following features:
1. Provide an alert to user when there is a name clash - alerting user that locally-defined concept-set matches similarly defined concept-set in concept-set reposistory
2. If someone defines hysterectomy as a new concept-set in cohort definitions concept-set tab; some form of dynamic search results appear in concept-set tab that shows the concept-set repository may make it easier and allow for easier reuse of concept-sets from concept-set-repository.
3. this process allows for governance and reproducibility. In v2.0+ when we have role-based-permissioning; a governance may be created to concept-set-repository for curated concept-sets. If a user selects a governed curated concept-sets from the concept-set-repository (and from certain user - e.g. admin), those should appear blue color font in cohort definition, compared to red color font for those concept-sets not in repository. This is similar to the standard and non-standard concepts.

**Comment by chrisknoll** [comment]
To answer your question: when you load a concept set into a cohort definition from the repository, it gets assigned a new local identifier.  You can see this identifier on the concept set list view in the first column. If you imported the same concept set 3 times, you'd have 3 concept sets with the same name, but each with their own IDs.  Granted this is a confusing state to be in, but usually the reason for this is that you take a broad concept set, import it a few times and adjust them accordingly for the specific use case.  

But, I think it make sense to prompt for a new name in the concept set when one is loaded from the repository with the same name as one inside the cohort definition.

For 2) above, I'm not sure how to address this, but I think the workflow in this case is:  they click the 'add' button to browse the concept set repository, and when they do not find something that they need, they can click the 'new concept set' button at the top to start a new concept set.  Note: this only creates that concept set in the cohort definition, it doesn't send it back to the repository for others to use.  (This could be a different feature request).

For 3), this sounds like a separate issue that would need more follow up:  incorporating role-based security and applying colors to concept set items to represent those concept sets that are in the repository and those in the local cohort definition.

**Comment by gowthamrao** [comment]
You ideas for changes makes sense for 1 and 2. If we can do it, that would be great

**Comment by pbr6cornell** [comment]
I agree that allowing two conceptsets to have the same label can be quite confusing (and I can attest that it has led me to make errors before), so if we can do something to eliminate that, I think that'd be a good fix for 2.8.
