### ISSUE TITLE
Index event selection based on calendar date

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#322]
Quality measures, such as HEDIS, often construct cohorts based on a calendar date  (ex:  all persons enrolled as of 31Dec2015), and then use that index date to apply additional criteria (e.g.: age > 18 as of 31Dec2015, had at least one occurrence of condition/drug/procedure in the 365d prior to 31Dec2015, etc.).

Currently, the cohort definition does not allow an arbitrary index date to be assigned, but instead cohort definitions are anchored on some occurrence of a clinical observation.    Here, the clinical observation of interest is the OBSERVATION_PERIOD record (find the observation period that spans the desired index date), but we need to specify the cohort_start_date rather than applying the observation_period_start_date.

**Comment by chrisknoll** [comment]
User specified start and end dates for cohorts are provided through the Observation Period criteria.

Please re-open this if that feature does not address this issue.
