### ISSUE TITLE
Create label and create a way to clearly delineate a criteria group

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#324]
Create an optional label for groups in Atlas
e.g. in Quality measures criteria are complex but are related
**1. Criteria group - Label:** Continuous enrollment criteria. Should have atleast 300 days in 365 days of coverage in a calendar year, seperately applied to 3 calendar years.
**2. Demographic criteria - Label:** - Females who are between 52 to 74 on December 31st of measurement year

Justification: Helps visually understand and track complex cohort-rules

**Comment by pbr6cornell** [comment]
More broadly, the notion of 'more effective labeling' in analysis designs and analysis reporting is something we should consider in ATLAS 3.0.

**Comment by anthonysena** [comment]
Closing due to age and the fact that inclusion rules can contain descriptions to satisfy the idea captured here.
