### ISSUE TITLE
Provide more explicit error in violating naming of concept sets

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#325]
### Expected behavior
Raise error stating that illegal characters cannot be included for example "/"
### Actual behavior
Error message: "An error occurred while attempting to load the concept from your currently configured provider. Please check the status of your selection from the configuration button in the top right corner."
### Steps to reproduce behavior
Create a concept set and include "/"

**Comment by chrisknoll** [comment]
Excellent issue report, @jhardin29 , thank you.

**Comment by jhardin29** [comment]
Thanks for creating the issue template headers, very explicit and helpful!

**Comment by anthonysena** [comment]
Reserved characters are handled properly in v2.6.0.
