### ISSUE TITLE
bug in clicking  explore tab

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#330]
### Expected behavior
click data source and page refreshes with explore information
### Actual behavior
click data source and page refreshes to the definition tab
### Steps to reproduce behavior
within a cohort click explore, click a data source

**Comment by anthonysena** [comment]
So this is related to the fact that when you select a data source in the "explore" tab, it changes the route to include the base64 encoded information for the data source. As a first step, I'll see if we can preserve the tabMode for the cohort definition page - it will still reload but should bring you back to the explore tab.
