### ISSUE TITLE
[v2.0] Vocab search - no more Results tab, or Result breadcrumbs

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#331]
### Expected behavior
Results tab present after searching; breadcrumbs to be able to return to specific search results
### Actual behavior
Results tab missing, no breadcrumbs
### Steps to reproduce behavior
Search for a concept, when results populate, no Results tab. Click on some other app section, then back to Vocabulary, no results breadcrumbs

**Comment by fdefalco** [comment]
results tab is actually going away in this release.  search results will appear in line below the search box.

**Comment by alondhe** [comment]
Ah okay. Will there still be a way to access the results from previously searched terms, or would you need to just run the search again?

**Comment by fdefalco** [comment]
You would have to run the search again.  I've gotten feedback that people like the prior search history so I'll see if I can work it in with the UI updates that are intended to make some future features easier with regard to search.
