### ISSUE TITLE
Choosing a Data Provider in Explore Tab Takes You Back to Definition Tab

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#332]
### Expected behavior
After choosing a data provider under the explore tab it will stay on that screen as it fetches the patient profiles. 
### Actual behavior
After choosing a data provider under the explore tab it shows the definition tab instead.
### Steps to reproduce behavior
Choose a cohort, click explore and then click on a data provider

**Comment by anthonysena** [comment]
Hi  - this is a duplicate of #330 so just closing this out.
