### ISSUE TITLE
Atlas Advanced Search Vocabulary Name

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Atlas#339]
### Expected behavior
I should be able to find SNOMED

### Actual behavior
How am I to know this is SNOMED?
Systematic Nomenclature of Medicine - Clinical Terms (IHTSDO)

### Suggested behavior
Display vocabulary Id followed by the name
SNOMED - Systematic Nomenclature of Medicine - Clinical Terms (IHTSDO)

**Comment by cgreich** [comment]
It should present both the short form (vocabulary_id) and the full name (vocabulary_name).

**Comment by ericaVoss** [comment]
Do you mean in the Advanced Search?

This is a duplicate issue . . . https://github.com/OHDSI/Atlas/issues/212

**Comment by fdefalco** [comment]
Erica is correct, please refer to #212 which will be addressed in the 2.0 release.  Here is the updated UI:

![image](https://cloud.githubusercontent.com/assets/6586384/22792995/7e9d3e44-eebc-11e6-9848-15d5e40251e7.png)
