### ISSUE TITLE
Request for 'Group' to Initial-Event cohort criteria

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#340]
### Expected behavior
Be able to set correlated/group criteria in intial event criteria
### Actual behavior
Not able to set correlated criteria
### Steps to reproduce behavior
No option for group in 'Initial event cohort'. There is option for group in the 'Initial event inclusion criteria'

For HEDIS measure - would like to specify a primary event criteria as.
-- Unilateral mastectomy (procedure) with a bilateral (procedure modifier) on same date of service
-- Two unilateral mastectomies (procedure) that are at-least 14 days apart

**Comment by chrisknoll** [comment]
Have you tried using nested criteria?  When you select the primary event (such as, a condition occurrence), you can then add a nested criteria looking for correlated events relative to the condition occurrence).

For your HEDIS example, it sounds like you want:

```
Primary event of:
procedure occurrence of Unilateral macetomy 
having all of: <-- this is the 'nested critera'
  at least 1 procedure occurrence of bilateral between 0 days before and 0 days after procedure occurrence

or a procedure occurrence of 'unilateral masectomy'
having all of: <-- this is the 'nested critera'
  at least 1 procedure occurrence of 'unilateral masectomy' between 1 day after and 14 days after procedure occurrence

limit primary events to: first event per person
```

Would that be what you want?

**Comment by gowthamrao** [comment]
Ooh wow! Did not realize it. Thank you!
