### ISSUE TITLE
Concept set comparison "open concept set" button doesn't work

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/Atlas#343]
### Expected behavior
A list of concept sets should open from which a user can select one

### Actual behavior
Nothing opens. Mousing over the concept set display shows X cursor.

### Steps to reproduce behavior
From within a concept set, navigate to the compare tab. Try to open an concept set for comparison

**Comment by anthonysena** [comment]
This appears to be the same as #333 - if so can you close this one? Thanks!
