### ISSUE TITLE
Error data sources, OHDSI cloud- 1k synthetic patients, person report

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#347]
### Expected behavior
click data sources, select OHDSI cloud - 1k synthetic patients, click person, page should render to person report

###Actual behavior
 page gives error

###Steps to reproduce behavior

click data sources, select OHDSI cloud - 1k synthetic patients, click person

**Comment by fdefalco** [comment]
the person report has been fixed.
