### ISSUE TITLE
Error on data sources, Truven CCAE, Procedure report

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#351]
### Expected behavior
click data source, Truven CCAE, click procedure, page should render to procedure report

###Actual behavior
 page gives error

###Steps to reproduce behavior

click data source, Truven CCAE, click procedure

**Comment by fdefalco** [comment]
These errors are actually just do to not having the results data available for the sources in our testing environment.  I'll leave this one open as a reminder to try and provide a more meaningful error message.
