### ISSUE TITLE
Enhance vocabulary search navigation for returning to search results list from concept detail view

### ISSUE THREAD

**Issue by leeevans** [OHDSI/Atlas#354]
### Expected behavior
In vocabulary search, on the search results, selected concept details view, click on a "back to results list" button or a breadcrumb link to navigate back to the vocabulary search results list

### Actual behavior
Selected concept is shown in breadcrumb trail (not clickable) and no link to return to search results list
Workaround: click on the "vocabulary" link in the menu and then click on the search results tab to return to search results list

### Steps to reproduce behavior (on OHDSI Cloud version of Atlas)
vocabulary search
enter text to search for a concept
click on concept name in search results list to open up view with concept details, related concepts, hierarchy, RC tabs
try to navigate back to the search results list

**Comment by fdefalco** [comment]
The back button performs this function currently.  The concept page doesn't currently know about the search that took place.
