### ISSUE TITLE
Vocabulary search results view "search results for" display field sometimes missing search text 

### ISSUE THREAD

**Issue by leeevans** [OHDSI/Atlas#355]
### Expected behavior
Vocabulary search results tab view shows search results list and always displays the words "search results for " and the search string

### Actual behavior
After performing a vocabulary search, click on the vocabulary menu link and click on results tab the search results view still shows list of search results but only displays the words "search results for"

### Steps to reproduce behavior (on OHDSI cloud version of Atlas)
Click on vocabulary menu option
Enter vocabulary search string
Search results tab displays "search results for " and the search string
Click vocabulary link in menu again
Click on results tab which still shows list of results but only displays the words "search results for"

Impact: I'm seeing this behavior when I click on the vocabulary menu link again as a workaround to return to search results list from vocabulary search concept detail view

**Comment by anthonysena** [comment]
Hi Lee - I can confirm this is an issue for Atlas 1.x but in Atlas 2.0, we will no longer have a separate tab for search results. Instead. the search results will load below the search text box which will eliminate this behavior.
