### ISSUE TITLE
Inconsistent concept name link/text background colors/color key info for classification concepts

### ISSUE THREAD

**Issue by leeevans** [OHDSI/Atlas#356]
### Expected behavior
The color key at the bottom of the concept set expression tab view indicates "green: classification, red: non-standard, blue: standard"
Classification concept name is displayed in light purple so the color key should say "purple: classification, red: non-standard, blue: standard" (or change the classification concept name link color to red and change the color key to say "red: classification/non-standard, blue: standard")

The concept details tab view (reached by clicking on concept name link) for a classification concept should also be updated to display the concept name and standard type with a purple text background, not red, if the color key is updated to say "purple: classification, red: non-standard, blue: standard".

### Actual behavior
The classification concept name displays as a light purple link
The color key says "green: classification, red: non-standard, blue: standard"
Clicking on the concept name for a classification concept shows the concept detail with the concept name and standard type displayed with a red text background.

### Steps to reproduce behavior (on OHDSI cloud version of Atlas)
Perform a vocabulary search for concept id = 45889191 which is a classification concept
Click on the shopping cart icon next to the concept to add it to a new concept set
Click on the "new concept set" breadcrumb link to navigate to the concept set expression tab view
Click on the concept name to view the concept details tab view

**Comment by anthonysena** [comment]
Hi Lee - I can confirm that in Atlas V2.0 we've fixed the inconsistencies related to the concept set color key displayed at the bottom.

I'm tagging @fdefalco since I want to get his input on your other point around the concept details tab view for classification concepts. I think your suggestion makes sense and makes the display consistent across these views.

**Comment by fdefalco** [comment]
Currently we display the red background on anything that isn't a standard concept, including classification concepts.  Differentiating between non-standard and classification makes sense to me.
