### ISSUE TITLE
Present record counts for all data sources?

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#358]
### Expected behavior
Search vocabulary for something (e.g. Acute myocardial infarction or Haemophilus influenzae Pneumonia), click on the concept name, click on record counts tab, present counts for all data sources (not just those with non 0 records)
### Actual behavior
only presented with data sources that have non 0 counts
### Steps to reproduce behavior
Search vocabulary for something, click on record counts tab

**Comment by anthonysena** [comment]
Hi Jill - this bug was related to a mistaken in configuration of our internal Atlas instance. I've corrected that problem and now each data source should return 0 counts when a concept is not present. Let me know if this persists and I'll re-open this item.
