### ISSUE TITLE
Integrate clipboard.js throughout Atlas

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#361]
Per #52, clipboard.js is now part of the Atlas build and needs to be incorporated into all areas of Atlas where copy/paste is required (for example, import/export of cohort definition JSON). This has been done in the estimation section for copying the R-code generated.

**Comment by fdefalco** [comment]
Closing and requesting that if there are copy/paste feature requests that they we identify where in the application we would like the functionality to exist.
