### ISSUE TITLE
Replace a Concept Set with Another

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#362]
This is an enhancement request not an issue.

Right now a concept set in a cohort can only be changed or deleted.  I would love if there was an option to swap it out for another.

Often I will have another more appropriate concept set developed to replaced one already in use.  A concept set can be used in many places in one cohort.  So doing a swap would be awesome.

**Comment by anthonysena** [comment]
Closing since it is a dupe of #365
