### ISSUE TITLE
Lag in Updating Description Text in Large Cohort Definition

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#363]
### Expected behavior
In the inclusion criteria, if you update text in the descriptions, it should be a normal/responsive as writing in any text box.

### Actual behavior
In large cohort (e.g. 3775 in Janssen) updating the text in inclusion criteria becomes extremely slow.  Text can take 30 seconds to appear after writing.

### Steps to reproduce behavior
Take large cohort like 3775 and update the description text in the inclusion criteria and you'll see the lag.

**Comment by chrisknoll** [comment]
The cohort you indicated produces a 4MB json file.  (Four Megabytes).  Every time something is updated in the cohort definition, the print friendly view and cartoon have to reprocess the document and render.  So, each. keypress. generates. four. megabytes.  This will take some time.

I'd try to optimize your cohort definition, remove unnecessary inclusion rules and concept sets, perhaps try to reduce concept sets with many individual concepts to something that can roll-up into a higher level concept to reduce the amount of data that needs to be managed in the definition.

**Comment by ericaVoss** [comment]
Hahaha . . . I know it is big and I'm not even done yet!  Still have a few more rules/concept sets to put in.

Does everything need to reprocess?  Could ATLAS only process it when the user looks at it?  The cartoon/print friendly are not where we spend the bulk of our time in the tool.

I could possibly shrink the concepts sets with these two ideas:
--Being able to filter by dose form and add that into a concept set definition.  If I need only orals it usually means I end up with a bulky concept set.
--being able to tie concept sets together A + B - C.

**Comment by chrisknoll** [comment]
No, the print friendly and cartoon was only an example. Another is the dirty check, where we compare the new json with the origional json to see if there are unsaved changes.  

In any case, I am not trying to dictate how you need to do your work, but it sounds like you're running into limitations on what you are trying to achieve using the tools.  I don't have any specific solutions for you that wouldn't involve significant re-architecture of how the system works, only the recommendation that you take care to optimize how you are defining your cohorts to be as efficient as possible (reducing those concept sets with 2000+ concepts in them would be a good start and removing any duplicate concept sets which also may have 2000+ concepts in them).

**Comment by ericaVoss** [comment]
First thanks for pointing out my one big duplicate - deleted that.

I think these recommendations could help me cut back on the bulk with concept sets without needing a significant re-architecture:
https://github.com/OHDSI/Atlas/issues/365

https://github.com/OHDSI/Atlas/issues/283

https://github.com/OHDSI/Atlas/issues/366

https://github.com/OHDSI/Atlas/issues/291

**Comment by chrisknoll** [comment]
fixed in 99872236b972834e79aa7ca9a135566f3afce307.
