### ISSUE TITLE
Ability to use windows shortcuts/functionality?

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#364]
This is an enhancement request not an issue.

If one could use windows functions like ctrl Z to undo for example deleting a rule that inadvertently is deleted it would be really helpful. Additionally if there was a way to multi select many rules at once to delete that would be a time saving. 

Thank you in advance for considering.

**Comment by anthonysena** [comment]
Closing due to age. Such a function would be useful but difficult to implement (in my opinion).
