### ISSUE TITLE
sorting by concept set name triggers route

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#37]
If you click on the Title column header on the /atlas/#/conceptsets page you get an error.  The event callback is based on a class, but it appears the class is assigned the to TH as well so when you attempt to sort you trigger a route with an undefined identifier:

/WebAPI/conceptset/undefined

**Comment by anthonysena** [comment]
Please also pull latest from Circe -> concept_set_picker_optionA as the fix required a change in that branch as well.
