### ISSUE TITLE
concept set definition doesn't dynamically change after correction

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/Atlas#371]
### Expected behavior
after user decides to delete(add) some concept from concept set this one should be deleted from(added to) code 
### Actual behavior
Code for concept set remains as it was firstly created despite all changes after. 
Changes of concepts or canges in concept set configurations ('mapped' ,'descendans' etc.) are not saved

**Comment by anthonysena** [comment]
I'm unable to reproduce this behavior on Atlas 2.0. If you can provide a link to a public concept set on the [OHDSI Atlas](http://www.ohdsi.org/web/atlas) instance along with steps to reproduce, we'll reopen this issue.
