### ISSUE TITLE
Introduce Language Packs into Cohort Bulder

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#374]
### Expected behavior
Cohort Definition Editor could support multiple languages on different UI elements (labels/buttons)

### Actual behavior
Editor has hard-coded language (US English)

### Background
The cohort builder is currently English-only, and there are parties that would benefit from having the tool 'skinned' to have native language on labels, buttons, etc.

The first step would be to introduce localization support into the components. This would involve replacing every hard-coded piece of content with references to an external/configurable language pack, and the labels would be set based on the locale-specific values in the language pack.

Once this is completed (the initial implementation could be English, since we already have all the content for those), we can have community contributors provide their own translations once we formalize a language-pack submission guide for the tools.

**Comment by cgreich** [comment]
Really? Who is that? These tools are for experts, not for the general population.

I understand that folks want to search the non-English synonyms of concepts, wtih accents and friendly behavior (finding Ö when looking for O etc.). But the UI?

**Comment by schuemie** [comment]
We were just in Korea where experts would like to use the tools but would be helped if the UI was in Korean. They did indicate that it is probably not a big issue that the vocab is still in English because they are taught English terms in medical school.

**Comment by cgreich** [comment]
Oh man. I'd start with a help page that translates things. They'll get used to it. We have so many real improvements to make.

**Comment by chrisknoll** [comment]
Right, @schuemie informed me that the vocabulary translation isn't at issue here, it's the instructions in the UI, or 'what does 'generate' mean' or which button is save or load, or error messages that come back, what do they mean..that sort of issue.  This is all to improve adoption, it isn't solving an analytical use case.

**Comment by anthonysena** [comment]
Perhaps folks could test out the Google Translate Chrome Plugin for translation to see if that helps?

https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb

Trying it myself, it seems like it might be worth a try. Once you have the plugin installed, you can launch it from the toolbar and translate a page:

![image](https://user-images.githubusercontent.com/12902366/28430342-2a92f0a8-6d4e-11e7-8f31-6b5b014206d5.png)

And this setting will persist during the browser session.

**Comment by chrisknoll** [comment]
Cool find.  I'm thinking we'll need fine control over how the text is translated, however. Like, the term 'save' might not be the right colloquial term for 'persist an item to the datastore' so when 'save' gets translated over it might turn into something like 'rescue'.  

In any event, you found a pretty clever workaround that people should try out to see how well it does (if they are bilingual).

**Comment by anthonysena** [comment]
Closed by #2494
