### ISSUE TITLE
show concept sets using the current concept as part of their definition

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#378]
This enhancement would be visible on a concept display.  It would give visibility to concept sets that use the current concept as part of their definition if it is included or including children, but not excluding.  This could help with concept set reuse or other use cases such as creating meaningful groupings for specific organizations (such as showing a concept is part of an area of scientific focus or therapeutic area.)

**Comment by pbr6cornell** [comment]
Great idea, but I'm suspecting this is a broader UI overhaul, which should be actively explored as part of ATLAS 3.0 planning.

**Comment by anthonysena** [comment]
Superseded by #2803.
