### ISSUE TITLE
async record count loading and add timeout controls

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#379]
Currently the evidence tab makes use of an asynchronous record count loading call to return results and then obtain counts.  The vocabulary search also uses two calls however doesn't return until the counts are available.  In addition both screens are limited by a client side timeout of 10 seconds for the record counts to be available.  

We would like to leverage the sync rc loading on the vocabulary page and add a configuration option to allow for longer async loading of record counts.

**Comment by anthonysena** [comment]
This fix is dependent on OHDSI/WebAPI#214
