### ISSUE TITLE
Cohort_definition_Id - next to Cohort label

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#380]
### Expected behavior
Be able to see the Cohort_definition_id next to Cohort on the top.
![image](https://cloud.githubusercontent.com/assets/13936600/23979951/17d21464-09d3-11e7-98d4-eab528870d8c.png)

### Actual behavior
Need to close the cohort to see the Cohort number.
![image](https://cloud.githubusercontent.com/assets/13936600/23979945/0ca57e82-09d3-11e7-9c1e-3ea7eeb8ef67.png)

### Steps to reproduce behavior

To know the cohort definition id, we have to close the cohort definition page and go to the Cohort landing page. It would make it easier to know the Cohort_definition_id as shown in the screen shot.
(Ofcourse - we can look at the URL )

**Comment by fdefalco** [comment]
resolved in feature-integration branch
