### ISSUE TITLE
cohort comparison feature

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#382]
This is an enhancement request not an issue

It would be very helpful to be able to compare cohorts similarly to the compare concept set feature to determine if there are identical subjects contained in two cohorts. If there are subjects that are included in both cohorts. 

Often there is a need to confirm that two cohorts do or do not contain unique subjects. As a use case - for the study I'm working on I determined via a query the overlap in subject ids and then manually reviewed the records through the profile feature and determined if a given subjects has the outcome that belongs to one cohort or the other. Then modified the rules in ATLAS that appeared to eliminate the overlap.

This would be very helpful if possible. Thank you.

**Comment by pbr6cornell** [comment]
+1 to this idea, but I think it falls into the more general desire to standardize cohort characterization, and then introduce a cohort comparison capability that would be based on the characterization (and showing the overlap in persons within the cohort would be part of that solution).  I think its a big opportunity, but also a big task, so I'd recommend we table for 2.4 and prioritize for 2.5

**Comment by anthonysena** [comment]
I'm going to move this issue to the 'After Symposium' review list but I believe with the introduction of the new cohort characterization features in https://github.com/OHDSI/WebAPI/issues/495 we're close to having an initial way to perform this type of analysis.

**Comment by pbr6cornell** [comment]
Definite feature request in ATLAS 3.0, but out of scope for ATLAS 2.8.

**Comment by anthonysena** [comment]
Closing since this type of functionality exists in [CohortDiagnostics](https://ohdsi.github.io/CohortDiagnostics/articles/WhatIsCohortDiagnostics.html)
