### ISSUE TITLE
Concept set name writes right to left

### ISSUE THREAD

**Issue by rtmill** [OHDSI/Atlas#384]
Within the cohort definition and you select concept sets, then new concept set... 

While changing the concept name it enters keystrokes backwards. For instance, here I typed 12345:
![image](https://cloud.githubusercontent.com/assets/13469976/24202292/01e0ec78-0ee9-11e7-8266-568e38e73b36.png)

**Comment by pbr6cornell** [comment]
this might be the greatest bug of all time!  can't replicate it on either
JNJ or OHDSI instances...

**Comment by chrisknoll** [comment]
I agree, someone at the F2F showed me this in real time (I think it was Gotham)and I opened my browser right next to him (we were both on chrome) and I could not reproduce!  

@rtmill , Can you give me information about what browser and version you are using (if it is chrome, please go to the Help->about chrome menu option to give the full version number.

Thank you!

**Comment by chrisknoll** [comment]
Update!  I just updated to chrome 57, and I see the issue!

I'll work on a fix immediately.

**Comment by t-abdul-basser** [comment]
@anthonysena @chrisknoll @fdefalco Given the non-trivial nature of this bug, would it be advisable to release a patch/minor version release ASAP?
