### ISSUE TITLE
Empty value as number field results in FAILED status

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#387]
### Expected behavior
When a certain user (we won't name names) forgets to populate a value as number type of field (say, demographic-->age criteria), perhaps Atlas could warn the user that they should actually populate those fields, otherwise the cohort won't run due to a malformed query.
### Actual behavior
User is confounded by "FAILED" cohort generation status, opens Git issue. 
### Steps to reproduce behavior
Add a demographic inclusion criteria, then add an age event criteria but leave the age blank.

**Comment by fdefalco** [comment]
This also occurs if a unit value is left blank.  In general, a cohort definition validation routine would be helpful.

**Comment by anthonysena** [comment]
Linking this to #1933. I'm not sure if such a warning already exists in the cohort definition editor but sounds like a worthwhile check to add if it doesn't already exist.

**Comment by pbr6cornell** [comment]
@pavgra if you can point me to the warnings documentation, I can confirm if this type of error is currently handled, and if not, happy to help work with you on spec out the design.
