### ISSUE TITLE
ATLAS on Firefox

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/Atlas#388]
### Expected behavior
Go to Atlas URL and open Atlas

### Actual behavior
Atlas animation gets stuck and never goes into Atlas UI

### Steps to reproduce behavior

Use Firefox 52.0.2 - 32 bit, go to your Atlas instance

**Comment by alondhe** [comment]
I believe Firefox support in general isn't really a priority, so this is probably far from the only issue that could arise.

**Comment by jmbanda** [comment]
True, I am just documenting the issue so people don't spend time looking at the error logs wondering what is happening :)

**Comment by anthonysena** [comment]
Thanks Juan - we've tried to make it clear that ATLAS works best on Google Chrome via the README but I'm also going to open an issue #423 to make note of these cross-browser compatibility issues.
