### ISSUE TITLE
Export feature in ATLAS does not let you copy concept

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#39]
I am unable to copy a long concept list from the export tab because of the new scrolling feature. It is very slow in letting me select the list

**Comment by anthonysena** [comment]
Let me try to see if we can implement a "copy" button to put this on the clipboard. If not, we'll have to devise a different approach

**Comment by chrisknoll** [comment]
Going to implement a 'select on focus' behavior for this release, and add the clipboard capability to the 1.0 release.

**Comment by chrisknoll** [comment]
Fixed in commit 6d351a5ba6330887fd9d755d292cc29cc00cdaba.
