### ISSUE TITLE
Optimize New Concept Set Rename

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#390]
### Expected behavior
When saving a new concept set from an optimized one, and giving it a name, the name is retained upon save.

### Actual behavior
The generated name is saved.

### Steps to reproduce behavior
1)
Create a concept set using:
4038838-Non-Hodgkin's lymphoma
434592-B-cell lymphoma

2)
Click "Descendants" and press the "Optimize" button.

3)  
On the "Concept Set Optimization" screen, hit the "Save Options" button and select "Create New Concept Set"

4)
Rename concept set to "Erica's Most Awesome Concept Set" and hit "Save" button.  But it tries to save it to "New Concept Set - OPTIMIZED"

**Comment by pbr6cornell** [comment]
Confirmed I can reproduce this bug in 2.3
