### ISSUE TITLE
Age Ranges on Datasource Dashboard view issue

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#391]
### Expected behavior
The upper right-hand graph should show the number of people in each age group
### Actual behavior
For MDCR, the counts seem shifted to the right with the largest count at age 85
For MDCD, the ages are all squished together and not readable
### Steps to reproduce behavior
View dashboards for MDCD and MDCR

**Comment by fdefalco** [comment]
resolved.
