### ISSUE TITLE
Text typed into an 'Add Value as String Criteria' text box is ordered right-to-left

### ISSUE THREAD

**Issue by mtadev** [OHDSI/Atlas#395]
### Expected behavior
Text typed into an 'Add Value as String Criteria' text box is ordered left-to-right (English) 

### Actual behavior
Text typed into an 'Add Value as String Criteria' text box is ordered right-to-left (English)

### Steps to reproduce behavior
1. On the 'Cohorts' page, tap 'New Cohort'
2. In 'Initial event cohort:', tap 'Add Initial Event' and select 'Add Observation Criteria'
3. Tap 'Add criteria attributes..' and select 'Add Value as String Criteria'
4. Type 'cancer' in the text box to the right of 'Xwith Value as String'
Observe: the typed text appears in the right-to-left order as 'recnac'

Note: Text typed into an 'Add Value as String Criteria' text box is ordered right-to-left in any Cohort definition criteria (e.g. 'Initial event inclusion criteria', 'Additional qualifying inclusion criteria')

Atlas      Version 2.0.0 
WebAPI Version 2.0.0

**Comment by chrisknoll** [comment]
Yes, this was fixed for #384, but hasn't been released officially. You can try to pull atlas from the master branch if you'd like to check the fix.
