### ISSUE TITLE
RC DRC always zero, not available

### ISSUE THREAD

**Issue by link9** [OHDSI/Atlas#397]
I am seungbin, a MS student on ajou university, korea, medical school, studying OHDSI web apps.

### Expected behavior
**In atlas demo** (http://www.ohdsi.org/web/atlas/#/search/1539411),
when I search concept id 1539411, I can see a record with RC, DRC

1539411	312961	Simvastatin 20 MG Oral Tablet	Clinical Drug	**27,252	29,394**	Drug	RxNorm

### Actual behavior

but I search same thing on my local installation, RC, DRC results always zero.
maybe some configuration is wrong, could anyone give me a hint where I should look into?
thank you..

1539411	312961	Simvastatin 20 MG Oral Tablet	Clinical Drug	**0	0**	Drug	RxNorm

### Steps to reproduce behavior
I installed W**ebAPI, MSSQL-EXPRESS locally** and configured source_daimon and checked on http://localhost:8080/WebAPI/source/sources

[{"sourceId":1,"sourceName":"SEUNGBIN_CDM","sourceDialect":"sql server","sourceKey":"MY_CDM","daimons":[{"sourceDaimonId":1,"daimonType":"CDM","tableQualifier":"dbo","priority":"0"},{"sourceDaimonId":2,"daimonType":"Vocabulary","tableQualifier":"dbo","priority":"0"},{"sourceDaimonId":3,"daimonType":"Results","tableQualifier":"dbo","priority":"0"}]},{"sourceId":2,"sourceName":"Default vocabulary","sourceDialect":"sql server","sourceKey":"vocab","daimons":[{"sourceDaimonId":4,"daimonType":"Vocabulary","tableQualifier":"dbo","priority":"1"}]}]

and on http://localhost:8080/WebAPI/vocabulary/search/1539411

[{"CONCEPT_ID":46146068,"CONCEPT_NAME":"Clopixol 10mg tablets (Waymade Healthcare Plc) 100 tablet","STANDARD_CONCEPT":"N","INVALID_REASON":"V","CONCEPT_CODE":"11539411000001108","DOMAIN_ID":"Drug","VOCABULARY_ID":"SNOMED","CONCEPT_CLASS_ID":"Pharma/Biol Product","INVALID_REASON_CAPTION":"Valid","STANDARD_CONCEPT_CAPTION":"Non-Standard"},{"CONCEPT_ID":46187887,"CONCEPT_NAME":"Coloplast sterile catheter valve CV3808 (Coloplast Ltd) 10 device","STANDARD_CONCEPT":"N","INVALID_REASON":"V","CONCEPT_CODE":"21539411000001107","DOMAIN_ID":"Drug","VOCABULARY_ID":"SNOMED","CONCEPT_CLASS_ID":"Pharma/Biol Product","INVALID_REASON_CAPTION":"Valid","STANDARD_CONCEPT_CAPTION":"Non-Standard"},{"CONCEPT_ID":37007070,"CONCEPT_NAME":"Juzo Soft class 1 (18-21mmHg) thigh length closed toe lymphoedema garment extra short size I Black pepper (Juzo UK Ltd)","STANDARD_CONCEPT":"N","INVALID_REASON":"V","CONCEPT_CODE":"31539411000001106","DOMAIN_ID":"Drug","VOCABULARY_ID":"SNOMED","CONCEPT_CLASS_ID":"Pharma/Biol Product","INVALID_REASON_CAPTION":"Valid","STANDARD_CONCEPT_CAPTION":"Non-Standard"},{"CONCEPT_ID":46023587,"CONCEPT_NAME":"Mediven Elegance class 2 (23-32mmHg) tights closed toe lymphoedema garment size V Black (Medi UK Ltd)","STANDARD_CONCEPT":"N","INVALID_REASON":"V","CONCEPT_CODE":"15394111000001105","DOMAIN_ID":"Drug","VOCABULARY_ID":"SNOMED","CONCEPT_CLASS_ID":"Pharma/Biol Product","INVALID_REASON_CAPTION":"Valid","STANDARD_CONCEPT_CAPTION":"Non-Standard"},{"CONCEPT_ID":46107108,"CONCEPT_NAME":"Procyclidine 5mg tablets (A A H Pharmaceuticals Ltd) 500 tablet","STANDARD_CONCEPT":"N","INVALID_REASON":"V","CONCEPT_CODE":"1539411000001109","DOMAIN_ID":"Drug","VOCABULARY_ID":"SNOMED","CONCEPT_CLASS_ID":"Pharma/Biol Product","INVALID_REASON_CAPTION":"Valid","STANDARD_CONCEPT_CAPTION":"Non-Standard"},**{"CONCEPT_ID":1539411,"CONCEPT_NAME":"Simvastatin 20 MG Oral Tablet","STANDARD_CONCEPT":"S","INVALID_REASON":"V","CONCEPT_CODE":"312961","DOMAIN_ID":"Drug","VOCABULARY_ID":"RxNorm","CONCEPT_CLASS_ID":"Clinical Drug","INVALID_REASON_CAPTION":"Valid","STANDARD_CONCEPT_CAPTION":"Standard"}]**

**Comment by alondhe** [comment]
I think your source_daimon records aren't set properly. Valid daimonTypes are "0" (for CDM), "1" (for Vocab), or "2" (for results), and you'd need to set the record with source daimonType of 2 to have a priority of 1.

**Comment by link9** [comment]
thanks for your reply!, but in the installation guide,
http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:webapi_installation_guide

the daimonTypes of the output is same
[
{"sourceId":1,"sourceName":"My Cdm","sourceDialect":"postgresql","sourceKey":"MY_CDM", "daimons":
  [ 
    **{"sourceDaimonId":1,"daimonType":"CDM","tableQualifier":"public","priority":"0"},
    {"sourceDaimonId":2,"daimonType":"Vocabulary","tableQualifier":"public","priority":"0"},
    {"sourceDaimonId":3,"daimonType":"Results","tableQualifier":"OHDSI.webapi","priority":"0"}**
  ]
},
{"sourceId":2,"sourceName":"Default vocabulary","sourceDialect":"postgresql","sourceKey":"vocab","daimons":
  [
    {"sourceDaimonId":4,"daimonType":"Vocabulary","tableQualifier":"public","priority":"1"}
  ]
}]

i think that's not the problem..

**Comment by alondhe** [comment]
Ah, that must be a new feature; that the daimonType can have values of "CDM", "Vocabulary", and "Results." So ignore that part of my reply, but I think you still need a results daimon with priority set to 1 to indicate that it should be used for pulling record counts.

**Comment by ErezYehuda** [comment]
I also seem to be having this exact issue. The issue appears to be (at least Atlas-side) line 66 of `Atlas/js/modules/WebAPIProvider/VocabularyProvider.js`.

**Comment by ErezYehuda** [comment]
I currently have a solution (it's very small) that I have tested but don't have privileges to create a branch for it to be evaluated. Is there anyone I should contact with the proposed correction?

**Comment by chrisknoll** [comment]
The steps are to fork the repository, then create a branch in your fork, and then submit a pull request from your fork's branch.  

You can find the developer guidelines for using GIT here: http://www.ohdsi.org/web/wiki/doku.php?id=development:ohdsi_github_projects_v2.

-Chris

**Comment by ErezYehuda** [comment]
@link9 
For those who don't want to wait for me, changing line 66 to
```
                                        let conceptKey = Object.getOwnPropertyNames(entries[e])[0];
                                        densityIndex[conceptKey] = entries[e][conceptKey];
```
has fixed the issue for me.

**Comment by anthonysena** [comment]
Recent commits to the master branches of Atlas & WebAPI per #379 also add the ability to cache the RC/DRC and a similar change was made to Atlas as described above. I'm going to close this out but please re-open this issue if it fails to solve the issues you saw in your environment.
