### ISSUE TITLE
Support for condition_status_concept_id

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#404]
### Expected behavior
Able to restrict to condition_occurrence that meet condition_status_concept_id criteria

**Examples of condition_status_concept_id's:**
- Admitting diagnosis: use concept_id 4203942
- Preliminary diagnosis: use concept_id 4033240
- Final diagnosis: use concept_id 4230359 – should also be used for ‘Discharge diagnosis’

### Actual behavior
No option to restrict by condition_status_concept_id

http://www.ohdsi.org/web/wiki/doku.php?id=documentation:cdm:condition_occurrence

**Comment by chandryou** [comment]
Recently, the same request was asked in the [Korean forum](https://forums.ohdsi.org/t/condition-occurrence-table-condition-status-concept-id/9509)

**Comment by clairblacketer** [comment]
Has this been added yet? The type concepts no longer support things like "primary condition", "secondary condition", etc. and that is all stored in CONDITION_STATUS_CONCEPT_ID.

**Comment by chrisknoll** [comment]
Sure we'll put it into the 2.8 release. Question: should this be a list of concepts, or a concept set?

**Comment by clairblacketer** [comment]
You could probably do a list of concepts since they are all supposed to be in the [Condition Status domain.](https://athena.ohdsi.org/search-terms/terms?domain=Condition+Status&standardConcept=Standard&page=1&pageSize=15&query=)

**Comment by chrisknoll** [comment]
Ok, sounds good. considering there's 22 total, that seems managable.  I was just asking because if there's going to be a hierarchy relationship between them in the future, we might want to start with a concept set expression.  We can always switch it out later.
