### ISSUE TITLE
Duplicate results in Atlas datasources drug report prevalence table when searching for drug

### ISSUE THREAD

**Issue by leeevans** [OHDSI/Atlas#405]
### Expected behavior
Drug report prevalence table should display a unique prevalence for each drug that matches the entered search string

### Actual behavior
Multiple duplicate prevalences shown 

### Steps to reproduce behavior
On ohdsi.org Atlas go to Drug Sources, synpuf 1% is selected, select Drug report from drop-down.
Drug Report Prevalence page is shown (heat-map), click on the Table tab.
Enter "diane" in the search box and press enter.
Duplicate entries are shown in the table for concept id 40169539 "Calcium Chloride 0.000996 MEQ/ML / Glucose 1.4 MG/ML / Magnesium Chloride 0.0000245 MEQ/ML / Sodium Chloride 0.00368 MEQ/ML / Sodium Lactate 0.0016 MEQ/ML Intraperitoneal Solution [Dianeal Low Calcium 3.5]"

**Comment by fdefalco** [comment]
@leeevans this isn't an ATLAS bug, I've confirmed that the ohdsi.org WebAPI is returning 22,386 rows and it includes the duplicates you mentioned.  In fact just about every record has duplicate entries.  Is it possible that the Achilles results table in the OHDSI environment has duplicated data?

**Comment by leeevans** [comment]
@fdefalco 

Is this the SQL query that is being run for that WebAPI call?
https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/report/drug/treemap.sql

If it is, then what may be happening is that the query/webapi returns the concept and 'concept_path' but Atlas only displays the concept and concept name so they look like duplicates.

Here is the sql query output for one example drug 19128170:

concept, concept_path, num_persons, percent_persons, records_per_person
19128170;"NA||NA||NA||Norgestrel||{21 (Ethinyl Estradiol 0.05 MG / Norgestrel 0.5 MG Oral Tablet) / 7 (Inert Ingredients 1 MG Oral Tablet) } Pack";9;0.00008;1.00000
19128170;"GENITO URINARY SYSTEM AND SEX HORMONES||SEX HORMONES AND MODULATORS OF THE GENITAL SYSTEM||Natural and semisynthetic estrogens, plain||Ethinyl Estradiol||{21 (Ethinyl Estradiol 0.05 MG / Norgestrel 0.5 MG Oral Tablet) / 7 (Inert Ingredients 1 MG Oral Table (...)";9;0.00008;1.00000
19128170;"NA||NA||NA||Inert Ingredients||{21 (Ethinyl Estradiol 0.05 MG / Norgestrel 0.5 MG Oral Tablet) / 7 (Inert Ingredients 1 MG Oral Tablet) } Pack";9;0.00008;1.00000

webapi output: http://api.ohdsi.org/WebAPI/cdmresults/1PCT/drug

{"conceptId":19128170,"conceptPath":"NA||NA||NA||Norgestrel||{21 (Ethinyl Estradiol 0.05 MG / Norgestrel 0.5 MG Oral Tablet) / 7 (Inert Ingredients 1 MG Oral Tablet) } Pack","numPersons":9,"percentPersons":0.00008,"recordsPerPerson":1},{"conceptId":40164242,"conceptPath":"RESPIRATORY SYSTEM||ANTIHISTAMINES FOR SYSTEMIC USE||Substituted alkylamines||Chlorpheniramine||Chlorpheniramine 0.4 MG/ML / Hydrocodone Bitartrate 0.4 MG/ML / Phenylephrine 1.5 MG/ML Oral Solution [HYDRO PC]","numPersons":9,"percentPersons":0.00008,"recordsPerPerson":1},{"conceptId":19044539,"conceptPath":"NERVOUS SYSTEM||PSYCHOLEPTICS||Carbamates||Meprobamate||Estrogens, Conjugated (USP) 0.45 MG / Meprobamate 200 MG Oral Tablet [PMB]","numPersons":9,"percentPersons":0.00008,"recordsPerPerson":1},{"conceptId":19041862,"conceptPath":"ALIMENTARY TRACT AND METABOLISM||DRUGS FOR CONSTIPATION||Contact laxatives||Bisacodyl||Bisacodyl 5 MG Delayed Release Oral Tablet [Bisco-Lax]","numPersons":9,"percentPersons":0.00008,"recordsPerPerson":1},{"conceptId":40167476,"conceptPath":"NA||NA||NA||eastern sycamore pollen extract||eastern sycamore pollen extract 1000 UNT/ML Injectable Solution","numPersons":9,"percentPersons":0.00008,"recordsPerPerson":1},{"conceptId":19128170,"conceptPath":"GENITO URINARY SYSTEM AND SEX HORMONES||SEX HORMONES AND MODULATORS OF THE GENITAL SYSTEM||Natural and semisynthetic estrogens, plain||Ethinyl Estradiol||{21 (Ethinyl Estradiol 0.05 MG / Norgestrel 0.5 MG Oral Tablet) / 7 (Inert Ingredients 1 MG Oral Tablet) } Pack","numPersons":9,"percentPersons":0.00008,"recordsPerPerson":1},{"conceptId":19128170,"conceptPath":"NA||NA||NA||Inert Ingredients||{21 (Ethinyl Estradiol 0.05 MG / Norgestrel 0.5 MG Oral Tablet) / 7 (Inert Ingredients 1 MG Oral Tablet) } Pack","numPersons":9,"percentPersons":0.00008,"recordsPerPerson":1}
