### ISSUE TITLE
Cannot clear out concept set

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#41]
Once a new concept set is created I cannot clear out the set to import a new one or start on a new defintion

**Comment by fdefalco** [comment]
There is a 'Close' button that allows you to close the current concept set.  Does that do what you are looking for?

**Comment by rmakadia** [comment]
The close button doesn’t do anything currently ☺ If it closes then we are all set. Thanks!

Rupa Makadia, M.S.
Manager, Epidemiology Analytics
[Janssen_Hor_RGB]
Janssen Research & Development
920 Route 202, Cube - 1114A
Raritan, NJ 08869
Tel: 908 927 3893
rmakadia@its.jnj.com<mailto:rmakadia@its.jnj.com>

**************************************************
Confidentiality Notice: This e-mail transmission may contain confidential or legally privileged information that is intended only for the individual or entity named in the e-mail address. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, or reliance upon the contents of this e-mail is strictly prohibited. If you have received this e-mail transmission in error, please reply to the sender, so that Johnson & Johnson can arrange for proper delivery, and then please delete the message from your inbox. Thank you.

**Comment by anthonysena** [comment]
Rupa, I believe we identified that this issue was related to browser caching. I'm going to close out this issue for now and we'll re-test it when we've addressed all of the other bugs that are part of this release. Just reach out to me if you are still facing problems.
