### ISSUE TITLE
How to use properly filter measurements by operator

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#412]
### Expected behavior
select pts BMI > 40. 
User should only use filter by value as number?

### Actual behavior
It is confusing which criterion to use.
See picture below
![image](https://user-images.githubusercontent.com/7526119/27356022-064cefbc-55db-11e7-8b7c-bd9bdaccebe6.png)

1.Advice if the first criterion should be removed or kept.
2. Clarify when operator logic would be used and how. (where the value is entered)
3. how to specify range for a value :   (see here:   V85.41; Body Mass Index 40.0-44.9, Adult )  **40<=x <45**
### Steps to reproduce behavior
see cohort http://www.ohdsi.org/web/atlas/#/cohortdefinition/906140

**Comment by chrisknoll** [comment]
The use of operators might be confusing, but the way the measurement criteria is just exposing filters on the measurement table.

If you  removed the Measurement operator, then the following row would match the criteria:

Operator = <
value as number = 41

Ie: the value as number is great than 40, but you didn't specify the operator.

What you have in your example will match the following records:
Value Operator == '>', Value as Number = 41
Value Operator == '>', Value as Number = 42
Value Operator == '>', Value as Number = 43 
...etc..

This is just an artifact about how measurements are recorded in the CDM.

-Chris
