### ISSUE TITLE
Radlex 'vocabulary' not included?!

### ISSUE THREAD

**Issue by dchannin** [OHDSI/Atlas#415]
www.radlex.org
http://bioportal.bioontology.org/ontologies/RADLEX

**Comment by fdefalco** [comment]
The vocabulary exposed through ATLAS is the CDM Vocabulary.  If you are interested in having a vocabulary included I would recommend it to the CDM and Vocabulary development work group.

http://www.ohdsi.org/web/wiki/doku.php?id=projects:workgroups:cdm-wg

**Comment by dchannin** [comment]
Frank,

  Went to the CDM discussion page and got "composer was opened without a
draft key" when trying to add a new post.
 Is there someone I can e-mail?

Thank you,
Dave

David S. Channin MD
David.Channin@gmail.com
+1.570.431.9729

**Comment by leeevans** [comment]
@dchannin I've created an OHDSI wiki user account for you so you can login and create new wiki page posts. I'll send you your user account info via email.

**Comment by dchannin** [comment]
Thank you.
