### ISSUE TITLE
Unable to launch ATLAS

### ISSUE THREAD

**Issue by DJGen** [OHDSI/Atlas#420]
### Actual behavior

application initialization failed
unable to connect to an instance of the webapi. please contact your administrator to resolve this issue.
![capture](https://user-images.githubusercontent.com/30093780/28094222-abfdd56a-6658-11e7-833c-9ae3a1f977f8.JPG)

the other program choices work

**Comment by fdefalco** [comment]
There was an issue with a build that disabled the public WebAPI earlier today.  The issue has been resolved.

**Comment by DJGen** [comment]
Thanks, working now

Sent from my Verizon 4G LTE Droid
On Jul 12, 2017 1:52 PM, Frank DeFalco <notifications@github.com> wrote:

There was an issue with a build that disabled the public WebAPI earlier today. The issue has been resolved.
