### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#423]
### Expected behavior

That ATLAS should work across combinations of major browsers and major operating systems. 

### Actual behavior

ATLAS works best in Google Chrome and the community has noted that other browsers (i.e. Firefox, Safari) either do not work at all or have certain problems.

We highly recommend that all ATLAS users use Google Chrome.

**Comment by fdefalco** [comment]
Closing META tag with existing issues closed.
