### ISSUE TITLE
Relationships are incorrect

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#427]
### Expected behavior
When you click on a relationship it will show all concepts that have that relationship with the initial concept

### Actual behavior
When you click on a relationship it shows only one concept

### Steps to reproduce behavior
Click on a relationship for a given concept.

![image](https://user-images.githubusercontent.com/12911960/28732584-5c2a6a16-73a6-11e7-9311-1ecd1c3846f6.png)

**Comment by fdefalco** [comment]
this was likely an issue with the introduction of a new library and is no longer reproducible.
