### ISSUE TITLE
Selection of multiple measurement as value as concepts

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#428]
### Expected behavior
Select more than one measurement value as concepts, for example, high, abnormal, use the filter to select the second concept. select the 'Add and close' button; expect more than one value as concept to appear in rule. 
### Actual behavior
Only the last measurement value as concept appears in rule. 
### Steps to reproduce behavior
Select more than one measurement value as concepts, for example, high, abnormal, use the filter to select a second value, select the 'Add and close' button. (NOTE: tried removing contents from the filter field and the last value as concept appears)
![image](https://user-images.githubusercontent.com/11822115/28780124-a6ee3404-75d3-11e7-959a-b018975c0fdb.png)

**Comment by pbr6cornell** [comment]
Should we be using conceptsets for measurement values as concepts, instead of this attribute picker screen?   Similarly, should we use conceptsets for measurement units?

**Comment by chrisknoll** [comment]
of if there's a hierarchy of measurement units...

**Comment by cgreich** [comment]
There isn't. We are working on a definitive list of units for each Measurement Concept.

**Comment by chrisknoll** [comment]
Will there be, tho? I mean does it make sense to say 'descendants of bpm'?  or 'descendants of ML'?  Concept sets are used to generate a set of values. In the case of measurement units, why would you say 'Give me measurements with value 50 of units 'descendants of anything measuring volume'?  I feel like if you are looking for a value, you must also be looking for a specific unit for that value...not something from a list of descendants....

**Comment by cgreich** [comment]
Yeah. Theoretically, you could provide e.g. glucose in blood in any concentration measurement you can put together from mass and volume. So, you could expect kg/cubic meter, or milli-carat per nano fluid ounce. In reality, you only have one, maybe two, and rarely three measurements actually used, in this case mg/dL or mmol/l. Really no need to create a complex hierarchy.

But if you insist: UCUM actually allows you to do something like derived units from basic units based on the notation of the concept_code. You can read about it here: http://unitsofmeasure.org/ucum.html#section-Tables-of-Terminal-Symbols. 

@vojtechhuser is trying to fix the allowable units and later a mechanism for automatic conversion.

**Comment by chrisknoll** [comment]
My point is: if you find kg/cubic meter or milli-carat per nano fluid ounce, can you use the same number to look across both units, or do you need to specify the unit and number as once thing.  If it is the latter, than using a concept set to define units makes no sense here.

Same question about derived units.  You wouldn't say '10' and then use a concept set expression that returns 'percent', 'parts per thousand' and 'parts per million', otherwise it would match 10 percent, 10 parts per thousand or 10 parts per million, which clearly are different values, and therefore you need to specify the number and the unit specifically.

And maybe we got off track @cgreich, I'm not arguing which list is the right list of units for measurements, I'm arguing the point about using concept sets to select the unit:

> @pbr6cornell :
> Should we be using conceptsets for measurement values as concepts, instead of this attribute picker screen? Similarly, should we use conceptsets for measurement units?

**Comment by vojtechhuser** [comment]
I think the question is more about non-unit values. E.g., leukocytes in urine at level 2 or 3 (but not absent or only at value of 1).

**Comment by cgreich** [comment]
@chrisknoll: 

"can you use the same number to look across both units, or do you need to specify the unit and number as singular thing" - not sure I understand. If you have several units for a measurement you need a conversion factor. For many of them the conversion factor is 1 (e.g. between g/L and mg/mL). That's probably mean by "same number". But it makes no difference. 

What we would like to achieve eventually is to have (i) a fixed list of "allowed" or "right" units, (ii) pick one as the Standard Unit and (iii) provide the conversion factors for all the others. Once we have that we have solved the whole unit problem. It is not hard, it's just a lot of work. Vojtech started it nicely.

@vojtechhuser:

"non-unit value" - same thing, again. The unit is just 1. Or something that is an annotation in UCUM speak, like "{cells}". Conversion factors between any of them are 1.

**Comment by anthonysena** [comment]
Closing due to age and that the original issue posted is resolved.
