### ISSUE TITLE
Sorting of cohorts by date not sorting correctly

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#444]
### Expected behavior
Sorting by "Created" or "Updated" dates in the Cohort table should sort by date correctly (by year, by month, by day).

### Actual behavior
In the OHDSI Atlas and in the Janssen instance, cohorts from 9/9/2016 are the "max", while cohorts from 1/1/2017 are the "min."

### Steps to reproduce behavior
Go to cohorts, sort the datatable by "Created" or "Updated."

**Comment by fdefalco** [comment]
fixed in https://github.com/OHDSI/Atlas/commit/61c06dd1d649a43ef8451640bb46cf930fbe13bf
