### ISSUE TITLE
Cohort inclusion report error

### ISSUE THREAD

**Issue by erwanlc** [OHDSI/Atlas#452]
### Expected behavior
When clicking on View Inclusion Report after generating a cohort, it would usually show a treemap which can highlight the inclusion rules that were applied.

### Actual behavior
The treemap is not generated. I'm getting the following error in Chrome Developer tools:
![error](https://user-images.githubusercontent.com/14557825/29913563-c7844274-8e35-11e7-8f63-db20fdf21c9d.PNG)

### Steps to reproduce behavior
Using the latest version of Atlas, generate a cohort with > 1 inclusion criteria. Click on View Inclusion Report. If you have the Chrome Dev tools open, you should see the error.

**Comment by fdefalco** [comment]
not reproducible.  from the look of the error it appears as if the d3 library failed to load in this instance.  In testing several cohorts with multiple inclusion criteria I did not see this error.  If you can reproduce the error please provide a copy of the cohort definition from the export tab and reopen the issue.
