### ISSUE TITLE
Search the vocabulary doesn't work

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Atlas#461]
Trying to find something, "aspirin" for example

http://www.ohdsi.org/web/atlas/#/search/aspirin 

I got no result. Looks like something is fishy with the vocab search. Should we worry about it?

**Comment by leeevans** [comment]
It's working again now.

It was a general database connection issue, not specific to vocab search. 
There were too many simultaneous connections open to the database.

**Comment by leeevans** [comment]
issue resolved

**Comment by dimshitc** [comment]
Thanks, Lee, very much appreciated. Works great now
