### ISSUE TITLE
Can't select visit type filters

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#47]
This could be a icon/image bug?

![image](https://cloud.githubusercontent.com/assets/6586384/13921021/492a6842-ef4c-11e5-9a80-bb3320c7732c.png)

**Comment by chrisknoll** [comment]
No, it's not an image.  It uses "glyphicon glyphicon-ok-sign" in a span to show the checkbox.

**Comment by chrisknoll** [comment]
The glyphicon files were deleted in this commit:  4793b4ef44c0d61742820a16cd75eb9216f14141

@fdefalco , I'd restore those files that were deleted to fix the broken functionality.

**Comment by fdefalco** [comment]
Any issue if we use fontawesome instead? I switched to it instead of glyphicons a while back.

**Comment by chrisknoll** [comment]
check-circle would be the equivalent, but will break circe/calypso in the interim (they do not have font awesome installed).  We can make this change when we merge the circe/calypso components into Atlas but that's outside the scope of the 0.9.9 milestone.

However, the glyphicon seems to be considered part of the bootstrap framework, so shouldn't we make this available for purposes of bootstrap compatibility?

**Comment by fdefalco** [comment]
Bootstrap is dropping them.

**Comment by chrisknoll** [comment]
Ok, in that case I can change the icons to font awesome based as part as the circe/calypso merge.  I'll update the milestone for this to 1.0.0.

**Comment by chrisknoll** [comment]
Fixed in commit 6095198f825ac23ce308faa57fdd69beaf93ce3a.
