### ISSUE TITLE
Incorrect RC and DRC reported in Atlas vocabulary

### ISSUE THREAD

**Issue by hajarhomayouni** [OHDSI/Atlas#478]
When I search for a vocabulary (e.g., asthma) in Atlas on my database, the results of RC and DRC are 0 for all of the resulted records. 

I checked the HTTP POST response and it is not [0,0] for some records but Atlas shows it as [0,0].

For example, I can see {"317009":[233057,366704]} in the HTTP respond but in high-level Atlas shows me RC:0 and DRC: 0 for 317009. 

Could you please tell me how I can solve this problem?

**Comment by fdefalco** [comment]
Can you check what data source is checked on the configuration screen for Record Counts RC/DRC.  That controls which counts should appear in the vocabulary search results.
