### ISSUE TITLE
Discrepancy between createCovariateSettings arguments in Atlas Estimation Tab and in FeatureExtraction 2.0.0

### ISSUE THREAD

**Issue by llhester** [OHDSI/Atlas#490]
### Expected behavior
The CohortMethod R code automatically generated within the Atlas Estimation tab should have the most updated arguments from FeatureExtraction 2.0.0.

### Actual behavior
The createCovariateSettings in CohortMethod R code generated in the Atlas Estimation tab has different arguments than FeatureExtraction 2.0.0 (these have not been updated). This led to an error when trying to extract features. This update might need to be made to the CohortMethod package, as well.

### Steps to reproduce behavior
Copied and pasted new arguments from createCovariateSettings in FeatureExtraction 2.0.0 and manually entered "TRUE" or "FALSE." This removed the error.

**Comment by anthonysena** [comment]
Hi - Feature Extraction 2.0.0 is still in testing and so the Atlas CohortMethod R code has not been updated yet to reflect the new ways of working with that particular package. 

The work-around you provide is a good way to approach this if you are in the process of testing FeatureExtraction 2.0.0. I'll keep this issue open as a reminder that we will need to update the Atlas code to reflect these new settings once CohortMethod and the PatientLevelPrediction packages leverage FE 2.0.

**Comment by anthonysena** [comment]
Closing as this was fixed with the v2.3 release.
