### ISSUE TITLE
optional.js missing (Offline mode issue?)

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#491]
### Expected behavior
Working Atlas  :)
### Actual behavior
I am using Atlas in offline mode using the local_cdn zip added to release 1.3.0
When I load Atlas i see the following errors:
Get http://[servername]/Atlas/js/optional.js Uncaught Errors: Script Error for: optional
...
Uncaught Error: load timeout for modules: module: optional!config.local_unnormalized4

### Steps to reproduce behavior
Try offline version?

I am not sure how to dive deeper in this problem. I have added the new config-local.js as described in 
http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas:setup
(notice that the port :8080 is missing in the url on this page. not sure this is needed or is the default anyway?)

I cannot find anything about optional.js in github code.

Is the localInstall zip still complete or does this need additional scripts maybe or is there another issue?

**Comment by PRijnbeek** [comment]
@chrisknoll i think the LocalInstall.zip needs to be updated. I see a lot of changes in main.js that will be overwritten when i replace it with the one in the zip. I also see a lot of extra libraries being used now that are not in the local_cdn folder.

Is there an easy way to fix this?

**Comment by chrisknoll** [comment]
@PRijnbeek : yes, there are new modules being used so main.js needs to be updated as well as the new modules that are referenced via CDN need to be downloaded.   I'll update the release with a new version of the file.

**Comment by PRijnbeek** [comment]
Since I am probably at the moment the only one that has the server in offline mode. It is also fine for me to do this next time Chris. Although I do think more datasources will follow that have no internet connection while running Atlas.

I guess the process is as follows?:

1. figure out from the main.js all the new libraries referenced through http (I do this using a text comparison tool called Beyond Compare)
2. download all these libs and add them to the zip file that needs to be attached to release
3. change all the references in main.js to /local_cdn/...

Am i missing any other steps so I can do this for the next release myself?

**Comment by chrisknoll** [comment]
You got it: anything that's new in the main.js with a https:// in the path means you need to go to that URL, save the content to your /local_cdn folder and modify the main.js to point to the local_cdn path.  After the files are downloaded and the main.js is updated, those things can be zipped together to be attached to the github release (which is optional if you want to keep all this to yourself, but I think it would be very helpful if you produced the zip file and then we can attach it to the release).

Hopefully I'm re-stating everything you described above :)  You have the right steps, and if there's anything that doesn't work out as expected, just let me know and I'll dig through it.

**Comment by chrisknoll** [comment]
@PRijnbeek, I've uploaded a new local install zip:
https://github.com/OHDSI/Atlas/releases/download/v2.2.0/AtlasLocalInstall.zip

Let me know if you have any problems.

-Chris

**Comment by PRijnbeek** [comment]
Hi Chris,

Thanks. This works.

I did the exercise myself and we ended up with the same zip file :)

I will start testing Atlas 2.2.0 now and will post any issues/questions

Peter
