### ISSUE TITLE
How to change the configuration

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#492]
### Expected behavior
If I change the database I want to use for Vocab and record counts this is applied and saved
### Actual behavior
I have no save option. I thought changing  would do a save automatically but that is not true.
### Steps to reproduce behavior
Make a change and refresh the page.

I tried the Clear Configuration Cache button but that did not help. It is also unclear to me what this actually does. I guess this is to avoid the hard refresh?

If its intention is to save and apply by doing a refresh etc it needs a fix and I would simply call it "save" since the user then assumes it is also applied.

Or am I missing something here?

Peter

**Comment by fdefalco** [comment]
The default record count source is defined for the WebAPI based on the source daimon configuration.  Changing it on the configuration tab only changes the settings for the current session.  

We do not have any user specific configuration information or user profiles for how ATLAS behaves or what sources are used and so there is no way to alter the configuration at an individual user, which is what I think you are interested in here. 

The 'Clear Configuration Cache' feature was added to address #447 and does not have any effect on the record count configuration.

**Comment by PRijnbeek** [comment]
Thanks, I actually was interested in setting this for all users but I understand you do not want to allow all users to make that decision. 

But how is the default set for the record count in source daimon? is that simply source_id = 1?

**Comment by fdefalco** [comment]
The default is established the the source daimon of the particular type (results, vocabulary, etc...) that has the highest value in the priority column.  The default is 0 and typically we see people set the priority to 1 when they want to establish the default source daimon to use.

**Comment by PRijnbeek** [comment]
Okay thanks.
