### ISSUE TITLE
Cohort Generation Failed

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#493]
### Expected behavior
Cohort are generated
### Actual behavior
Generation status is Failed
### Steps to reproduce behavior
We have a multi database setup, so each database has its own results schema that contains the heracles tables (i had to add manually because the webapi will not create them for each database in multi database setup).

I have added all the required permissions I think for ohdsi_app on the heracles tables.

How can I find out why it failed? is there a log somewhere in which I can see if there are still access problems/ missing tables etc?

**Comment by gowthamrao** [comment]
Is this something we could also review here http://forums.ohdsi.org/t/ohdsi-tables-architecture-deploying-on-multiple-dbms-platforms/3481


Trying to get the Google spreadsheet referenced in my post completed.

(I know I am not offering the solution, just making sure the relevant information is gathered in one place)

**Comment by chrisknoll** [comment]
We added some logging information to the COHORT_GENERATION_INFO table.  Could you check that table to see what the text in the fail_message column is for the cohort_definition_id?

**Comment by PRijnbeek** [comment]
It is the BadSqlGrammarException again we discussed in #437 

I will continue the discussion there and close this one.
