### ISSUE TITLE
Number of persons in Dashboard has lower scale

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#497]
### Expected behavior
In AchillesWeb the number of persons had a higher scale (2 behind .): 2.13M
### Actual behavior
Now this is changed in Atlas to 2M
### Steps to reproduce behavior
Compare both versions.

I do not know if there was a specific reason for this change, but I would recommend to keep the scale of two for smaller databases.

**Comment by fdefalco** [comment]
resolved in feature-integration branch
https://github.com/OHDSI/Atlas/commit/bb26099897dd18b491827824a47b656a8368ffe9
