### ISSUE TITLE
Enhancement request - Convey problems in cohort with use of concept sets  

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#498]
### Issues
1. When creating a cohort if a given concept set is not used anywhere in the cohort can ATLAS present a message to the user asking if it can be deleted? 
2. If a given concept set is used but references an incorrect domain can this be flagged to the user? 
3. If a given concept set is used but does not reference all of the domains can this be flagged to the user with the domains that are missing? 
### Ideas for Solutions
1. Provide a clean cohort button or present user a warning flag in the concept table alerting the user it is not used and the option to delete the concept set from there. 
2. Provide a warning to the user in the rule that the concept is used incorrectly and/or do so in the concept set table and provide reference to the rule number that incorrectly uses the concept set. 
3. Same as 2 immediately above except add references to the missing domains. 

Tagging posts #283 and #474 as they are related. 
Tagging @fdefalco @ericaVoss @chrisknoll @rmakadia to see what ideas they may have regarding how to resolve the issues. 

Thank you!

**Comment by ericaVoss** [comment]
The first issue is related to #283 and I agree this is important.

**Comment by cgreich** [comment]
Actually, there is 

4. If a given concept is upgraded (invalid_id='U' and exists (concept_relationship record with 'concept replaced by' then flag or update.
