### ISSUE TITLE
ATLAS Temp Tables Length > 22 characters

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#504]
### Expected behavior
Temp tables names are compliant across DBs

### Actual behavior
#collapse_constructor_input
#collapse_constructor_output

Temp table names should be shorter than 22 characters to prevent Oracle from crashing

### Steps to reproduce behavior
I found this by passing ATLAS code through SQL Translate.  I thought I would just relay the warning.

**Comment by chrisknoll** [comment]
Yes, this issue is tracked in the Circe repository under this issue: OHDSI/circe-be#12.  The fix has been applied to that library, and will be fixed in WebAPI for the next release (2.2.1).

If that resolves your problem, please feel free to close this issue.

**Comment by ericaVoss** [comment]
Got it!  Awesome!
