### ISSUE TITLE
Allow override of drug exposure length for Custom Drug Era Cohort Exit Criteria

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#508]
Would it be possible to enhance the Cohort Exit Criteria to ignore the DAYS_SUPPLY or DRUG_EXPOSURE_END_DATE and just use Surveillance Window and Persistence Window (if the user wanted to do that)?

**Comment by chrisknoll** [comment]
Yes, that's possible.  We'll work on incorporating that in an update.

**Comment by pbr6cornell** [comment]
I'm not sure exactly what the suggestion is here, but I think the current cohort definition tool allows for flexibility in defining various options around cohort exit strategy.  If we do decide to add any new feature, we should be clear in our documentation about how it interacts with the other existing parameters.

**Comment by chrisknoll** [comment]
I think the idea is to specify an override of days supply of '0' for the 'Continuous Exposure exit criteria' such that days supply is 0 for all records, and then the surveillance window is added to the drug exposure start date.

Currently, you're forced to apply days supply.
