### ISSUE TITLE
Export SQL feature not working.

### ISSUE THREAD

**Issue by lalitnookala** [OHDSI/Atlas#519]
### Expected behavior
After establishing a cohort, one should be able to go to the  Export tab -> SQL -> choose the flavor and be able to generate the SQL query for the cohort
### Actual behavior
While trying to generate the SQL query, the page shows "Loading" once the SQL is selected but an output is never returned.
### Steps to reproduce behavior

1. Go to http://www.ohdsi.org/web/atlas/#/home
2. Click on Cohorts on the left navigation bar.
3. Search for Cohort id 1663553
4. Go to Export tab once the cohort loads up
5. Click on SQL tab

The SQL query is not generated after waiting for an hour or more.

Thanks

**Comment by fdefalco** [comment]
There appears to be a missing value in your definition that is causing the error.  If you check your qualifying inclusion criteria, criteria number 3 titles PlateletCount is missing a value.  If you add a value and save your definition the SQL should then load properly.
