### ISSUE TITLE
Age unit not displayed

### ISSUE THREAD

**Issue by lalitnookala** [OHDSI/Atlas#520]
### Expected behavior
While establishing a new cohort, when an age criterion is added to inclusion criteria, the unit of age should be displayed, years, month, days etc.
### Actual behavior
Currently, no units are displayed, leaving the user to guess that it probably is in years
### Steps to reproduce behavior

1. Create a new cohort
2. Add an inclusion criterion
3. Add age criterion to the above inclusion criterion
4. You will see a textbox to enter a number for age but the unit is not displayed.

**Comment by fdefalco** [comment]
changing text from 'with age' to 'with age in years'

**Comment by fdefalco** [comment]
will appear resolved in ATLAS version 2.3
https://github.com/OHDSI/Atlas/commit/ba21e2eca6f69da86b8f1dee1dd4e3cf91edc5ba

**Comment by lalitnookala** [comment]
Thank you.

Lalit S Nookala
*Senior Analyst*
(P) 615-294-4723
(E) lalit.nookala@gmail.com

   - www.linkedin.com/in/lalitnookala/
