### ISSUE TITLE
Notification link experience

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#522]
Great notification system, super helpful! @fdefalco @chrisknoll @anthonysena @alondhe 
### Expected behavior
Start a cohort generating for a given datasource, Click notification icon, after Status is COMPLETE, Click on Job Name and land on View Reports page for cohort/data source
### Actual behavior
Start a cohort generating for a given datasource, Click notification icon, after Status is COMPLETE, Click on Job Name and land back on Generation page
### Steps to reproduce behavior
Start a cohort generating for a given datasource, Click notification icon, after Status is COMPLETE, Click on Job Name

**Comment by pbr6cornell** [comment]
Related to #1694

**Comment by pavgra** [comment]
@pbr6cornell , should we treat this one as a copy of https://github.com/OHDSI/Atlas/issues/1819 and close it out?

**Comment by anthonysena** [comment]
Closing this in favor of #1819. Also linking to the work done in #2024.
