### ISSUE TITLE
Condition Drilldown Report

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#523]
### Expected behavior
Select reporting tab, select datasource, select condition report, select a condition, click on treemap tab, scroll down to drilldown report, 1) should see condition prevalence and age decile/prevalence report clearly; 2) should see results from condition prevalence by month report in suitable size font to be visible on the page
### Actual behavior
Select reporting tab, select datasource, select condition report, select a condition, click on treemap tab, scroll down to drilldown report, 1) cannot see condition prevalence and age decile/prevalence report clearly; 2) cannot see results from condition prevalence by month report in suitable size font to be visible on the page
### Steps to reproduce behavior
Using cohort 5223, Select reporting tab, select Optum SES 655, select condition report, select first  condition, click on treemap tab, scroll down to drilldown report, view condition prevalence and condition prevalence by month reports.

**Comment by anthonysena** [comment]
@jhardin29 this issue appears to be resolved in the latest release. I'm going to close it but please let me know if you are still facing an issue here.
