### ISSUE TITLE
Notification job progress reports completion as not 100%

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#526]
### Expected behavior
Completed jobs should be 100%

### Actual behavior
Completed jobs are less than 100% in some cases, and not always consistent (between 90% - 99%)

### Steps to reproduce behavior
Execute a cohort reporting job 
Review % complete when job is marked 'Finished'

### Concerns about implementation
It's possible that the implementation for cohort reporting is polling the results database (haven't reviewed the code) but the concerns is that if this is using analysis_ids from heracles or physically hitting the results database, we could run into problems where 'slot-oriented' database connections (like PDW) will have resources consumed for a simple status check, and counting analysis_ids is something that is very specific to heracles processing, but not  generalizable to other types of backend processing (such as IR calculation, feature extraction, cohort generation).

**Comment by anthonysena** [comment]
Tagging @pavgra - is this closed via https://github.com/OHDSI/Atlas/pull/980?

**Comment by pavgra** [comment]
@anthonysena , yes, that have been fixed by applying consistent approach to Notifications tracking and quite significant refactoring
