### ISSUE TITLE
Cohort Generate with Features not working in 2.3 candidate

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#533]
### Expected behavior
Generate a cohort with features. In the 'Cohort Features', select a concept to explore using the 'Explore' button. The screen will refresh with the concept selected and its ancestors/descendants visible.

### Actual behavior

Clicking on the 'Explore' button doesn't appear to do anything. Here is the error in the console:

![image](https://user-images.githubusercontent.com/12902366/35240828-af2cafe0-ff82-11e7-8947-50dd1aaeccc6.png)

### Steps to reproduce behavior

Generate with features and attempt to explore one.

**Comment by chrisknoll** [comment]
Explore button fixed for 2.3 release.
