### ISSUE TITLE
refresh vocabulary in Atlas

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Atlas#536]
Atlas doesn't show the proper list of descendant concepts for this case 
http://www.ohdsi.org/web/atlas/#/concept/42018423
We figured out that this concept has descendants only in the latest versions of SNOMED.

@leeevans, can you please upload the latest version of the vocabulary into the Atlas?
It's available on Athena: http://athena.ohdsi.org

**Comment by leeevans** [comment]
@dimshitc the OHDSI cloud ATLAS has been refreshed with v5.0 26-JAN-18 vocabulary data
