### ISSUE TITLE
[Negative Controls] Splicer Summary Bug

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#540]
### Expected behavior
Splicer data tells you evidence associated to your concept of interest.

### Actual behavior
Wasn't pulling the codes right.

Put this patch in:
https://github.com/OHDSI/CommonEvidenceModel/commit/79e39ce00b498e74f904c8d52b1e43ded289987c#diff-9eaba0108e94dcd142e3f9a861ddc5e2

**Comment by anthonysena** [comment]
Fixed via https://github.com/OHDSI/WebAPI/commit/7d09e69bb7c0b430c760dafc8ee75496b37dab88
