### ISSUE TITLE
Support VSAC external value sets

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#557]
### Expected behavior
user can take advantage of VSAC value sets 

### Actual behavior
all value sets must be imported in .txt or created from scratch

### Steps to reproduce behavior
n/a

**Comment by Sigfried** [comment]
The Architecture WG has started talking about how to do this. I'm thinking we also might want to support PheKB, and try to align ourselves with other algorithmic repositories beyond OHDSI.

In the case of VSAC, maybe it would be better if OHDSI dispensed with concept sets altogether and used VSAC-based value sets. We'd probably have to extend VSAC and maybe write our own interface to it, but if shared, standardized electronic phenotypes are ever going to be meaningful, we'll have to reach beyond our own community to collaborate on value sets and phenotype definitions. (And if our phenotypes happen to be more powerful than PheKB or whoever we think of coordinating with, we'll have to improve them.)

**Comment by weiskopf** [comment]
I know this is an old thread, but I'm trying to find info on the presence of VSAC value sets in OHDSI, and this is the top hit. Have you been continuing work on this issue? Thanks in advance for any info!

**Comment by lrasmus** [comment]
Hi @weiskopf - @rkiefer from the PhEMA team developed a tool to load value sets from VSAC into OHDSI (https://github.com/PheMA/vsac_to_omop).  We need to look at how to better integrate this, and welcome any input you have.

**Comment by weiskopf** [comment]
Very cool, thanks! I'll check this out, and if I have any thoughts will definitely follow up.
