### ISSUE TITLE
invalid concepts are not included

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/Atlas#558]
### Expected behavior
Deprecated and updated concepts are able to be used for creating cohort definition using 'event_source_concept_id' attribute. 
### Actual behavior
Concept set doesn't include updated or deprecated concepts 
### Steps to reproduce behavior
To allow invalid concepts to be included into codesets
![capture](https://user-images.githubusercontent.com/25959256/35632601-c5102d1c-06af-11e8-85ff-a207420a020f.PNG)

**Comment by anthonysena** [comment]
Linking to OHDSI/WebAPI#136

**Comment by anthonysena** [comment]
@chrisknoll - looking at the work done in https://github.com/OHDSI/circe-be/pull/71, it appears this is issue is resolved. That said, I still see this `invalid_reason is null` code applied on the 2.7.2 build. So I'm a bit confused on where this landed.

**Comment by chrisknoll** [comment]
Hmm, that is odd, the change should be available in 1.8.0.  Where are you seeing the 'invalid_reason is null' being applied?

Maybe it's in the WebAPI layer?

**Comment by anthonysena** [comment]
Maybe - here is a cohort where I see it:

http://www.ohdsi.org/web/atlas/#/cohortdefinition/1770900

![image](https://user-images.githubusercontent.com/12902366/60548659-9ce75080-9cf0-11e9-821f-0577ff24f2ba.png)

**Comment by chrisknoll** [comment]
That's crazy strange. Let me dig into this to see why that is happening.

**Comment by chrisknoll** [comment]
I found it:  https://github.com/OHDSI/circe-be/blob/master/src/main/resources/resources/vocabulary/sql/conceptSetDescendants.sql

This is when it's pulling in the descendants.  The `is null` check wasn't removed from here all concepts in the concept ancestor should be valid concepts.  We could remove it, but I think i was just trying to minimize changes.

Let me know and I'll open up a issue in circe to remove it from the descendant concepts, but if I am correct, it won't make any logical difference.

**Comment by anthonysena** [comment]
Ah thank you for figuring that out! From my perspective, I think it is OK to leave it as-is for the reasons you stated: your using concept_ancestor as part of the JOIN criteria which will only contain valid, standard concepts. At this point, let's not introduce more changes unless its necessary. If you agree, let's close this out. Thanks!
