### ISSUE TITLE
Concept Set Saving Issues

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#56]
Each time the save button is clicked, the dialog box comes up saying 'This concept set is not saved, proceed with changes?'. This would make sense when attempting to clear the set without saving, but not when actively in the process of saving. 

I got stuck in a loop where each time I clicked 'save' a new concept set was created with the same name. Refreshing the application fixed the save loop but now I have three sets all with the same name. Could a way to delete concept sets be added, or have a box pop-up saying that there is already a concept set with that name? This could cut down on confusion when searching for a concept set.

**Comment by anthonysena** [comment]
Hi Clair - I believe we've addressed the save button issue as part of our Milestone V0.9.0 release. Could you check this on hixbeta to see if the behavior is what your expecting?

The other points you raised in terms of: deleting concept sets, making concept set names unique and forcing you to change the concept name if it is still the default "New concept set" are items that we may defer for the next release as they'll require some additional work. 

I'm tagging this issue for our current milestone so we don't lose track of it for the saving portion. Then this may be shifted to the next release to fix these issues. Just reach out if you have any questions!
