### ISSUE TITLE
Missing column at exported SQL when add nested criteria.

### ISSUE THREAD

**Issue by maxtortime** [OHDSI/Atlas#572]
### Expected behavior
When I set Initial event cohort like below
![image](https://user-images.githubusercontent.com/10532570/36364796-a1c6690a-1589-11e8-81d0-e75fc048bcb4.png)

Exported SQL should be below

```sql
with primary_events (event_id, person_id, start_date, end_date, op_start_date, op_end_date, visit_occurrence_id) as
(
-- Begin Primary Events
select row_number() over (PARTITION BY P.person_id order by P.start_date) as event_id, P.person_id, P.start_date, P.end_date, OP.observation_period_start_date as op_start_date, OP.observation_period_end_date as op_end_date, P.visit_occurrence_id
FROM
(
  select P.person_id, P.start_date, P.end_date, row_number() OVER (PARTITION BY person_id ORDER BY start_date ASC) ordinal, P.visit_occurrence_id
  FROM 
  (
  select PE.person_id, PE.event_id, PE.start_date, PE.end_date, PE.target_concept_id, PE.visit_occurrence_id FROM (
...
```

### Actual behavior
But Exported SQL didn't contain `PE.visit_occurrence_id` and query cannot be executed.

### Steps to reproduce behavior
1. Create Cohort
2. Setting Criteria and Nested Criteria on Initial event cohort
3. Go to Export
4. See the SQL from MSSQL Server tab.
5. Check missing column.

**Comment by chrisknoll** [comment]
Yes, this has been fixed in circe-be 1.4.0, and will be available in the next WebAPI release.
