### ISSUE TITLE
Incorrect limitation of initial events

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/Atlas#575]
### Expected behavior
If 'Limit initial events to all events per person' is chosen, all events of interest are captured in cohort.
Number of records is expected to be greater then number of persons.
### Actual behavior
Only earliest event per person is chosen and number of records is always equal to number of persons

**Comment by chrisknoll** [comment]
Could you post your test case to http://www.ohdsi.org/web/atlas/?

**Comment by chrisknoll** [comment]
Discussed on forum: http://forums.ohdsi.org/t/limit-cohort-expression-results/1329 and closing here.
