### ISSUE TITLE
Missing concepts

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Atlas#586]
### Expected behavior
When "heart", "cardiac", "foot", "smoke", etc. is entered into the vocabulary search bar, it should return results related to the string

### Actual behavior
All of the above searches return zero results

### Steps to reproduce behavior
Type one of the above terms into the search bar and click enter

**Comment by leeevans** [comment]
@MelaniePhilofsky there was an issue with the OHDSI Atlas connection to the database.  That issue has now been resolved. Please add a comment if it is now resolved for you and I can close this issue.

**Comment by MelaniePhilofsky** [comment]
Now resolved. Thanks @leeevans
