### ISSUE TITLE
Problem about the ATLAS

### ISSUE THREAD

**Issue by ZHU-C** [OHDSI/Atlas#588]
Hello everyone：
I'm a student at NANJING MEDICAL UNIVERSITY in China and  doing some researches about OHDSI now.
However after I downloaded the Atlas 2.3.0 and configured ,I find the Atlas page with blank,like the picture below
![9jq2kbeqw h6wzkb jche82](https://user-images.githubusercontent.com/37094768/37013313-304d645c-2134-11e8-8b49-1d90a5446e27.png)
And this is the config-js 
`define([], function () {
	var configLocal = {};

	// clearing local storage otherwise source cache will obscure the override settings
	localStorage.clear();

	// WebAPI
	configLocal.api = {
		name: 'OHDSI',
		url: 'http://localhost:8000/WebAPI/'
	};

	

	return configLocal;
});
`

PS.I have changed the tomcat several port to 8000 already.
I just wonder if someone can help me run the Atlas correctly.
Sincerely
ZHU.

**Comment by alondhe** [comment]
Can you post the console errors thrown by your browser?

**Comment by t-abdul-basser** [comment]
And Tomcat logs :) if possible...

**Comment by chrisknoll** [comment]
I'm working with @ZHU-C through this form post: http://forums.ohdsi.org/t/have-some-problmes-about-atlas/4102/10. I don't think it's a WebAPI/Atlas issue, but will close this once it's resolved.

**Comment by t-abdul-basser** [comment]
Thank you @chrisknoll. Understood.
