### ISSUE TITLE
Remove cachebusting from AMD configuration

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#591]
### Expected behavior
Loading resources from server should be based on HTTP caching settings specified in headers

### Actual behavior
One of the PRs from 2.3 introduced a cache busting routine that tags all resources loaded by the AMD loader with ?={some hash value}.  

### Steps to reproduce behavior
Open chrome dev tools, load atlas, and view network panel. You will see certain resources downloaded with a hash suffix on it.

**Comment by chrisknoll** [comment]
@pavgra and @OHDSI/odysseus : I think this was introduced with one of your later PRs in version 2.3.  Before removing this feature, could you explain why you needed it?  We've gone through several years of Atlas releases without this enabled, and with the proper cache headers fromt he HTTP server, the browser will properly reload dirty files from the server.

**Comment by pavgra** [comment]
@chrisknoll, I am not sure, which HTTP server you are talking about, but the one, which servers ohdsi.org/web/atlas returns following:
```
Expires:Wed, 11 Jan 1984 05:00:00 GMT
```
Which is not correct, and as I understand, caching is just disabled. In other case, if we turn some expire date, it is always unpredictable, how big it should be. If it is big - browser will not refetch files and of course will not know about file's changed datetime. In opposite case - whole idea of caching is killed. Typically, the issue is solved by generation of such name for JS bundle, which either fully comprises
random hash, or consist it in filename. But since you reject usage of bundlers, this is not an option. That's why such mechanism was suggested to overcome cached and not updated resources.

**Comment by chrisknoll** [comment]
Well the Expires is set in the past to disable cachine, so maybe that's the behavior of the webserver.

The HTTP server I was referencing was our internal IIS servers which support 'ETag' headers which basically creates a hash of the file and returns that hash in the HTTP header as 'ETag': <hash>.  Clients requesting resources will send the last known 'ETag' value and if the server has the same hash of the resource, a 304: Not Modified is returned as shown here:
![networkrequests](https://user-images.githubusercontent.com/6818777/37780308-e07bced0-2dc4-11e8-8091-6c046dbdc533.png)
![headers](https://user-images.githubusercontent.com/6818777/37780303-de674b10-2dc4-11e8-9c0d-1a8b436348fc.png)

So, ohdsi.org should enabled ETags so that caching can be leveraged based on file modification.

My point is:  I'm not in favor of applying an application work around for things that should be controlled at the webserver layer.  Additionally, this has some negative side effects:  You have to properly remove the cached hash value from the local storage or else the prior hash will continue to be used.  And, when the hash does change, any breakpoints you've set up (in chrome dev tools for this example) get cleared because /js/components/someModule.js?hash=hash1 is not the same resources as /js/components/someModule.js?hash=hash2 so it will wipe out any breakpoints.

But, I'd be fine with all of this if  it was an a state that could be disabled by default and enabled by configuration.  In our environments we'd disable it, but if you need it, you'd enable.

**Comment by chrisknoll** [comment]
> In opposite case - whole idea of caching is killed. Typically, the issue is solved by generation of such name for JS bundle, which either fully comprises
> random hash, or consist it in filename. But since you reject usage of bundlers, this is not an option.

I'd like to ask that you please don't misrepresent my position on bundlers.  We do use bundlers, Atlas charts is a bundled component and we consume it from the NPM:
```
"atlascharts": "https://unpkg.com/@ohdsi/atlascharts@1.1.0/dist/atlascharts.min",
```

It is my opinion, tho, that in the case of Atlas, it's an enormous application so creating one big Atlas bundle that would probably be several megabytes to download in 1 shot any time a minor change is made is definitely something I'm prone to avoid.  The AMD module loading system we have allows us to download only those assets which change (via the ETag caching described above) and we could move to have some portions of the application bundled into chunks that might make sense.  But it's absolutely not true that I'm against bundlers.  I'm against bundlers as a prerequesite to develop code, but I consider bundling a release step, not a development cycle activity (but I know I'd get a lot of disagreement). I don't want to drag this thread into an argument about bundlers, but I did want to say "please don't make blanket statements about my position on the use of bundlers".

**Comment by chrisknoll** [comment]
@leeevans : It appears that ohdsi.org/atlas is running on Apache 2.4.18, and I found documentation about FileETag:
https://httpd.apache.org/docs/2.4/en/mod/core.html#fileetag

Is it possible that this could be enabled so that resources returned by the webserver can have an ETag header included?

**Comment by leeevans** [comment]
@chrisknoll I've forwarded you an old email trail related to this request.
I believe the outcome of that email was to turn off the cache on OHDSI cloud so that users would immediately see the latest Atlas application files when a new release was auto deployed.

Let me know if you want the ETag restored in the header. There is a proxy in the middle so that may also need to be adjusted.

The cache was turned off using the below config in httpd.conf

<filesMatch "\.(html|htm|js|css)$">
  FileETag None
  <ifModule mod_headers.c>
     Header unset ETag
     Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
     Header set Pragma "no-cache"
     Header set Expires "Wed, 11 Jan 1984 05:00:00 GMT"
  </ifModule>
</filesMatch>

**Comment by chrisknoll** [comment]
I think we want the FileETag. That will let the browser say 'I have in my cache a file with this etag' and the server can say 'Ok, you got the latest: here's a 304: Not Modified result'.

But by unsettling the ETag, the browser can't do that.  Did you want to try to enable FileETag and I can check to see if the headers get dropped in the requests?

Btw: the filesMatch regex: it's possible that will match on requests for somefile.js but not somefile.js?hash=alalsk12.  I could be wrong there, but can we try with setting the ETag, and if that fails, we might  need to adjust the filesMatch to also allow an optional query string at the end of the filename.

I wouldn't do any of this now due to the OHDSI symposium being active, maybe we can pick this up early next week?

**Comment by chrisknoll** [comment]
Also reading up here: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching.  They talk about no-cache and no-store, I think the option we would want here is only 'no-cache' but I'll keep reading up on it.

**Comment by leeevans** [comment]
@chrisknoll OK ping me next week

**Comment by anthonysena** [comment]
Noting that I'm unsure if this is a performance item or if this discussion is no longer relevant. Let's decide how to proceed with this one as part of the 2.8 planning.

**Comment by pbr6cornell** [comment]
@chrisknoll or @leeevans , please determine status of this issue.

**Comment by chrisknoll** [comment]
Since the prescribed mode of running the application is to bundle the application, I don't believe the question of 'cache busting' is an issue anymore.
