### ISSUE TITLE
Concept Picker needs loading indicator

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#595]
### Expected behavior
When searching, a loading spinner will give feedback to user that the concept query is happening.

### Actual behavior
No spinner, so a user can type in one search term followed by a second search, and while they are working on the results of the first search, the second search completes and replaces the table results with the new search.

### Steps to reproduce behavior

Create a criteria (like condition) and add a condition type criteria.
Click Add
Type IP and enter
clear search and enter

What happens:  The IP search results will appear, and then shortly after, the results will be replaced with all results. This is because there were multiple queries  being executed, and the last one finishes and overwrites the results.

Another option is to cancel pending searches.

**Comment by anthonysena** [comment]
On the 2.7.2 build, searching now will load a "loading" indicator. ATLAS still allows you to submit multiple searches which is a bug. We should disable searching while a vocabulary search is in progress.
