### ISSUE TITLE
Display menu items based on user permissions

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#596]
### Expected behavior
We should have a consistent experience across sections for users who lack permissions to use a section.

### Actual behavior
No error message is displayed whereas on other tabs there is a 'Feature is protected' warning

### Steps to reproduce behavior
Go to configuration tab while not logged in

### Broader Discussion
I think it might be beneficial for us to customize the appearance of the left menu based on the permissions of the current user.  This way we could simplify the user interface for people who are only consuming evidence versus working on developing content.  Using this paradigm we would only show options in the menu that a user has permissions to use instead of listing all options and then individual error messages as they try to use each one.

**Comment by anthonysena** [comment]
I believe that this issue was addressed as part of #601. I will leave this open so that we can focus on the idea around the "broader discussion" as I agree that it would be useful to only show those features which a user can access.

**Comment by anthonysena** [comment]
Closing in favor of OHDSI/WebAPI#2236.
