### ISSUE TITLE
Add ability to select >1 concept sets for covariates to include/exclude from PS

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/Atlas#597]
### Expected behavior
When creating PLE at least 2 anchor concept sets for (target and comparator drugs) can be included.

### Actual behavior
Only 1 concept set can be included to included/excluded covariates.
Thus separate concept set should be created for this

**Comment by anthonysena** [comment]
@eldarallakhverdiiev - The challenge here becomes resolution of the concept sets into a list of concepts. - For example consider if you have 2 concept sets and one concept set explicitly **excludes** a concept while the other **includes** the concept. In this situation, do we include or exclude the concept?

I think in this instance, the user creating the estimation specification needs to explicitly create a single concept set for covariate inclusion/exclusion. Perhaps there is another approach for combining concept sets so I'd appreciate any feedback. Thanks!

**Comment by eldarallakhverdiiev** [comment]
Not sure that I understood you correctly . I imagine the next use case : for some PLE there are 2 cohorts where one is based on all patients used from drug_concept_set_A and another one - drug_concept_set_B. I guess that for propensity score adjustment both drug_concept_set_A and drug_concept_set_B should be excluded because of high and non-useful correlation.  
Right now for this purpose there should be created separate 
drug_concept_set_C which includes drug_concept_set_A and drug_concept_set_B. 

My proposition was to avoid step of creating additional concept set by allowing 
inclusion of several concept sets in PLE specification tab.Does it make sense?

**Comment by anthonysena** [comment]
Thanks @eldarallakhverdiiev - that does make sense. I understand your use case here - we'd like to avoid creating a seperate concept set (drug_concept_set_C) but instead express that as: (drug_concept_set_A + drug_concept_set_B).

The assumption that is made here is that the concepts included in drug_concept_set_A are unique and can be combined with drug_concept_set_B to create drug_concept_set_C. However, that uniqueness cannot be guaranteed and therefore combining two concept sets may require further decision making. Take the following (hypothetical) example: 

Concept Set A includes concept_id = 123456
Concept Set B excludes concept_id = 123456

If we want to create Concept Set C by combining Concept Set A and Concept Set B, what do we do with concept_id = 123456? We could attempt to create rules for handling these types of conflicts when combining these concept sets into Concept Set C. However, this feels more complex compared to having a user explicitly define Concept Set C.

I think the context of a PLE and thinking about covariates to include/exclude, it is unlikely that 2 concepts sets you'd like to use for including/excluding covariates would overlap in the way I described but again, there is no way to guarantee it.

I hope that this example makes my previous post clearer.
