### ISSUE TITLE
cdm sources visible without permissions

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#599]
### Expected behavior
Users are only able to see sources they have permissions to generate cohorts.

### Actual behavior
If a user does not have permissions to a source CDM the source still appears in the list available for cohort generation. An error occurs when the user attempts to generate the cohort however no user feedback is provided and the cohort appears to be processing.  

### Steps to reproduce behavior
Visit the cohort generation tab on a cohort with revoked permissions to a source.

**Comment by anthonysena** [comment]
Tagging @pavgra for comments as this may have been addressed in the most recent release.

**Comment by pavgra** [comment]
Was fixed:
![image](https://user-images.githubusercontent.com/10010071/48441537-cf403f80-e759-11e8-9cc7-ea9df5650732.png)
