### ISSUE TITLE
Cleanup moduleIDs from main.js

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#611]
### Expected behavior
We should have a clean set of module paths in the main.js requirejs.config() options that allows us to add new components to the system without having to modify configuration.

### Actual behavior
We have a one-module-per-config-entry situation that means adding new components requires configuration change, when it could be set up that just adding the component to the components folder will make it available.

### Steps to reproduce behavior

When creating a new compoent, you place the component and template under /components/myNewComponent.js[.html].  The current pattern is to add a new path entry in the configuration like so:
```
		"configuration": "components/configuration",
		"concept-manager": "components/concept-manager",
		"conceptset-browser": "components/conceptset-browser",
```

What should happen is that these moduleIDs prefixed with 'components/' should be removed from the config, and in the application, when the module is refernced it shoudl be referenced as 'compoents/{moduleName}'.  Then, any time a new component gets added we just place it in the filesystem with the proper filename=moduleID, and then we can reference it as components/{moduleId}.  

We also might consider putting our components into subfolders, or make another top-level folder under /js that contains other groups of modules (like utils, tests, vizualziations) and we can refer to those compoentns in those folders as {topModuleFolder}/{moduleId}, and have all this without needign to ever modify the configuration file.

**Comment by anthonysena** [comment]
This feels like something we should undertake in conjunction to the work @pavgra proposed in #633. I'd propose we track this as part of #633 and I'll close this for now.

**Comment by chrisknoll** [comment]
Actually I think i'd leave this open, it's related to #633, but this specifically talks about how we're managing our configuration file.  Even with the work done in #633, we could have one-module-per-config entries remain, and then we haven't addressed this issue.

**Comment by anthonysena** [comment]
No objections to re-opening - we can track configuration specific topics here.

**Comment by pbr6cornell** [comment]
What specifically do we need to align on and execute for ATLAS 3.0?

**Comment by anthonysena** [comment]
Looking at the current `/js/main.js` on master, this appears to have been addressed at some point so closing this out.
