### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jingsongs** [OHDSI/Atlas#615]
Could this program and some dependent packages  be installed on Ubuntu?   Thankyou.

**Comment by anthonysena** [comment]
I'm not sure if others in the community have attempted to run WebAPI/Atlas on Ubuntu. I'd suggest taking a look at the installation and configuration guides if you would like to attempt to set up the application:

WebAPI: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:webapi_installation_guide

Atlas: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas

If you have any issues, please feel free to post them up here and we will do our best to support you.
