### ISSUE TITLE
Ability to copy inclusion rules in other cohorts

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#618]
Currently we cannot copy an individual inclusion criteria into a new cohort an enhancement would be the ability to copy an inclusion rule and its concept set into a new cohort

**Comment by pbr6cornell** [comment]
If I understand this correctly, much like we have a conceptset library, and a cohort library, you'd like to have a 'inclusion criteria' library, which can allow for importing into a cohort during the design phase?

**Comment by rmakadia** [comment]
Yes! That would save a lot of time for standard inclusion rules that get implemented exactly the same for each cohort that's created

**Comment by anthonysena** [comment]
Closed via #2623.
