### ISSUE TITLE
Ability to toggle inclusion rules "on and off" when generating cohorts

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#619]
To have the ability to toggle inclusion rules on and off (with a check box button) when generating cohorts so that the time to generate results is shortened when exploring how different rules work

**Comment by pbr6cornell** [comment]
What is the desired behavior when an inclusion rule is 'checked off'?  Do you want the cohort to pretend as if the inclusion rule doesn't exist at all, but keeping it there rather than deleting it so that it can be used in other copies/runs?

**Comment by rmakadia** [comment]
Yes @pbr6cornell that is correct. When trying to understand the effect of a single criteria among a long list, we have to wait until all the rules are evaluated. Having the ability to just evaluate a few rules to understand if they were implemented correctly, or need modification would save a lot of time.

**Comment by cgreich** [comment]
@rmakadia: But that only makes sense if you actually generate. In E360, the commercial tool IQVIA is building, the criteria are applied on the fly, and you can see the effect before running any cohort generation process and then looking at an attrition report. Here, in ATLAS, you need to generate, and that takes time. True what-if scenarios are somewhat awkward that way.

**Comment by chrisknoll** [comment]
@cgreich  raises a good point:  in Atlas, when you generate you see the impact across all inclusion rules. You don't need to turn anything on or off, you can see (either via the % to gain or the intersection report) exactly how all inclusion rules impact cohort selection.  What would the purpose of turning it off do?  It's true that execution time would be shorter, but running it 10 times to check 10 combinations vs. 1 time and seeing all 10 combos together...wouldn't that be more efficient?

**Comment by rmakadia** [comment]
The purpose of having the feature would be when we are still trying to explore or understand how a particular rule makes an impact to the index cohort. Building our cohorts for the purposes of clinical trial feasibility requires us to input upwards to 50 inclusion rules, most of which are standard that we don't need to change or think about too much but there are some when that need extra care and evaluation. After creating the cohort with all the rules, running it 10 times multiple by the number of rules is a very long time just to understand/evaluate 1 or 2 key rules...there are plenty of ways to work around this currently such as copy the cohort and just look at one or two rules or input all variations and look at % gain as @chrisknoll suggested. This feature would be a nice to have for sure just to save generation time.

**Comment by chrisknoll** [comment]
Understood, @rmakadia , thanks for clarification.

**Comment by anthonysena** [comment]
Closed via #2726
