### ISSUE TITLE
Replace parameters in the SQL generated for cohort construction prior to copying to clipboard

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#621]
### Expected behavior
Select the SQL dialect of choice
Similar to SQL render shiny app - replace @vocabulary_database_schema, @cdm_database_schema thru a UI
copy SQL from Export tab of Cohorts using clipboard

### Actual behavior
Can copy using copy to clipboard option, but have to
do a find and replace of parameters

### Steps to reproduce behavior
Construct a cohort
Go to export table --> SQL

**Comment by anthonysena** [comment]
Closing this as it is related to OHDSI/WebAPI#656 and will also note that http://data.ohdsi.org/SqlDeveloper/ is a nice resource for working with OHDSI-SQL.
