### ISSUE TITLE
Cohort definition gracefully handling null criteria

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#624]
## Current behavior

The current 'bug' is if you open a section (like 'initial event inclusion criteria' beneath the initial event), but you don't include at least one criteria, then it doesn't know how to handle that.

Here's a screenshot of what it did look like before I fixed it:

![image](https://user-images.githubusercontent.com/731930/38156957-449621e0-3450-11e8-8e79-c3b6ee36981c.png)

To correct, this I just clicked the red button: 'Remove initial event inclusion criteria', which gives this view:

![unnamed](https://user-images.githubusercontent.com/731930/38156975-64546bcc-3450-11e8-8367-42fa56aa4e84.png)

### Desired behavior

If a user incorrectly opens a 'null' section in the cohort definition, perhaps the UI should warn the user and/or remove the null section before generation?

**Comment by anthonysena** [comment]
Tracking this under #498 as this could be handled as a diagnostic check that could also disable the generation of a cohort.
