### ISSUE TITLE
Feature Report Drug domain name could be clearer

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#626]
### Expected behavior
Click on the drug button for a cohort where a feature report has been generated. The screen presents the drug names and cohort counts and proportions. There is no indication that the drugs are drug eras or drug exposures, unless the user clicks column visibility and selects the covariate name column. 
Could the drug button instead be labeled drug eras to make it clearer to those reviewing?

**Comment by anthonysena** [comment]
The feature report was depreciated in v2.6.0 and so I'm closing out this issue. @jhardin29 let me know if you have any concerns.
