### ISSUE TITLE
ATLAS UI fails to load JS resources

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Atlas#628]
### Expected behavior
All JS resources are loaded properly by browser.

### Actual behavior
In some corporate networks with proxy/firewall unpkg.com host is not in whitelist.
It's the reason that
https://unpkg.com/@ohdsi/atlascharts@1.1.0/dist/atlascharts.min.js file is not loaded and UI fails to start.

### Suggested fix
Include atlascharts.min.js file in local static resources. OR give a possibility to override require.js configuration file to re-set the library paths.

**Comment by pavgra** [comment]
@konstjar, second option - give a possibility to override JS libraries location, looks more reasonable to me.  In such way it would be possible to exclude usage of CDN resources in favor of local ones. Just wondering, may be there already exists such hidden possibility? May be @fdefalco or @anthonysena knows?

**Comment by anthonysena** [comment]
@konstjar, @pavgra - as far as I know, we don't currently have a way to override the locations of these libraries through configuration. The concern I have here is keeping things synchronized - if we need to update a JS library, how will this impact others that are sourcing the library from a local copy or another whitelisted CDN?

If we can decide on a design here, it would be a nice contribution to enable this type of configuration.

**Comment by pavgra** [comment]
@anthonysena , I thought of smth like this (just pseudo-code):
```
const localLibs = require('local-libs');
requirejs.config({
  paths: {
    "someLib": "https://internet.com",
   ...localLibs,
  }
});
```

**Comment by chrisknoll** [comment]
requirejs supports fallbacks in the event a CDN resource fails.  See here: https://stackoverflow.com/questions/12073768/requirejs-local-fallback-for-if-cdn-fails?answertab=active#tab-top

```
// in your requirejs config
requirejs.config({
    paths: {
        jquery: [
            'http://somecdn.com/jquery.min', // your cdn
            'lib/jquery' // your fallback
       ]
    }
});
```

The sad part is that we have to now bundle the external libs inside the repo, which is something I'd like to avoid.

**Comment by chrisknoll** [comment]
We can use package.json to configure dependencies, most (if not all) of the CDN dependencies probably have a NPM package that bundles the resources.  We can modify our require.js config to use the fallbacks to load the local resources.  The only extra step for people who need self-contained resources is they will have to ```npm install``` at a command line to get the resources downloaded.  This additional step will no doubt spawn additional support questions.

**Comment by pavgra** [comment]
@chrisknoll , I think, we should use external resources as fallback. Otherwise, it will try to reach the internet first which we try to avoid.

**Comment by gklebanov** [comment]
The security policy will generally prohibit all external communication. If the application that is deployed on internal network  will try to communicate with the outside world, it will not pass the security assessment and will not be approved to even be deployed.

**Comment by pavgra** [comment]
@chrisknoll, @gklebanov, what we have today:
- there is a will to change project code and not wait for bundle assembly (@chrisknoll)
- there is a need to remove usage of CDNs and other external resources

I believe, the solution which should work:
- leave all entries for local project files in the `requirejs.config` -> `paths` prop as-is -> we won't need to rebuild a bundle each time a change occurs
- bundle all external libs into a single file and declare it for requirejs via `bundles` property (https://stackoverflow.com/a/31865443). This will require one-time compilation of external deps, which doesn't prevent us from changing project w/o a need to re-assemble it all, but reduces amount of network calls & makes all ext libs to be stored locally. Also, listing of all the external libs will be stored in a single place -  `package.json`

**Comment by chrisknoll** [comment]
Right, I'd thought of this myself:  no building between code changes, but allow for a 'package' type of build that would combine fines and minify into something more appropriate for production deploys.  

I've never found the cycles to work through this myself, but if you guys have a need for it, and you can be transparent about the approach, I'm all for it. I'm assuming you'd want to set up additional script actions in pacakge.json so you can do things like ```npm run pacakge``` or maybe you are thinking another builder tool like grunt, gulp, or just scripting webpak?

You don't need to wait for anything from me, if you guys are introducing a 'deploy-time' process to get all the assets into a local bundle for faster downloads and no external CDN dependencies, I won't stand in the way of that. My only concern was that we don't burden our dev cycle to run a toolchain, and it sounds like you have an approach that can get us the best of both worlds.
