### ISSUE TITLE
Display RC / DRC of current concept on Hierarchy View

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#63]
Currently RC / DRC are only available for the parents and children but not the current record

**Comment by anthonysena** [comment]
+1 to this - you'll likely have seen it upstream since you selected it and this would be a nice place to see it again.

**Comment by fdefalco** [comment]
resolved in feature-integration branch
https://github.com/OHDSI/Atlas/commit/9821d5c64572f8f4ab5847d11ebe67a9feb5046a
