### ISSUE TITLE
Non-ajax login will not retrieve permission in new version WebAPI

### ISSUE THREAD

**Issue by SBylemans** [OHDSI/Atlas#637]
### Expected behavior
When performing a login through an endpoint that does not use an ajax call, the permissions for the user are initiated in AuthAPI.js.

### Actual behavior
There are no permissions present in the AuthAPI.js

### Steps to reproduce behavior
Login through an endpoint that does not use ajax calls e.g. Google, OpenID, FB,...

This happens due to pull request 316 on WebAPI. The permissions are no longer present in the token and therefore are not instantiated when redirecting to _/welcome/:token_ after logging in through a service that does not use ajax.

### Possible solution
Add a call to the permission endpoint in WebAPI when rerouting from _/welcome/:token_ (in app.js replace the routing code for _/welcome/:token_ ) :

   ```javascript
'/welcome/:token': function (token) {
                        require(['welcome'], function () {
                            authApi.token(token);
                            $.ajax({
                                url: config.api.url + "permission",
                                method: "GET",
                                headers: {
                                    Authorization: authApi.getAuthorizationHeader()
                                },
                                contentType: 'application/json',
                                success: function (permissions) {
                                    permissionStrings = permissions.map(function(element){
                                        return element.permission;
                                    })
                                    authApi.setPermissions(permissionStrings.join("|"));
                                }
                            });
                            document.location = "#/welcome";
                        });
                    },
```
**EDIT**
The proposed solution retrieves all the permissions present in WebAPI, we can still solve it this way but requires an endpoint in WebAPI to retrieve the permissions of the logged in user. (eg _/user/permissions_)

**Comment by pavgra** [comment]
Permissions now are loaded each time you open Atlas
https://github.com/OHDSI/Atlas/blob/master/js/services/AuthAPI.js#L63
