### ISSUE TITLE
some datatable problem

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/Atlas#648]
### Steps to reproduce behavior

open chrome debugger
navigate to:  http://www.ohdsi.org/web/atlas/#/concept/44833365
(after loading) click on hierarchy tab

Page seems to load ok, but console logs error message:

`Uncaught TypeError: Unable to process binding "dataTable: function (){return {
									data:currentConceptArray,options:{
										dom:'t',language:{
											search:'Filter Broader Concepts: '},rowCallback:model.contextSensitiveLinkColor,lengthMenu:[[-1],['All']],orderClasses:false,ordering:true,order:[[ 6,'desc']],columns:[{ title:'Id',data:'CONCEPT_ID'},{ title:'Code',data:'CONCEPT_CODE'},{ title:'Name',data:'CONCEPT_NAME',render:model.renderLink,width:'50%'},{ title:'Class',data:'CONCEPT_CLASS_ID'},{ title:'RC',data:'RECORD_COUNT'},{ title:'DRC',data:'DESCENDANT_RECORD_COUNT'},{ title:'Distance',data:function(d){ return Math.max.apply(Math,d.RELATIONSHIPS.map(function(o){return o.RELATIONSHIP_DISTANCE;}))}},{ title:'Domain',data:'DOMAIN_ID'},{ title:'Vocabulary',data:'VOCABULARY_ID',width:'100px'}]}} }"
Message: Cannot read property 'nodeName' of undefined
    at t.<anonymous> (jquery.dataTables.min.js?_=46sytf:116)
    at t.iterator (jquery.dataTables.min.js?_=46sytf:100)
    at t.<anonymous> (jquery.dataTables.min.js?_=46sytf:116)
    at Function.add (jquery.dataTables.min.js?_=46sytf:103)
    at update (knockout.dataTables.binding.js?_=46sytf:84)
    at function.a.j.q (knockout.min.js?_=46sytf:66)
    at l (knockout.min.js?_=46sytf:44)
    at Object.a.w.a.j (knockout.min.js?_=46sytf:47)
    at knockout.min.js?_=46sytf:66
    at Object.o (knockout.min.js?_=46sytf:10)`

**Comment by Sigfried** [comment]
Not sure if this is related or a separate bug. Also, I can't replicate this on public site because my chrome break points don't work there for some reason. But on my local instance (http://127.0.0.1:xxx/#/concept/44833365), when I put a break point at: https://github.com/OHDSI/Atlas/blob/master/js/components/concept-manager.js#L467, I see that `currentConceptObject` isn't being found in `related`, so `undefined` is being pushed onto `currentConceptArray`, which is probably not the right behavior. What's supposed to be happening there? Since I can't get break points working on the public site, I'm not sure if it's something with my setup.

**Comment by Sigfried** [comment]
Thanks, Anthony.

I'd offer to fix it except: (1) the branch I'm working on is all experimental stuff, so you don't want that; (2) I haven't worked on ATLAS in quite a while and am not sure I'm up on the conventions for making simple bug fixes (make a bug fix branch, I suppose, and then do a PR?), and (3) my fix (the `if` below) gets rid of the error, but I'm not sure if the next two lines are still supposed to run.

						$.when(densityPromise).done(function () {
							var currentConceptObject = _.find(related, c => c.CONCEPT_ID == self.currentConceptId());
							if (currentConceptObject) {
								self.currentConceptArray.push(currentConceptObject);
							}
							self.model.relatedConcepts(related);
							relatedPromise.resolve();
						});

**Comment by anthonysena** [comment]
Thanks @Sigfried for the offer to fix. If you would like to take a pass at fixing this error, you are correct in that you should create a branch off the latest code in master, make your fixes on that feature branch and then submit it as a PR and one of us will review it. 

For reference, we have a set of best practices for developers that may be helpful here: http://www.ohdsi.org/web/wiki/doku.php?id=development:ohdsi_github_projects_v2

The code you referenced looks like the right place to make the changes; to confirm the location, you are looking in js/app.js for this or somewhere else?

**Comment by anthonysena** [comment]
Closing and relating to #1063. We should warn when attempting to browse the hierarchy for non-standard concepts.
