### ISSUE TITLE
Atlas UI to export SQL - copy SQL, after filling the parameters

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#657]
### Expected behavior
Option to replace 
@cdm_database_schema
@target_database_schema
@target_cohort_table
@target_cohort_id
 while copying to clipboard

### Actual behavior
No such option to replace parameters.

### Steps to reproduce behavior
N/A

This functionality exists in SqlRender, but having it integrated in Atlas would make it easier for the analyst.

**Comment by pbr6cornell** [comment]
You should use SqlRender package, which allows you to replace all
parameters AND translate the SQL that whatever source database environment
you have.

**Comment by gowthamrao** [comment]
You are right, SqlRender can do it, but if we support this functionality in Atlas - it would be much easier.?

Using SqlRender: The process would be (as I understand it) copy the OHDSI SQL into the SqlRender R Shiny app, or put the the OHDSI SQL into a file and have SqlRender R package read it. Pass in parameters and we get the translated output either an another file or in the R Shiny app.

But Atlas already does all/most of that when we generate the cohort within Atlas. So maybe it will reduce the number of steps needed and make it easier by letting us use the same tool and not have to go to SqlRender.

Sorry - I should have said, the request was to integrate the functionality already in SqlRender into Atlas (correcting my post above).

**Comment by chrisknoll** [comment]
The only issue is how we get those parameters from the user.  Today, on the export tab, it's just a sort of -read-only view of the script, with no user input elements.  Maybe at the bottom if we add a button letting the user specify options, and a reload button (because we wouldn't want to regenerate the sql every keystroke or even every field change...set all the field values then click 'reload'

**Comment by anthonysena** [comment]
For those that desire the ability to translate OHDSI-SQL to their RDBMS SQL dialect and to replace parameters, I'd recommend using:

http://data.ohdsi.org/SqlDeveloper/

**Comment by anthonysena** [comment]
Closing in favor of OHDSI/WebAPI#656.
