### ISSUE TITLE
cohort generate with feature - add information about concepts 

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#659]
When we look at the features generated in this function, we get summary information about a concept. Summaries are reported at the concept-names, but concept-names are not unambiguous.

In this example generated from SynPuf data Oxycodone is repeated multiple times - but each row record has different person-count and %of cohort information. To understand the difference between the different Oxycodones we will need the concept_id, concept's vocabulary, concept class id - in addition to concept name.

![image](https://user-images.githubusercontent.com/13936600/39161306-10faed38-473e-11e8-81bf-7ea76c1bfc8b.png)

Please add concept_id, concept_name, concept_class_name, domain_name with hyperlink to concept_id details (new tab)

**Comment by anthonysena** [comment]
Closing as this functionality was depreciated with the v2.6.0 release.
