### ISSUE TITLE
Bring back link to patient profile from cohort

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#660]
### Issue detail
There was a functionality where we could use the patient profile to visualize the natural history of a person identified thru cohort generation process. We could go to 'Report' tab of Atlas under cohort generation, and a list of person_id's that are in the cohort would appear. We could filter the persons based on demographic, conditions, procedure criteria and then select any person in the list. When selected, the person's profile would come. All data about the person from their first to last entry in the CDM would be presented. The cohort period (between cohort start date and cohort end date) would be highlighted, while the period before and after the cohort period would be lighter in color. 

This functionality was very useful to do a sanity check to see if the cohort generated is accurate. It also helped to understand baseline of the person and visually understand the characteristics of the person when they became eligible for the cohort, and natural history leading to that eligibility. Studying such case series, helped with brainstorming ideas worthy of research.

This functionality of linking the person generated thru cohort generation is now gone.

### Potential solution
Bring it back. With the redesign of the Report tab of cohort, this functionality has now gone. One location to put this functionality back would be under the generate tab.

![image](https://user-images.githubusercontent.com/13936600/39186117-71187e2a-4797-11e8-8552-8abc6a26ae5f.png)

Another option is in the patient profile. In addition to the Data Source drop down, another optional drop down maybe offered that allows the user to select the 'cohort definition id'.

**Comment by fdefalco** [comment]
Please check this out: 
https://www.youtube.com/watch?v=V3hVgIOV6Z8&t=24s

**Comment by gowthamrao** [comment]
@fdefalco  here is a gold :star:
