### ISSUE TITLE
Data Source Editor - Save button disabled state display issue

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#661]
When disabled, due to no current changes, there is an issue with the display of the save button and it appears completely gray as shown in the attached image.

![image](https://user-images.githubusercontent.com/6586384/39266126-1a6e2376-4897-11e8-9174-d0c881addaae.png)

**Comment by anthonysena** [comment]
Tagging @pavgra to confirm if this is still an issue in the latest release.

**Comment by pavgra** [comment]
@fdefalco / @anthonysena , this is what I see. "Save" seems to be visible

![image](https://user-images.githubusercontent.com/10010071/49524400-ad7a3a00-f879-11e8-8f0f-9df8ee4b1186.png)

**Comment by anthonysena** [comment]
Thanks for confirming @pavgra. I'll close this out.
