### ISSUE TITLE
public site missing all RC/DRC

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/Atlas#663]
### Expected behavior

To see record counts for standard codes appearing in data.

### Actual behavior

Not.

### Steps to reproduce behavior

http://www.ohdsi.org/web/atlas/#/concept/443729

To confirm that at least one patient has this code, go to http://www.ohdsi.org/web/atlas/#/profiles/CS1/5 and filter by 443729.

**Comment by ericaVoss** [comment]
But isn't the only data source for public ATLAS Synpuf?  The RC and DC from that wouldn't make much sense.

**Comment by Sigfried** [comment]
Yeah, I see numbers there now. Any ideas why they weren't there before? Because I still have that problem on my development instance. Did anyone change anything that might have affected this since April 27? Frank told me the counts had been generated in March, so I guess it couldn't have been that.

**Comment by fdefalco** [comment]
The counts are cached in the WebAPI when it starts.  You can take a look in your job history in ATLAS and see if the 'warming cache' job had any issues.
