### ISSUE TITLE
Achilles Display issues

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#665]
Minor issues for future releases

**Dashboard:** Duplication of tick labels on x-axis
![image](https://user-images.githubusercontent.com/13936600/39368892-cf9919c8-4a08-11e8-9fd2-0c012a1826e9.png)

**Data density:** mouse hover tool tip not working as intended here. 
![image](https://user-images.githubusercontent.com/13936600/39368961-040432d8-4a09-11e8-9cbd-4266d5e53188.png)

**Condition** and **Condition era**: Tree map, does not have hierarchical clustering/nests of conditions
![image](https://user-images.githubusercontent.com/13936600/39369074-4f8cfd3e-4a09-11e8-9e1d-e2fb3a0a3938.png)

**Comment by fdefalco** [comment]
Duplication of x axis values resolved in #653.

Condition and condition era: This is not an ATLAS bug.  This indicates that the concept_hierarchy helper table from Achilles needs to be created.

http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas:achilles_v_1_5

No reproducible issues with tooltips.
