### ISSUE TITLE
importing concept set from repository overwrites concept set expression

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#669]
As per @pbr6cornell - when in a cohort definition, on the concept set tab there is now an ability to import a concept set from the repository.  Doing so will overwrite the currently selected concept set with the one chosen.  

If this is the expected behavior then perhaps we rename the button with 'Replace' otherwise we should provide a warning to the user of what they are about to do.

**Comment by anthonysena** [comment]
I'd suggest the following when importing a concept set

- If the target concept set expression is empty (i.e. the concept set has no entries) then import without any prompt.
- If the target concept set is not empty, prompt the user that they will overwrite and allow them to proceed or cancel.

**Comment by ssuvorov-fls** [comment]
@anthonysena Hello, can you reproduce this error? I've tried but everything seems to be ok

**Comment by ssuvorov-fls** [comment]
@anthonysena reproduced, fixing
