### ISSUE TITLE
Observation Period report is missing in dropdown

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Atlas#676]
### Expected behavior
I expect that we can see "Observation Period" report the same way as in ACHILLES reports: 
http://www.ohdsi.org/web/achilles/#/OHDSI_Sample_Database/observationperiods

### Actual behavior
Currently this functionality is missing in ATLAS

### Steps to reproduce behavior
Open Data Sources menu item and observe  Reports dropdown
http://www.ohdsi.org/web/atlas/#/datasources

**Comment by fdefalco** [comment]
This report was implemented in AchillesWeb only and is not available in ATLAS at this time.  Will be moved to enhancements planning.

**Comment by pbr6cornell** [comment]
@alondhe , will this be added to ATLAS 2.8, or are you going to wait until ATLAS 3.0?
