### ISSUE TITLE
If admin deletes cohort, he will be logged out

### ISSUE THREAD

**Issue by johnSamilin** [OHDSI/Atlas#677]
### Expected behavior
Admin deletes cohort, then is redirected to the list of cohorts
### Actual behavior
Admin deletes cohort, then is being logged out
### Steps to reproduce behavior
Log is, delete a cohort

**Comment by chrisknoll** [comment]
Hi, @johnSamilin, 
  It looks like we're trying to solve this issue via a front-end workaround (where we call a refreshToken() call to webAPI before each and every web service call.  And it looks like you identified we need it before chort ssaving, but also before concept-set saving, but what you may not have found yet is that it should be before incidence rate saving, estimation saving, and prediction saving...but you might also find out that it needs to be done before cohort generation, concept-set optimzation...pretty much any time you make a call to WebAPI.

... this is madness!

My suggestion:  figure out a solution at the WebAPI level.   If we want to reset a timeout on the authentication token every time there's a WebAPI interaction, why don't we set up an additional Filter for WebAPI that refreshes the token (if security is enabled)?  This way, it's not up to Atlas devs to make sure they do this gesture every time they make a webAPI call, and instead the token will automatically be refreshed when any action is performed.
