### ISSUE TITLE
Enhancement to support site specific defaults for Atlas generated R code

### ISSUE THREAD

**Issue by leeevans** [OHDSI/Atlas#681]
### Expected behavior
support site specific defaults for Atlas generated R code

### Actual behavior
Atlas generated R code must always be edited by the user to specify site specific parameters like connection strings and database/schema names. 

### Notes
Perhaps the R code could be generated from a template file which could be (optionally) customized at the local site when Atlas is deployed/upgraded. 

Alternatively the generated R code could include a separate file that could be customized with the local site specific parameters.

In addition, for sites with read-only CDMs and separate 'user scratch schemas' it would be helpful to be able to reference the logged in Atlas userid within the output database/schema parameter, in the generated R code.

**Comment by anthonysena** [comment]
@leeevans - I know this is an old item but am wondering if it is still an issue with the current incarnation of estimation/prediction since they allow you to download an R package?

**Comment by pbr6cornell** [comment]
I think there are few items here to note:

1)  If one installs ARACHNE execution engine, then generation can take place without requiring user to modify R script.  @pavgra , please tag this issue with the documentation around ARACHNE documentation, including installation and user guide.

2) As @anthonysena is highlighting, ATLAS 2.7+ now allows for downloading of estimation and prediction R packages, which can be opened in RStudio, modified and executed.   @anthonysena , please tag this issue with the documentation for how to execute a PLE/PLP R package from ATLAS.

3)  For ATLAS 3.0, we may want to consider some new option, where a user can provide some input parameters on system settings and have the ability to download the package with the parameters fully populated (without having to go into the code).

**Comment by anthonysena** [comment]
Closing due to age.
