### ISSUE TITLE
Patient profiles - search by person.person_source_value

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#682]
### Expected behavior
Be able to search for a person by both person_id and person_source_value during secure and authenticated mode for approved role based access

### Actual behavior
Can only search for a person by person_id in all levels of security and role based access

### Steps to reproduce behavior
See default behavior
![image](https://user-images.githubusercontent.com/13936600/39951754-01a5ea56-555b-11e8-9c19-9f5fd80db433.png)

**Comment by gowthamrao** [comment]
relates to https://github.com/OHDSI/Atlas/issues/683

**Comment by anthonysena** [comment]
Closing due to age.
