### ISSUE TITLE
Version of WebApi

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#688]
Can I assume that WebAPI is backward compatible so if i am running two versions of Atlas they both should work or is that not guaranteed? I am asking because I had some issues with installing the new version and like to make sure the team can keep working on the old version (while the new WebApi.war is deployed)

Is it possible to add somewhere in Atlas the version of the WebAPI that is actually being used?
The release notes on the home page are hard coded to the version of the WebAPI that has the same version number as ATLAS.

**Comment by chrisknoll** [comment]
We can add a startup request to go to WebAPI/info, which returns the version of the WebAPI that is configured.  2.3 to 2.4 should be backwards compatible so you should be able to point a 2.3 atlas at a 2.4 webAPI.

**Comment by PRijnbeek** [comment]
Thanks. It would be a helpful feature also for debugging/solving issues in the field to see they have forgotten to update WebAPI.

**Comment by pbr6cornell** [comment]
We should document compatible versions of ATLAS and WebAPI.  Related to #1910 , should we include WebAPI version in the label as well?

**Comment by anthonysena** [comment]
Closed via #1910
