### ISSUE TITLE
Cohort definition:  error handling divide-by-zero for ratios

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#69]
When creating cohort definition inclusion criteria around measurements, when checking if value is above or below normal, the query divides value_as_number by range_high/low.  however, that will cause problem if range_high/low value is 0.  do a check in query so divide-by-zero doesnt occur.

**Comment by anthonysena** [comment]
I feel you got this one already @chrisknoll but wanted to have you confirm before closing out.

**Comment by alondhe** [comment]
Hey @chrisknoll and @anthonysena , just adding my +1 to this as being an issue we found when running in Redshift. 

The below code snippet ends up yielding a divide-by-zero error in Redshift, as the engine will end up trying to execute the divide by at some point before the > 0 check. @ganisimov suggested we could add a TranslateSQL rule to insert a NULLIF into the denominator when such a division pattern is found, but we both felt it might be better suited as an Atlas code fix.

```
WHERE 
                C.range_high > 0.0000
                AND 
                (C.value_as_number / C.range_high) > 1.0000

```
