### ISSUE TITLE
[Bug] - utilization function of heracles

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#697]
### Expected behavior
When selecting filters in panel, summary table should change

with no filters selected
![image](https://user-images.githubusercontent.com/13936600/40271968-544077fe-5b73-11e8-80f8-71021415fbea.png)

### Actual behavior

with filters selected
![image](https://user-images.githubusercontent.com/13936600/40271973-675fed38-5b73-11e8-8173-f66d19f4b582.png)

### Steps to reproduce behavior

@pavgra @chrisknoll

**Comment by pavgra** [comment]
@anthonysena , this one was merged into RC 2.4.1 branch

**Comment by gowthamrao** [comment]
@pavgra the issue applies to both visits and drugs. Looks like only visit was fixed?

**Comment by pavgra** [comment]
@gowthamrao, should be fixed in 2.4.3 now
