### ISSUE TITLE
Trashing an Unsaved Concept Set

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#702]
### Expected behavior
When you hit the "trash" button on an unsaved concept set, it takes you out of the concept set.  The same way the X button does.

### Actual behavior
When you "trash" an unsaved concept set it throws a warning but doesn't do anything.

### Steps to reproduce behavior
1. go to atlas
2. hit Vocabulary
3. go to import
4. import 9201
5. hit the trash button, it warns you and does no action

This is just a nice to have . . . I keep doing it by accident.

**Comment by anthonysena** [comment]
This is still an issue with 2.6 except that when you click the 'trash' icon, it will prompt about the deletion and  then close. 

Instead, the 'delete' icon should be removed in this experience since you have not saved the concept set to the server.

**Comment by johnSamilin** [comment]
this issue is fixed by https://github.com/OHDSI/Atlas/blob/master/js/pages/concept-sets/conceptset-manager.js#L273
