### ISSUE TITLE
Atlas - cost and utilization - Heracles - make the UI of visit similar to drug

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#715]
Visit reports - Can visit reports be made similar to drug reports. **Description of drug reports**. 

- **filter panel** In drug the summary table has only one filter - 'Drug Source' i.e. drug_type_concept_id.
![image](https://user-images.githubusercontent.com/13936600/40547271-766a11b0-5fff-11e8-9bb1-9f8ffae2b33b.png)
- **summary table shows all drug_concept_id's** is a long table that includes all drug concepts.
![image](https://user-images.githubusercontent.com/13936600/40547341-a66e9dea-5fff-11e8-8440-1efa14aa7ddd.png)
- no period (period_type) filter.
- each drug summary row has concept_id, concept_name, vocabulary name, concept class information
- ability to sort summary table

- drill down is possible by selecting a single drug. A new filter panel comes up
![image](https://user-images.githubusercontent.com/13936600/40547444-e3c10426-5fff-11e8-949b-9cf4a74805ba.png)
![image](https://user-images.githubusercontent.com/13936600/40547459-edad5534-5fff-11e8-925d-5f22cec4ece5.png)
with default 'Monthly' for period type and drug source = ''. Allows ability to drill down by period_type and drug_source

**Request:** we would like visit reports to be similar in UI to drug UI. 
Current Visit UI is as follows
![image](https://user-images.githubusercontent.com/13936600/40547519-1c6c23dc-6000-11e8-9f25-db205e722bad.png)

Changes:
- Summary filter panel should only have 'Visit Type' labeled 'Visit Source' similar to drug
- Summary table should have all summaries by visit's concept id, i.e. long summary table (similar to drug). 
- should not have period-type reports i.e. no graph or raw data. 
- if user selects any single row of summary, then a new filter comes with period_type and visit source should appear. Default monthly is selected and visit_source = '', similar to drug.
- in raw data table add new columns: concept_id with link to vocabulary, concept (similar to drug in drug table), concept vocabulary, concept class id

**Comment by anthonysena** [comment]
Closing due to age.
