### ISSUE TITLE
Atlas - cohort characterization - right click to open new window

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#723]
### Expected behavior
Provide ability to right-click and open new window where possible. e.g. in cost and utilization, it is possible to right click and open new window here

![image](https://user-images.githubusercontent.com/13936600/40575537-b3d424a4-60b4-11e8-9694-927143cf74bb.png)

but not here 
![image](https://user-images.githubusercontent.com/13936600/40575544-cfabda8c-60b4-11e8-8c93-7a3ef4ab3b7f.png)

but we can click thru. In addition to being able to click thru, it would be nice to also be able to open in new window.

**Comment by pbr6cornell** [comment]
In the ATLAS 3.0 design, we should think about effective use of 'open in new window' for reports across the system.

**Comment by anthonysena** [comment]
Closing due to age.
