### ISSUE TITLE
Error selecting MedDRA concept

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#727]
### Expected behavior
When inspecting a concept (from SNOMED) in atlas, selecting the ancestor concept from MedDRA should allow you to view the hierarchy from MedDRA.

### Actual behavior
Selecting the MedDRA PT from a SNOMED concept leads to an error in the UI.

### Steps to reproduce behavior
1. navigate to concept 197236.
2. Filter to MedDRA vocab
3. Selected MedDRA PT.
4. Observe error in console, and UI is corrupted.

Screenshots:

![s1_snomedconcept](https://user-images.githubusercontent.com/6818777/40675943-2c383c98-6347-11e8-9844-64d5aaa102d5.png)

![s2_selectmeddra](https://user-images.githubusercontent.com/6818777/40675948-3025ef8a-6347-11e8-9f64-554502f219c3.png)

![s2_errors](https://user-images.githubusercontent.com/6818777/40675954-3328ca40-6347-11e8-807f-18ac70e3be55.png)

**Comment by anthonysena** [comment]
Closing as this bug was addressed as part of #1179
