### ISSUE TITLE
Import custom cohort definition

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#73]
Use case: There are cohorts defined in a way that could not have been done using the standard cohort editor (aka Circe). These need to be imported via Atlas in such a way that they are given a unique ID and this cohort is imported into the cohort definition and cohort tables.

**Comment by t-abdul-basser** [comment]
Do you have examples of such cohorts? If so, how were they created?

**Comment by cahilton** [comment]
At Regenstrief, we import cohorts from our NLP system, since they share patient ids.

**Comment by t-abdul-basser** [comment]
Thanks! Do we have any other examples?

**Comment by anthonysena** [comment]
Hi Taha - I can share some examples and the motivation for this item. I'm currently working on a study where we created a cohort based on the date of a drug switch. I could not do this via the cohort expression editor and had to create this using SQL code. The unfortunate reality today is that once you have to step outside of the tools to define a cohort, it is not easy to step back into them to continue your analysis.

The goal with this issue is to allow someone to define a cohort (using Atlas or any other tool) and materialize the cohort into the standard cohort tables with a unique identifier. Then you would be able to to resume using Atlas to obtain cohort statistics, review patient profiles, etc. 

Hope this helps and thanks for raising the question.

**Comment by t-abdul-basser** [comment]
Thank you. That is very helpful.
