### ISSUE TITLE
"Cohort Exit Criteria" vs "Censoring Events"

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#734]
### Expected behavior
When defining a cohort in ATLAS, I would expect all aspects of "Cohort Exit Criteria" to be in the same section.  Any options that help define the end of the cohort would be part of the "Cohort Exit Criteria".

### Actual behavior
There is a section called "censoring events" which seems to apply to the cohort exit criteria, yet it is in its own section.  I would propose all this functionality should be in one section.

![image](https://user-images.githubusercontent.com/6305439/41037662-ec75f96c-6961-11e8-837c-dbebabe74654.png)

### Steps to reproduce behavior

1. Go to ATLAS
2. Go to the Cohort Definition tab and hit "New Cohort" button 
3. On the "new cohort" you'll see "censoring events" section

Linking forum post:
http://forums.ohdsi.org/t/cohort-exit-in-atlas/4521

**Comment by chrisknoll** [comment]
I think this was addressed with the grouping of the cohort entry, inclusion and cohort exit. @ericaVoss , please let us know if this is still an issue for you.

**Comment by paroolsingh** [comment]
Hi, 
I am a newbie and just installed Atlas. Please help me in understanding the difference between exit criteria and censoring event. Also let me know it there is some detailed documentation available for the same.

**Comment by chrisknoll** [comment]
Including the latest UI for reference:
![image](https://user-images.githubusercontent.com/6818777/50240827-d8917d00-0393-11e9-88a4-88d0862458a7.png)

@paroolsingh : This UI shows how the Cohort Exit is defined in 2 parts: event persistence and Censoring events.  

Event Persistence is a way of saying: once you've found a Cohort Entry Event, how long should that event persist?  There are 3 options:  until the end of the observation period (known as 'end of continuous observation'); fixed duration relative to event (allowing you to say that the event should persist 30 days after the start of 10 days after the end of the event); and end of a continous drug exposure, allowing you to use records from drug_exposure to build custom drug eras that will determine when the cohort entry event ends.

Censoring Events is a way to select records from data that should terminate a cohort entry event before the event persistence ends.  For example, if your cohort entry is a diagnosis of some condition (ex: fever), and you know that there is a lab test that can indicate the person's no longer qualified for that condition (a body temperature measuement < 99.0 F), you can create a cohort where people enter with the diagnosis of fever, the fever diagnosis should extend 14 days (using the option 2 of event persistence) but, if you find a measurement of body temperature of < 99.0, the event's exit date should be the date of the measurement.

So, Event Persistence works together with Censoring events (if censoring events are specified).  Event persistence says 'how long does this entry event last?' and censoring events say 'the event should terminate early if you find an appropriate record in data'.
