### ISSUE TITLE
Initial event date to offset from start date, may not be applying properly

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#735]
If a cohort is built by selecting the option of "Limit initial events to" to "all events" per person, it appears that 

![image](https://user-images.githubusercontent.com/13936600/41058377-a01dd0cc-6997-11e8-89b0-ad416c8a6380.png)

does not apply properly.
http://www.ohdsi.org/web/atlas/#/cohortdefinition/1769103

Cohort_end_date is found to be greater than 365 after cohort_start_date for a person in many cases

Same as https://github.com/OHDSI/WebAPI/issues/467

**Comment by chrisknoll** [comment]
Is it possible that 2 individual events were grouped together by the collapse logic?

```
   A ------- 365d -----|
                           B ------- 365d -----|
results in:
  |---------------- >365d ---------------|

```

**Comment by gowthamrao** [comment]
That is a probable. 
Makes sense @chrisknoll . Collapse strategy is doing what it is designed to do; a subject cannot have overlapping date ranges in the cohort. i.e. the same subject cannot have 
```   
      A ------- 365d -----|
               B ------- 365d -----|
```
So, the analyst who built the cohort has to be very careful when using cohort-exit criteria.

Maybe we could use this as an educational warning that will come up in Atlas UI when a user selects "Limit initial events to" to "all events"


Looks like the functionality is working as designed - this is not a bug
