### ISSUE TITLE
Space (UX) issue at Cohort generation tab

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#736]
![image](https://user-images.githubusercontent.com/10010071/41118906-5411f046-6a5f-11e8-95c3-804bb401f06f.png)

**Comment by fdefalco** [comment]
Currently the space you are highlighting is reserved for reports that are accessed by clicking the View Reports button.  I am of the opinion that all reports should be accessed via the reporting tab and the space you highlight be used to show the data sources without the current vertical scroll area.

**Comment by pavgra** [comment]
@fdefalco, so why not to collapse the area to current size only when the report mode is selected? And when the button was not clicked, expand the area and do not have this white big blanket

**Comment by anthonysena** [comment]
Closing as this is related to #1882 and we can track the work there.
