### ISSUE TITLE
Cohort Censor Window in Cohort Builder does not save dates correctly

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Atlas#752]
### Expected behavior
Dates are saved correctly as user defined them

### Actual behavior
If I set 2018-06-25 date in starting or ending date fields, the date will be saved as 2018-06-24. It looks it decreased date to -1 day.

### Steps to reproduce behavior
1. Create or open existing cohort
2. Scroll down to Cohort Censor Window
3. Define the dates for starting and ending values
4. Save cohort
5. Review saved dates

**Comment by chrisknoll** [comment]
So, sometimes, what I have seen is that there's some sort of timezone interference happening where the date is transformed to a local time zone (like, UTC -5) so the date (which assumes midnight) get's adjusted to an earlier local timezone and causing the date to get offset by what appears to be a day.

**Comment by anthonysena** [comment]
Closing this out due to the explanation provided by @chrisknoll and lack of activity.
