### ISSUE TITLE
Exclude Option in the TYPE Field

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#753]
### Expected behavior
When adding a TYPE filter (e.g. CONDITION_TYPE_CONCEPT_ID) there is an option to both INCLUDE or EXCLUDE type concepts.

### Actual behavior
The user can only specify concepts to INCLUDE for the TYPE filters.

### Steps to reproduce behavior
Create cohort, with a condition occurrence event
Add criteria attribute of condition type criteria

**Comment by gowthamrao** [comment]
It would be great if the UX is similar to concept-sets. We have hierarchy in concept ancestor for type concepts e.g.[ concept id 32023](http://athena.ohdsi.org/search-terms/terms/32023?fullscreen=false&levels=10&standardsOnly=false&zoomLevel=4)

It would be great to support hierarchy in type concepts

**Comment by ericaVoss** [comment]
@gowthamrao I agree - and it could be very simple, patient reported, claims, EHR, etc.  But I think that needs to be a Vocabulary entry.  Let me open one!

**Comment by chrisknoll** [comment]
@gowthamrao , I'm not sure you can say those concepts are in concept ancestor.  The link you provided shows values from concept_relationship, but that doesn't mean they are pulled into concept ancestor (tho, @cgreich should confirm this).  I checked our internal vocabulary, and I couldn't find 32023 as either an ancestor_concept or descendant_concept in concept_ancestor.  Vocabulary version was: ```v5.0 01-DEC-17```

**Comment by chrisknoll** [comment]
This feature has been implemented. Users can now say 'is any of' or 'is not any of' a list of concepts.
