### ISSUE TITLE
Improvements for the "Filter" feature in the cohort definition

### ISSUE THREAD

**Issue by prathamesh1993** [OHDSI/Atlas#756]
The filter on cohort definition page currently does a string search on the "Names" column in the cohort table. The results are not indicative of the actual cohort definition because of non-standard naming.
It will be very useful to have an advanced search filter where the search feature looks at the deeper concept sets in the cohort definition. 

This additional feature will not only keep the name of the cohort unique to the author, but also help other users look at existing cohorts in the cohort table.

**Comment by pbr6cornell** [comment]
related to desire to search cohorts by underlying concepts included
