### ISSUE TITLE
Cohort Censor Window & Print Friendly

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#758]
### Expected behavior
Print friendly contains all information from the Cohort Definition page.

### Actual behavior
Missing Cohort Censor Window information.

### Steps to reproduce behavior

1. Generate a cohort definition and set a Cohort Censor Window
2. Save cohort definition 
3. On the Export tab, see the Cohort Censor Window is not listed

**Comment by anthonysena** [comment]
Unable to reproduce this bug in V2.6.0. Closing it out but please let me know if this problem is still observed @ericaVoss.
