### ISSUE TITLE
Profile chart display: unzooming doesn't work if no events captured

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/Atlas#805]
### Expected behavior
User miss-clicks and choose range where no events captured. He can go back with double-click

### Actual behavior
Unzooming works fine while there are events shown in zoomed display, but doesn't for empty range
(like in the screenshot)
### Steps to reproduce behavior
![heracles_1](https://user-images.githubusercontent.com/25959256/43528759-61db4c3a-95b2-11e8-8592-ece5301fc40b.PNG)

**Comment by anthonysena** [comment]
Reviewed on Atlas/WebAPI WG and unable to reproduce using the latest code on master. Closing this one out.
