### ISSUE TITLE
Date format after job launch

### ISSUE THREAD

**Issue by mpozhidaeva** [OHDSI/Atlas#819]
### Expected behavior
Date format of the generated job date is the same as after the page refresh (for example, "6/22/2018 8:07:57 PM").
### Actual behavior
Date format of the generated job date is like "2018-08-08T21:25:08+03:00". Changed incorrectly after the first status updating. After page refreshing format is ok.
### Steps to reproduce behavior
Generate cohort and check "Generated" column (without page refreshing).
Or execute IR analysis and check "Starting" column.

### Notes:
- Would be great to check other similar cases.
- Affected version: 2.4.3
![image 6](https://user-images.githubusercontent.com/31308645/43867841-98e82ba0-9b73-11e8-865c-55b46d88ac34.png)
![image 7](https://user-images.githubusercontent.com/31308645/43867842-9906d208-9b73-11e8-8b06-e1ffecf9de15.png)

**Comment by anthonysena** [comment]
Unable to reproduce on v2.6.0
