### ISSUE TITLE
Cohort Generation Reports refresh while other sources are generating

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#827]
### Expected behavior
Viewing the features/inclusion reports should not refresh while other sources are polling for status.

### Actual behavior
While viewing generation results on one source, if another source is generating, the source being viewed gets de-selected/reloads/refreshes while the other source is being polled.

### Steps to reproduce behavior
Note: you need multiple sources generating to see this result:

1. Create cohort definition, make sure it's suitably complex to take some time to complete.
2. Generate cohort on one source.
3. Wait for generation to finish.
4. Generate cohort on second source.
5. While generating, view the reports on the first source. You should see that during the poling interval, the 'view report' view refreshes, as if the 'selectedReport' was being updated.

**Comment by anthonysena** [comment]
Unable to reproduced on v2.6.0.
