### ISSUE TITLE
Record counts not populating correctly

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#828]
### Expected behavior
Record count should show somewhere around 10Mil for the concept_id 2616666 (cpap device) in CDM_TRUVEN_CCAE_v750.

### Actual behavior
Record count shows as zero and the record counts tab has no data

### Steps to reproduce behavior
Set configuration to CDM_TRUVEN_CCAE_v750 and search for 2616666.

**Comment by anthonysena** [comment]
Per WebAPI/Atlas WG call: this may be related to the cache warming in the application.
