### ISSUE TITLE
Achilles age at first occurrence box-and-whisker plot of drug era not rendering properly

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#850]
### Expected behavior
Box and whisker plot should be properly rendered

### Actual behavior
![image](https://user-images.githubusercontent.com/38339058/44266164-87ac2500-a1f7-11e8-88dc-235b6c3bec1b.png)

### Steps to reproduce behavior

To Reproduce
go to achilles
go to drug era
select a drug (simethicone for example)
scroll down to graph

**Comment by fdefalco** [comment]
Duplicate of https://github.com/OHDSI/WebAPI/issues/702
