### ISSUE TITLE
Achilles - measurement frequency distribution histogram - not aligned with axis

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#851]
### Expected behavior
histogram should be aligned with X-axis

### Actual behavior

![image](https://user-images.githubusercontent.com/13936600/44266264-ec677f80-a1f7-11e8-829c-ed9d9d85bf83.png)

### Steps to reproduce behavior

To Reproduce
go to achilles
go to measurement
select a measurement
scroll down to frequency distribution visualization

**Comment by chrisknoll** [comment]
It's not a visualization problem, at least using your sample data provided in the other issue.

**Comment by fdefalco** [comment]
@johnSamilin Could you investigate why the frequencyDistribution graph component is creating this unusual offset?  @chrisknoll was able to confirm that it isn't an issue with the underlying atlascharts component.

**Comment by chrisknoll** [comment]
Yes, the verification of it working properly can be found here:
https://github.com/OHDSI/Visualizations/issues/36

In @fdefalco 's example screenshot, what I have seen is that people actually appear to have an age of -1 in the actual data leading to a negative value on the histogram.  But, his sample data didn't show that, so I'm not actually sure where that negative bar is coming from.

**Comment by johnSamilin** [comment]
>I'm not actually sure where that negative bar is coming from.
it's because of that there was custom implementation of the histogram in atlas
