### ISSUE TITLE
Unable to copy json/concept identifier list/included concept identifier list from existing concept set to new concept set - new release

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#860]
### Expected behavior
open existing concept set; click export tab, click concept set expression JSON button (or concept identifier list or included concept identifier list); open new concept set, click export tab, click in json window and attempt to paste JSON by using ctrl V  or by right mouse clicking
### Actual behavior
above and the json will not paste into the window
### Steps to reproduce behavior
open existing concept set; click export tab, click concept set expression JSON button; open new concept set, click export tab, click in json window and attempt to paste JSON by using ctrl V  or by right mouse clicking

**Comment by anthonysena** [comment]
Hi @jhardin29 - I was taking a look into this issue and I think that the workflow your using for concept set import is incorrect. For concept sets:

- open a concept set
- click export tab 
- click 'copy' on the concept set expression
- close the concept set
- navigate to search -> import tab
- paste in the concept set JSON

After that, you should have a new concept set. I know that this workflow for importing concept sets is different from cohort definitions which is confusing and needs improvement.

Please let me know if I've misunderstood the issue or if you have any questions.

**Comment by jhardin29** [comment]
Hi @anthonysena yes my mistake i didn't understand the workflow was different. I was using the identical approach as that for cohorts. It works fine using your outlined steps. Thanks!
