### ISSUE TITLE
Cohort definition warnings on using conceptsets don't look in all the places where they could be used

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#867]
PREFACE:  The new 'WARNINGS' feature in the Cohort Definition Editor is TREMENOUSLY useful!  It's already helped me a half-dozen times to catch mistakes that I made that I would have otherwise not found until I ran the cohort or QC'ed it.  Great stuff!  Given I love this feature, I'm being nitpicky about what it currently does.

### Expected behavior
Only get warning of : "Concept Set <conceptset name> is not used" when the conceptset is contained in cohort definition object but not used anywhere in the cohort definition logic for initial events or inclusion criteria

### Actual behavior

Warning is issued inappropriately in 2 situations that I found:
1.  If the conceptset is used as part of source concept attribute (e.g. CONDITION_SOURCE_CONCEPT_ID in <conceptset>)

2.  If a criteria has a nested criteria, and the conceptset is used within the nested criteria.

### Steps to reproduce behavior

Create a cohort definition with a conceptset, add the conceptset to source concept filter or in nested criteria, and you'll get both warnings

**Comment by AntonStepanof** [comment]
Looks like it was fixed at https://github.com/OHDSI/Atlas/issues/1250
I checked cases with nested criterias and source concept attribute locally.
@anthonysena  Could you please check that?

**Comment by anthonysena** [comment]
Hi @AntonStepanof - sorry for the delay but agree that this issue is closed via #1250 so I'll close out this issue. Thanks!
