### ISSUE TITLE
Username & Password For DataSource

### ISSUE THREAD

**Issue by umesh-clinakos** [OHDSI/Atlas#877]
### Expected behavior
Before the recent update, I can use Atlas data source without giving username and password.

### Actual behavior
Now it is asking for username and password.
### Steps to reproduce the behavior
Click on the data source and it will ask for the one.

can you provide the username and password for data source.

**Comment by hsyun98** [comment]
Having the same issue here :(

**Comment by umesh-clinakos** [comment]
Yes, I got the username & password for the same. Its username is "demo" and password is also "demo".

**Comment by chrisknoll** [comment]
Questions related to the public instance of Atlas should be posted to the OHDSI forums: http://forums.ohdsi.org/.  

@umesh-clinakos , the user/password is being controlled to deal with licensing issues raised by SNOMED.  Please do not post those credentials here.
