### ISSUE TITLE
Login profile for Atlas

### ISSUE THREAD

**Issue by chantekhani89** [OHDSI/Atlas#890]
I now have to sign in to run Atlas?  Where do I create my login profile?

**Comment by leeevans** [comment]
@chantekhani89  please see the below thread on the OHDSI forums:

http://forums.ohdsi.org/t/security-on-ohdsi-org-atlas/4791/4

**Comment by shahzeb1** [comment]
Hello, is there no easy to way to log in to the demo [Atlas website](http://www.ohdsi.org/web/atlas/#/home) without sending direct messages to users on that forum?
