### ISSUE TITLE
Add Relationship column in "Related Concepts" tab in the vocabulary browser

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Atlas#892]
### Expected behavior
It's possible to add "Relationship" column in grid

### Actual behavior
Actually "Relationship" is present in filter options only

### Steps to reproduce behavior
1. Go to vocabulary
2. Search 'aspirin'
3. Click on any record in grid and open "Related Concepts" tab

![image](https://user-images.githubusercontent.com/4144173/45149388-12b68480-b1d2-11e8-9537-d29d17aa0e57.png)

**Comment by anthonysena** [comment]
Closing due to age.
