### ISSUE TITLE
Auto-generated R code from Atlas (2.4.0) not compatible with FeatureExtraction (2.1.5) function

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/Atlas#894]
I executed the auto-generated R code from Atlas (2.4.0) for building a prediction model.

### Expected behavior
Copy-pasting auto-generated R code should create a prediction model.

### Actual behavior
 I receive the following error.
`Error in FeatureExtraction::createCovariateSettings(useDemographicsGender = TRUE,  : 
  unused arguments (useConditionOccurrenceInpatientAnyTimePrior = FALSE, useConditionOccurrenceInpatientLongTerm = FALSE, useConditionOccurrenceInpatientMediumTerm = FALSE, useConditionOccurrenceInpatientShortTerm = FALSE)`

It seems as if there are a number of parameters used in the auto-generated R code that are not part of the `createCovariateSettings()` function of FeatureExtraction (2.1.5).

### Steps to reproduce behavior
1. Create two Cohorts
2. Create a Prediction
3. Execute auto-generated R code under the Utilities tab

**Comment by anthonysena** [comment]
Hi @lhjohn - this has been corrected in Atlas 2.6. The auto-generated code has been replaced by functionality that will allow you to design your prediction problem and download an R package that contains code compatible with the OHDSI Methods Libraries. I'll close this out but reach out if you have any questions. Thanks!
