### ISSUE TITLE
Fix error message when no WebAPI available

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#898]
### Expected behavior
A single error icon with two error messages should be displayed.

### Actual behavior
The error messages stack vertically with duplicate error icons.

![image](https://user-images.githubusercontent.com/6586384/45314735-891ff300-b500-11e8-89fd-e354bacf6579.png)

### Steps to reproduce behavior
Launch ATLAS with no available WebAPI.

**Comment by anthonysena** [comment]
Discussion from WebAPI Call:

https://github.com/OHDSI/Atlas/blob/master/index.html#L82
https://github.com/OHDSI/Atlas/blob/master/index.html#L89

Consider converting these checks into a computed observable that is utilized to check the app status.  We can maintain a list of error messages based on the checks done at app start up.
