### ISSUE TITLE
Data Sources: length of drug era plot missing

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#907]
### Expected behavior
In Atlas Data Sources, the drug era report should have a 'length of era' plot as in AchillesWeb

### Actual behavior

In Atlas DS:
![image](https://user-images.githubusercontent.com/8037742/45501500-5c154f80-b74f-11e8-96ed-b1418635fd1b.png)

### Steps to reproduce behavior
Run Achilles, open up Atlas Data Sources, go to Drug Era report, pick a drug era, look for length of era plot.

**Comment by t-abdul-basser** [comment]
Thanks @alondhe. I think that this divergence is a predictable consequence of maintaining two separate code bases for AchillesWeb and Atlas Data Sources. I would suggest that 1) we work with the Atlas team to add to Atlas DS any visualizations that are in Achilles Web but are missing from Atlas DS, as you are suggesting here; 2) That we freeze AchillesWeb, direct users to Atlas DS.

**Comment by alondhe** [comment]
Agreed, @t-abdul-basser  -- we want to move off of AchillesWeb and just use Atlas, but we can't until Atlas DS is fully functional. I can keep opening bug tickets here, but is there a better approach we should take?

**Comment by anthonysena** [comment]
Reviewing the endpoint in our environment: `/WebAPI/cdmresults/<source>/drugera/<concept>`, it looks like the information needed for this plot is being returned: 

![image](https://user-images.githubusercontent.com/12902366/55509387-ebba1700-5629-11e9-954c-28760aaf12e0.png)

So, all that should be needed here is to recreate the box plot from Achilles:

![image](https://user-images.githubusercontent.com/12902366/55509645-6e42d680-562a-11e9-8cd0-98b6223ce539.png)

This should fit in nicely next to the "Age at First Occurrence" plot on the drug era display

**Comment by pbr6cornell** [comment]
@alondhe will you fix this for ATLAS 2.8?
