### ISSUE TITLE
Atlas vocabulary search - searching for source code did not result expected results

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#911]
I searched for ICD10CM code `S39.92XS   Unspecified injury of lower back, sequela` in ATLAS, and found an unusual behavior. I dont know why this is happening.

### Expected behavior
Return search result for this query
http://www.ohdsi.org/web/atlas/#/search/S39.92XS

### Actual behavior
![image](https://user-images.githubusercontent.com/13936600/45652466-b2adc100-baa2-11e8-88e5-56167836e9f1.png)

### Steps to reproduce behavior
http://www.ohdsi.org/web/atlas/#/concept/45549452
The concept code exists!

**Comment by anthonysena** [comment]
![image](https://user-images.githubusercontent.com/12902366/47691076-0f82b800-dbc7-11e8-9e6d-b81ae6444579.png)

Closing as it appears to be fixed with the 2.6 release.
