### ISSUE TITLE
Workflow 3 - Concept Set Comparison

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#92]
1. Create 2 concept sets (A & B)
2. Compare 2 concept sets such that you can see which concepts fall in A but not B, B but not A, etc.
3. Comparison could be done on both included concepts and included source codes
4. 2-circle Venn diagram representation of the data above

**Comment by fdefalco** [comment]
This looks like it could be leveraged for the concept set venn visualization. https://github.com/benfred/venn.js

**Comment by anthonysena** [comment]
Per discussion today: it would be useful to allow for comparing across concept sets & vocabulary versions.

**Comment by anthonysena** [comment]
Related #82: The use case we need for negative controls to use when designing/executing a comparative cohort analysis is to: 

1. Find the negative control outcomes for T
2. Find the negative control outcomes for C
3. Select the intersection of negative control outcomes for T and C

This can be accomplished by adding a feature to concept sets which is 'compare with another concpetset expression',  Which basically shows the union and intersection of two conceptsets....(basically it partitions the union of concepts from both expressions into 3 lists:   

1. concepts in 1 but not 2,  
2. concepts in 2 but not 1,  
3. and concepts in both 1 and 2.  

For the specific use case of negative controls for comparative analysis, we'd want to get the 'concepts in both 1 and 2',  but for other broader use cases, looking at the other sets would be valuable
