### ISSUE TITLE
warning on type - hard to figure out as new user 

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#925]
### Expected behavior
no warning

### Actual behavior
warning that is not easy to get rid off.
It is hard to know as user that severity (blue i) is really not that important 
It took me 5+ min to figure out what is meant by the warning. 

I eventually did (to have a feeling of no warnings in my cohort definition)
![image](https://user-images.githubusercontent.com/7526119/45776573-4efdd200-bc21-11e8-8d71-cf1b30e09b50.png)

**Comment by pbr6cornell** [comment]
This is related to making the Warnings tab in Cohort bug-free, which is an ATLAS 2.8 goal. 

@pavgra and @chrisknoll , where can I find the documentation around the set of checks that are currently being performed?  I'd like to review and help make them clearer for users (potentially revising which checks we actually perform and how they are labeled)

**Comment by KSadomtsev** [comment]
in 2.8 it works much better and clearer
