### ISSUE TITLE
Still using config-local.js? That was so 2017! js/config/local.config.js is the new config-local.js

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#928]
### Expected behavior
I can override the configuration of ATLAS using `$/js/config-local.js`.

### Actual behavior
I have to move and rename `$/js/config-local.js` to `$/js/config/local.config.js` as shown in : https://github.com/OHDSI/Atlas/blob/master/js/config/app.config.js

Furthermore, the message that is shown in the developer console wasn't clear when I initially read it:

![image](https://user-images.githubusercontent.com/12902366/45839007-1c1b1300-bce1-11e8-8cf5-734b536dc4dd.png)

It would be clearer if this read instead:

> Local configuration not found.  Using default values. To use a local configuration and suppress 404 errors, create a file called local.config.js and place it in the /js/config directory of the ATLAS root directory. In previous versions of Atlas, this file was named config-local.js in the /js directory of ATLAS root. If you have that file please move it to /js/config and rename it to local.config.js

For reference, this is a breaking change introduced as part of this commit: https://github.com/OHDSI/Atlas/commit/2e912c878d54106a18f76a6d081686abe280e086 and needs to be clearly stated as part of the next set of release notes.

Tagging @pavgra @chrisknoll @johnSamilin for awareness

**Comment by anthonysena** [comment]
Hope no one takes offense at what was intended to be a funny issue title - I understand that breaking changes are required when we're in the midst of restructuring the code organization. Just wanted to note it here so that we can update the information message in the dev console and note it for the release notes.

**Comment by pavgra** [comment]
@anthonysena , here is the story:
- since there appeared a couple of new config files during work on Terms & Conditions popup, we've added separate folder for configs
- so the `config-local.js` was renamed to `app.config.js` and moved into the `js/config`
- but since we didn't want to break back-compatibility, we left fallback for `config-local.js`, so for now you can do either - or:

![image](https://user-images.githubusercontent.com/10010071/45840651-85048a00-bce5-11e8-94cd-b272627fb448.png)

However, seems that smth works in not expected way, we'll get a look into it

**Comment by chrisknoll** [comment]
@pavgra,

> so the config-local.js was renamed to app.config.js and moved into the js/config

I hope not. config-local.js is just a local configuration file to overide config.js. I hope you meant 'config.js was renamed to app.config.js'.

> However, seems that smth works in not expected way, we'll get a look into it

That logic in the code looks like you get a warning if either file is missing, maybe that's the problem.

We didn't really get a chance to collaborate on this feature so I am sorry that we weren't able to give some feedback on the approach.

1.  I think we should have just 1 config 'root' that can be overriden by a config-local update.  To this end, the root config.js file can import 'config/app.config' and 'config/otherConfig', and also 'optional!config-local'.  The one config-local file will be responsible for overriding all the child elements of the root config file.

2. I don't htink the T&C stuff should be that ocnfigurable.  People ould alter the terms and conditions on whim and then it won't pass SNOMED requirements for having the correct language.  We shouldn't leave it to the local config to determine what the T&C says, just if it is enabled or not. Tho this end: I'd suggest a new component folder called 'terms-and-conditions' that we can implement the snomed terms and conditions, and we can implement as part of the config file the name of the T&C component that should be displayed on startup (if enabled). In the future we could set up a colletion of T&C components that each need to be agreed to (we can save the response in local storage under the key of the t&c component name -> value of accept/reject.

**Comment by anthonysena** [comment]
OK - @pavgra you are correct in that my app was still able to function without the new /js/config/local.config.js. However, it was still unexpected to see that error in my dev console. I don't think that error can be avoided unless you have both the /js/config-local.js AND the /js/config/local.config.js since your trying to maintain backwards compatibility by looking for both files. 

To the points that @chrisknoll raised: I support having a single place to look for configuration and right now to maintain backwards compatibility, I'd support keeping config.js and config-local.js in the /js folder. For ATLAS 3.0, we can review this point and potentially put the config under /js/config/. Let me know if I've missed anything.

**Comment by anthonysena** [comment]
Thanks @chrisknoll!
