### ISSUE TITLE
Atlas startup issue |giving blank screen

### ISSUE THREAD

**Issue by vkramd** [OHDSI/Atlas#935]
### Expected behavior
Atlas should start with the home screen being visible on startup.

### Actual behavior
When i launch atlas from my tomcat i get a blank screen with atlas logo.

### Steps to reproduce behavior
1. Download atlas from git repo.
2. change it's name to atlas and place in the tomcat webapps folder.
3. Start the tomcat server.
4. Hit the server url with the atlas as context root.

**Comment by anthonysena** [comment]
Hi - have you followed the instructions on the OHDSI wiki? http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas
