### ISSUE TITLE
Concept Set Filtering

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#95]
Is it possible to add a way to filter concepts sets by creator?

**Comment by fdefalco** [comment]
Not currently as we do not have authentication integrated into ATLAS.  As such, we don't know who created what.

**Comment by anthonysena** [comment]
+1 to this and tying it to #86

**Comment by anthonysena** [comment]
This has been addressed by #566 and requires the use of security to utilize this feature.
