### ISSUE TITLE
Annotation Widget Proposal - ATLAS

### ISSUE THREAD

**Issue by CodeSchneider** [OHDSI/Atlas#958]
In order to improve ATLAS's ability to validate a cohort, I've implemented an **annotation widget**. This annotation widget allows a user in ATLAS to perform manual chart review, i.e. answer a set of questions (or multiple sets) regarding a subject in a cohort. The results of the chart review are persisted for later processing. The knockout view-model design of the widget is shown below:

![annotation_atlas_viewmodel_diagram](https://user-images.githubusercontent.com/7592718/46393235-522d9f00-c6b2-11e8-8e08-c23254c28b62.jpg)

Also, if you'd like to view a breakdown of each of the above view-model's properties/methods, you can view the document [here](https://docs.google.com/spreadsheets/d/1LIK3h0lOnUTXwA6J3NXFp28iQqqfkvLRzJG16hxAwvU/edit?usp=sharing).

If you'd like to view the accompanying OHDSI webapi proposal, go [here](https://github.com/OHDSI/WebAPI/issues/622).

A picture of the widget is shown below (sidebar on right):

<img width="1249" alt="annotation_ui" src="https://user-images.githubusercontent.com/7592718/46393370-f1eb2d00-c6b2-11e8-98af-34c61fd256d1.png">

Branch for review: https://github.com/OHDSI/Atlas/tree/annotation

**Comment by jduke99** [comment]
Ideas: 

- New Tab under Cohort Definition "Annotation"
-  In annotation, you would name the study, select or create question set, select number of subjects
-  More to discuss...

**Comment by anthonysena** [comment]
Closing as duplicative of #2593.
