### ISSUE TITLE
Not Enough Permissions to Generate Tooltip Error

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#963]
### Expected behavior
Either tooltip doesn't appear or generation is not possible.

### Actual behavior
Tooltip appears suggesting permissions are not sufficient to generate however generation still occurs.

### Steps to reproduce behavior
Mouse over generate button on generation tab.

![image](https://user-images.githubusercontent.com/6586384/46482405-8b096900-c7c3-11e8-93b2-a88e5f8acd71.png)

**Comment by anthonysena** [comment]
Unable to reproduce this in our beta environment. closing for now but please let me know if you still see this issue and we can re-open.
