### ISSUE TITLE
Record count tab on concept details not displaying counts

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#969]
### Expected behavior
Display each data source's record count for this concept.

### Actual behavior
Loading indicator remains active without change.

### Steps to reproduce behavior
Navigate to a concept, go to the record count tab.

![image](https://user-images.githubusercontent.com/6586384/46490105-150dfd80-c7d5-11e8-9cbc-b82d166abac9.png)

**Comment by fdefalco** [comment]
![image](https://user-images.githubusercontent.com/6586384/46493593-c6656100-c7de-11e8-9f43-7d44c7729244.png)

Potentially related error.

**Comment by ericaVoss** [comment]
I'm seeing this as well.
