### ISSUE TITLE
browsing hierarchy tab adds extra entries to center table

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#972]
### Expected behavior
As you navigate by clicking on elements in the hierarchy the center table updates to the currently selected concept.

### Actual behavior
As you navigate by clicking on elements the new concept is added to the center table and accumulates with additional clicks instead of replacing the existing table content.

### Steps to reproduce behavior
Browse to the concept hierarchy tab. Navigate to parents or children in the concept hierarchy.

![image](https://user-images.githubusercontent.com/6586384/46492081-93b96980-c7da-11e8-8f21-c0296c140a06.png)

**Comment by anthonysena** [comment]
Closed via #1162
