### ISSUE TITLE
cohort pathway - non consistent font size used

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#974]
### Expected behavior
Use a max of 14px font for titles.

### Actual behavior
use of 18px font

### Steps to reproduce behavior
visit cohort pathway report

![image](https://user-images.githubusercontent.com/6586384/46493281-eba59f80-c7dd-11e8-9bd7-82f1cbc98747.png)

**Comment by pbr6cornell** [comment]
We need to apply consistent formating across all features, and should make that a hard requirement for ATLAS 3.0.

**Comment by anthonysena** [comment]
Consistency for the headers was achieve through the use of a shared component. Closing this out.
