### ISSUE TITLE
Mysterious Design numeric value in Cohort Pathways

### ISSUE THREAD

**Issue by AnthonyMolinaro** [OHDSI/Atlas#977]
### Expected behavior
If the numeric value representing Design is meaningful, some context should be provided so a user knows what it means.
### Actual behavior
A negative integer: -77772149
### Steps to reproduce behavior
Generate a new ccohort pathway and examine Design after clicking on All Executions.

![cohortpathways](https://user-images.githubusercontent.com/31700317/46495902-a2a51980-c7e4-11e8-9e5c-a7e9b3da5584.PNG)

**Comment by chrisknoll** [comment]
It's a hash value.  It's a meaningless number, but we could come up with some kind of content to make it clickable, perhaps a date of when the design was persisted.

**Comment by anthonysena** [comment]
Closing - as of the 2.7.2 release, this now displays as "V1", "V2", and so on based on the design used when generating the analysis.
