### ISSUE TITLE
Popup blocker warning for PLP package download

### ISSUE THREAD

**Issue by AnthonyMolinaro** [OHDSI/Atlas#983]
### Expected behavior
Download the R package for your PLP study or see an error message if something went wrong.

### Actual behavior 
Using Chrome my popup blocker blocked the download and it wasn't obvious this was happening.

### Steps to reproduce behavior
1. Turn on popup blocker.
2. Create a PLP study.
3. Name the R package and click download.

**Comment by chrisknoll** [comment]
Sites use adblocker detection to show a message on screen, maybe we can add a panel to the top/bottom of the atlas main container and if we detect a pop-up blocker is in place, we can show the panel indicating that the blocker should whitelist atlas?

**Comment by pavgra** [comment]
@chrisknoll, blocked download popups are typically due to improperly implemented downloading mechanisms - when the browser thinks that smth is being downloaded w/o user's intent. So that's the other story relatively to adblockers
