### ISSUE TITLE
Refactor Estimation & Prediction Features

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#988]
Per feedback in https://github.com/OHDSI/Atlas/pull/953, there are a number of items to discuss and refactor to make these consistent with other parts of the code base.

**Comment by pavgra** [comment]
Quite a lot of feedback available here also - https://github.com/OHDSI/WebAPI/pull/620#pullrequestreview-162199279

**Comment by anthonysena** [comment]
Thanks @pavgra - I'll review and address these items with you either via a call or via the review itself.

**Comment by pavgra** [comment]
- Import methods are missing for both PLE and PLP

**Comment by pavgra** [comment]
Some work required to make the modules to look more-or-less good:

![image](https://user-images.githubusercontent.com/10010071/46683922-7233f580-cbbf-11e8-9cba-4d63216e6ee4.png)

![image](https://user-images.githubusercontent.com/10010071/46684066-c9d26100-cbbf-11e8-90f3-92596137d5ec.png)

![image](https://user-images.githubusercontent.com/10010071/46684135-f1c1c480-cbbf-11e8-845f-761c028ff519.png)

![image](https://user-images.githubusercontent.com/10010071/46684952-5120d400-cbc2-11e8-94ab-fc6fd62991ca.png)

![image](https://user-images.githubusercontent.com/10010071/46685155-c391b400-cbc2-11e8-9faa-9edd81c2acc6.png)

![image](https://user-images.githubusercontent.com/10010071/46685287-1d927980-cbc3-11e8-997c-d301f51bd5aa.png)

**Comment by pavgra** [comment]
Routing is not used for nested pages:
![image](https://user-images.githubusercontent.com/10010071/46690337-09a14480-cbd0-11e8-8b83-441cdcbf8c92.png)

**Comment by pavgra** [comment]
Why does PLP manager save the design before package downloading even without notifying me of it?

**Comment by pavgra** [comment]
Estimation and Prediction classes have exactly the same set of fields but for some reason, they all were copy-pasted but not moved into MappedSuperclass

**Comment by pavgra** [comment]
All buttons at PLE - Comparison page are located on right except for Add Outcome - user has to do following action with his / her mouse to setup props, which obviously tells about poor UX

![image](https://user-images.githubusercontent.com/10010071/46695302-3576f700-cbdd-11e8-988f-8566ce4c89ad.png)

**Comment by pavgra** [comment]
Although, https://github.com/OHDSI/WebAPI/pull/643 and https://github.com/OHDSI/Atlas/pull/1011 implement back-end security and fix UI security-related bugs, there are a lot of places where permissions check is not done. This should be addressed

**Comment by pavgra** [comment]
Would be good to add descriptions to each block in study designer (e.g. there is a nice description of those things in @jreps tutorial)
![image](https://user-images.githubusercontent.com/10010071/46907290-5cd00b80-cede-11e8-818d-fe2460df4cb5.png)

**Comment by anthonysena** [comment]
Closing this out since we've addressed most of these items in #1220 and I've created some new issues to note the lack of import (#1335) and optimizations for defining the specification (#1336).
