### ISSUE TITLE
Validating study choices

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#994]
We need to add more validation checks (server side and client side) for estimation / plp studies. This should also ensure cohort definitions are valid (no critical errors). I need to expand the list but leaving this here to detail these checks out later.

**Comment by pbr6cornell** [comment]
This would be a high priority for ATLAS 2.8.   Perhaps @Kenn4095 can help with writing out the set of test cases that we need to work through.

**Comment by anthonysena** [comment]
#2044 and associated work has added the capability to check study design choices.
